KhronosGroup/SPIRV-LLVM-Translator

- .travis.yml
- utils/check_code_format.sh
- utils/check_code_tidyness.sh
- utils/clang-tidy-diff.py
Modifies the Travis configuration file to run clang-format and clang-tidy on pull requests.
> Run clang-format and clang-tidy on pull requests

- tools/llvm-spirv/CMakeLists.txt
Trying to get travis working again
> Changes in upstream LLVM changed the behaviour of out of tree builds linking dynamically

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorInsertDynamic.ll
According to the specification the result type must be an OpTypeVector.
> Fix return type of OpVectorInsertDynamic

- test/lit.site.cfg.py.in
Removed LIT_SITE_CFG_IN_FOOTER as in llvm repo as in llvm
https://reviews.llvm.org/D51357
> Fix lit tests for Travis CI builds

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVBasicBlock.cpp
- lib/SPIRV/libSPIRV/SPIRVBasicBlock.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/transcoding/LoopUnroll.ll
loop-simplify pass is added to simplify search of Continue Target operand of
OpLoopMerge instruction
> Translation of loop unrolling metadata

- .travis.yml
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
With xenial we get more up to date nightly packages.
UPDATE: seems like it takes some minutes until we get workers, but seems good enough for now
> travis: move to xenial

- CMakeLists.txt
- LLVMSPIRVLib.pc.in
- lib/SPIRV/libSPIRV/SPIRVEnum.h
> Some fixes I didn't tried to upstream yet

- .travis.yml
Upload binaries of the translator to the github repo.
> Enable publishing of built artifacts via github releases.

- include/LLVMSPIRVLib.h
Original patch by: Marco Antognini
> Drop spurious namespace specifiers; NFC

- .travis.yml
- README.md
- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/2010-04-19-FramePtr.ll
> Create llvm_release_80 branch

- test/DebugInfo/X86/dw_op_minus_direct.ll
Update debug info tests after changes introduced by
llvm/llvm-project@9dbeca3d77869f93109ac50fd9827c5546b2dc05
> Sync with LLVM

- README.md
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Fix typo in build instructions

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
Test for this was added by svenvh. I can add to this pull request though if desired.
> Fixing preservation of unsignedness for read_imageui functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
https://github.com/KhronosGroup/SPIRV-Registry/blob/00cac61a8d6749785450d88f3c4ada8aa76faaa2/extensions/INTEL/SPV_INTEL_fpga_memory_attributes.asciidoc
> Translate Intel FPGA max_concurrency memory attribute

- include/LLVMSPIRVLib.h
- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- tools/llvm-spirv/llvm-spirv.cpp
Mostly typo fixes, but also propagating the error message when SPIR-V module importing fails.
> Improve error handling

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
> Translate Intel FPGA singlepump/doublepump memory attributes

- lib/SPIRV/Mangler/Mangler.cpp
- test/transcoding/OpImageSampleExplicitLod_arg.cl
- test/transcoding/enqueue_marker.cl
Minor refactoring to aid debugging of mangler substitution issues.
Fix a mangling issue for `enqueue_marker`.
> Fix mangling of enqueue_marker

- lib/SPIRV/OCLUtil.cpp
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
This is a cherry-pick from master:
- 97df8a2: Fix mangling for work_group_barrier and sub_group_barrier functions
> Fix mangling for work_group_barrier and sub_group_barrier functions

- README.md
* Specify the correct APT repository for LLVM 8 Ubuntu packages
* Specify the llvm_release_80 branch for clones of the LLVM/SPIR-V
translator Git repository
> [NFC] Update README.md for LLVM 8

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm.invariant.ll
> Handle translation of llvm.invariant.* intrinsics

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/SampledImageRetType.ll
> Fix return type for __spirv_SampledImage call

- README.md
As discussed in the tooling call.
> README.md: Elaborate on backporting to releases

- test/transcoding/enqueue_marker.cl
Corresponding Differential Revision: https://reviews.llvm.org/D66512
Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>
> Fix LIT after rL369641: [OpenCL] Fix declaration of enqueue_marker

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugControlFlow.cl
- test/DebugInfo/DebugUnstructuredControlFlow.cl
> [NFC] Fix misleading comment in the test for debug info/control flow

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/enqueue_kernel.ll
Cherry-pick 05e8a8b from master to llvm_release_80
> Cherry-pick 05e8a8b from master to llvm_release_80

- lib/SPIRV/libSPIRV/SPIRVStream.h
- test/copy_object.spt
- test/linkage-name.spt
- test/matrix_times_scalar.spt
- test/opundef.spt
- test/redundant_word.spt
- test/vector_times_scalar.spt
Signed-off-by: Qinglai Xiao <q.xiao@think-silicon.com>
> Support semicolon started comment in text format

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/enqueue_kernel.cl
Set HasEvents to true if num_events_in_wait_list is NULL and event_ret
is not NULL. See #331
> Fix enqueue_kernel translation

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> Add nullptr checks to avoid potential nullptr dereferencing

- lib/SPIRV/SPIRVReader.cpp
>[Alignment][NFC] Convert StoreInst to MaybeAlign
>
>Summary:
>This is patch is part of a series to introduce an Alignment type.
>See this thread for context: http://lists.llvm.org/pipermail/llvm-dev/2019-July/133851.html
>See this patch for the introduction of the type: https://reviews.llvm.org/D64790
>
>Reviewers: courbet
>
>Subscribers: hiraditya, jfb, llvm-commits
>
>Tags: #llvm
>
>Differential Revision: https://reviews.llvm.org/D69303
>
>llvm-svn: 375499
Signed-off-by: Ilya Mashkov ilya.mashkov@intel.com
> Fix build after r375499 and r375498

- lib/SPIRV/SPIRVReader.cpp
- test/OpFAdd.spvasm
- test/OpFDiv.spvasm
- test/OpFMul.spvasm
- test/OpFNegate.spvasm
- test/OpFSub.spvasm
- test/OpIAdd.spvasm
- test/OpIMul.spvasm
- test/OpISub.spvasm
- test/OpShiftLeftLogical.spvasm
This includes tests for translation of FPFastMathMode decorations for OpFAdd, OpFSub, OpFMul, OpFDiv, OpFRem and OpFNegate.
This also adds tests for translation of NoSignedWrap and NoUnsignedWrap decorations for OpIAdd, OpIMul, OpISub and OpShiftLeftLogical, in addition to testing the translation of NoSignedWrap for OpSNegate.
> Fix setting of nsw flag when translating OpSNegate and add translation of FPFastMathMode decorations

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/annotate_attribute.ll
> Backport UserSemantic decoration support to 8.0 release

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Update for
- 1b2842bf902 ("[Alignment][NFC] CreateMemSet use MaybeAlign",
2019-12-09).
- d77ae1552fc ("[DebugInfo] Support to emit debugInfo for extern
variables", 2019-11-22).
> Update for LLVM API changes

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_fpga_memory_attributes.asciidoc
> Translate Intel FPGA bank_bits memory attribute

- test/transcoding/FPGAIVDepLoopAttr.ll
The particular order of !"llvm.loop.parallel_access_indices" metadata
operands being non-deterministic and irrelevant, it makes sense to
alleviate the LIT tests from the corresponding restriction on the index
groups' order.
E.g. both of the below scenarios would now pass the tests:
!0 = !{!"llvm.loop.parallel_access_indices", !1, !2}
OR
!0 = !{!"llvm.loop.parallel_access_indices", !2, !1}
> Enhance FPGA IVDep attribute testing

- .travis.yml
- CMakeLists.txt
- README.md
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
> Update version of LLVM from 10 to 11

- CMakeLists.txt
See the corresponding issue: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/131.
> Update LLVM_SPIRV_VERSION in CMakeLists.txt to 8.0.0.1

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/AtomicCompareExchange.ll
> Translate LLVM's cmpxchg instruction to SPIR-V

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm.sqrt.ll
> Translate llvm.sqrt.* intrinsics to SPIR-V

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
> Fix potential null pointer dereference

- test/DebugInfo/X86/xray-split-dwarf-interaction.ll
Signed-off-by: Vladimir Lazarev <vladimir.lazarev@intel.com>
> [SYCL] Fix LIT after LLVM change in community

- lib/SPIRV/SPIRVReader.cpp
- test/OpFNegate.spvasm
- test/transcoding/TransFNeg.cl
BinaryOperator::CreateFNeg -> UnaryOperator::CreateFNeg
> Fix build after ddd11273d

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/FPGALoopAttr.ll
- test/transcoding/FPGALoopMergeInst.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
> [NFC] Fix spelling for Intel Loop Controls

- README.md
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/442
> README.md: Mention retrieving llvm archive signatures

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm.ceil.ll
- test/llvm.fabs.ll
Signed-off-by: Arvind Sudarsanam <arvind.sudarsanam@intel.com>
> Transform fabs and ceil llvm intrinsics into SPIRV extended instructions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStaticVar.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_fpga_memory_attributes.asciidoc
> Translate Intel FPGA force_pow2_depth memory attribute

- lib/SPIRV/SPIRVReader.cpp
Update for LLVM commit 1ee6ec2bf37 ("Remove "mask" operand from
shufflevector.", 2020-03-31).
> Update for LLVM API changes to CreateShuffleVector

- lib/SPIRV/SPIRVLowerMemmove.cpp
- test/transcoding/llvm.memmove.ll
- Add support for "partial" move
- Teach the pass to look through addrspace cast
- Add support for multiple casts
Signed-off-by: Alexey Bader <alexey.bader@intel.com>
> Improve llvm.memmove intrinsic support

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL20.cpp
> Remove deprecated spirv-atomic-prefix option

- lib/SPIRV/SPIRVWriter.cpp
> Fix a warning from "Enable strict rules to set ContractionOFF (#521)"

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/constexpr_vector.ll
- test/transcoding/SPV_INTEL_function_pointers/vector_elem.ll
- Auto add ReferencedIndirectly decoration when creating a function pointer
- Fix constexprs lowering for const vectors of funcpointers
> Function pointers support improvements

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/undef-func-call.ll
PR with fix for master branch: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/541.
> Backport fix for issue #524 to llvm 10 branch

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_function_pointers/bitcast.ll
> Allow to cast function pointers

- lib/SPIRV/SPIRVLowerBool.cpp
- test/TruncToBool.ll
> [Backport] Fix for trunc to bool lowering (LLVM-10)

- lib/SPIRV/SPIRVLowerBool.cpp
- test/TruncToBool.ll
> [Backport] Fix for trunc to bool lowering (LLVM-9)

- lib/SPIRV/SPIRVLowerBool.cpp
- test/TruncToBool.ll
> [Backport] Fix for trunc to bool lowering (LLVM-8)

- lib/SPIRV/SPIRVWriter.cpp
> Fix issues found by a static analysis tool.

- utils/check_code_format.sh
- utils/check_code_tidyness.sh
Patch fixes github issue:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/496
Cherry-pick of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/562.
> Fix base branch in code check scripts

- utils/check_code_format.sh
- utils/check_code_tidyness.sh
Patch fixes github issue:
#496
Cherry-pick of #562.
> Fix base branch in code check scripts for llvm 7

- utils/check_code_format.sh
- utils/check_code_tidyness.sh
Patch fixes github issue:
#496
Cherry-pick of #562.
> Fix base branch in code check scripts for llvm 8

- lib/SPIRV/SPIRVWriter.cpp
> Add CapabilityFPGABufferLocationINTEL only when the decoration is added

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/DebugInfo/Generic/linear-dbg-value.ll
https://www.khronos.org/registry/spir-v/specs/unified1/OpenCL.DebugInfo.100.html
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug according to specification

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
Adding new decorations from spec: https://github.com/intel/llvm/pull/1611/
> Float controls decs

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/TransOCLMD.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
intel/llvm#1611
(Master pull request #677)
> Float Controls Decoration backport for 70 release

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
intel/llvm#1611
(Master pull request #677)
> Float Controls Decoration backport for 90 release

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
https://github.com/intel/llvm/pull/1611
(Master pull request #677)
> Float Controls Decoration backport for 100 release

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
This option required for compatibility with older version of translator
> Add DebugInfoEIS option to allow setting desired extended instruction set for debug info

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
intel/llvm#1611
(Master pull request #677)
> Float Controls Decoration backport for 80 release

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/event_no_group_cap.cl
> OpGroupWaitEvents doesn't require the Group capability

- lib/SPIRV/SPIRVWriter.cpp
- test/ctpop.ll
Add llvm.ctpop.* translation to BitCount instruction
Add test for this
> Add llvm.ctpop* intrinsic translation

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/nearbyint.ll
Add nearbyint intrinsic support in SPIRV
> Add nearbyint support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
According to the spec
https://github.com/intel/llvm/pull/1612
> Implement SingleElementVectorINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/GlobalFunAnnotate.ll
- test/transcoding/IntelFPGAMemoryAccesses.ll
- test/transcoding/IntelFPGAMemoryAttributes.ll
- test/transcoding/IntelFPGAMemoryAttributesForStruct.ll
- test/transcoding/IntelFPGAReg.ll
- test/transcoding/annotate_attribute.ll
- test/transcoding/annotation_dbg_info_drop.ll
- test/transcoding/intel_fpga_lsu_optimized.ll
> Fix ptr/var/global annotations after https://reviews.llvm.org/D88645

- lib/SPIRV/SPIRVWriter.cpp
Seems to have been introduced by #750
> Fix -Wparentheses build warning in asserts

- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
> Fix issues found by a static analysis tool

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpSpecConstantComposite.spvasm
- test/transcoding/SpecConstantComposite.ll
> Support of OpSpecConstantComposite instruction

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
llvm/llvm-project@fe431683484a3041e024ab2373bb707b1ca8d1cf in llvm master
changed how this API is used.
Signed-off-by: Dave Airlie <airlied@redhat.com>
> Support LLVM 12 interface change for getTypeByName

- lib/SPIRV/SPIRVReader.cpp
- test/GroupAndSubgroupInstructions.spvasm
> Add 'convergent' attribute for group and subgroup instructions.

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Corresponding commit: llvm/llvm-project@41c3b2713
> Fix build after 41c3b2713 llvm commit

- .github/workflows/check-code-style.yml
- .github/workflows/check-out-of-tree-build.yml
- .travis.yml
> Fix out-of-tree builds by installing OpenMP libs explicitly

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
The objective of this change is to reduce `OpCode`-based branching in the base
class for atomic instructions, and to simplify specialization for ones that will
be added in future.
> [NFC] Instantiate atomic instructions via inheritance

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_single_element_vector.ll
Spec can be found at intel/llvm#1612
> Implement SingleElementVectorINTEL decoration on llvm_release_80 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_single_element_vector.ll
Spec can be found at intel/llvm#1612
> Implement SingleElementVectorINTEL decoration on llvm_release_90 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_single_element_vector.ll
Spec can be found at intel/llvm#1612
> Implement SingleElementVectorINTEL decoration on llvm_release_100 branch

- docs/SPIRVRepresentationInLLVM.rst
Fix a typo in LLVM IR example.
> Update links to external documents.

- lib/SPIRV/SPIRVToOCL20.cpp
- test/mem_fence_explicit_arguments.spt
> Add support for non-constant 'Scope' operand of OpMemoryBarrier

- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
> Improve decoding of constant composites

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/fp-intrinsics.ll
- test/negative/llvm-unhandled-intrinsic.ll
- test/transcoding/AllowIntrinsics.ll
Signed-off-by: gejin <ge.jin@intel.com>
> [Backport] Add support for some llvm FP intrinsic in llvm-spirv

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
Our compiler is triggering various errors. This is a patch to fix them.
> Fix various compiler errors.

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
The API change is brought by llvm/llvm-project@e5d958c.
Fixes #932
> Fix builds: adjust to the new DbgVariableIntrinsic API

- include/LLVMSPIRVLib.h
> [Backport] Fix isSpirvBinary signature

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVError.h
> Print path info in error messages only in debug build

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/suminmaxIntr.ll
Add llvm.smax, llvm.smin , llvm.umax, llvm.umin intrinsic translation and add test for that
> Add llvm.*max and llvm.*min intrinsics translation

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- test/OpenCL.std/vload_half.spvasm
- test/OpenCL.std/vload_halfn.spvasm
- test/OpenCL.std/vloada_halfn.spvasm
- test/OpenCL.std/vloadn.spvasm
…vloada_halfn OpenCL EIS instructions
> Backmerge fix for emission of SPIR-V friendly IR for vload to llvm_release_100

- include/LLVMSPIRVLib.h
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerOCLBlocks.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
Initial preparation commit for migrating to using the new LLVM pass manager
> Migrating to new PM

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/llvm-intrinsics/fshr.ll
Add llvm.fshr intrinsic translation, similar to llvm.fshr translation.
Add test for that
A detailed description of FSHR can be found at
https://llvm.org/docs/LangRef.html#llvm-fshr-intrinsic
> Translate the llvm.fshr intrinsic function

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/group-decorate.spt
- test/transcoding/readonly.ll
> Map NoWrite function parameter attribute on LLVM readonly

- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopAttr.ll
> [NFC] Fix FPGALoopAttr.ll after fd94103

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
- lib/SPIRV/SPIRVToOCL.h
* "has virtual functions and accessible non-virtual destructor"
* runOnModule "can be marked override"
> Fix -Werror=non-virtual-dtor -Werror=suggest-override errors

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
This code is not needed after 9f3c10f4.
> [NFC] Remove dead code

- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- lib/SPIRV/SPIRVReader.cpp
This PR includes 2 commits:
1. Cherry-pick of 960cbc9
2. Setting correct branch and filenames in workflow files
> Fix GitHub Actions CI on llvm_release_120 branch

- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- test/lit.cfg.py
Comply with LLORG community changes in llvm/llvm-project@a1e6565.
> Facilitate pre-installed Clang detection for in-tree builds

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Fix a small memory leak after #924; @KornevNikita could you please review this fix?
> Fix OpModuleProcessed memory leak

- lib/SPIRV/SPIRVLowerMemmove.cpp
- test/llvm-intrinsics/memmove.ll
It is possible that for a single element Src type size doesn't
match memory size to move (for example we copy N elements of one
integer array to an address of a first element of another integer
array).
> Improve handling of memmove when Lenght > size of the type to move

- include/LLVMSPIRVOpts.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/spirv-version-controls-1.spt
- test/negative/spirv-version-controls-2.spt
- tools/llvm-spirv/llvm-spirv.cpp
> Up max SPIR-V version to 1.4

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- CMakeLists.txt
- README.md
- docs/SPIRVRepresentationInLLVM.rst
- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/lower-non-standard-types.ll
- test/negative/invalid-vloada-half-scalar.ll
- test/negative/invalid-vloada-half-vector.ll
- test/negative/spirv-version-controls-1.spt
- test/negative/spirv-version-controls-2.spt
- test/transcoding/enqueue_kernel.cl
- tools/llvm-spirv/llvm-spirv.cpp
Also cherry-picking latest commits from master(main) branch.
> Fork llvm_release_130 branch

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/isnan.ll
> Map llvm.isnan on OpIsNan

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
> [Backport][8v]Linkage type fix for global variables translation

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
> [Backport][12v]Linkage type fix for global variables translation

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
> [Backport][11v]Linkage type fix for global variables translation

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
> [Backport][10v]Linkage type fix for global variables translation

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
> [Backport][9v]Linkage type fix for global variables translation

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
For the reason that they have been removed from llvm.
> Replace add-, get-, has-, removeAttribute by related methods.

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/exec_mode_float_control_khr.ll
- test/transcoding/LoopUnroll.ll
- test/transcoding/NoSignedUnsignedWrap.ll
- test/transcoding/SPV_INTEL_vector_compute/exec_mode_float_control.ll
- test/transcoding/annotate_attribute.ll
- test/transcoding/block_w_struct_return.cl
- test/transcoding/global_block.cl
> Add SPIR-V 1.4 checks

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
> [Backport][13v] Amend SingleElementVectorINTEL decoration use cases

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
> [Backport][12v] Amend SingleElementVectorINTEL decoration use cases

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
> [Backport][11v] Amend SingleElementVectorINTEL decoration use cases

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/decoration_single_element_vector.ll
> [Backport][10v] Amend SingleElementVectorINTEL decoration use cases

- test/llvm-intrinsics/experimental.noalias.scope.decl.ll
- test/transcoding/builtin_vars_opt.ll
> [NFC] Fix tests with wrong alias metadata

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/decoration_single_element_vector.ll
> [Backport][8v] Amend SingleElementVectorINTEL decoration use cases

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/decoration_single_element_vector.ll
> [Backport][9v] Amend SingleElementVectorINTEL decoration use cases

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_half.ll
> Fix translation of OpTypeJointMatrixINTEL with element of type `half`

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- test/AtomicBuiltinsFloat.ll
- test/negative/InvalidAtomicBuiltins.cl
- test/transcoding/AtomicFAddEXTForOCL.ll
- test/transcoding/AtomicFMaxEXTForOCL.ll
- test/transcoding/AtomicFMinEXTForOCL.ll
cherry-pick from master to llvm_release_110 #1116
> Add support for cl_ext_float_atomics in SPIRVWriter (#1116)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
> [Backport][80] Add mapping for DWARF language codes to SourceLanguage (#1074)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
> [Backport][90] Add mapping for DWARF language codes to SourceLanguage (#1074)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
> [Backport][120] Add mapping for DWARF language codes to SourceLanguage (#1074)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
> [Backport][100] Add mapping for DWARF language codes to SourceLanguage (#1074)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
Temporary disable check for VCFunction attribute.
> Enable transVCMetadata flow for all functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_function_pointers/decor-func-ptr-arg-attr.ll
Spec: [pull/4958](https://github.com/intel/llvm/pull/4958)
> Add new decoration for SPV_INTEL_function_pointers

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][90] Enable transVCMetadata flow for all functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][100] Enable transVCMetadata flow for all functions

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/ldexp.cl
> [Backport][100] Convert ldexp scalar arg to vector

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/ldexp.cl
> [Backport][110] Convert ldexp scalar arg to vector (#1300)

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/ldexp.cl
> [Backport][120] Convert ldexp scalar arg to vector

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/ldexp.cl
> [Backport][90] Convert ldexp scalar arg to vector

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_media_block_io.ll
> [Backport][100] Add support for MediaBlockIOINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_media_block_io.ll
> [Backport][90] Add support for MediaBlockIOINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_media_block_io.ll
> [Backport][80] Add support for MediaBlockIOINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_media_block_io.ll
> [Backport][110] Add support for MediaBlockIOINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_media_block_io.ll
> [Backport][120] Add support for MediaBlockIOINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix.ll
> Represent init/fill joint_matrix instruction as OpCompositeConstruct

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoSubrange.ll
If there is count field in DISubrange, then lowerBound may not be equal
to zero.
> Fix DISubrange translation

- test/transcoding/SampledImage.cl
This is to adjust tests after https://reviews.llvm.org/D118894, github
commit: llvm/llvm-project@18834dca2d787fb46532c0b688e396613e132020
> Fix lit test after changes in Clang

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_bfloat16.ll
This patch adds translation for bfloat16 as matrix type
> Fix translation for matrix slicing with bfloat16

- test/transcoding/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension.ll
> [NFC] Replace CHECK to CHECK-DAG in new test

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/complex-constexpr-vector.ll
- test/constexpr_phi.ll
- test/constexpr_vector.ll
- test/vector-metadata-constexpr.ll
> [Baclport][130] Important patches to support constant expressions translation.

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoSubrange.ll
> Fix wrong DICompositeType size

- include/LLVMSPIRVOpts.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/spirv-version-controls-negative-1.spt
- test/spirv-version-controls-negative-2.spt
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport] Up max SPIR-V version to 1.4 (#1161)

- lib/SPIRV/SPIRVLowerOCLBlocks.cpp
Checking that actions on new PRs are working after the default branch was renamed.
> Fix some typos

- test/transcoding/SPV_KHR_integer_dot_product-sat.ll
- tools/llvm-spirv/llvm-spirv.cpp
> Cherry-pick to llvm_release_130

- test/transcoding/SPV_KHR_integer_dot_product-sat.ll
- tools/llvm-spirv/llvm-spirv.cpp
> Cherry-pick to llvm_release_140

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- lib/SPIRV/SPIRVWriter.cpp
The Ubuntu 18.04 image is marked deprecated [1], so move to a newer
image.
> [CI] Upgrade to Ubuntu 20.04

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
> [CI][Backport 12] Upgrade to Ubuntu 20.04

- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
> [NFC][LLVM 12] Add override to fix warning

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- .travis.yml
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [CI][Backport 14] Upgrade to Ubuntu 20.04

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
- .travis.yml
> [CI][Backport 13] Upgrade to Ubuntu 20.04

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
> [CI][Backport 10] Upgrade to Ubuntu 20.04

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
> [NFC] Remove dead code related to Intel's JointMatrix extension

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
In this change set, we avoid local copy of strings.
Signed-off-by: Arvind Sudarsanam <arvind.sudarsanam@intel.com>
> [NFC] Fix some static analyzer issues

- test/complex-constexpr.ll
bbfb13a5ffbc "[ConstExpr] Remove select constant expression" forbids select constant expression
> [NFC] Update complex-constexpr.ll

- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/DebugInfo/NonSemanticShader200/SourceLanguageLLVMToSPIRV.ll
Spec: KhronosGroup/SPIRV-Registry#186
> [DebugInfo] Add more source languages and align to spec changes

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfoLowerBound.ll
Backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1901
> [Backmerge to 12] Improve DbgArrayType compatibility (#1901)

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/registerallocmode.ll
We are planning on using this in the backend.
> Support 0 value of Intel-specific RegisterAllocMode MD

- lib/SPIRV/SPIRVWriter.cpp
I forgot to update this in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/0ef30a3dfeec433b6d4de4e9cc2a6817032b93e3
> [NFC] Update comment

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/Generic/function-ptr-templ-null.ll
- test/DebugInfo/Generic/function-ptr-templ.ll
It might be set as null in case if a function pointer is passed as auto template parameter.
The patch also adds a test for a 'good' DW_TAG_template_value_parameter value for function pointers, just because this case was untested.
> [DebugInfo] Handle null value of DW_TAG_template_value_parameter

- lib/SPIRV/SPIRVUtil.cpp
patch by
Artur Gainullin <artur.gainullin@intel.com>
> [NFC] Fix windows build after 7c59e8

- .github/workflows/check-code-style.yml
- .github/workflows/check-out-of-tree-build.yml
This reverts commit b378140863da53bd9fdc313514e00d8c8f45a98f.
Adjustment after
commit e87e4cfc12884479ff402e0689f374f155a41abf
Author: Shilei Tian <i@tianshilei.me>
Date:   Sat May 6 23:26:43 2023 -0400
[OpenMP] Make `libomptarget` link against `libomp`
> Revert "[TRY] Remove OpenMP install"

- lib/SPIRV/SPIRVTypeScavenger.cpp
Eliminating unnecessary copies to improve performance.
> Fixing issues in type scavenger related to copy efficiency

- test/DebugInfo/X86/split-dwarf-omit-empty.ll
https://github.com/llvm/llvm-project/commit/e731a2678c7cf81b1d3817489a52b519cb14f85e
> Update DebugInfo/X86/split-dwarf-omit-empty.ll after community change

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- test/DebugInfo/NonSemantic/Shader200/DebugInfoStringType.ll
- test/DebugInfo/NonSemantic/Shader200/DebugInfoSubrange.ll
- test/DebugInfo/NonSemantic/Shader200/DebugInfoTargetFunction.ll
- test/DebugInfo/NonSemantic/Shader200/DebugLinePriority.spt
Implement DebugLine/DebugNoLine for NonSemantic.Shader.DebugInfo.100 and NonSemantic.Shader.DebugInfo.200.
Updated test/DebugInfo/NonSemantic/Shader200/DebugInfoStringType.ll  to test these changes.
> Implement DebugLine and DebugNoLine

- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
Update test for llvm-project commit llvm/llvm-project@d80fdc6fc1a6
> Update DebugInfo/FortranArray test after DWARF emission fix

- lib/SPIRV/SPIRVWriter.cpp
SPIRVWriter perf optimize for object copy
> optimizing away pair type object copy in spv writer

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/Shader200/DebugInfoSubrange.ll
- test/DebugInfo/NonSemantic/Shader200/FortranDynamicArrayExpr.ll
Count should be the 3rd parameter.
> [DebugInfo] Fix DebugTypeSubrange parameters order

- test/DebugInfo/Generic/multiline.ll
- test/DebugInfo/X86/discriminator2.ll
- test/DebugInfo/X86/discriminator3.ll
- test/DebugInfo/X86/ending-run.ll
Update tests for llvm-project commit 6aa94c64a532 ("[DWARF] Add printout for op-index", 2023-07-12).
> Update DebugInfo tests for op-index addition

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata-debug.ll
It's duplicating existing information in the SPIR-V and it has complex structure.
> Don't preserve debug metadata with --spirv-preserve-auxdata

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVWriter.cpp
Also fix 'unused variable' warning.
> [NFC] Remove uses of supportsTypedPointers()

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/DIImportedEntity.ll
Should be more cautious with inline namespaces
> [Backport to 14][DebugInfo] Fix parent scope index for ImportedEntity

- lib/SPIRV/SPIRVWriter.cpp
- test/fp_to_int_intrinsic.ll
- test/llvm-intrinsics/fp_to_int_intrinsic.ll
Translate llvm.fptosi.sat.*  to OpConvertFToS and llvm.fptoui.sat.* to OpConvertFToU.
> Translate llvm.fpto[s|u]i.sat.* intrinsics

- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
This version should be more much stable comparing to fix in #2199
> [NFC] Fix CHECKs FortranArray.ll

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Duplicate declarations are non conformant with spec which rendered current implementation of SPIRVModuleImpl::addXXXType useless for some types. This commit is an easy fix for bool, float and void. Integer is changed from std::map to SmallDenseMap with 4 inlined buckets. Most of the time Integer will only have 8, 16, 32 and 64 bitwidth so it's much more efficient to use this specialized map.
> Fix duplicate type declarations when using addXXXType api

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
Due to change in LLVM IR in commit dea16ebd2613a4a218c53045270fc4fcc9b427ad.
> Change ConstantInt.getType to ConstantInt.getIntegerType

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugTypeMember.ll
Test Value field in SPIRV TypeMember.
Also remove some unreachable code.
> [NFC] [DebugInfo] Test Value field in SPIRV TypeMember

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Update after llvm commit 9997e0397156 ("[RemoveDIs] Update DIBuilder to conditionally insert DbgRecords (#84739)", 2024-03-12).
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2432
> Update SPIRVToLLVMDbgTran after DIBuilder API changes

- test/extensions/INTEL/SPV_INTEL_fpga_reg/IntelFPGAReg.ll
> [NFC] Remove tbaa metadata from fpga_reg test

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Make code clearer and check for exact number of operands.
> [NFC] Make assertion precise

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/spirvSourceCL2.0.ll
- test/transcoding/spirvSourceCLCXX.ll
Align with https://github.com/llvm/llvm-project/commit/5fd5b8ada70d9cbdaa8cc5bea50a6314e3140364.
> Set spirv.Source according to the opencl.ocl.version and opencl.cxx.version.

- docs/SPIRVRepresentationInLLVM.rst
Add section about loop controls
> Update SPIRVRepresentationInLLVM.rst to include loop controls

- .github/workflows/check-out-of-tree-build.yml
> [Backport to 14] [CI] Upgrade out-of-tree job to Ubuntu 22.04

- .github/workflows/check-out-of-tree-build.yml
> [Backport to 15] [CI] Upgrade out-of-tree job to Ubuntu 22.04

- .github/workflows/check-out-of-tree-build.yml
> [Backport to 17] [CI] Upgrade out-of-tree job to Ubuntu 22.04

- .github/workflows/check-code-style.yml
- lib/SPIRV/SPIRVWriter.cpp
also fix formatting issue from a recent PR.
> [NFC][CI] Add polly to clang-format checks

- lib/SPIRV/OCLUtil.h
- test/atomic_explicit_arguments.spt
- test/barrier_explicit_arguments.spt
- test/mem_fence_explicit_arguments.spt
- test/transcoding/atomic_explicit_arguments.cl
- test/transcoding/barrier-runtime-scope.ll
The refactoring is to simplify the optimization and vectorization of generated functions.
> Refactor switch function creation to generate single return point

- .github/workflows/check-code-style.yml
(cherry picked from commit a4010e023cdad74f5759e444fb58fbe678b12b64)
> [Backport to 16] [CI] Upgrade upload-artifact to v4

- .github/workflows/check-code-style.yml
> [Backport to 18] [CI] Upgrade upload-artifact to v4 (#2717)

- .github/workflows/check-code-style.yml
> [Backport to 17] [CI] Upgrade upload-artifact to v4 (#2717)

- .github/workflows/check-code-style.yml
> [Backport to 15] [CI] Upgrade upload-artifact to v4 (#2717)

- .github/workflows/check-code-style.yml
> [Backport to 14] [CI] Upgrade upload-artifact to v4 (#2717)

- .github/workflows/check-code-style.yml
> [Backport to 19] [CI] Upgrade upload-artifact to v4 (#2717)

- tools/llvm-spirv/llvm-spirv.cpp
Backport part of dfeb22b8 ("Add an option to translate LLVM IR to SPIR-V using the LLVM SPIRV Backend target (#2716)", 2024-09-16) to avoid the error
Option 'spirv-ext' registered more than once
when llvm-spirv is built against an LLVM that has the experimental SPIR-V backend enabled.
> Backport fix for duplicate -spirv-ext registration

- lib/SPIRV/SPIRVWriter.cpp
(cherry picked from commit a4010e023cdad74f5759e444fb58fbe678b12b64)
> [Backport to 16] Fix uninitialized DominatorTree member

- lib/SPIRV/SPIRVReader.cpp
> Replace getDeclaration with getOrInsertDeclaration after upsteam changes

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/lround.ll
Support for llvm.lround.* intrinsics to handle rounding operations with float to integer conversion.
> Add support for llvm.lround.*

- test/DebugInfo/X86/header.ll
Update for LLVM commit 7b23f413d1.
> Update DebugInfo header.ll test after LLVM change

- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
- test/extensions/INTEL/SPV_INTEL_bindless_images/negative/i32-in-physical64.ll
The updated SPV_INTEL_bindless_images spec can be seen in this PR: intel/llvm#13753
> [Backport to 15] Add updated SPV_INTEL_bindless_images preview extension (#2559)

- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
- test/extensions/INTEL/SPV_INTEL_bindless_images/negative/i32-in-physical64.ll
The updated SPV_INTEL_bindless_images spec can be seen in this PR: intel/llvm#13753
> [Backport to 17] Add updated SPV_INTEL_bindless_images preview extension (#2559)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
Update after llvm-project commit `979c275097a6 ("[IR] Store Triple in Module (NFC) (#129868)", 2025-03-06)`.
> Update after llvm::Triple changes

- test/smulextended_builtin.ll
> Fix S/UMulExtended instructions translation on llvm_release_15

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_vector_compute/buffer_surface_intel.ll
It should be a target extension type.
> Fix OpTypeBufferSurfaceINTEL translation for opaque pointers

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_vector_compute/buffer_surface_intel.ll
It should be a target extension type.
> [Backport to 16] Fix OpTypeBufferSurfaceINTEL translation for opaque pointers

- README.md
Co-authored by: Ashbaugh, Ben <ben.ashbaugh@intel.com>
> [NFC] Update README reflecting process of preview extensions removal

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/KHR/SPV_KHR_cooperative_matrix/access_store.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
Same as https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2170
> [Backport to 15] Reverse translation for SPV_KHR_cooperative_matrix extension

- .github/workflows/check-code-style.yml
> [CI] Update runner for tidy and format checks to ubuntu 22

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2443
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2464
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3128
> [Backport to 18] Backport fixes for OpenCL convert_ builtins

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2443
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2464
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3128
> [Backport to 17] Backport fixes for OpenCL convert_ builtins

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2443
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2464
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3128
> [Backport to 16] Backport fixes for OpenCL convert_ builtins

- .github/workflows/backport-to-branch.yml
Example use: /backport llvm_release_190
> [CI] Add actions job to create backports

- .github/workflows/backport-to-branch.yml
- Wrong comment syntax for used
- Fixed return for Get commit sha job
> [CI] Fix typos in the backport script

- .github/workflows/backport-to-branch.yml
- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
Otherwise we need to start CI manually.
> [CI] Add listener for other workflows to trigger them on a backport

- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
> Remove internal values for SPV_INTEL_cache_controls pt.2

- test/instructions/select.ll
- test/instructions/vector-bitwise-operations.ll
- test/instructions/vector-floating-point-arithmetic.ll
- test/instructions/vector-integer-arithmetic.ll
Added tests for:
- lowering of select instructions
- vector type integer,arithmetic,and bitwise operations
> Porting tests for instructions from llvm-project

- lib/SPIRV/OCLToSPIRV.cpp
In SPIRV-Translator for `llvm_release_160`, the `BitCast` instruction from `float` to `int` is currently applied only to argument 2 of the `AtomicCmpXchg` call. This approach works correctly when using opaque pointers. However, when typed pointers are present, SPIRV-Translator must also insert `BitCast` instructions for arguments 0 and 1, as is done in the `llvm_release_150` branch.
Prior to this change, SPIRV-Translator generated the call `__spirv_AtomicCompareExchangeWeakPU3AS1fiiiif` for this atomic operation. After adding the additional `BitCast` instructions, the generated call becomes `__spirv_AtomicCompareExchangeWeakPU3AS1iiiiii`.
This modification is compatible with both opaque and typed pointers.
The change for llvm_release_150: …
> Add `BitCast` instructions from `float` to `int` for `AtomicCmpXchg` calls

- test/struct.ll
- test/unnamed-global.ll
--Test for structs and unnamed globals.
> Addtion of struct.ll and unnamed-global.ll

- include/LLVMSPIRVOpts.h
- lib/SPIRV/libSPIRV/SPIRVFnVar.cpp
- lib/SPIRV/libSPIRV/SPIRVFnVar.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Fix code quality issues reported by a static analysis tool.
> Fix code quality issues.
