KhronosGroup/SPIRV-LLVM-Translator

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_function_pointers/alias.ll
- test/transcoding/alias.ll
Currently llvm-spirv crashes with an assert when translating uses of aliases which are not the callee of a function call instruction. This change remedies this by handling these uses of aliases the same way
function call callees are handled: by using the value of their aliasee.
> Translate aliases to aliasee value in more contexts

- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
The parseIR API has been updated again in b56df190b013 to require a ParserCallbacks object which is not implicitly convertible from a lambda. This change adds an explicit conversion to fix the build failure.
> Update for another parseIR LLVM API change

- test/transcoding/optional-core-features-multiple.ll
Update a test for llvm-project commit 9ed2f14c8717 ("[AsmParser] Remove typed pointer auto-detection", 2023-01-18).
> Update test for typed pointer auto-detection removal

- lib/SPIRV/OCLToSPIRV.cpp
Update for llvm-project commit 89427bb7cbd1 ("[NFC] Deprecate DataLayout::getPrefTypeAlignment", 2023-01-24).
> Update for getPrefTypeAlignment API deprecation

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVUtil.cpp
In some cases, return value of consume_front is ignored. This change fixes the issue.
Signed-off-by: Arvind Sudarsanam <arvind.sudarsanam@intel.com>
> Fix static analysis issues

- test/transcoding/clk_event_t.cl
- test/transcoding/pipe_builtins.cl
Non-opaque pointers are (almost) not supported in LLVM passes, so compilation with higher than O0 optimization level with -no-opaque-pointers flag will result in assertions firing.
To avoid this there are 2 options:
1. Pass -O0 to the tests and update checks;
2. Remove the flag and XFAIL the tests.
Short term option 1. is better, long term - 2. is better.
By this patch I vote for 2.
> [NFC] Remove -no-opaque-pointers flag from 2 .cl tests and XFAIL them

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVWriter.cpp
Update includes after llvm-project commit 62c7f035b439 ("[NFC][TargetParser] Remove llvm/ADT/Triple.h", 2023-02-07).
> Update for removal of ADT/Triple.h

- test/DebugInfo/X86/dbg-declare-alloca.ll
Update a test after llvm-project commit c65b4d64d4b0 ("[SelectionDAG] Do not second-guess alignment for alloca", 2023-02-09).
> Update alloca DebugInfo test

- lib/SPIRV/SPIRVReader.cpp
- test/llvm-intrinsics/memset-opaque.ll
Non-constant @llvm.memset calls are presently lowered by generating synthetic functions with the mangled name of memset. However, the reader tries to use this name to generate the intrinsic call again. This causes verification issues if the SPIRVWriter and SPIRVReader do not agree on whether or not to use opaque pointers. This change uses the actual type of the function (which will take into account whether or not it is in opaque pointer mode) to generate the LLVM intrinsic name, fixing the mismatch issues.
> [OpaquePointers] Handle llvm.memset intrinsic mangling mismatches.

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/transcoding/kernel_query.ll
This specifies the right operand types for GetKernelWorkGroupSize, GetKernelPreferredWorkGroupSizeMultiple,
GetKernelNDrangeMaxSubGroupSize,
and GetKernelNDrangeSubGroupCount to fix a function signature mismatch bug on reverse translation.
> [OpaquePointers] Fix translation of kernel query instructions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_buffer_location/FPGABufferLocation.ll
This PR is regarding spec https://github.com/KhronosGroup/SPIRV-Registry/pull/185
This patch parse the string in a "ptr.annotation" call, extracting buffer location information and create a SPIRV decoration on the pointer using the buffer location information. This applies only on the pointer argument of OpLoad/Opstore
> Decorate the pointer argument of OpLoad and Opstore with BufferLocationINTEL

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 15] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVTypeScavenger.cpp
As computerPointerElementType is recursive, it's possible for the hash table to be resized during the call to the function. If this happens, then the reference to the value is no longer a valid reference, and may overwrite memory (or just plain segfault).
> Fix potential pointer lifetime issue in the type scavenger.

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 14] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 13] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/group-decorate.spt
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 12] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 11] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 10] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
> [Backport to 9] Translate readnone attribute as function parameter attribute (#1697)

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_element.ll
The instruction returns (Row, Column) coordinate of dynamically selected element of a matrix
Updated version of the spec is here
https://github.com/intel/llvm/pull/8175
Instruction correctness checks will be added later among non-backward compatible changes.
> Add JointMatrixGetElementCoordINTEL instruction

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/DebugInfo/NonSemanticKernel100/FortranArray.ll
- test/DebugInfo/NonSemanticKernel100/SourceLanguageLLVMToSPIRV.ll
This extended source language table is used by DebugCompilationUnit instruction when the extension is enabled. It enables support for more languages than exists in a core specification.
Spec: https://github.com/KhronosGroup/SPIRV-Registry/pull/186/
Enabling of Fortran language also allowed to fix FortranArray test that was originally XFAIL-ed in 9e234d9.
> [DebugInfo] Add new Source Languages table used in DebugCompilationUnit 

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemanticKernel100/DebugInfoTargetFunction.ll
It's being added in
https://github.com/KhronosGroup/SPIRV-Registry/pull/186
In DWARF it's used in 'trampoline' functions generated for Fortran external function calls.
> [DebugInfo] Add Target Function optional parameter to DebugFunction

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- tools/llvm-spirv/llvm-spirv.cpp
Under this option this extended instruction set will be implemented Spec:
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc
TODO: to rename NonSemantic.Kernel.DebugInfo.100 to NonSemantic.Shader.DebugInfo.200 when the name is stable
Signed-off-by: Sidorov, Dmitry dmitry.sidorov@intel.com
> [DebugInfo] Add an option for NonSemantic.Shader.DebugInfo.100

- lib/SPIRV/OCLToSPIRV.cpp
This change fixes the following issue reported by static analyzer:
Unchecked return value
Thanks
> [NFC] Fix static analyzer issues

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/float16.ll
Itanium name mangling gives different type names for the _Float16, _Float32, etc. types than the more common half/float/double names. This adds support for people who use these types in SPIR-V kernels.
> [OpaquePointers] Demangle _Float* correctly for determining argument types.

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_bfloat16.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_tf32.ll
It specifies how to interpret 'Component Type' when components of a joint matrix are storages for values of different types, for example float for TF32, unsigned short for bfloat16.
At this point only tf32 type interpretation is added during SPIR-V generation. Adding it to bf16 is a breaking change and
requires adaptation across drivers.
Spec update:
https://github.com/intel/llvm/pull/8175
> Add ComponentTypeInterpretation for joint matrix type

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/NonSemanticKernel100/FortranArray.ll
- test/DebugInfo/NonSemanticKernel100/FortranDynamicArrayExpr.ll
- test/DebugInfo/NonSemanticKernel100/FortranDynamicArrayVar.ll
This instruction describes a dynamic array, mostly for Fortran 90.
Unlike DebugTypeArray it has Data Location, Associated, Allocated and Rank parameters. If the appropriate metadata parameters appear in LLVM IR in DW_TAG_array_type metadata, then such debug type becomes treated as dynamic array by the translator (of course if the appopriate extended instruction set is enabled).
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/pull/186
> [DebugInfo] Add DebugTypeArrayDynamic translation

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/NonSemanticKernel100/DebugInfoStringType.ll
This type instruction describes a string, mostly for Fortran 90.
Spec:
KhronosGroup/SPIRV-Registry#186
> [DebugInfo] Support translation of DIStringType

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/NonSemanticKernel100/DIModule.ll
This entity represents a module in the programming language, for example a Fortran module.
Spec:
KhronosGroup/SPIRV-Registry#186
The implementation is the same as for SPV_INTEL_debug_module extension. Spec for extension:
https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_debug_module.asciidoc
> [DebugInfo] Support translation of DIModule

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVBuiltinHelper.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/spirv-target-types.ll
The target extension type for SPIR-V is essentially target("spirv.TypeName", <image type>, <int params>).
Most of the work to support translation of these types has already happened beforehand, so the primary step here is to enable translation work in SPIRVWriter as well as making the SPIRVBuiltinHelpers work with target types as well.
Constructing LLVM IR from SPIR-V using these types is not yet supported, mainly out of uncertainty of the proper interface to let the resultant consumers indicate that they wish to support these types.
> [OpaquePointers] Add support for translating target extension types.

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
Node.js 12 actions are deprecated, so update to v3 which uses Node 16.
See also https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> [CI] Upgrade to actions/checkout@v3

- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
Despite multiple inheritance static_cast from 'SPIRVEntry *' to 'SPIRVFunction *' should be safe. Replacing static_cast with dynamic_cast would be even safer, but it would add extra runtime overhead. So add ignore this clang-tidy check.
> [NFC] Add NOLINTNEXTLINE for static_cast

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/DebugFunction.cl
- test/DebugInfo/DebugInfoSubrangeWithOnlyCount.spt
- test/DebugInfo/Generic/tu-member-opaque.spvasm
- test/DebugInfo/NonSemantic/DebugFunction.cl
- test/DebugInfo/NonSemantic/Shader200/DIModule.ll
- test/DebugInfo/NonSemantic/Shader200/DebugInfoSubrange.ll
- test/DebugInfo/NonSemantic/Shader200/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/OpenCL100/DebugInfoSubrange.ll
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
This patch fixes the discovered typos in Debug Instruction names, so we can generate spec-conformant SPIR-V module.
https://registry.khronos.org/SPIR-V/specs/unified1/DebugInfo.html
> [NFC][DebugInfo] Align Instruction names to the specification

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_memory_attributes/IntelFPGAMemoryAttributes.ll
- test/extensions/INTEL/SPV_INTEL_fpga_memory_attributes/IntelFPGAMemoryAttributesForStruct.ll
UserSemantic's handling is done alike to other decorations. However, we should preserve the braces so we save the full input string during the forward and reverse translation.
> Translate annotation string with the braces for UserSemantic decoration

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/transcoding/block_w_struct_return.cl
- test/transcoding/enqueue_kernel.cl
- test/transcoding/global_block.cl
This specifies the right parameter types for EnqueueKernel and for block
functions (with mangled names of the form {__*,}_block_invoke{_*,}{_kernel,}),
so that SPIR-V code is generated for these as expected. This fixes a
crash in the Intel OpenCL CPU backend, and likely other SPIR-V
consumers.
> [OpaquePointers] Fix translation of EnqueueKernel and block functions

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoLowerBound.ll
This goal is to have compability beteen pre llvm14 and after llvm14 translator versions while translating DbgArrayType. E.g.
llvm_release_100 -> .spv -> llvm_release_140
llvm_release_140 -> .spv -> llvm_release_100
> Improve DbgArrayType compability

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfoLowerBound.ll
llvm11+ has UpperBound and LowerBound as metadata. This commit implements a loop the same way it is implemented in new translator versions(llvm14+)
> Improve DbgArrayType compatibility

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/SPV_INTEL_variable_length_array/complex-cfg.ll
VLAs were translated in section where non-instruction SPIR-V values are translated. However translation of them produce LLVM IR instructions. This patch moves translation of VLAs to the proper place where other instructions are created, so the placeholder creation logic also works for them. This fixes the case when VLA used in complex control flow graph caused producing of invalid LLVM module during reverse translation.
> [Backmerge to 13] Fix SPIRV->LLVM translation of variable lenght arrays

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin-vars-gep.ll
- test/transcoding/builtin_vars_gep.ll
The existing logic for the replacement of builtin variables with calls to functions relies on relatively brittle tracking that is broken when opaque pointers is turned on, and will be even more thoroughly broken if/when typed geps are replaced with i8 geps or ptradd. This patch replaces that logic with a less brittle variant that is able to handle any sequence of bitcast, gep, or addrspacecast instructions between the global variable and the ultimate load instruction.
It still will error out if the variable is used in too insane of a fashion (say, trying to load an i32 out of the i64, or a misaligned vector type).
> [OpaquePointers] Adjust builtin variable tracking to support i8 geps.

- test/GroupAndSubgroupInstructions.spvasm
- test/spirv-tools-dis.ll
After SPIRV-Tools commit 2e0f4b52 ("tools: refactorize tools flags parsing. (#5111)", 2023-02-27), spirv-as needs to be told explicitly when reading from stdin.
> Update spirv-as invocations

- lib/SPIRV/SPIRVReader.cpp
- test/create-placeholders-for-phi-operands.ll
- test/transcoding/SPV_INTEL_variable_length_array/complex-cfg.ll
VLAs were translated in section where non-instruction SPIR-V values are translated. However translation of them produce LLVM IR instructions. This patch moves translation of VLAs to the proper place where other instructions are created, so the placeholder creation logic also works for them. This fixes the case when VLA used in complex control flow graph caused producing of invalid LLVM module during reverse translation.
> [Backmerge to 10] Fix SPIRV->LLVM translation of variable lenght arrays

- lib/SPIRV/SPIRVReader.cpp
- test/create-placeholders-for-phi-operands.ll
- test/transcoding/SPV_INTEL_variable_length_array/complex-cfg.ll
VLAs were translated in section where non-instruction SPIR-V values are translated. However translation of them produce LLVM IR instructions. This patch moves translation of VLAs to the proper place where other instructions are created, so the placeholder creation logic also works for them. This fixes the case when VLA used in complex control flow graph caused producing of invalid LLVM module during reverse translation.
> [Backmerge to 12] Fix SPIRV->LLVM translation of variable lenght arrays

- lib/SPIRV/SPIRVReader.cpp
Transforming dynamic casts to casts to handle issue with possible dereference of null return values since it makes asserts that the cast are successful & doesn't fail.
> Static analyzer fixes: dereference null return values

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_buffer_location/FPGABufferLocation.ll
Fix the `ptr.annotation` in reverse translator such that the generated pointer annotation call is being used properly in the IR.
The IR generated from the previous code base is:
```
%0 = xxx
%1 = ptr.annotation %0 ...  (left unused)
%2 = load %0 ...
```
while the expected form is:
```
%0 = xxx
%1 = ptr.annotation %0 ...
%2 = load %1 ...
```
> fix the ptr.annotation generation in reverse translator

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Ensure that ExprLB is non-NULL before using it.
> [NFC] Check for nullptr from getDbgInst

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoLowerBound.ll
Backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1897
> [Backmerge to 9] Improve DbgArrayType compatibility

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/SPV_INTEL_variable_length_array/complex-cfg.ll
VLAs were translated in section where non-instruction SPIR-V values are translated. Hovewer translation of them produce LLVM IR instructions. This patch moves translation of VLAs to the proper place where other instructions are created, so the placeholder creation logic also works for them. This fixes the case when VLA used in complex control flow graph caused producing of invalid LLVM module during reverse translation.
> [Backmerge to 11] Fix SPIRV->LLVM translation of variable lenght arrays

- include/LLVMSPIRVExtensions.inc
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_tensor_float32_conversion/convert_tensor_float32.ll
Extension name will be preserved for a while for binary compatibility.
> [Backport to 15] Rename ConvertFToTF32INTEL to RoundFToTF32INTEL

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfoLowerBound.ll
Backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1901
> [Backmerge to 11] Improve DbgArrayType compatibility (#1901)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/Shader200/FortranComplex.ll
- tools/llvm-spirv/llvm-spirv.cpp
It's mapped on new Encoding value for DebugBasicType in NonSemantic.Shader.DebugInfo.200 spec.
If another DebugInfo instruction set is specified - it's mapped to DW_TAG_unspecified_type
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/pull/186 (TBD)
> [DebugInfo] Add DW_ATE_complex_float translation

- lib/SPIRV/CMakeLists.txt
Move the LLVM components to LINK_COMPONENTS because the DEPENDS list has the same semantics as add_dependencies(). In this
case it doesn't include the LLVM components when calling the linker.
It's almost complete revert of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1543
> Fix standalone builds with LLVM_LINK_LLVM_DYLIB=ON

- lib/SPIRV/SPIRVReader.cpp
Convert dyn_cast to cast for uses with no nullptr check.
> [NFC] Fix misuse of dyn_cast

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/Generic/c-and-cpp-mixed.ll
- test/DebugInfo/X86/mixed-nodebug-cu.ll
- test/DebugInfo/X86/split-dwarf-omit-empty.ll
It's possible for LLVM IR module to contain multiple CU in case if this module is a result
of llvm-link between two modules compiled for different languages and or compiled with
different options.
This patch introduces handling of such modules.
std::unordered_map<SPIRVId, std::unique_ptr<DIBuilder>> BuilderMap was introduced
to SPIR-V consumption part and
std::unordered_map<const DICompileUnit *, SPIRVExtInst *> SPIRVCUMap was introduced
to SPIR-V generation part to preserve Scope relations between DI metadata in SPIR-V and vice versa.
Note, that DIBuilder has a single CU field and this class is not trivially copiable.
> [DebugInfo] Support multiple CompileUnits

- lib/SPIRV/SPIRVUtil.cpp
Fix the build after llvm-project commit 7c59e8001a3b ("Reland: [Demangle] replace use of llvm::StringView w/ std::string_view", 2023-04-20).
> Update for llvm::StringView removal

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/DebugInfoProducer.ll
Keep existing W/A (emit `ModuleProcessed` instruction - introduced by 601e4a5) for other debug info specs, except NonSemantic.Shader.DebugInfo.100
> [DebugInfo] Add module producer info for NonSemantic.Shader.DebugInfo.200

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
`PointerType::get(Context` will return typeless/opaque pointer. While it is OK for KHR translator since it's being built on top of LLVM trunk, where opaque pointers are enabled by default - it won't work for intel/llvm, where their generation is disabled.
Upstream of https://github.com/intel/llvm/pull/9118
> [NFC] Use typed pointers for null function pointers debug info

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/relationals_select.ll
According OpenCL spec, the relationals builtin function shall return a '1' if the specified relation is true for scalar argument types. The functions shall return a '-1' (i.e. all bits set) if the specified relation is true for vector argument types.
> Fix relationals builtin translation bug

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/TransTypeCompositeCaseClass_.ll
Tag should be OpConstant, not Literal.
> [DebugInfo] Fix Composite type translation for NonSemantic spec

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/NonSemantic/DebugFunction.cl
- test/DebugInfo/NonSemantic/DebugInfoProducer.ll
- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
This instruction is generated for DWARF `DISPFlagMainSubprogram` flag of function as well as for `spir_kernel` functions.
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugEntryPoint
> [DebugInfo] Support translation of DebugEntryPoint instruction

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_masked_gather_scatter/intel-gather-scatter.ll
It prevents their declaration from generation in case if SPV_INTEL_masked_gather_scatter and -spirv-allow-unknown-intrinsics are both enabled.
> [NFC] Add gather/scatter intrinsics to 'known'

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
Some SPIR-V producers generate invalid source language value (invalid = other than the enum values defined in spv::SourceLanguage). While in many cases this is rightly translated to DW_LANG_OpenCL, the original source language value should be preserved in LLVM module metadata for later use by LLVM IR consumers.
I will talk about this change during the next OpenCL Tooling call.
> Preserve invalid SPIRV source lang literal in module metadata

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/Shader200/InlineNamespace.ll
In NonSemantic.Shader.DebugInfo.200 `DebugLexicalBlock` has Inline namespace parameter, which specifies if C++ namespace is inline or not. 
It allows us to save `exportSymbols` field of `DINamespace` metadata.
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/pull/186/
> [DebugInfo] Translate inline namespace debug info

- lib/SPIRV/CMakeLists.txt
Move the LLVM components to LINK_COMPONENTS because the DEPENDS list has the same semantics as add_dependencies(). In this case it doesn't include the LLVM components when calling the linker.
It's almost complete revert of #1543
> [Backport to 16] Fix standalone builds with LLVM_LINK_LLVM_DYLIB=ON

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Before reading Target function name operand of `DebugFunction` we need to make sure it's the translation of appropriate debug extension. Otherwise, we can get in a situation, where we do have 11 operands, but the last one is not a `String` with name, but the `DebugFunctionDeclaration`.
Also added more checks for differing operand numbers in different debug specs.
This is a follow-up/alignment fix for: 55ce223 and 02d37bb
> [DebugInfo] Fix translation of Target Function operand

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVTypeScavenger.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/OpenCL.std/printf.spvasm
- test/extensions/EXT/SPV_EXT_relaxed_printf_string_address_space/non-constant-printf.ll
- test/extensions/INTEL/SPV_INTEL_fpga_buffer_location/FPGABufferLocation.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/const-function-pointer.ll
- test/extensions/INTEL/intel-basic-vector-pointers-opaque.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/OpSwitchChar.ll
- test/transcoding/constant-vars.ll
- test/transcoding/global_block.cl
- test/type-scavenger/call.ll
- test/type-scavenger/globals.ll
- test/type-scavenger/load-indirect.ll
- test/type-scavenger/recursive-type.ll
This is a massive change, which consists of the following pieces that are not so easily seperable (why this is a large, single commit instead of many smaller ones):
* Use typed pointer types in the external interface of the scavenger.
* Use target extension types in lieu of DeferredType to represent types not yet known. These types are now target("typevar", N), where N is some integer.
* Use TypedPointerType in lieu of DeducedType. This makes multi-level pointer types simpler to use.
* Replace std::pair<unsigned, DeducedType> with a more generalized TypeRule class, which simplifies some of the rules for the typing procedure.
* Make computePointerElementType and correctUseTypes both rely on the same list of type rules, removing duplication.
* Add support for vectors of pointers, arrays of …
> [OpaquePointers] Rewrite the type scavenger.

- test/DebugInfo/NonSemantic/DebugInfoProducer.ll
There is a bug in `-r -spirv-text` mode in translation of Strings with spaces.
Temporary avoid running such pipeline until proper fix is delivered.
> [NFC][DebugInfo] Rewrite `NonSemantic/DebugInfoProducer` test

- README.md
- tools/llvm-spirv/llvm-spirv.cpp
In https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/667bf137eeda7af93b482552c8959376e9565fc1 we renamed
`-spirv-ocl-builtins-version` to `-spirv-target-env` but we missed updating a couple of spots.
> [NFC] Update missed error msg/doc with rename of -spirv-ocl-builtins-version

- test/DebugInfo/NonSemantic/DebugFunction.cl
It fails in out-of-tree build because the debug info producer looks different for pre-installed LLVM compiler, e.g.:
`Ubuntu clang version 17.0.0 (++20230502031405+3e850a6`
> Fix DebugFunction test

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
Some SPIR-V producers generate invalid source language value (invalid = other than the enum values defined in spv::SourceLanguage). While in many cases this is rightly translated to DW_LANG_OpenCL, the original source language value should be preserved in LLVM module metadata for later use by LLVM IR consumers.
> [Backport to 15] Preserve invalid SPIRV source lang literal in module metadata

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoLLVMArg.ll
DebugOperation is updated adding (in a scope of NonSemantic.Shader.DebugInfo.200):
If Operation is Arg, the DebugOperation has only
one optional operand, which is <id> of a non-debug instruction whose value is used as an argument of a debug expression.
> [DebugInfo] Translate DW_OP_LLVM_arg with more then one parameter

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/relationals_select.ll
According OpenCL spec, the relationals builtin function shall return a '1' if the specified relation is true for scalar argument types. The functions shall return a '-1' (i.e. all bits set) if the specified relation is true for vector argument types.
> [Backport to 16] Fix relationals builtin translation bug (#1962)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
Some SPIR-V producers generate invalid source language value (invalid =
other than the enum values defined in spv::SourceLanguage). While in
many cases this is rightly translated to DW_LANG_OpenCL, the original
source language value should be preserved in LLVM module metadata for
later use by LLVM IR consumers.
Co-authored-by: Michal Paszkowski <michal@paszkowski.org>
> [Backport to 9] Preserve invalid SPIRV source lang literal in module metadata (#1951) (#1992)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
Some SPIR-V producers generate invalid source language value (invalid =
other than the enum values defined in spv::SourceLanguage). While in
many cases this is rightly translated to DW_LANG_OpenCL, the original
source language value should be preserved in LLVM module metadata for
later use by LLVM IR consumers.
Co-authored-by: Michal Paszkowski <michal@paszkowski.org>
> [Backport to 11] Preserve invalid SPIRV source lang literal in module metadata (#1951) (#1992)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Handle the case when we have `DebugInfoNone` for the Text argument which is usually expected to be `OpString`.
> [DebugInfo] Fix translation of DebugSource Text argument

- lib/SPIRV/SPIRVWriter.cpp
The key used for uniquing the SPIR-V opaque types in transSPIRVOpaqueType uses a StringRef. The main use of transSPIRVOpaqueType call it on the name of the LLVM struct type, which lives for as long as the LLVM context is live. But the uses here were relying on a method that returns a std::string, which means the string is freed at the end of the function call, and the value stored in the map is therefore a use-after-free if there is ever another call to translate said type.
> [NFC] Avoid use-after-free in translating Constant* types.

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/builtin-functions.ll
- test/builtin-globals.ll
- tools/llvm-spirv/llvm-spirv.cpp
Currently, we always convert SPIR-V builtins to globals for forward translation and to functions for reverse translation.
I have a use case where I want to keep them as globals for reverse translation, so I added this mode.
Implemenations for both cases already existed, I just consolidated them and added the option.
> Add option to control builtin format for reverse translation

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/spirv-target-types-buffer.ll
This target extension type is created here: https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/lib/GenXIntrinsics/GenXSPIRVWriterAdaptor.cpp#L245
As with other target extension types, reverse translation is not yet supported.
> Support the spirv.BufferSurfaceINTEL target extension type

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/DebugInfo/storagePath_dwo.ll
LLVM compileUnit dwoId is translated to/from DebugBuildIdentifier.
LLVM compileUnit splitDebugFilename is translated to/from DebugStoragePath.
Specification:
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugBuildIdentifier
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugStoragePath
> [DebugInfo] Support translation of DebugBuildIdentifier/DebugStoragePath instruction

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/X86/rematerialize.ll
- test/DebugInfo/X86/sycl-vec-3.ll
- test/DebugInfo/X86/vector.ll
It should be OpConstant
Based on top of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2005
> [DebugInfo] Fix DebugTypeVector Component Count

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
It's a follow up for
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1996 since I couldn't update the PR
> [DebugInfo] Relax consumer checks for checksum info

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata.ll
It's already explicitly handled for forward and reverse translation, and it's a bit complicated to handle MDNode metadata. Just skip it so we don't assert.
If I see this come up in more cases I will add support for MDNode metadata.
> Skip spirv decoration metadata with --spirv-preserve-auxdata

- .github/workflows/check-code-style.yml
Ensure the code-formatting job uses clang to generate compile_commands.json, to avoid passing GCC-specific flags to clang-format or clang-tidy.
> [CI] Use clang to generate compile_commands

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/Shader200/DebugInfoSubrange.ll
- test/DebugInfo/NonSemantic/static_member_array.ll
- test/DebugInfo/OpenCL100/DebugInfoSubrange.ll
It no longer has a Scope (parent) parameter. It results in several changes including how to determine DIBuilder to use for debug info generation.
The patch also fixes a bug of incorrect debug info assignment in case of recursion DebugInfo inst generation.
> [DebugInfo] Adjust TypeMember for NonSemantic spec

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_buffer_location/FPGABufferLocation.ll
For a memcpy call, there also could be `ptr.annotation` generated before the src and dest pointer. Update the code to check `ptr.annotation` for OpCopyMemorySized and update lit test
> fix ptr.annotation in reverse translator for OpCopyMemorySized

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoProducer.ll
- test/DebugInfo/NonSemantic/DebugInfoProducer.ll
- test/DebugInfo/NonSemantic/Shader200/storagePath_dwo.ll
Only generate BuildIdentifier and StoragePath if non-semantic debug is enabled
> Only generate BuildIdentifier if non-semantic debug is enabled

- test/complex-constexpr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/select.ll
- test/layout.ll
- test/transcoding/AtomicCompareExchange_cl20.ll
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/spirv-private-array-initialization.ll
These tests generally require adjustments to their check lines to match opaque pointer output, or extra bitcasts, or the like correctly. For the function pointer tests in particular, some adjustments to the input IR have been made to minimize the impact on existing checks.
> [NFC] Adjust several lit tests to use opaque pointers.

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/DebugInfoTypeInheritance.ll
It does not have `Child` parameter comparing to OpenCL specification.
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc#DebugTypeInheritance
> [DebugInfo] Adjust TypeInheritance for NonSemantic spec

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/Generic/inlined-locations.ll
The change is done as a part of NonSemantic.Shader.200 spec, and the new arguments for the `DebugInlinedAt` instruction will look like:
| \<id\> Line| \<id\> Column| \<id\> Scope| Optional\<id\> Inlined|
|--------|--------|--------|--------|
> [DebugInfo] Add Column parameter to DebugInlinedAt instruction

- test/DebugInfo/Generic/c-and-cpp-mixed.ll
- test/DebugInfo/NonSemantic/Shader200/DebugInfoTargetFunction.ll
Update tests for llvm-project commit 4418434c6de7 ("[DebugMetadata] Simplify handling subprogram's retainedNodes field. NFCI (1/7)", 2023-06-07).
> Update DebugInfo tests after retainedNodes change

- test/DebugInfo/Generic/imported-name-inlined.ll
- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
- test/DebugInfo/X86/lexical-block-file-inline.ll
Update tests for llvm-project commit d80fdc6fc1a6
("[DebugMetadata][DwarfDebug] Fix DWARF emisson of function-local imported entities (3/7)", 2023-06-15).
> Update DebugInfo tests after DWARF emission fix

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-crash.ll
In `SPIRVReader`, we erase unused functions pretty late, but we were applying the ExtInst for `--spirv-preserve-auxdata` after that, causing us to try to work on a deleted function which lead to a crash.
This isn't a problem for the `SPIRVWriter` case because the unused function deletion happens way earlier.
> Fix crash with --spirv-preserve-auxdata and removed function

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/X86/DIModuleContext.ll
- test/DebugInfo/X86/Fortran-DIModule.ll
- test/DebugInfo/X86/dimodule-external-fortran.ll
We support `DebugModuleINTEL` instruction as a part of [SPV_INTEL_debug_module extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_debug_module.asciidoc).
We also support translation of `DebugModule` instruction as a part of NonSemantic.Shader.200 specification, which is basically the same as for DebugModuleINTEL (introduced in #1878).
There was a problem in reverse translation when the extension and NonSemantic.Shader.100 debug info is enabled, which is fixed by this patch.
The related tests cases are enabled back.
> [DebugInfo] Fix translation of SPV_INTEL_debug_module extension

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin-vars-gep.ll
- test/transcoding/builtin_vars_gep.ll
The existing logic for the replacement of builtin variables with calls to functions relies on relatively brittle tracking that is broken when opaque pointers is turned on, and will be even more thoroughly broken if/when typed geps are replaced with i8 geps or ptradd. This patch replaces that logic with a less brittle variant that is able to handle any sequence of bitcast, gep, or addrspacecast instructions between the global variable and the ultimate load instruction.
It still will error out if the variable is used in too insane of a fashion (say, trying to load an i32 out of the i64, or a misaligned vector type).
------------------------ Backport notes ---------------------
- This patch is backported as a fix to scalar reads from vector global variables.
- Replaced LLVM::APInt::isZero() …
> [Backport to 9] Adjust builtin variable tracking to support i8 geps

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin-vars-gep.ll
- test/transcoding/builtin_vars_gep.ll
The existing logic for the replacement of builtin variables with calls to functions relies on relatively brittle tracking that is broken when opaque pointers is turned on, and will be even more thoroughly broken if/when typed geps are replaced with i8 geps or ptradd. This patch replaces that logic with a less brittle variant that is able to handle any sequence of bitcast, gep, or addrspacecast instructions between the global variable and the ultimate load instruction.
It still will error out if the variable is used in too insane of a fashion (say, trying to load an i32 out of the i64, or a misaligned vector type).
> [Backport to 15][OpaquePointers] Adjust builtin variable tracking to support i8 geps

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin-vars-gep.ll
- test/transcoding/builtin_vars_gep.ll
The existing logic for the replacement of builtin variables with calls to functions relies on relatively brittle tracking that is broken when opaque pointers is turned on, and will be even more thoroughly broken if/when typed geps are replaced with i8 geps or ptradd. This patch replaces that logic with a less brittle variant that is able to handle any sequence of bitcast, gep, or addrspacecast instructions between the global variable and the ultimate load instruction.
It still will error out if the variable is used in too insane of a fashion (say, trying to load an i32 out of the i64, or a misaligned vector type).
------------------------- Backport notes -------------------------
- This patch is backported as a fix to scalar reads from vector global variables.
- Original test from …
> [Backport to 14] Adjust builtin variable tracking to support i8 geps

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/NonSemantic/Shader200/DebugTypeDef.ll
Compilation unit can be translated earlier, e.g. in `transEntryPoint()`. We should save the translated LLVM value to be used further.
> [DebugInfo] Cache CU value translated outside of usual flow

- lib/SPIRV/SPIRVReader.cpp
Update after llvm-project commit 3900860b386a ("[Support] Move StringExtras.h include from Error.h to Error.cpp", 2023-07-13).
> Update for StringExtras.h include change

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/NonSemantic/Shader200/DebugTypeDef.ll
Solving the same issue as / follow up for
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2072
Results of all transDebug... function are being stored in cache. This patch fixes a trivial error - we should not rewrite a 'good' value (if it exists) with nullptr.
> [DebugInfo] Correctly use cached DICompilationUnit

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
getNonOpaquePointerElementType is deprecated. This patch removes 3 calls to it where it's no longer require functional changes.
There are several more calls to this API, but it requires some follow changes at this moment.
> [OpaquePointers][NFC] Remove 3 calls of getNonOpaquePointerElementType

- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-crash.ll
The `-opaque-pointers` flag is no longer supported.
> [NFC] Remove last -opaque-pointers flag from test

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/freeze.ll
Workaround unsupported freeze insn by:
1. replacing uses of freeze's result with freeze's source or a random (but compilation reproducible) constant if freeze's source is undef/poison
2. deleting freeze insn.
Long term solution is to add a freeze instruction extension in SPIR-V.  Issue is tracked in (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1140)
> Workaround unsupported freeze insn

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/freeze.ll
Backport workaround for unsupported freeze instruction.
> [Backport to 16] Workaround unsupported freeze insn

- test/constexpr_phi.ll
Fix checks that were ineffective because the labels were incorrectly formed.  Check results were updated to make them pass.
> [NFC] Fix checks with incorrect labels

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
It is a temporary change to enable back CI until we change LLVM version
> [CI] Use llvm-toolchain-focal-17/ on the main branch

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-attrkind.ll
For AttrKind attributes, we need to convert them to the AttrKind enum before checking if it exists or adding it, otherwise it gets added as a string.
> Fix AttrKind attributes with --spirv-preserve-auxdata

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVUtil.cpp
- tools/llvm-spirv/llvm-spirv.cpp
Removes use of 
1. setOpaquePointer --> Can be removed without any side effect.
2. isOpaqueOrPointeeTypeMatches --> is always true.
Thanks
> [NFC][OpaquePointers] Remove deprecated functions: setOpaquePointer, isOpaqueOrPointeeTypeMatches

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
This commit changes "Source Lang Literal" flag from simple a scalar value to a vector of pairs: (compile unit, source language).
> Adjust "Source Lang Literal" logic to support multiple CompileUnits

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
This reverts commit 93b6d57759a12875810a215ef781ccb0e928f374 and should make CI pass again after merging #2097
> Revert "[CI] Use llvm-toolchain-focal-17/ on the main branch (#2104)"

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
After the first loop of deleting instructions in ValuesToDelete, deleted
instructions in ValuesToDelete are in an unstable state. Then in the
second loop of deleting, dyn_cast to GlobalValue could return true for
an instruction and double eraseFromParent causes crash. The crash is
observed in a multi-threaded test case.
Global values in ValuesToDelete are functions. Unused functions are
deleted by eraseUselessFunctions anyway.
> Fix delete of functions that becomes unused

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin-vars-gep.ll
- test/transcoding/builtin_vars_gep.ll
The existing logic for the replacement of builtin variables with calls to
functions relies on relatively brittle tracking that is broken when opaque
pointers is turned on, and will be even more thoroughly broken if/when typed
geps are replaced with i8 geps or ptradd. This patch replaces that logic with a
less brittle variant that is able to handle any sequence of bitcast, gep, or
addrspacecast instructions between the global variable and the ultimate load
instruction.
It still will error out if the variable is used in too insane of a fashion (say,
trying to load an i32 out of the i64, or a misaligned vector type).
> [Backport to 16] [OpaquePointers] Adjust builtin variable tracking to support i8 geps. (#1892)

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
After the first loop of deleting instructions in ValuesToDelete, deleted
instructions in ValuesToDelete are in an unstable state. Then in the
second loop of deleting, dyn_cast to GlobalValue could return true for
an instruction and double eraseFromParent causes crash.
Global values in ValuesToDelete are functions. Unused functions are
deleted by eraseUselessFunctions anyway.
(cherry picked from commit aea1ac74ed4301df12adbffff535f72f37d0bb13)
> [Backport to 14] Fix delete of functions that becomes unused

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
`TransOperand` is never called for StrideIdx (3), because the loop below ends at MinOperandCount (3).
> [NFC][DebugInfo] Remove unused code

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Change `auto` to `auto *` when the type is a pointer.  This makes the code comply with the clang-tidy `llvm-qualified-auto` check.  That check is already enabled, but the code base wasn't fully compliant yet.
> [NFC] Use `auto *` for pointer types

- include/LLVMSPIRVExtensions.inc
- test/extensions/EXT/SPV_EXT_image_raw10_raw12.spvasm
Add basic support for the SPV_EXT_image_raw10_raw12 extension [1] such that SPIR-V modules using the extension can be consumed.
[1] https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/EXT/SPV_EXT_image_raw10_raw12.asciidoc
> Add SPV_EXT_image_raw10_raw12 reader support

- lib/SPIRV/SPIRVReader.cpp
- test/create-placeholders-for-phi-operands.ll
- test/extensions/INTEL/SPV_INTEL_variable_length_array/basic.ll
- test/extensions/INTEL/SPV_INTEL_variable_length_array/negative.ll
- test/extensions/INTEL/SPV_INTEL_variable_length_array/vla_spec_const.ll
Intrinsics: Add type overload to stacksave and stackstore
This allows use with non-0 address space stacks. llvm_ptr_ty should
never be used. This could use some more percolation up through mlir,
but this is enough to fix existing tests.
https://reviews.llvm.org/D156666
> [NFC] Update stacksave and stackrestore after 25bc999d

- .github/workflows/check-code-style.yml
- lib/SPIRV/SPIRVReader.cpp
Ensure the correct clang-format binary is picked up, as `clang-format-diff.py` currently seems to look for clang-format-17 while we install clang-format-18.
> [CI] Explicitly set clang-format binary

- lib/SPIRV/SPIRVWriter.cpp
- test/negative/extension_from_metadata.ll
When translating the `spirv.Extension` metadata of an LLVM Module, report an error when encountering an extension that has been explicitly disabled.
> Report disallowed extensions in metadata

- test/SpecConstants/bool-spirv-specconstant.ll
- test/llvm-intrinsics/bswap.ll
- test/llvm-intrinsics/dynamic-memmove.ll
- test/llvm-intrinsics/instrprof.ll
- test/llvm-intrinsics/invariant.ll
- test/llvm-intrinsics/sadd.with.overflow.ll
- test/llvm-intrinsics/trap.ll
- test/llvm-intrinsics/umul.with.overflow.ll
This is a bulk conversion done using the migration script.
> Convert SpecConstants+intrinsics tests to opaque pointers

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fpclass.ll
After bitcast float to integer we should use not SAbs but UAbs call. But since UAbs is a bit useless - we shouldn't generate *Abs at all.
> Fix is.fpclass intrinsic emulation

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/type-scavenger/equivalence.ll
Correctly find equivalence class in type scavenger.
> [OpaquePointers] Correctly find leader of EC in type scavenger

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/KHR/SPV_KHR_bit_instructions/capabilities.ll
Requiring the `Shader` capability for any module that uses `llvm.bitreverse` is problematic for OpenCL execution environments. Only require the `Shader` capability if we cannot use the `BitInstructions` capability.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2139
> Only require Shader capability if unavoidable

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/array_of_matrices.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/array_of_matrices.ll
visit method of the sort relies on getNonLiteralOperands method of the
SPIRVType which is being inserted in the module. Without it dependent
types can be inserted in the module in incorrect order.
For example:
TypeCooperativeMatrixKHR %ID%
TypeStruct ... %ID%
is the correct order, but without the patch in some cases the translator
could generate the opposite order.
> Fix TopologicalSort for Joint and Cooperative matrices

- CONTRIBUTING.md
- test/DebugInfo/lit.local.cfg
We have been using GitHub Actions on the `main` branch for a while now, but there were still some dangling references to Travis.
> [NFC] Update Travis references to GitHub Actions

- test/extensions/INTEL/SPV_INTEL_fp_max_error/IntelFPMaxError.ll
This issue was exposed by some additional testing. 
ldexp takes a float and an int as inputs and not float and float as shown here.
Thanks
> Fix ldexp builtin prototype in one of LIT tests

- docs/SPIRVRepresentationInLLVM.rst
- include/LLVMSPIRVExtensions.inc
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_cache_controls/basic_load_store.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/global_var.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/kernel_arg.ll
Specification: https://github.com/KhronosGroup/SPIRV-Registry/pull/216
> [Backmerge, LLVM16] Support for SPV_INTEL_cache_controls

- docs/SPIRVRepresentationInLLVM.rst
- include/LLVMSPIRVExtensions.inc
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_cache_controls/basic_load_store.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/global_var.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/kernel_arg.ll
Specification: https://github.com/KhronosGroup/SPIRV-Registry/pull/216
> [Backmerge, LLVM14] Support for SPV_INTEL_cache_controls

- test/DebugInfo/Generic/c-and-cpp-mixed.ll
- test/extensions/EXT/SPV_EXT_relaxed_printf_string_address_space/non-constant-printf.ll
- test/transcoding/global-constant-expression.ll
- test/transcoding/spirv-private-array-initialization.ll
Manually convert some tests to opaque pointers that the migration script did not handle correctly.
> Manually convert tests to opaque pointers

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fpclass.ll
We should compare not only to zero integer, but also 'negated' zero.
This PR is built in top of: Fix check for (neg) zero for fpclass emulation #2151
> Fix check for (neg) zero for fpclass emulation

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_cooperative_matrix.asciidoc
> Support forward translation of arithmetic instructions for TypeCooperativeMatrixKHR

- test/transcoding/CreatePipeFromPipeStorage.ll
- test/transcoding/OpPhi_ArgumentsPlaceholders.ll
- test/transcoding/annotate_attribute.ll
- test/transcoding/extract_insert_value.ll
- test/transcoding/intrinsic_result_store.ll
- test/transcoding/memory_access.ll
- test/transcoding/spirv-private-array-initialization.ll
This converts the remaining transcoding tests that weren't converted in previous PRs.
> Convert remaining transcoding tests to opaque pointers

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/ubsantrap.ll
It's the similar case as llvm.trap intrinsic - the preferred way is to ignore it in the translator.
> Ignore llvm.ubsantrap intrinsic

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_different_type.ll
In some cases, we will see IR with the following
```
@__spirv_BuiltInGlobalInvocationId = external dso_local local_unnamed_addr addrspace(1) constant <3 x i64>, align 32
...
%0 = load <6 x i32>, ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, align 32
%1 = extractelement <6 x i32> %0, i64 0
```
Note the global type and load type are different. Change the handling of vector loads from vector globals to reconstruct the global vector type and then bitcast to the load type.
Thanks to @jcranmer-intel for helping me find the simplest solution.
> Fix SPIR-V global to function replacement for differing load types

- lib/SPIRV/SPIRVWriter.cpp
Definition of StringRef.consume_front also performs prefix check. It makes additional check redundant.
> [NFC] Remove unnecessary prefix check in LLVMToSPIRVBase::getFPBuiltinType

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
Implement translation via SPIR-V friendly calls, as:
1. the LLVM instructions are not capable to accept target extension types;
2. matrix arithmetic instructions require additional carry additional rules, which LLVM can not perform (for example while technically Add for vectors and (flattened) matrices is the same - yet for matrices we need to perform extra checks, also mul instruction is complitely different).
As for now some BE would need to recognize and define what to do with a call to __spirv_FMul(matrixA, matrixB). Better option is to map such SPIR-V to an intrinsic or define an appropriate type in LLVM (hence defining rules for GEP and other instructions) , but it's off the table now.
> Reverse translation of arithmetic instructions for cooperative matrixes

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/access_store.ll
Implement translation via SPIR-V friendly calls, as:
1. the LLVM instructions are not capable to accept target extension types;
2. cooperative matrix is an opaque object and accessing elements is implementation defined, hence we can't use GEP to which AccessChain naturally maps, since GEP has a different meaning.
As for now some BE would need to recognize and define what to do with a call to __spirv_AccessChain(matrix, index). Better option is to map such SPIR-V to an intrinsic or define an appropriate type in LLVM (hence defining rules for GEP and other instructions) , but it's off the table now.
> Reverse translation of access + load/store operations for cooperative matrix

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/NonSemantic.AuxData.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-attrkind.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-crash.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata-debug.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata.ll
- tools/llvm-spirv/llvm-spirv.cpp
Backport the below changes to 14:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/f729c493a48d547fed2cd4f1fc38e8df77bfdbea
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/89d658c2ebf41ec514bdc6c09e8f8aa117cae46f
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/9823690a9ef43655e6d3fb7818c586bf57cf8091
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/d498f485cbcb242ff19c74b8fcd8ef28a6328b53
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/d24b9c645c637ff54027a528a29e5fe1d4582459
I made the following changes that are not in the original changes:
1) Use llvm::Optional instead of std::optional 
2) Port tests to not use opaque pointers and related flags
3) Fix patch fail due to missing unrelated function in this branch
> [Backport to 14] Backport spirv-preserve-auxdata changes

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/NonSemantic.AuxData.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-attrkind.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-crash.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata-debug.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata.ll
- tools/llvm-spirv/llvm-spirv.cpp
Backport the below changes to 15:
f729c49
89d658c
9823690
d498f48
d24b9c6
I made the following changes that are not in the original changes:
Use llvm::Optional instead of std::optional
Port tests to not use opaque pointers and related flags
Fix patch fail due to missing unrelated function in this branch
Make some locals const as per clang-tidy
> [Backport to 15] Backport spirv-preserve-auxdata changes

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/NonSemantic.AuxData.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-attrkind.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes-crash.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-attributes.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata-debug.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-all-function-metadata.ll
- tools/llvm-spirv/llvm-spirv.cpp
Backport the below changes to 16:
f729c49
89d658c
9823690
d498f48
d24b9c6
I made the following changes that are not in the original changes:
Port tests to not use opaque pointers
Fix patch fail due to missing unrelated function in this branch
> [Backport to 16] Backport spirv-preserve-auxdata changes

- test/DebugInfo/NonSemantic/DebugFunction.cl
Addresses https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2176
> do not rely on version of compiler being $VER.0.0

- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
Added -DAG to CHECK for DebugFunction. It's better not to relax order of checks for debug info instructions, but in this case it should be OK as the main purpose of the test is not about DebugFunction.
> [NFC] Align FortranArray.ll test

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
Follow-up to the opaque pointer transition llvm/llvm-project@7b9d73c2f90
> [NFC] Remove Type::getInt8PtrTy after 7b9d73c2f90

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
The patch added extra parameter to StaticMemberType for differentiation between DW_TAG_variable and DW_TAG_member in DWARF5.
> [NFC] Fix build after da90fd7524

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
This PR aims to introduce CooperativeMatrixPrefetchINTEL capability and operation, and make initial introduction of entities in llvm-spirv translator.
> support joint matrix prefetch

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
d0ae2391 adds RunTimeLang parameter to createEnumerationType function.
Use default value for the new parameter.
> [NFC] Fix build after llvm commit d0ae2391

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/bf16_conversion_instructions.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/tf32_conversion_instructions.ll
Previously added scalar/vector ConvertFToBF16INTEL, ConvertBF16ToFINTEL and RoundFToTF32INTEL conversions are now enabled for cooperative matrix type under SPV_INTEL_joint_matrix extension following the spec: https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix.asciidoc
Note, joint matrices are not allowed as input/output for these conversions as it is being deprecated.
> Enable BFloat16 and TensorFloat32 conversions for cooperative matrices

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_apply.ll
This PR aims to introduce entities related to OpCooperativeMatrixApplyFunctionINTEL in llvm-spirv translator, according to https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix.asciidoc.
TODO update the spec
> Add OpCooperativeMatrixApplyFunctionINTEL instruction

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_element.ll
This is a backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/dd8b2176414e40b60b49a68c0e10c2efb1baa77b
The instruction returns (Row, Column) coordinate of dynamically selected element of a matrix
Updated version of the spec is here
intel/llvm#8175
Instruction correctness checks will be added later among non-backward compatible changes.
Signed-off-by: Sidorov, Dmitry dmitry.sidorov@intel.com
> [Backport to 14] Add JointMatrixGetElementCoordINTEL instruction

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_element.ll
This is a backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/dd8b2176414e40b60b49a68c0e10c2efb1baa77b
The instruction returns (Row, Column) coordinate of dynamically selected element of a matrix
Updated version of the spec is here
intel/llvm#8175
Instruction correctness checks will be added later among non-backward compatible changes.
> [Backport to 15] Add JointMatrixGetElementCoordINTEL instruction

- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/bf16_conversion_instructions.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_apply.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/tf32_conversion_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/array_of_matrices.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/conversion_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix_wrong_scope.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix_wrong_use.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/matrix_times_scalar.ll
Use should be: MatrixA, MatrixB or Accumulator.
Scope must be at max Invocation (others are not supported
by the translator).
> Add error checking for cooperative matrix use and scope parameters

- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
Change Scope argument to one of two available options: ScopeWorkgroup/ScopeWorkgroup.
> Fix cooperative matrix prefetch test (scope parameter)

- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
The goal is to fix the KHT cooperative matrix test by putting arguments order for CooperativeMatrixLoadKHR() function invocation in correspondence with the extension doc (https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_cooperative_matrix.asciidoc#3428-memory-instructions)
> Fix KHT cooperative matrix test

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_memory_accesses/fpga_lsu_function_call.ll
This fixes reverse translation for SPV_INTEL_fpga_memory_accesses. Theoretically it fixes more, but seems like without the extension we don't generate UserSemantic decoration in this case at all. Will be investigated separately.
> Fix reverse translation for a decoration applied to a function parameter

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_different_type.ll
In some cases, we will see IR with the following
@__spirv_BuiltInGlobalInvocationId = external dso_local local_unnamed_addr addrspace(1) constant <3 x i64>, align 32
...
%0 = load <6 x i32>, ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, align 32 %1 = extractelement <6 x i32> %0, i64 0
Note the global type and load type are different. Change the handling of vector loads from vector globals to reconstruct the global vector type and then bitcast to the load type.
Thanks to @jcranmer-intel for helping me find the simplest solution.
> [Backport to 9] Fix SPIR-V global to function replacement for differing load types

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_different_type.ll
In some cases, we will see IR with the following
@__spirv_BuiltInGlobalInvocationId = external dso_local local_unnamed_addr addrspace(1) constant <3 x i64>, align 32
...
%0 = load <6 x i32>, ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, align 32 %1 = extractelement <6 x i32> %0, i64 0
Note the global type and load type are different. Change the handling of vector loads from vector globals to reconstruct the global vector type and then bitcast to the load type.
Thanks to @jcranmer-intel for helping me find the simplest solution.
> [Backport to 14] Fix SPIR-V global to function replacement for differing load types

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_memory_accesses/IntelFPGAMemoryAccesses.ll
- test/extensions/INTEL/SPV_INTEL_fpga_memory_accesses/intel_fpga_lsu_optimized.ll
- test/extensions/INTEL/SPV_INTEL_fpga_memory_attributes/IntelFPGAMemoryAttributesForStruct.ll
- test/transcoding/annotate_attribute.ll
- test/transcoding/annotation_generic_decoration.ll
- test/transcoding/multiple_user_semantic.ll
- test/transcoding/multiple_user_semantic_nonopaque.ll
- test/transcoding/multiple_user_semantic_on_struct.ll
There is a fundamental misalignment between when translating llvm.ptr.annotation to [SPIRV's OpMemberDecorate](https://registry.khronos.org/SPIR-V/specs/1.0/SPIRV.html#OpMemberDecorate).
llvm.ptr.annotation is applied onto a pointer.
OpMemberDecorate is applied on a type, which means that all variables of this type will have this Decoration.
This change fixes this misalignment by translating llvm.ptr.annotation to [SPIRV's OpDecorate](https://registry.khronos.org/SPIR-V/specs/1.0/SPIRV.html#OpDecorate) instead, which instead places the decoration onto the pointer.
> Fixing Intrinsic::ptr_annotation

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
The following warning used to appear:
SPIRVInstruction.h:3745:23: warning: ISO C++11 requires at least one argument for the "..." in a variadic macro _SPIRV_OP(ReadClockKHR)
> Fix warning with variadic macro

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
Replace instances of `getInt8PtrTy` after llvm commit llvm/llvm-project@6cd7500ae690 ("[llvm][IR] Remove method IRBuilderBase::getInt8PtrTy (#74096)", 2023-12-01).
> Update after getInt8PtrTy LLVM API removal

- lib/SPIRV/SPIRVWriter.cpp
- test/FCmpFalse.ll
- test/FCmpFalse_Vec.ll
There is no direct equivalent for "fcmp false" in the specification [https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_relational_and_logical_instructions], but we may return ConstantFalse in this case instead of reporting error.
This patch depends on https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2216
> add support for the 'fcmp false' instruction

- README.md
The previous badges were no longer reflecting the current status, always showing green.
> README.md: Update status badge URLs

- lib/SPIRV/OCLToSPIRV.cpp
Pointer named Expected was taken by reference to closure to be executed later by Mutator. Mutator executes the closure in his destructor which happens after the destruction of Expected pointer stack frame. This fix clears some ASan errors from #2233.
> Access out of scope fix in OCLToSPIRVBase::visitCallAtomicCmpXchg

- lib/SPIRV/SPIRVWriter.cpp
Allocated SPIRVExecutionMode class wasn't added as dependant resource in SPIRVModule. Fix some ASan errors in issue #2233.
> Memory leak fix in LLVMToSPIRVBase::transExecutionMode

- lib/SPIRV/SPIRVReader.cpp
- test/composite_construct_struct_non_constant.spt
This patch introduces a way to use runtime values for structure fields.
> Fix reverse translation of non-constant values of OpCompositeConstruct

- README.md
Mention explicitly in the README that only SPIR-V modules that declare the `Kernel` capability are supported.  This is a key restriction for anyone looking to translate between (arbitrary) SPIR-V and LLVM IR, so mention it at the top of the README.
This came up in the OpenCL Tooling TSG call of Dec 14th; tagging @asudarsa, @bashbaug, @keryell.
> README.md: State Kernel capability restriction

- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
Replace with the `{starts,ends}_with` variants, after LLVM commit llvm/llvm-project@5ac12951b4e9 ("[ADT] Deprecate StringRef::{starts,ends}with (#75491)", 2023-12-17).
This is a mechanical change applied using:
```
git grep -l startswith | xargs sed -i -e 's/startswith/starts_with/g'
git grep -l endswith | xargs sed -i -e 's/endswith/ends_with/g'
```
> Update for StringRef::{starts,ends}with deprecation

- lib/SPIRV/libSPIRV/SPIRVStream.cpp
SPIRVEntry created in function getEntry isn't deleted when it is ExtOp and isn't SourceContinued. Fixes most of ASan errors in issue #2233.
> Memory leak fix in SPIRVDecoder::getSourceContinuedInstructions

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/SPV_INTEL_function_pointers/global_ctor_dtor_opaque.spt
When SPV is generated from LLVM IR with opaque pointer enabled, ctor
function in global ctors has opaque pointer type rather than function
type. When translating the SPV back to LLVM IR with typed pointer like
in LLVM 14, ctor function type is casted to i8* pointer in the global
ctors initializer. This results in error in LLVM verifier.
This PR fixes the issue by removing the cast.
> [SPV->LLVM] Fix global c/dtors type if SPV is from opaque type LLVM

- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/PreprocessMetadata.h
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.h
- lib/SPIRV/SPIRVLowerBool.h
- lib/SPIRV/SPIRVLowerConstExpr.h
- lib/SPIRV/SPIRVLowerMemmove.h
- lib/SPIRV/SPIRVLowerOCLBlocks.h
- lib/SPIRV/SPIRVLowerSaddWithOverflow.h
- lib/SPIRV/SPIRVRegularizeLLVM.h
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVWriter.h
When these passes are used in LLVM new pass manager, they can't be
skipped since they are not optimization passes which are optional.
Before this PR I'm seeing crash in compiler when bisecting pass manager.
> Mark all passes as required in LLVM new pass manager

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
These utility functions are no longer being used, so remove them.
> Remove unused utility functions; NFC

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/image_signedness.ll
Return type of image read and Texel type of image write builtins may be
unsigned. Before this PR, the builtin names in SPIR-V Friendly IR were
always mangled with signed type.
> [SPV -> SPV-IR] Fix image builtin mangling of unsigned type

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fp_max_error/IntelFPMaxError.ll
Report an error if fpbuiltin-max-error found without extension enabled
> [SPIRV-V Extension] fpbuiltin-max-error w/o extension

- lib/SPIRV/OCLToSPIRV.cpp
ImageOpMask pointer was passed to closure as reference. Closure is executed outside of original stack frame which renders reference invalid. Fixes some ASan errors from issue #2233.
> Access out of scope fix in OCLToSPIRVBase::visitCallReadWriteImage

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
According to a new specification, CoordX and CoordY parameters are not needed for prefetch in CooperativeMatrixPrefetchINTEL(), only offset pointer is enough. This PR is to fix support for joint_matrix_prefetch in SPIRV according to the new specification.
> Remove CoordX and CoordY arguments of OpCooperativeMatrixPrefetchINTEL

- docs/SPIRVRepresentationInLLVM.rst
Global variable declarations are not permitted to have no address space or ``addrspace(0)``. This PR is to document this contract.
> Document contract between LLVM IR producer and the translator wrt. global variable declarations

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/KHR/SPV_KHR_bit_instructions/capabilities.ll
- test/transcoding/OpBitReverse_i32.ll
- test/transcoding/OpBitReverse_v2i16.ll
This translator currently only supports the OpenCL/compute "flavour" of SPIR-V, but for the `llvm.bitreverse` intrinsic it could produce SPIR-V modules declaring the `Shader` Capability.
When translating `llvm.bitreverse` without having the `SPV_KHR_bit_instructions` extension enabled, avoid producing SPIR-V modules declaring the `Shader` Capability and report an error instead.
> Never emit CapabilityShader for bitreverse

- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
SPIRVEntry is created by function getEntry() but not deleted in a few frame ending branches. Fixes some ASan errors from #2233.
> Memory leak fix in SPIRVFunction::decodeBB

- include/LLVMSPIRVExtensions.inc
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- test/extensions/INTEL/SPV_INTEL_fpga_cluster_attributes/function_attributes.ll
Commit also adds new extension capability FPGAClusterAttributesV2INTEL. 
Specification:
https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/INTEL/SPV_INTEL_fpga_cluster_attributes.asciidoc
> Added support for StallFreeINTEL

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
Reverts KhronosGroup/SPIRV-LLVM-Translator#2278
> Revert "Remove CoordX and CoordY arguments of OpCooperativeMatrixPrefetchINTEL"

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/spirv-triple-with-version.ll
- test/spirv-version-controls.spt
Use target triple's subarch component, if present, for setting exact SPIR-V version for the SPIR-V emission.
Resolves #1509.
> Use triple subarch to emit exact SPIR-V version

- lib/SPIRV/SPIRVReader.cpp
- test/composite_construct_array_non_constant.spvasm
- test/composite_construct_struct_non_constant.spt
- test/composite_construct_vector_non_constant.spvasm
This patch introduces a way to use runtime values for array and vector types. It continues #2256
> Fix reverse translation of non-constant values of OpCompositeConstruct pt.2

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/DebugInfo-GV-with-DIE.ll
- test/DebugInfo/DebugInfo-GV-with-SMD-and-DIE.ll
Preserve DIExpression in DIGlobalVariableExpression.
Preserving DIExpressions is necessary because of this change in LLVM:
commit 638a8393615e911b729d5662096f60ef49f1c65e
Author: Michael Buch <michaelbuch12@gmail.com>
Date:   Mon Nov 13 06:04:27 2023 +0000
Reland "[clang][DebugInfo] Emit global variable definitions for static data members with constant initializers" (#71780)
> [DebugInfo] Preserve DIExpression in DIGlobalVariableExpression

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/image_signedness_spv_ir.ll
This PR preserves unsigned return type of image read and unsigned texel
type of image write builtins as ZeroExtend image operand in SPIRV.
> [SPV-IR -> SPIRV] Fix image builtin unsigned type not preserved

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.h
- lib/SPIRV/SPIRVWriter.cpp
- test/entry_point_func.ll
- test/extensions/INTEL/SPV_INTEL_fpga_argument_interfaces/sycl-kernel-arg-annotation.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/select.ll
- test/extensions/INTEL/SPV_INTEL_unstructured_loop_controls/FPGAUnstructuredLoopAttr.ll
- test/mem2reg.cl
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/OpenCL/atomic_work_item_fence.cl
- test/transcoding/OpenCL/barrier.cl
- test/transcoding/OpenCL/mem_fence.cl
- test/transcoding/OpenCL/sub_group_barrier.cl
- test/transcoding/OpenCL/work_group_barrier.cl
- test/transcoding/SampledImage.cl
- test/transcoding/kernel_arg_type_qual.ll
- test/transcoding/kernel_query.ll
- test/transcoding/registerallocmode.ll
- test/transcoding/spirv-target-types-buffer.ll
kernels can be called from other translation units, so we can't know if a kernel is called or not. Reverting this so we get back `Export` Linkage declarations which are required to support linking of spirv files.
This reverts commit 46285e43abcc606791a0dd18858fd88af2894294.
> Revert "Don't wrap kernels that are not being called in the module (#2119)"

- test/DebugInfo/NonSemantic/Shader200/FortranArray.ll
Revert change to Fortran array test.  Previous change was in:
> Author: Viktoria Maximova <viktoria.maksimova@intel.com>
> Date:   Tue Jan 16 17:16:33 2024 +0100
> 
>     Fix DebugInfo/NonSemantic/Shader200/FortranArray.ll (#2303)
> 
>     The change is needed after llvm/llvm-project@fc6faa11
> 
The LLVM change that motivated the change to FortranArray.ll has been reverted:
> Author: Davide Italiano <davidino@fb.com>
> Date:   Tue Jan 16 16:56:24 2024 -0800
> 
>     Revert "[CloneFunction][DebugInfo] Avoid cloning DILocalVariables of inlined functions (#75385)"
> 
>     This reverts commit fc6faa1113e9069f41b5500db051210af0eea843.
> [NFC] Revert change to Fortran array test

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
Add support for load/store operations for a cooperative matrix such that original matrix shape is known and implementations are able to reason about how to deal with the out of bounds.
CapabilityCooperativeMatrixCheckedInstructionsINTEL = 6192
CooperativeMatrixLoadCheckedINTEL = 6193
CooperativeMatrixStoreCheckedINTEL = 6194
> add support for out of bounds load/store

- include/LLVMSPIRVLib.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/libSPIRV/SPIRVError.cpp
- lib/SPIRV/libSPIRV/SPIRVError.h
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- test/negative/spirv_report_bad_input.spt
- tools/llvm-spirv/llvm-spirv.cpp
The goal of the PR is to add API to SPIR-V LLVM Translator to query error message by an error code as discussed in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2298
A need and possible application is a way to generate human-readable error info by error codes returned by other SPIRV Translator API calls, including getSpirvReport().
> add API to query error message by an error code

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfo-GV-with-DIE.spt
Ensure that SPIR-V that uses a DebugGlobalVariable's Variable field to hold an Expression
can be reverse translated. A Variable field can be used to hold an Expression in order to
preserve a DIExpression in a DIGlobalVariableExpression in LLVM IR.
> [Backport to 15][DebugInfo] Preserve DIExpression in DIGlobalVariableExpression

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/image_signedness.ll
Return type of image read and Texel type of image write builtins may be unsigned. Before this PR, the builtin names in SPIR-V Friendly IR were always mangled with signed type.
(cherry picked from commit e9b95fbc3f58c7d8084620fd58b8bd936c640d37)
> [Bckport to 14][SPV -> SPV-IR] Fix image builtin mangling of unsigned type (#2273)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
Add support for checked matrix construct instruction.
Specification draft: https://github.com/intel/llvm/blob/2fa153ee852ea3d7d64df097f1f494cddacee90e/sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix.asciidoc
> add support for checked matrix construction

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugInfo-GV-with-DIE.ll
- test/DebugInfo/DebugInfo-GV-with-SMD-and-DIE.ll
Guard placing a DIExpression in SPIR-V's DebugGlobalVariable's Variable field with a nonsemantic check.
> [DebugInfo] Guard Expression in DebugGlobalVariable with nonsemantic

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/image_signedness.ll
Return type of image read and Texel type of image write builtins may be unsigned. Before this PR, the builtin names in SPIR-V Friendly IR were always mangled with signed type.
(cherry picked from commit e9b95fbc3f58c7d8084620fd58b8bd936c640d37)
> [Backport to 17][SPV -> SPV-IR] Fix image builtin mangling of unsigned type (#2273)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfo-GV-with-DIE.spt
Ensure that SPIR-V that uses a DebugGlobalVariable's Variable field to hold an Expression
can be reverse translated. A Variable field can be used to hold an Expression in order to
preserve a DIExpression in a DIGlobalVariableExpression in LLVM IR.
> [Backport to 16][DebugInfo] Preserve DIExpression in DIGlobalVariableExpression

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/image_signedness.ll
Return type of image read and Texel type of image write builtins may be unsigned. Before this PR, the builtin names in SPIR-V Friendly IR were always mangled with signed type.
(cherry picked from commit e9b95fbc3f58c7d8084620fd58b8bd936c640d37)
> [Backport to 16][SPV -> SPV-IR] Fix image builtin mangling of unsigned type (#2273)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/image_signedness.ll
Return type of image read and Texel type of image write builtins may be unsigned. Before this PR, the builtin names in SPIR-V Friendly IR were always mangled with signed type.
(cherry picked from commit e9b95fbc3f58c7d8084620fd58b8bd936c640d37)
> [Backport to 15][SPV -> SPV-IR] Fix image builtin mangling of unsigned type (#2273)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfo-GV-with-DIE.spt
Ensure that SPIR-V that uses a DebugGlobalVariable's Variable field to hold an Expression
can be reverse translated. A Variable field can be used to hold an Expression in order to
preserve a DIExpression in a DIGlobalVariableExpression in LLVM IR.
> [Backport to 17][DebugInfo] Preserve DIExpression in DIGlobalVariableExpression

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
The Headers for this extension were published so we should use them instead:
https://github.com/KhronosGroup/SPIRV-Headers/commit/a8af2ce341cfd73a44a37bf62642a2cdf45938df
> Remove internal values for SPV_INTEL_cache_controls

- test/DebugInfo/DebugInfoTypeVector.spvasm
It should have tested DebugInfoNone base type
> [NFC] Fix DebugTypeVector test

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
In cpp std::map type is a red-black tree implementation. It's search time is O(log N) and 
pointers are scattered through memory. 
In comparison unordered_map is a hash table which doesn't have the same iteration guarantees 
as red-black tree but it's search time is O(1) plus the constants like calculating hash function and 
load from the table.
The SPIRVModuleImpl::SPIRVIdToEntryMap is used in SPIRVModuleImpl::getEntry function which is widely used
as a key component of the parser.
It's a small fix but yields around 30% speedup for translation SPIR-V to IR.
> map to unordered_map for SPIRVIdToEntryMap type

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fpga_buffer_location/sycl-buffer-location-with-ptr-annotation.ll
- test/transcoding/multiple_user_semantic_on_struct.ll
There was an assumption, that ptr.annotation encoding buffer_location should be used by load or store instructions. But there is no such restriction in the specification (there were such checks in `checkMemUser` used by `allowDecorateWithBufferLocationOrLatencyControlINTEL`).
This fix also required adjustments in the reader part as traversing dominator tree and replacing old instructions with ptr.annotation won't work for for return basic blocks. So the patch refactors this part causally fixing an issue with multiple structure annotations (instead of analysis in `replaceOperandWithAnnotationIntrinsicCallResult` - we should already update a Value map with pairing ptr.annotation with previously decorated SPIR-V instructions), exposed by a change in …
> Fix BufferLocationINTEL decoration translation

- lib/SPIRV/SPIRVWriter.cpp
- test/DebugInfo/DebugDeclareUnused.cl
- test/DebugInfo/DebugInfoLLVMArg.ll
- test/DebugInfo/DebugInfoTypeInheritance.ll
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
- test/DebugInfo/expr-opcode.ll
For now just convert BB with convertFromNewDbgValues, will figure out something smarter a bit later.
I've updated several tests with dbg.declare intrinsic adding --experimental-debuginfo-iterators=1 to check if it works.
Resolved https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2357 for now
> [NFCI] Prepare for non-instrinsic debug info

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> Fix allowed types for OpConstantNull

- .github/workflows/check-code-style.yml
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 18] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 17] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 16] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 15] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 14] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/OpConstantNull.spvasm
> [Backport to 13] Fix allowed types for OpConstantNull (#2361)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- test/DebugInfo/DebugInfoGlobalVariableNone.spvasm
- test/DebugInfo/DebugInfoTypeInheritance.spvasm
- test/DebugInfo/DebugInfoTypePtrToMember.spvasm
- test/DebugInfo/DebugInfoTypeVector.spvasm
- test/DebugInfo/DebugTypeMember.spvasm
- test/DebugInfo/NonSemantic/Shader200/FortranArrayNoType.spt
OpenCL and NonSemantic DebugInfo specifications are flexible in terms of allowing any debug information be replaced with DebugInfoNone, so various of SPIR-V producers follow that and generate it for base types of several debug instructions, leaving SPIR-V consumers to handle this. By default the translator replaces missing debug info with tag: null, which is in most cases correct. Yet, there are situations, where it's not allowed by both LLVM and DWARF, for example for DW_TAG_array_type DWARF spec sets, that DW_AT_type attribute is mandatory. For such cases new transNonNullDebugType wrapper function was added to the translator, generating "DIBasicType(tag: DW_TAG_unspecified_type, name: "SPIRV unknown type")" where DebugInfoNone was used as the type. This function doesn't replace all …
> [Backport to 14][DebugInfo] Fix SPIR-V consumption of DebugInfoNone for debug types

- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/feature_requires_minversion.ll
When restricting the allowed SPIR-V version using `--spirv-max-version`, some constructs may not be translatable due to being unavailable in older SPIR-V versions.  Instead of asserting, report an error.
It would be nice to also report the construct leading to the version conflict, but that information isn't readily available at this point.
> Report unmet version requirement as error

- CMakeLists.txt
When using the `spirv-tools` system package on Ubuntu 20.04 the `SPIRV-Tools-shared` CMake target, which represents `/usr/lib/x86_64-linux-gnu/libSPIRV-Tools.so`, is imported and used for linking and include directories. However, on Ubuntu 22.04 it does not exist which results in the following error:
```
CMake Error at /builds/SPIRV-LLVM-Translator/CMakeLists.txt:124 (get_target_property):
get_target_property() called with non-existent target "SPIRV-Tools-shared".
```
Instead, on Ubuntu 22.04 the `SPIRV-Tools-static` CMake target is imported, which represents `/usr/lib/x86_64-linux-gnu/libSPIRV-Tools.a`, which suggests the project or package maintainers changed the default library type being compiled.
This patch updates the `CMakeLists.txt` to check if either of these targets exists, …
> [Backport to 16] cmake: Fix using spirv-tools package on Ubuntu 22.04

- include/LLVMSPIRVOpts.h
- test/negative/spirv-version-controls-1.spt
- test/negative/spirv-version-controls-2.spt
- tools/llvm-spirv/llvm-spirv.cpp
Recognize SPIR-V 1.5 modules and allow specifying the `--spirv-max-version=1.5` option.
This does not implement any SPIR-V 1.5 functionality yet, so mark 1.5 as "experimental".
> Add SPIR-V 1.5 enum value

- lib/SPIRV/libSPIRV/SPIRVError.cpp
The prototype for `getErrorMessage()` is declared in `LLVMSPIRVLib.h`, but `SPIRVError.cpp` defining that function did not include `LLVMSPIRVLib.h`.  This can be problematic for builds that use `-fvisibility=hidden`.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2376
> Include `LLVMSPIRVLib.h` in `SPIRVError.cpp`

- lib/SPIRV/SPIRVWriter.cpp
- test/group_non_uniform_shuffle_down.ll
The contract between some frontends and Translator is that calls to functions, 
which are matching to hardcoded name, are converted to matching Ops in SPIR-V. 
The translation from LLVM to SPIR-V of OpGroupNonUniformShuffleDown call was done incorrectly.
The struct member which is correct result type for the op was left unwrapped which lead to
SPIR-V nonconforming with specification.
> Struct as result type in OpGroupNonUniformShuffleDown translation fix

- lib/SPIRV/libSPIRV/SPIRVError.cpp
The prototype for `getErrorMessage()` is declared in `LLVMSPIRVLib.h`, but `SPIRVError.cpp` defining that function did not include `LLVMSPIRVLib.h`.  This can be problematic for builds that use `-fvisibility=hidden`.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2376
(cherry picked from commit 81f78d24db3662220d3c293f3ba0514fad3e0c94)
> [Backport to 18] Include `LLVMSPIRVLib.h` in `SPIRVError.cpp` (#2377)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/subgroup_spirv_1_5.cl
For SPIR-V 1.4 and earlier, the `Id` operand of `OpGroupNonUniformBroadcast` must come from a constant instruction.
Ensure that any emitted SPIR-V module using a non-constant `Id` operand declares SPIR-V version 1.5.  Bail out if the maximum SPIR-V version was restricted to < 1.5, to avoid producing invalid SPIR-V.
> [SPIR-V 1.5] Fix OpGroupNonUniformBroadcast version requirement

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/transcoding/unused-sret-opaque-ptr.ll
Usually sret parameters are accessed by a memory instruction, which would tell SPIRVTypeScavenger which type to use for this function parameter. But if sret parameter is unused later in the module scavenger would fail attempting to deduce type from the mangled name.
> Fix function with unused sret parameter

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_checked.ll
This PR is to ensure that CooperativeMatrixLoadCheckedINTEL, CooperativeMatrixStoreCheckedINTEL and CooperativeMatrixConstructCheckedINTEL instructions can correctly accept TypeJointMatrixINTEL as an input during both forward and reverse translation.
> Out of bounds cooperative matrix load/store/fill work with legacy TypeJointMatrixINTEL

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_cache_controls/decorate-prefetch-w-cache-controls.ll
- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopMergeInst.ll
- test/transcoding/SPV_INTEL_kernel_attributes/register_map_interface_attribute.ll
- test/transcoding/SPV_INTEL_kernel_attributes/spirv_fpga_function_decorations.ll
Back-port of RegisterMapInterfaceINTEL and !spirv.Decoration metadata patches from llvm16 version of Translator, as well as some tests covering Intel extensions.
> Back-port of some patches from llvm16 version of Translator.

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/undef-gv.ll
Previously the translator would create OpVariable with init field pointing to OpUndef. That is not conformant with the specification, so when LLVM GV is initialized with undef - we should skip initializer in SPIR-V.
Later in the reader it's likely to become zeroinitialized, but it depends on the linkage and storage class. Checking correctness of this logic goes outside of this patch.
Fixes part of https://github.com/intel/llvm/issues/9961
> Fix GV initialized with undef translation

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/llvm-intrinsics/fmuladd.ll
- tools/llvm-spirv/llvm-spirv.cpp
Add option --spirv-ext-inst=[none|OpenCL.std] to control what external instructions can be used when translating form LLVM IR to SPIR-V.
> Add --spirv-ext-inst option

- lib/SPIRV/Mangler/Mangler.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Use unordered_map instead of map for better performance.
> [NFC] Use unordered_map for better performance

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_task_sequence/negative/invalid_async_capacity.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/negative/invalid_get_capacity.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/task_sequence.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/task_sequence_zero_capacity_literals.ll
This patch fixes verification of Get/Async Capacity literals making translator accept zero values which are valid by spec.
> Fix TaskSequenceCreateINTEL instruction verification

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/transcoding/unused-sret-opaque-ptr.ll
Usually sret parameters are accessed by a memory instruction, from which would tell SPIRVTypeScavenger which type to use for this function parameter. But if sret parameter is unused later in the module scavenger would fail attempting to deduce type from the mangled name.
> [Backport to 18] Fix function with unused sret parameter (#2381)

- lib/SPIRV/SPIRVTypeScavenger.cpp
- test/transcoding/unused-sret-opaque-ptr.ll
Usually sret parameters are accessed by a memory instruction, from which would tell SPIRVTypeScavenger which type to use for this function parameter. But if sret parameter is unused later in the module scavenger would fail attempting to deduce type from the mangled name.
> [Backport to 17] Fix function with unused sret parameter (#2381)

- lib/SPIRV/SPIRVToOCL20.cpp
- test/tail-call-atomic-cmp-exchg.ll
In translation from  __spirv_AtomicCompareExchange to OpenCL builtin atomic_compare_exchange_strong_explicit, a new alloca `expected` is created and read/written in the OpenCL builtin.
The OpenCL builtin call can't have tail marker since the marker requires that callee doesn't access alloca from the caller. Otherwise llvm alias analysis deduces that the alloca isn't accessed by the call, and instcombine pass replaces the load from the alloca after the call with the value stored to the alloca before the call.
> [SPIRVToOCL20] Remove tail from atomic_compare_exchange_strong_explicit call

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> [Backport to 18] Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> [Backport to 17] Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> [Backport to 14] Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> [Backport to 16] Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpVectorShuffle.spvasm
> [Backport to 15] Handle OpVectorShuffle with differing vector sizes

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
- test/transcoding/BuildNDRange.ll
It's also first part of fix which removes noncompliance of uadd/sub_with_overflow intrinsics.
SPIRVUtil changes are needed to support situations where builtin don't have corresponding store instruction.
> Add IAddCarry and ISubBorrow builtins

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Translator accepting two formats currently - SPIR-V and SPT.
SPT is a textual format used internally for tests without any formal specification.
Parsing a textual format is slower than binary format and SPT also is less strict in comparison to SPIRV. 
Because parsing in Translator is organized around iostream interfaces and implementations are mostly shared, the binary format is parsed much slower than it can be.
The commit starts an effort of splitting implementations to make SPIR-V hot path faster and easier to read.
In addition to that from both implementations the Decoder class is removed - it doesn't bring any important functionality which couldn't be solved by few lines of explicit simple code.
> [NFC] Split of SPT and SPIR-V in header parsing

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/var_undef.ll
SPIRVVariable should have a WordCount of 4 + 1 (if optional Initializer is added).
Set WordCount to 4 if Initializer is not added.
> Set WordCount for SPIRVVariable correctly

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_different_type.ll
In some cases, we will see IR with the following
@__spirv_BuiltInGlobalInvocationId = external dso_local local_unnamed_addr addrspace(1) constant <3 x i64>, align 32
...
%0 = load <6 x i32>, ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, align 32 %1 = extractelement <6 x i32> %0, i64 0
Note the global type and load type are different. Change the handling of vector loads from vector globals to reconstruct the global vector type and then bitcast to the load type.
Thanks to @jcranmer-intel for helping me find the simplest solution.
> [Backport to 17] Fix SPIR-V global to function replacement for differing load types

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/layout.ll
- test/type-scavenger/globals.ll
If a global is initialized with a ConstantExpr returning a pointer (getelementptr), the right type has to be deduced instead of defaulting it to i8*.
> Fix globals' type deduction in TypeScavenger

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
Node.js 16 actions are [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), so update to v4 which uses Node 20.
> [CI] Upgrade to actions/checkout@v4

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/layout.ll
- test/type-scavenger/globals.ll
If a global is initialized with a ConstantExpr returning a pointer (getelementptr), the right type has to be deduced instead of defaulting it to i8*.
> [Backport to 17] Fix globals' type deduction in TypeScavenger

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/SpecConstants/spec-constant-length-array.ll
SPIR-V arrays can have their length specified via a specialization constant. In case an `alloca` instruction uses a specialization constant `s` as length, generate an array variable of length `s`.
> Allow specialization constant length arrays

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/extensions/INTEL/SPV_INTEL_task_sequence/sret-get.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/void-get.ll
This change adds support for void return-type of Get instruction and handles the case when Get instruction has 'sret' parameter.
> Fix translation of __spirv_TaskSequenceGetINTEL

- lib/SPIRV/libSPIRV/SPIRVBasicBlock.cpp
Although `OpPhi` and `OpVariable` instructions should not be in the same SPIR-V block in a valid module, take into account this case when inserting new `OpVariable` operations.
No test added, as no valid SPIR-V module can lead to this scenario.
> Insert `OpVariable` instructions after `OpPhi`

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
It seems like casting from pointer union on LLVM 15 branch is bugged. Here we are crashing in transTypeArrayDynamic attempting to get a ConstantInt from debug subrange count of on line 450: if (auto *Count = SR->getCount().get<ConstantInt *>()). Count here is:
(const llvm::PointerUnion<llvm::ConstantInt*, llvm::DIVariable*,
llvm::DIExpression*> * const)
so we should be able to cast it to ConstantInt, and it's happening successfully on main and llvm_release_140 branch (code, test and translation flow in this case is identical for all branches), and only on LLVM15 it results in a crash.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2444
> Workaround LLVM 15 bug with getting an element of a PointerUnion

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 17] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 14] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 16] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 15] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 13] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 12] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
This change fixes cases when the input function name does not match OpenCL spec but starts with `convert_` prefix, e.g. `convert_float_42`.
> Fix handling of OpenCL convert_ builtins

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/Generic/c-and-cpp-mixed.ll
- test/DebugInfo/InvalidSourceLanguageSPIRVtoLLVM.spvasm
- test/DebugInfo/X86/mixed-nodebug-cu.ll
- test/DebugInfo/X86/split-dwarf-omit-empty.ll
This commit changes "Source Lang Literal" flag from simple a scalar value
to a vector of pairs: (compile unit, source language).
> [Backport to 16] Adjust "Source Lang Literal" logic to support multiple CompileUnits (#2098)

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_subgroup_requirements/named_sub_group_sizes.ll
On the LLVM IR side, use of SPV_INTEL_subgroup_requirements (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2317, https://github.com/intel/llvm/pull/12335) was specified by the use of a magic value on the intel_reqd_sub_group metadata. Following [this discussion](https://github.com/intel/llvm/pull/12335#discussion_r1504466824), the SYCL headers using this extension had this magic value updated from 0 to -1 (on the IR side), so this PR syncs up with that change.
> Update magic value used in named sub group size extension

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
> [Backport to 11] Add IAddCarry and ISubBorrow builtins (#2392)

- lib/SPIRV/libSPIRV/spirv_internal.hpp
Task Sequence Specification was created without explicitly reserving the 6411 token enum. During spec review, that number was reserved by CooperativeMatrixPrefetchINTEL, but Task Sequence was not updated to use a new enum at that point in time, resulting in development with the old enum. 6199 is the newly (confirmed) reserved token enum.
> switch task sequence enum to new available enum

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMSPIRVOpts.cpp
The list of extensions has grown considerably, which makes this member function definition fairly large.  Move it out of the header.
> [NFC] Move enableAllExtensions out of header

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
This eliminates the need for casts, making the various overrides easier to read.
> [NFC] Return a VersionNumber from getRequiredSPIRVVersion

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
This PR aims to introduce CooperativeMatrixPrefetchINTEL capability and operation, and make initial introduction of entities in llvm-spirv translator.
> [Backport to 17] support joint matrix prefetch (#2212)

- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/conversion_instructions.ll
* Run validation where it was intended
* Do the expected source language check
> Remove several TODOs from the tests

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
Check that builtin is valid mostly by matching the regular expression - remove unneeded checks.
This is a follow-up to #2443
> Rewrite OpenCL explicit conversion builtins handling

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/llvm-intrinsics/memcpy.align.ll
> [Backport to 18][SPIR-V 1.4] Allow OpCopyMemorySized to have Memory Operands for both Source and Target

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/llvm-intrinsics/memcpy.align.ll
> [Backport to 17][SPIR-V 1.4] Allow OpCopyMemorySized to have Memory Operands for both Source and Target

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/llvm-intrinsics/memcpy.align.ll
> [Backport to 16][SPIR-V 1.4] Allow OpCopyMemorySized to have Memory Operands for both Source and Target

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/llvm-intrinsics/memcpy.align.ll
> [Backport to 15][SPIR-V 1.4] Allow OpCopyMemorySized to have Memory Operands for both Source and Target

- test/debug-label-skip.ll
Update a test after llvm-project commit llvm/llvm-project@379628d446e5 ("[RemoveDIs] Add flag to preserve the debug info format of input IR (#87379)", 2024-04-05).
> Disable automatic debug format conversion for 1 test

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
Add support for load/store operations for a cooperative matrix such that original matrix shape is known and implementations are able to reason about how to deal with the out of bounds.
CapabilityCooperativeMatrixCheckedInstructionsINTEL = 6192
CooperativeMatrixLoadCheckedINTEL = 6193
CooperativeMatrixStoreCheckedINTEL = 6194
> [Backport to 17] Add support for checked load/store/construct matrix instructions

- lib/SPIRV/SPIRVUtil.cpp
- test/GEPOperator.spvasm
This PR is to fix the issue when SPIRV Translator expects now to see exactly GetElementPtrInst in an access chain for a builtin variable and crashes in lib/SPIRV/SPIRVUtil.cpp in replaceUsesOfBuiltinVar() with llvm_unreachable() call. See https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2486 for the detailed description. Attached is a test case that demonstrates the problem and leads to a crash in current version(s) of SPIRV Translator.
> Both GetElementPtrConstantExpr and GetElementPtrInst may represent access to a buildin variable

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
In preparation for LLVM's [deprecation](https://discourse.llvm.org/t/psa-instruction-constructors-changing-to-iterator-only-insertion/77845) of Instruction constructors and Create methods that accept `Instruction` pointers, upgrade call sites to pass an iterator instead of an `Instruction` pointer.
This patch only upgrades constructor and `Create` calls that were trivial to upgrade with no impact on the test suite.  Some calls remain to be upgraded as future work.
> Start moving away from insert-before Instruction pointers

- test/GEPOperator.spvasm
Test added in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2487 is using spirv-as, should require the feature.
> Add REQUIRES spirv-as feature for GEPOperator.spvasm

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/OpLessOrGreater.ll
This is a follow-up to 08884df
> [SPIR-V 1.5] Deprecate OpLessOrGreater in favor of OpFOrdNotEqual

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.h
- test/llvm-intrinsics/fp_to_arbitrary_size_int_intrinsic.ll
It is possible that incoming LLVM IR conversion instructions convert floating point to non-standard integer types. 
For e.g. %0 = call i2 @llvm.fptosi.sat.i2.f32(float %input)
Such types are not supported in SPIR-V. This PR cleans up such code and removes occurrence of non-standard integer types.
Thanks
> Regularize LLVM code to remove use of non standard integer types in fptoui and fptosi intrinsics

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Fixed ParentIdx was mismatched for DebugTypeInheritance type in context of NonSemantic.Shader.DebugInfo.100. That lead to heap buffer overflow in SPIRVExtInst::getExtOp getter when instruction was incorrectly casted
to SPIRVExtInst as parent of the culprit instruction in SPIRVToLLVMDbgTran::getDIBuilder. The missmatch happen because in previous used standard OpenCL.DebugInfo.100 DebugTypeInheritance had Child field as zero indexed argument. In newer standard that field is removed.
> Fix of ParentIdx mismatch for DebugTypeInheritance in SPIRV.debug.h

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fcmp.ll
- test/transcoding/fneg.ll
Since SPIR-V 1.6 may be used with `OpFNegate` and with the binary floating-point comparison instructions (including `OpOrdered` and `OpUnordered`).
> [SPIR-V 1.6] Extend the use of the FPFastMathMode decoration

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
~~This reduces the number of required type casts.~~
This unifies all the version methods used in translator.
> Use VersionNumber instead of SPIRVWord

- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
In preparation for LLVM's [deprecation](https://discourse.llvm.org/t/psa-instruction-constructors-changing-to-iterator-only-insertion/77845) of `Instruction` constructors and `Create` methods that accept `Instruction` pointers, upgrade call sites to pass an iterator instead of an `Instruction` pointer.
This is a continuation of #2498, updating some cases that are different from the bulk changes done earlier.
> Move away from some more insert-before constructors; NFC

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_checked.ll
Add support for load/store operations for a cooperative matrix such that original matrix shape is known and implementations are able to reason about how to deal with the out of bounds.
CapabilityCooperativeMatrixCheckedInstructionsINTEL = 6192
CooperativeMatrixLoadCheckedINTEL = 6193
CooperativeMatrixStoreCheckedINTEL = 6194
> [Backport to 17] add support for out of bounds load/store (#2277)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Fixed ParentIdx was mismatched for DebugTypeInheritance type in context of NonSemantic.Shader.DebugInfo.100. That lead to heap buffer overflow in SPIRVExtInst::getExtOp getter when instruction was incorrectly casted to SPIRVExtInst as parent of the culprit instruction in SPIRVToLLVMDbgTran::getDIBuilder. The mismatch happen because in previous used standard OpenCL.DebugInfo.100 DebugTypeInheritance had Child field as zero indexed argument. In newer standard that field is removed.
> [Backport to 14] Fix of ParentIdx mismatch for DebugTypeInheritance in SPIRV.debug.h (#2490)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Fixed ParentIdx was mismatched for DebugTypeInheritance type in context of NonSemantic.Shader.DebugInfo.100. That lead to heap buffer overflow in SPIRVExtInst::getExtOp getter when instruction was incorrectly casted to SPIRVExtInst as parent of the culprit instruction in SPIRVToLLVMDbgTran::getDIBuilder. The mismatch happen because in previous used standard OpenCL.DebugInfo.100 DebugTypeInheritance had Child field as zero indexed argument. In newer standard that field is removed.
> [Backport to 16] Fix of ParentIdx mismatch for DebugTypeInheritance in SPIRV.debug.h (#2490)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Fixed ParentIdx was mismatched for DebugTypeInheritance type in context of NonSemantic.Shader.DebugInfo.100. That lead to heap buffer overflow in SPIRVExtInst::getExtOp getter when instruction was incorrectly casted to SPIRVExtInst as parent of the culprit instruction in SPIRVToLLVMDbgTran::getDIBuilder. The mismatch happen because in previous used standard OpenCL.DebugInfo.100 DebugTypeInheritance had Child field as zero indexed argument. In newer standard that field is removed.
> [Backport to 17] Fix of ParentIdx mismatch for DebugTypeInheritance in SPIRV.debug.h (#2490)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
Fixed ParentIdx was mismatched for DebugTypeInheritance type in context of NonSemantic.Shader.DebugInfo.100. That lead to heap buffer overflow in SPIRVExtInst::getExtOp getter when instruction was incorrectly casted to SPIRVExtInst as parent of the culprit instruction in SPIRVToLLVMDbgTran::getDIBuilder. The mismatch happen because in previous used standard OpenCL.DebugInfo.100 DebugTypeInheritance had Child field as zero indexed argument. In newer standard that field is removed.
> [Backport to 18] Fix of ParentIdx mismatch for DebugTypeInheritance in SPIRV.debug.h (#2490)

- lib/SPIRV/SPIRVWriter.cpp
- test/ComparePointers.cl
- test/complex-constexpr.ll
- test/type-scavenger/ptr-abuse.ll
> Translate icmp eq and icmp ne to PtrEqual and PtrNotEqual respectively

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
Don't attempt to print the object itself (which results in binary noise) but print the relevant information from the SPIRVDecorate* objects.
> addDecorate: make debug messages readable

- lib/SPIRV/SPIRVWriter.cpp
Contributes to https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2509 .
> Skip adding decorations for OpForward

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 13] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 14] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 15] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 16] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 17] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/SPIRVWriter.cpp
> [Backport to 18] Skip adding decorations for OpForward (#2529)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/NonSemantic/Shader200/DebugLineOnlyOnce.ll
In https://github.com/KhronosGroup/SPIRV-Registry/blob/9df72fe377f68baa97f963a3f7462d2d7c0a6908/nonsemantic/NonSemantic.Shader.DebugInfo.100.asciidoc
We have the following info for DebugLine:
"Specify source-level line and column information. This information applies to all following instructions, up to the first occurrence of any of the following: the next end of block, the next DebugLine instruction, or the next DebugNoLine instruction.
This instruction must only appear within a block."
The 'CurrentDebugLine' info of the SPIRV module being created was not being reset at the end of each basic block. This resulted in some duplication of identical looking DebugLine extended instructions across blocks and spirv validator threw an error about a SPIR-V value being defined more than once. …
> Avoid duplication of DebugLine extended instruction

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- test/align-duplicate.ll
> Avoid duplicate Alignment decorations

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- test/align-duplicate.ll
(cherry picked from commit 926ca2ae84971661589c4f39ddff816618adc73c)
> [Backport to 14] Avoid duplicate Alignment decorations (#2537)

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- test/align-duplicate.ll
(cherry picked from commit 926ca2ae84971661589c4f39ddff816618adc73c)
> [Backport to 15] Avoid duplicate Alignment decorations (#2537)

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- test/align-duplicate.ll
(cherry picked from commit 926ca2ae84971661589c4f39ddff816618adc73c)
> [Backport to 17] Avoid duplicate Alignment decorations (#2537)

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
- test/align-duplicate.ll
(cherry picked from commit 926ca2ae84971661589c4f39ddff816618adc73c)
> [Backport to 18] Avoid duplicate Alignment decorations (#2537)

- lib/SPIRV/SPIRVReader.cpp
After LLVM commit 91446e2aa687 ("Repply#2 "[RemoveDIs] Load into new debug info format by default in LLVM (#89799)"", 2024-05-03), we need to disable the new debug record format explicitly until we have migrated to the new format.
> Disable new debug record format

- test/mem2reg.cl
Update a test after llvm-project commit e74a7a9fd79a ("cc1: Report an error for multiple actions unless separated by -main-file-name (#91140)", 2024-05-07).
> Drop redundant -S in clang invocation of mem2reg test

- test/CMakeLists.txt
- test/lit.cfg.py
- test/lit.site.cfg.py.in
Various tests already declare `REQUIRES: spirv-dis`, but this feature was never enabled so those tests were always skipped as "unsupported".
> cmake: Add spirv-dis lit feature

- .github/workflows/check-out-of-tree-build.yml
LLVMExports.cmake from already installed packages references files from the libllvmlibc package.
> [CI] Fix out-of-tree build by installing libllvmlibc

- .github/workflows/check-code-style.yml
LLVMExports.cmake from already installed packages references files from the libllvmlibc package.
> [CI] Fix code style checks by installing libllvmlibc

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
This reverts commit 93f2783317007343da7e8b00be0a363f2171d77f.
> Reland "Remove CoordX and CoordY arguments of OpCooperativeMatrixPrefetchINTEL"

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> Add return type for OpReadClockKHR SPIR-V friendly IR

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
Recently, LLVM migrated to new debug format replacing debug intrinsics with so-called records. The DIBuilder api supports both formats now with grace deprecation period for intrinsics. Currently Translator during reverse translation have new format disabled by flag and still supports only old one.
Documentation for the migration: https://llvm.org/docs/RemoveDIsDebugInfo.html
> Support for record debug format

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/PassPlugin.cpp
- lib/SPIRV/SPIRVUtil.cpp
The llvm project plans to deprecate `StringRef::equals` in favor of `StringRef::operator==`.
Most of these changes were done using `sed -i -e 's/\.equals("\([a-z0-9_\-]*\)")/ == "\1"/g'`
> [NFC] Use StringRef::operator== instead of StringRef::equals

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
Similar as ConvertHandleToImageINTEL, ConvertHandleToSampledImageINTEL builtin may have the same argument type but different return types. So we need to add ret type as name suffix when translating to LLVM IR.
> [SPV_INTEL_bindless_images] Add ret type to convert-SampledImage builtin name

- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
- test/extensions/INTEL/SPV_INTEL_bindless_images/negative/i32-in-physical64.ll
The updated SPV_INTEL_bindless_images spec can be seen in this PR: intel/llvm#13753
(cherry picked from commit e9a9a3fc1fd3e57449ba22d0065a373eaf4b1a53)
> [Backport to 14] Add updated SPV_INTEL_bindless_images preview extension (#2559)

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.cl
Add support for mapping the `cl_khr_kernel_clock` extension builtins to and from the `SPV_KHR_shader_clock` extension.
Provisional extension description: https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#cl_khr_kernel_clock .
Builtins: https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#kernel-clock-functions .
SPIR-V environment: https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_cl_khr_kernel_clock .
> Add cl_khr_kernel_clock support

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/extensions/INTEL/SPV_INTEL_cache_controls/basic_load_store_arg_dec.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/call_inst_arg_dec.ll
The patch adds CacheControls(Load/Store)INTEL decorations representation as metadata placed on memory accessing instruction with the following form: !spirv.DecorationCacheControlINTEL !X
!X = !{i32 %decoration_kind%, i32 %level%, i32 %control%,
i32 %operand of the instruction to decorate%}
It's being done this way as it's less likely for the metadata attached to function calls or memory instructions being optimized out than in a case when it's attached to pointer in LLVM IR.
Also patch creates a dummy GEP accessing pointer operand of the instruction to perform SSA copy of the pointer and attaches !spirv.Decorations metadata to the GEP, so several memory access instructions with different cache locality would use different decorated copies of the same pointer.
Few notes about this …
> Re-implement Intel cache controls decoration

- test/transcoding/constant-vars.ll
Update a test after llvm-project commit d10b76552f91 ("[ConstantFold] Remove notional over-indexing fold (#93697)", 2024-05-30) causing the `inbounds` to be dropped.
> Update constant-vars test after LLVM GEP change

- .github/workflows/patch-release.yaml
- README.md
Some of the upstream PRs are getting backported to the `llvm_release_*` branches, but those changes are never released. That prevents them from distributing as precompiled packages in various distributions like `conda-forge` and others. This PR targets this issue by creating automated workflow that is triggered once a month and generates automated releases for each such branch if there were changes since last release.
- Adds workflow to generate releases every month from `llvm_release_*` branches in the format `%llvm_major%.%llvm_minor%.%latest patch version +1%`. For example:
- v18.1.1
- v17.0.2
- v17.0.1
- v14.0.1
- etc
- Release description matches as close as possible to current releases. The only difference is that llvm versions is represented by two numbers, instead of three, …
> Add automated release workflow

- test/complex-constexpr.ll
It started to fail again after deab451e7a7f . Only bitcast to inttoptr has left in constexpr context in this test.
TODO: do code cleanup in lib/SPIRV/SPIRVLowerConstExpr.cpp
> [NFC] Update complex-constexpr.ll test

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/extensions/INTEL/SPV_INTEL_cache_controls/call_inst_arg_dec.ll
- test/extensions/INTEL/SPV_INTEL_cache_controls/multiple-decoration-single-arg.ll
In this case zero GEP will be created a single time, all the decorations will be attached to it.
> Add support for multiple Intel cache controls on a single argument

- test/DebugInfo/DebugDeclareUnused.cl
- test/DebugInfo/DebugInfoLLVMArg.ll
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
- test/DebugInfo/Generic/c-and-cpp-mixed.ll
- test/DebugInfo/NonSemantic/Shader200/FortranDynamicArrayExpr.ll
- test/DebugInfo/NonSemantic/Shader200/FortranDynamicArrayVar.ll
- test/complex-constexpr-vector.ll
Required after llvm/llvm-project@dc726c340392d:
Reapply#4 "[RemoveDIs] Load into new debug info format by default in LLVM
> [NFC] Update few tests check lines to use debug records

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.cpp
The affected source files were relying on transitive includes that were no longer included after recent llvm-project changes (such as 36c6632eb43b ("[IR] Don't include PassInstrumentation.h in PassManager.h (NFC) (#96219)", 2024-06-21)).
> Fix missing includes

- test/DebugInfo/X86/InlinedFnLocalVar.ll
Update a check pattern in a test after llvm-project commit 04c27852e470 ("[MC,COFF] Change how we handle section symbols", 2024-06-25).
> Update DebugInfo test after LLVM section symbol change

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [LLVM->SPIRV] Fix target id in decorates when there is forward decl

- test/link-attribute.ll
The test performed a read_image operation on an image declared `write_only`.  `spirv-val` recently started flagging this.
Update the image access attribute to "read-only" (i.e., 0).
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2597
(cherry picked from commit bd0fffe337d27b33168731ce00b097277568a841)
> [Backport to 17] Fix image access in link-attribute test (#2598)

- test/link-attribute.ll
The test performed a read_image operation on an image declared `write_only`.  `spirv-val` recently started flagging this.
Update the image access attribute to "read-only" (i.e., 0).
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2597
(cherry picked from commit bd0fffe337d27b33168731ce00b097277568a841)
> [Backport to 18] Fix image access in link-attribute test (#2598)

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [Backport to 14][LLVM->SPIRV] Fix target id in decorates when there is forward decl (#2606)

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [Backport to 16][LLVM->SPIRV] Fix target id in decorates when there is forward decl (#2606)

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [Backport to 15][LLVM->SPIRV] Fix target id in decorates when there is forward decl (#2606)

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [Backport to 17][LLVM->SPIRV] Fix target id in decorates when there is forward decl (#2606)

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/decoration-forward-decl.ll
> [Backport to 18][LLVM->SPIRV] Fix target id in decorates when there is forward decl (#2606)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
According to a new specification, CoordX and CoordY parameters are not needed for prefetch in CooperativeMatrixPrefetchINTEL(), only offset pointer is enough. This PR is to fix support for joint_matrix_prefetch in SPIRV according to the new specification.
backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2278
> [Backport to 14] Remove CoordX and CoordY arguments of OpCooperativeMatrixPrefetchINTEL

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/aab92ecc22e2f1e fix the usage ibut did not remove the include.
> Remove unecessary include that require c++20

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerLLVMIntrinsic.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerOCLBlocks.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
The LLVM Programmer's Manual states that `DEBUG_TYPE` should be set after the includes.
> Set DEBUG_TYPE after all includes

- .github/workflows/check-out-of-tree-build.yml
As per the CI logs:
```
CMake Warning:
Manually-specified variables were not used by the project:
LLVM_EXTERNAL_PROJECTS
-- Build files have been written to: /home/runner/work/SPIRV-LLVM-Translator/SPIRV-LLVM-Translator/build
```
According to https://reviews.llvm.org/D20838 it looks like this is only relevant for in-tree builds, so no need to pass it here.
> Do not pass -DLLVM_EXTERNAL_PROJECTS="SPIRV-Headers" for an out of tree build

- tools/llvm-spirv/CMakeLists.txt
When llvm-spirv is built in-tree as part of LLVM, and the LLVM build also includes libclc, libclc will require a native version of llvm-spirv to be built. To accommodate this, call setup_host_tool. This change by itself is intended to have no effect at the moment, but enables a future LLVM change.
> Allow llvm-spirv to be built natively in LLVM cross builds.

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> Don't add initializer to local variables with external linkage

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> [Backport to 17] Don't add initializer to local variables with external linkage.

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> [Backport to 18] Don't add initializer to local variables with external linkage.

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> [Backport to 14] Don't add initializer to local variables with external linkage. 

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> [Backport to 16] Don't add initializer to local variables with external linkage. 

- lib/SPIRV/SPIRVReader.cpp
- test/local_var_keeps_external.ll
> [Backport to 15] Don't add initializer to local variables with external linkage. 

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/llvm-intrinsics/lifetime.ll
While clang is generating alloca in private address space for OpenCL following target's datalayout, some of the passes might generate it in generic AS and for this cases we have to create OpVariable in function storage class and create a cast to generic. Additionally if such alloca was an operand of lifetime instruction - then SPIR-V without storage class adjustment validation for lifetime instruction will be violated (pointer operand must be with Function storage class).
This became exposed after https://github.com/llvm/llvm-project/pull/97306 which was fixing handling of byval pointer parameter of a function during inlining, byval pointer for OpenCL will be generated in default (under an option - generic) address space making the alloca to store value of the function's operand also be …
> Adjust OpVariable's users and Lifetime ptr operand storage classes

- test/llvm-intrinsics/dynamic-memmove.ll
Update a test after llvm-project commit 92a06546ab50 ("[LowerMemIntrinsics] Lower llvm.memmove to wide memory accesses (#100122)", 2024-07-26).
> Update llvm.memmove test after LLVM change

- .github/workflows/check-in-tree-build.yml
> [CI] Upgrade in-tree job to Ubuntu 22.04

- .github/workflows/check-in-tree-build.yml
> [Backport to 19] [CI] Upgrade in-tree job to Ubuntu 22.04 (#2658)

- .github/workflows/check-in-tree-build.yml
> [Backport to 18] [CI] Upgrade in-tree job to Ubuntu 22.04 (#2658)

- .github/workflows/check-in-tree-build.yml
> [Backport to 17] [CI] Upgrade in-tree job to Ubuntu 22.04 (#2658)

- .github/workflows/check-in-tree-build.yml
> [Backport to 16] [CI] Upgrade in-tree job to Ubuntu 22.04 (#2658)

- .github/workflows/check-in-tree-build.yml
> [Backport to 14] [CI] Upgrade in-tree job to Ubuntu 22.04 (#2658)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/addrspace_global_annotations.ll
This change fixes the assertion:
```
Assertion `C->getType() == Ty->getElementType() && "Wrong type in array element initializer"' failed
```
> Fix addrspace generation in reverse translation for global annotations

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fp-intrinsics.ll
Add translation for atan, acos, asin, cosh, sinh and tanh LLVM intrinsics which are mapped to corresponding OpenCL extended instructions.
> Add translation for Intrinsic::{atan,acos,asin,cosh,sinh,tanh}

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
Verified locally by changing the version from `65536` to `66560` in `test/transcoding/atomics.spt`.
> [SPIR-V 1.4] Removed OpAtomicCompareExchangeWeak

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fp-intrinsics.ll
Backport #2657 to LLVM 19 branch.
> [Backport to 19] Add translation for Intrinsic::{atan,acos,asin,cosh,sinh,tanh} (#2657)

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer

- .github/workflows/check-out-of-tree-build.yml
> [Backport to 18] [CI] Upgrade out-of-tree job to Ubuntu 22.04

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [Backport to 14][OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer (#2668)

- .github/workflows/check-out-of-tree-build.yml
> [Backport to 16] [CI] Upgrade out-of-tree job to Ubuntu 22.04

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> Fix element type when reading OpPtrDiff

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [Backport to 19][OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer (#2668)

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [Backport to 18][OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer (#2668)

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [Backport to 17][OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer (#2668)

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
> [Backport to 16][OCLToSPIRV] Translate floating-point atomic_compare_exchange as integer (#2668)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 19] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 18] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 17] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 14] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 15] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
> [Backport to 16] Fix element type when reading OpPtrDiff (#2683)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length.spvasm
Translation of the attached test would currently fail due to the SPIRVReader attempting to process the `%matTy` operand as a regular value instead of a type.  `OpCooperativeMatrixLengthKHR` seems to be pretty unique in taking an additional type operand beyond the result type, so special-case it in the reader.
The translator currently accepts a non-type operand for `OpCooperativeMatrixLengthKHR` too, even though that's not within the specification; see various TODOs in the existing SPV_KHR_cooperative_matrix tests.  Leave that relaxation in place, by only translating the operand as a type when it is an `OpTypeCooperativeMatrixKHR`.
> SPIRVReader: handle direct types with CooperativeMatrixLengthKHR

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/spirv_report_bad_input.spt
- test/spirv_report.spt
- tools/llvm-spirv/llvm-spirv.cpp
Partially load SPIR-V from the stream and decode only selected for the report instructions, needed to retrieve general information about the module: capabilities, extensions, version, memory model and addressing model.
In addition to immediately helpful for back-ends lists of capabilities and extensions declared in SPIR-V module, a general intent also is to extend report details in future by feedbacks about further potentially useful analysis, statistics, etc.
> [Backport to 16] add API call to display general information about the module (#2298)

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/spirv_report_bad_input.spt
- test/spirv_report.spt
- tools/llvm-spirv/llvm-spirv.cpp
Partially load SPIR-V from the stream and decode only selected for the report instructions, needed to retrieve general information about the module: capabilities, extensions, version, memory model and addressing model.
In addition to immediately helpful for back-ends lists of capabilities and extensions declared in SPIR-V module, a general intent also is to extend report details in future by feedbacks about further potentially useful analysis, statistics, etc.
> [Backport to 17] add API call to display general information about the module (#2298)

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/spirv_report_bad_input.spt
- test/spirv_report.spt
- tools/llvm-spirv/llvm-spirv.cpp
Partially load SPIR-V from the stream and decode only selected for the report instructions, needed to retrieve general information about the module: capabilities, extensions, version, memory model and addressing model.
In addition to immediately helpful for back-ends lists of capabilities and extensions declared in SPIR-V module, a general intent also is to extend report details in future by feedbacks about further potentially useful analysis, statistics, etc.
> [Backport to 14] add API call to display general information about the module (#2298)

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/negative/spirv_report_bad_input.spt
- test/spirv_report.spt
- tools/llvm-spirv/llvm-spirv.cpp
Partially load SPIR-V from the stream and decode only selected for the report instructions, needed to retrieve general information about the module: capabilities, extensions, version, memory model and addressing model.
In addition to immediately helpful for back-ends lists of capabilities and extensions declared in SPIR-V module, a general intent also is to extend report details in future by feedbacks about further potentially useful analysis, statistics, etc.
> [Backport to 15] add API call to display general information about the module (#2298)

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/debugtrap.ll
We already ignore llvm.trap, adding llvm.debugtrap as well.
> Ignore llvm.debugtrap

- lib/SPIRV/SPIRVWriter.cpp
- test/array-alloca.ll
- test/simple.ll
In LLVM, array allocations might have constant size:
```llvm
%array = alloca i32, i64 4, align 4
```
Represent this kind of allocations using `OpVariable + OpBitcast`.
Before this patch, the `SPV_INTEL_variable_length_array` extension was used.
> Handle constant sized array allocations using no extension

- lib/SPIRV/OCLUtil.cpp
- test/extensions/INTEL/SPV_INTEL_subgroups/cl_intel_sub_groups.ll
Per cl_intel_subgroups_short V 1.1.0 short16 is allowed for these builtins.
See: https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_subgroups_short.html
Also add missing tests for char16
> Allow short16 for ushort16 intel_sub_group_block_read/write

- CMakeLists.txt
- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/spirvbackend-usage.ll
- tools/llvm-spirv/CMakeLists.txt
- tools/llvm-spirv/llvm-spirv.cpp
This PR adds an option to translate LLVM IR to SPIR-V using the LLVM SPIRV Backend target:
* cmake is modified to search for the LLVM SPIRV Backend target while configuring the project,
* if LLVM is built with SPIRV Backend support, we may use the interface exposed by SPIRV BE to translate Module to SPIR-V code if a user explicitly asks for this way of LLVM IR transaformation.
> Add an option to translate LLVM IR to SPIR-V using the LLVM SPIRV Backend target

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
Avoid deprecation warnings after LLVM commit 2f50b280dc8e ("[DebugInfo] Enable deprecation of iterator-insertion methods (#102608)", 2024-09-20).
> Update after Instruction iterator-insertion deprecation

- lib/SPIRV/SPIRVReader.cpp
Update after llvm commit 04d8e364bbf7 ("[IRBuilder] Deprecate CreateGlobalStringPtr() (NFC)", 2024-09-23).
> [NFC] Replace deprecated CreateGlobalStringPtr

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/memset-align.ll
`llvm.memset` intrinsic is translated to `OpCopyMemorySized` using a newly created global variable with the required value as a source operand. This PR sets proper alignment to this newly created global variable.
> Set required alignment to CopyMemorySized newly created source var

- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/AtomicCompareExchange.ll
- test/atomic-load-store.ll
- test/atomicrmw.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fadd_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fadd_float.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fadd_half.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_float.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_half.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_float.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_half.ll
- test/transcoding/OpenCL/atomic_syncscope_test.ll
- test/transcoding/fence_inst.ll
This patch collects the mapping from LLVM SyncScope ID, which was spread out across multiple sites, into a single utility function. Furthermore, it realigns the mapping to match LLVM conventions, namely it defaults to `System` / `CrossDevice` (please see <https://github.com/llvm/llvm-project/pull/106429>) for more context for the proposed changes.
> Centralise & tweak handling of SyncScope to SPIR-V translation

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor_addrspace.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
- No option is passed to the forward translation stage and function pointers are in …
> Introduce CodeSectionINTEL storage class

- test/DebugInfo/X86/header.ll
Update a test after llvm commit e6bf48d11047 ("[X86] Don't request 0x90 nop filling in p2align directives (#110134)", 2024-10-02).
> Update header.ll DebugInfo test after LLVM change

- lib/SPIRV/SPIRVReader.cpp
- test/phi-multiple-predecessors.spvasm
This PR partially fixes issue https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2702 in the part that is responsible for SPIR-V to LLVM IR translation. Namely, this PR ensures that all PHI nodes of a `Function` has the number of incoming blocks matching block's predecessor count. When a PHI node doesn't conform to this rule, this PR inserts missing number of (Value, Basic Block) pairs to make the PHI node valid.
Another problem from https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2702, that is violation of the requirement to OpPhi's to have exactly one Parent ID operand for each parent block of the current block in the CFG in the output SPIR-V code, is out of scope of this PR.
> Ensure that PHI node has an incoming value per each predecessor instance

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
```
/SPIRV-LLVM-Translator/lib/SPIRV/SPIRVRegularizeLLVM.cpp:535:15: warning: implicit conversion turns string literal into bool: 'const char[39]' to 'bool' [-Wstring-conversion]
535 |       assert(!"Cache controls must decorate a pointer");
|              ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/assert.h:93:27: note: expanded from macro 'assert'
93 |      (static_cast <bool> (expr)                                         \
|                           ^~~~
```
The original code is not wrong but `false &&` is only a few characters more and does the same thing without warning.
> Fix string to bool conversion warnings in some asserts

- lib/SPIRV/SPIRVWriter.cpp
By adding the missing `break`.
```
SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:3718:5: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
3718 |     default:
|     ^
SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:3718:5: note: insert 'break;' to avoid fall-through
3718 |     default:
|     ^
|     break;
```
As the default case was just `break`, the behaviour is the same but this should prevent future mistakes here.
> Fix unannotated fall-through warning in SPIRVWriter.cpp

- lib/SPIRV/SPIRVWriter.cpp
```
.../SPIRV-LLVM-Translator/lib/SPIRV/SPIRVWriter.cpp:1697:44: warning: private field 'IndexGroupArrayMap' is not used [-Wunused-private-field]
1697 |   LLVMToSPIRVBase::LLVMToSPIRVMetadataMap &IndexGroupArrayMap;
|
```
IndexGroupArrayMap is used but only during the constructor to validate and build other things.
This change happened in 4a7804bc45ada92b8365c82b99387726382b5d7d where code was moved from a separate method, into the constructor.
> Remove unused private member from LLVMParallelAccessIndices

- test/extensions/KHR/SPV_KHR_untyped_pointers/untyped_var.spvasm
With the latest release of spirv-tools (1.3.296) this test now passes.
> UnXFAIL untyped_var test after spirv-tools update

- test/zero-length-array.ll
> Require spirv-dis in zero-length-array.ll

- test/DebugInfo/X86/constant-loclist.ll
The test has evolved upstream since it was forked into this repository and started failing now after a recent llvm change.  Re-align the invocations and FileCheck patterns with the test in llvm-project.
> Align constant-loclist test to upstream

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Most uses of std functionality already have explicit `std::` qualifications, so qualify the remaining unqualified uses and drop the `using namespace` directives.
> [NFC] Drop 'using namespace std' everywhere

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 19] Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
This patch also introduces limited translation of nofpclass LLVM parameter attribute.
> Add fast math flag translation for OpenCL std lib

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
Contributes to https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2769
> Fix SPIRVCopyMemory::validate()

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/AtomicBuiltinsFloat.ll
- test/AtomicCompareExchange.ll
- test/AtomicCompareExchange_cl20.ll
- test/atomic-load-store.ll
- test/atomicrmw.ll
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/OpenCL/atomic_syncscope_test.ll
- test/transcoding/atomic_explicit_arguments.cl
- test/transcoding/atomic_flag.cl
- test/transcoding/atomic_load_store.ll
- test/transcoding/atomics_1.2.ll
This change allows to preserve the correct builtin mangling in reverse translation.
All the existing tests for atomics (except atomic flag instructions which are not covered by the extension) were updated to verify we get the same mangling with and without extension enabled.
> Fix mangling for atomic builtins used with SPV_KHR_untyped_pointers

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 14] Introduce CodeSectionINTEL storage class (#2728)

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/transcoding/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 15] Introduce CodeSectionINTEL storage class (#2728)

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 16] Introduce CodeSectionINTEL storage class (#2728)

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 17] Introduce CodeSectionINTEL storage class (#2728)

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor_addrspace.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 18] Introduce CodeSectionINTEL storage class (#2728)

- .github/workflows/check-in-tree-build.yml
> [CI] Do not run check-in-tree after pushes to llvm_release_*

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/alias.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/bitcast.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/decor-func-ptr-arg-attr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/fp-from-host.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-as-function-arg.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer-dedicated-as.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/global_ctor_dtor_addrspace.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/gv-func-ptr.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/non-uniform-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/referenced-indirectly.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/select.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 19] Introduce CodeSectionINTEL storage class (#2728)

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 18] Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 17] Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 16] Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 15] Ignore UserSemantic decorations on BuiltIn variables

- lib/SPIRV/SPIRVReader.cpp
- test/OpDecorateString_UserSemantic_Builtin.spvasm
> [Backport to 14] Ignore UserSemantic decorations on BuiltIn Variables

- .github/workflows/check-in-tree-build.yml
> [Backport to 19] [CI] Do not run check-in-tree after pushes to llvm_release_*

- .github/workflows/check-in-tree-build.yml
> [Backport to 18] [CI] Do not run check-in-tree after pushes to llvm_release_*

- .github/workflows/check-in-tree-build.yml
> [Backport to 17] [CI] Do not run check-in-tree after pushes to llvm_release_*

- .github/workflows/check-in-tree-build.yml
> [Backport to 16] [CI] Do not run check-in-tree after pushes to llvm_release_*

- .github/workflows/check-in-tree-build.yml
> [Backport to 15] [CI] Do not run check-in-tree after pushes to llvm_release_*

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
> SPIRVReader: Add OpCopyMemory support

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 14] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 15] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 16] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 17] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 18] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
> [Backport to 19] Fix SPIRVCopyMemory::validate() (#2770)

- lib/SPIRV/OCLUtil.cpp
- test/extensions/INTEL/SPV_INTEL_subgroups/cl_intel_sub_groups.ll
Per cl_intel_subgroups_short V 1.1.0 short16 is allowed for these builtins.
> [Backport to 19] Allow short16 for ushort16 intel_sub_group_block_read/write

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
(cherry picked from commit 8dc0349c0860172c52d600f2a7422502f11bde2e)
> [Backport to 18] SPIRVReader: Add OpCopyMemory support (#2779)

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
(cherry picked from commit 8dc0349c0860172c52d600f2a7422502f11bde2e)
> [Backport to 16] SPIRVReader: Add OpCopyMemory support (#2779)

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
(cherry picked from commit 8dc0349c0860172c52d600f2a7422502f11bde2e)
> [Backport to 15] SPIRVReader: Add OpCopyMemory support (#2779)

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
(cherry picked from commit 8dc0349c0860172c52d600f2a7422502f11bde2e)
> [Backport to 14] SPIRVReader: Add OpCopyMemory support (#2779)

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/get_image_num_mip_levels.ll
- test/transcoding/image_with_access_qualifiers.ll
This patch ensures that we are loading image type, not untyped pointer type when the extension is used. This way we also preserve correct mangling during the reverse translation.
> SPV_KHR_untyped_pointers - fix images translation

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- test/extensions/KHR/SPV_KHR_integer_dot_product/SPV_KHR_integer_dot_product-nonsat.ll
- test/extensions/KHR/SPV_KHR_integer_dot_product/SPV_KHR_integer_dot_product-sat.ll
#1174 implements translating integer dot product OCL builtins to SPIR-V builtins. This pull request is to do the reverse translation.
> Translate integer dot product SPIR-V builtins to OCL builtins

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/AtomicCompareExchangeWeak.spvasm
`OpAtomicCompareExchangeWeak` has been removed and #2665 added a validation for it.
This pull request replaces `OpAtomicCompareExchangeWeak` with `OpAtomicCompareExchange`.
> Handle removed OpAtomicCompareExchangeWeak

- test/ExtendBitBoolArg.ll
- test/SpecConstants/specconstantop-init.spvasm
- test/complex-constexpr-vector.ll
- test/extensions/INTEL/SPV_INTEL_masked_gather_scatter/intel-gather-scatter.ll
- test/lshr_shl_i1_regularize.ll
- test/transcoding/relationals_select.ll
- test/uitofp-with-bool.ll
Update for LLVM commit 38fffa630ee8 ("[LLVM][IR] Use splat syntax when printing Constant[Data]Vector. (#112548)", 2024-11-06).
> Update tests after LLVM IR splat syntax change

- lib/SPIRV/OCLUtil.cpp
- test/extensions/INTEL/SPV_INTEL_subgroups/cl_intel_sub_groups.ll
Per cl_intel_subgroups_short V 1.1.0 short16 is allowed for these builtins.
> [Backport to 17] Allow short16 for ushort16 intel_sub_group_block_read/write

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
This was hitting a "not implemented UNREACHABLE".  Like the other cooperative matrix operations, map this construct to a SPIR-V friendly IR function call.
> SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/OCLUtil.cpp
- test/extensions/INTEL/SPV_INTEL_subgroups/cl_intel_sub_groups.ll
Per cl_intel_subgroups_short V 1.1.0 short16 is allowed for these builtins.
> [Backport to 16] Allow short16 for ushort16 intel_sub_group_block_read/write

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
This patch also introduces limited translation of nofpclass LLVM parameter attribute.
> [Backport to 19] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
This patch also introduces limited translation of nofpclass LLVM parameter attribute.
> [Backport to 18] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
This patch also introduces limited translation of nofpclass LLVM parameter attribute.
> [Backport to 17] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
Note, this backport doesn't add handling of nofpclass attribute, as it doesn't present in LLVM yet.
> [Backport to 16] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
Note, this backport doesn't add handling of nofpclass attribute, as it doesn't present in LLVM yet.
> [Backport to 15] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/fast-math-opencl-builtins.ll
Note, this backport doesn't add handling of nofpclass attribute, as it doesn't present in LLVM yet.
> [Backport to 14] Add fast math flag translation for OpenCL std lib

- lib/SPIRV/SPIRVReader.cpp
- test/phi-multiple-predecessors-invalid-input.spvasm
The goal of the PR is to ensure that PHI node has an incoming value per each predecessor instance even if the input SPIR-V module is invalid as reported by spirv-val.
This PR fixes solution https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2736 intended to fix https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2702
This previous version https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2736 works well for valid SPIR-V modules, but fails to produce correct LLVM IR if a SPIR-V input is incorrect in terms of OpPhi's number of incoming blocks does not match block's predecessor count.
> Ensure that PHI node has an incoming value per each predecessor instance even if the input SPIR-V module is invalid

- lib/SPIRV/SPIRVReader.cpp
- test/phi-multiple-predecessors-invalid-input.spvasm
- test/phi-multiple-predecessors.spvasm
This PR partially fixes issue #2702 in the part that is responsible for SPIR-V to LLVM IR translation. Namely, this PR ensures that all PHI nodes of a Function has the number of incoming blocks matching block's predecessor count. When a PHI node doesn't conform to this rule, this PR inserts missing number of (Value, Basic Block) pairs to make the PHI node valid.
Another problem from #2702, that is violation of the requirement to OpPhi's to have exactly one Parent ID operand for each parent block of the current block in the CFG in the output SPIR-V code, is out of scope of this PR.
> [Backport to 15] Ensure that PHI node has an incoming value per each predecessor instance

- lib/SPIRV/SPIRVReader.cpp
- test/phi-multiple-predecessors-invalid-input.spvasm
- test/phi-multiple-predecessors.spvasm
This PR partially fixes issue #2702 in the part that is responsible for SPIR-V to LLVM IR translation. Namely, this PR ensures that all PHI nodes of a Function has the number of incoming blocks matching block's predecessor count. When a PHI node doesn't conform to this rule, this PR inserts missing number of (Value, Basic Block) pairs to make the PHI node valid.
Another problem from #2702, that is violation of the requirement to OpPhi's to have exactly one Parent ID operand for each parent block of the current block in the CFG in the output SPIR-V code, is out of scope of this PR.
> [Backport to 14] Ensure that PHI node has an incoming value per each predecessor instance

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 19] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 18] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 17] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 16] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/transcoding/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 14] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/constant_composite.spvasm
> [Backport to 15] SPIRVReader: Support OpConstantComposite for cooperative matrix

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/CXX/global-ctor.cl
- test/EnqueueEmptyKernel.ll
- test/SpecConstants/spec-constant-length-array.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/task_sequence.ll
- test/extensions/INTEL/SPV_INTEL_task_sequence/task_sequence_zero_capacity_literals.ll
- test/extensions/KHR/SPV_KHR_untyped_pointers/untyped_ptr_access_chain.ll
- test/llvm-intrinsics/memset-opaque.ll
- test/transcoding/CreatePipeFromPipeStorage.ll
- test/transcoding/constant-vars.ll
- test/transcoding/kernel_query.ll
This improves SPV_KHR_untyped_pointers extension.
Removing struct type from special handling (translate as typed pointer) allowed to fix `spirv-val` error in `CXX/global-ctor.cl` test:
```
error: line 88: OpFunctionCall Argument <id> '25[%this1]'s type does not
match Function <id> '11[%_ptr_Generic_class_Something]'s parameter type.
%30 = OpFunctionCall %void %_ZNU3AS49SomethingC2Ei %this1 %26
```
Other changes allow to translate structs in a new way without violating validation or test checks.
> Use untyped pointers when translating pointer to structure

- lib/SPIRV/SPIRVReader.cpp
> [NFC] Use hasAlignment helper

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_arbitrary_precision_fixed_point/capability-arbitrary-precision-fixed-point-numbers.ll
- test/extensions/INTEL/SPV_INTEL_arbitrary_precision_floating_point/capability-arbitrary-precision-floating-point.ll
- test/group_non_uniform_shuffle_down.ll
Do not lose variable type in forward translation - take it from the already translated "untyped" variable.
> Fix translation of `load` instruction used with `SPV_KHR_untyped_pointers`

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyLogical.spvasm
fixes #2768
Generate an LLVM memcpy for OpCopyLogical, rather than a call to an OpCopyLogical function.
(cherry picked from commit 1a1bf17d9e8684cd826e4278e78f63aa80e2e2ca)
> [Backport to 19] Generate load and store for OpCopyLogical (#2825)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 14] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 15] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 16] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 17] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 18] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
> [Backport to 19] [NFC] Use hasAlignment helper (#2856)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/ptr_diff.ll
We should not lose operand type when `SPV_KHR_untyped_pointers` is used.
> Fix reverse translation of `OpPtrDiff` with untyped pointers

- lib/SPIRV/SPIRVReader.cpp
- test/builtin_returns_struct.spvasm
- test/iaddcarry_builtin.ll
- test/isubborrow_builtin.ll
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
Semantically we can translate `OpIAddCarry` and `OpISubBorrow` back into `@llvm.uadd.with.overflow` and `@llvm.usub.with.overflow` respectively. It require small transformation as there is a difference between return types in SPIR-V and LLVM IR - e.g., SPIR-V instructions return `{i32, i32}` struct, but LLVM intrinsics return `{i32, i1}`.
> Translate OpIAddCarry and OpISubBorrow back to llvm intrinsics

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [Backport to 14] [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [Backport to 15] [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [Backport to 17] [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [Backport to 18] [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/AlignmentId.spvasm
> [Backport to 19] [SPIR-V 1.2] SPIRVReader: Add AlignmentId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 19] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 18] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 17] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 16] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 15] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVReader.cpp
- test/MaxByteOffsetId.spvasm
> [Backport to 14] [SPIR-V 1.2] SPIRVReader: Add MaxByteOffsetId support

- lib/SPIRV/SPIRVBuiltinHelper.cpp
- test/printf-spv-ir-to-ocl.ll
When SPIRVToOCL20Pass is used in OCL CPU backend to translate SPV-IR builtin to OCL builtin, __spirv_ocl_printf call has bigger number of arguments than number of parameters.
> [SPIRVToOCL20] Fix __spirv_ocl_printf translation assert error

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/Shader200/DebugInfoSubrange.ll
- test/DebugInfo/NonSemantic/Shader200/DebugTypeDef.ll
- test/DebugInfo/NonSemantic/Shader200/FortranDynamicArrayExpr.ll
1)
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/450b9dff870214a5b484e720f51b9a2b33dab8b7
[Backport to 15][DebugInfo] Cache CU value translated outside of usual flow Compilation unit can be translated earlier, e.g. in `transEntryPoint()`. We should save the translated LLVM value to be used further.
2)
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/9f0117bb9d719ea50bc551dc029ac0ae02fd30d1
[Backport to 15][DebugInfo] Correctly use cached DICompilationUnit Followup for
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2072
3)
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/0f835cc0ab44c1c15ced28b06ef3aa01b263cc95
[Backport to 15][DebugInfo] Fix DebugTypeSubrange parameters order Count should be the 3rd parameter.
> [Backport to 15][DebugInfo] Backporting 3 patches to LLVM 15

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [SPIR-V 1.2] SPIRVReader: Support LocalSizeId

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/NonSemantic/DIImportedEntity.ll
Original commit:
______________________________________
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2095
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2110
Should be more cautious with inline namespaces
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/34e1327f4f007b01f46b5a8354cbceb29a9e2241
______________________________________
> [Backport to 15][DebugInfo] Fix parent scope index for ImportedEntity

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/array_of_matrices.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/bf16_conversion_instructions.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_apply.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_bfloat16.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_half.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/access_store_untyped.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/arithmetic_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/array_of_matrices.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/conversion_instructions.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
Ensure that we do correct translation of matrices (`SPV_KHR_cooperative_matrix` and `SPV_INTEL_joint_matrix` extensions) when untyped pointers are enabled.
This mainly fixes mangling issues in reverse translation for the untyped pointer. 
Also added handling for typed and untyped SPIR-V friendly access chain instructions in forward translation (a point to review and discuss).
> Improve matrices translation with SPV_KHR_untyped_pointers

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
This commit addresses issues with EnumClass handling in DebugEnumType. 
In reverse translation, a bug caused the EnumClass flag to be incorrectly applied to every DebugEnumType with an UnderlyingType.
Additionally, in forward translation, the support for EnumClassFlag was missing entirely.
> [DebugInfo] Fix EnumClass support

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [Backport to 14] [SPIR-V 1.2] SPIRVReader: Support LocalSizeId (#2898)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [Backport to 15] [SPIR-V 1.2] SPIRVReader: Support LocalSizeId (#2898)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [Backport to 16] [SPIR-V 1.2] SPIRVReader: Support LocalSizeId (#2898)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [Backport to 17] [SPIR-V 1.2] SPIRVReader: Support LocalSizeId (#2898)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/LocalSizeId.spvasm
> [Backport to 19] [SPIR-V 1.2] SPIRVReader: Support LocalSizeId (#2898)

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fp-intrinsics.ll
Add translation for atan2 LLVM
intrinsic which is mapped to corresponding OpenCL extended
instructions.
> Add translation for Intrinsic::atan2

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id)

- CMakeLists.txt
- README.md
- test/CMakeLists.txt
- test/lit.cfg.py
- test/lit.site.cfg.py.in
- tools/llvm-spirv/CMakeLists.txt
Currently, when making spirv-tools available to the translator two things happen:
1. Tests requiring spirv-tools binaries such as `spirv-as` or `spirv-dis` can run.
2. `llvm-spirv` is linked against spirv-tools libraries to enable `--spirv-tools-dis` option.
This patch separates (2.) into a different option (`LLVM_SPIRV_ENABLE_LIBSPIRV_DIS`), so that we can still run tests requiring spirv-tools binaries even if we don't want to link `llvm-spirv` against spirv-tools libraries.
> Add cmake option to enable --spirv-tools-dis feature

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 19] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 18] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 17] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 16] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 15] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/LocalSizeHintId.spvasm
> [Backport to 14] [SPIR-V 1.2] SPIRVReader: Support LocalSizeHintId

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 19] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 18] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 17] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 16] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 15] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- test/SubgroupsPerWorkgroup.spvasm
- test/SubgroupsPerWorkgroupId.spvasm
> [Backport to 14] [SPIR-V 1.1/1.2] SPIRVReader: Add SubgroupsPerWorkgroup(Id) (#2916)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 19][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 18][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 17][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 16][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 15][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 14][DebugInfo] Fix EnumClass support (#2876)

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
Adds support for SPIR-V [OpBitcast](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpBitcast) instructions where the source is a pointer and the destination is not a pointer, and where the source is not a pointer and the destination is a pointer.  This needs to be handled as a special case because the LLVM [bitcast](https://llvm.org/docs/LangRef.html#bitcast-to-instruction) instruction does not support this.
> handle OpBitcast between pointers and non-pointers

- test/transcoding/OpImageSampleExplicitLod_arg.cl
- test/transcoding/OpImageWrite.cl
Use clang's tablegen-driven mechanism for builtins, which is faster than parsing the opencl-c.h header.
> Add -fdeclare-opencl-builtins to more .cl tests

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/NonSemantic.AuxData.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-gv-attributes.ll
- test/extensions/KHR/SPV_KHR_non_semantic_info/preserve-gv-metadata.ll
Motivations is similar as f729c49. This PR addresses SYCL device global which may have attributes "sycl-device-image-scope", "sycl-host-access" and "sycl-unique-id". Failure to preserve "sycl-unique-id" after llvm-spirv translation triggers assert at
https://github.com/intel/llvm/blob/2824f61dd36790448a224cd596985bd01cbcd0f3/llvm/lib/SYCLLowerIR/DeviceGlobals.cpp#L85
Also preserve GlobalVariable metadata as an improvement, though there is no test to show this is really needed.
> Translate nonsemantic attribute and metadata of GlobalVariable

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 19] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 18] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 17] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 16] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 15] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVReader.cpp
- test/OpBitcast_ptr_scalar.spvasm
- test/OpBitcast_ptr_vector.spvasm
> [Backport to 14] handle OpBitcast between pointers and non-pointers

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Update for llvm-project commit abba01adad5d ("[ADT] Deprecate PointerUnion::{is,get} (NFC) (#122623)", 2025-01-13).
> Update for deprecation of llvm::PointerUnion::get

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
Update for llvm-project commit abba01adad5d ("[ADT] Deprecate PointerUnion::{is,get} (NFC) (#122623)", 2025-01-13).
> Update more llvm::PointerUnion::get calls

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
`SPV_KHR_cooperative_matrix` extension defines that the only argument accepted in this instruction is `Matrix Type <id>`, not the pointer to an actual matrix.
This resolves #2963
> Align translation of `OpCooperativeMatrixLengthKHR` to match the spec

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Change #122928 in LLVM modifies the signature of `createObjectPointerType` in a backwards incompatible fashion; this adapts the translator's single use of that interface to match the new signature, whilst retaining existing behaviour.
> Adapt to change introduced by #122928 in upstream

- test/DebugInfo/X86/dwarf-public-names.ll
Update after llvm-project commit 7c729418d721 ("[llvm][DebugInfo] Attach object-pointer to DISubprogram declarations (#122742)", 2025-01-17).
> Update dwarf-public-names.ll after LLVM change

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVToOCL.cpp
With opaque pointers, this is equivalent to calling `IRBuilder::CreateAddrSpaceCast`.
> [NFC] Stop using IRBuilder::CreatePointerBitCastOrAddrSpaceCast

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> [Backport to 14] Add return type for OpReadClockKHR SPIR-V friendly IR

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> [Backport to 16] Add return type for OpReadClockKHR SPIR-V friendly IR

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> [Backport to 15] Add return type for OpReadClockKHR SPIR-V friendly IR

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> [Backport to 17] Add return type for OpReadClockKHR SPIR-V friendly IR

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_shader_clock/shader_clock.ll
> [Backport to 18] Add return type for OpReadClockKHR SPIR-V friendly IR

- tools/llvm-spirv/CMakeLists.txt
For in-tree builds with shared libraries, setting the rpath not only works, but is required.
Fixes #2906
> Limit NO_INSTALL_RPATH to out-of-tree builds.

- lib/SPIRV/SPIRVWriter.cpp
This PR is to fix usage of the SPIR-V Backend API by updating the list of supported by the SPIR-V Backend extensions and removing no longer needed options in the call to the SPIR-V Backend API call. More details about the context of the change are available in https://github.com/llvm/llvm-project/pull/124745 where The SPIR-V Backend API was refactored wrt. a way it's working with user facing options.
> Update the list of supported by the SPIR-V Backend extensions and remove unneeded options in the call to the SPIR-V Backend API call

- lib/SPIRV/SPIRVLowerConstExpr.cpp
Update for llvm-project commit 79499f010d2b ("[NFC][DebugInfo] Deprecate iterator-taking moveBefore and getFirstNonPHI (#124290)", 2025-01-28).
> Update for deprecation of insertBefore/moveBefore

- test/DebugInfo/NonSemantic/Shader200/DebugLinePriority.spt
This test had the following issues:
- The ID bound in the header was set too low.
- The OpVariable with ID 6 was declared with the Function (7) storage class, but defined outside of a Function.  Change its storage class to CrossWorkgroup (5).
Fix those and run spirv-val on this test.
> Fix DebugLinePriority.spt SPIR-V validation errors

- test/DebugInfo/NonSemantic/Shader200/DebugLinePriority.spt
This test had the following issues:
- The ID bound in the header was set too low.
- The OpVariable with ID 6 was declared with the Function storage class, but defined outside of a Function.
Fix those and run spirv-val on this test.
(cherry picked from commit 05adb2479d3ee31f34c8466e336c19693170bf55)
> [Backport to 19] Fix DebugLinePriority.spt SPIR-V validation errors

- test/DebugInfo/NonSemantic/Shader200/DebugLinePriority.spt
This test had the following issues:
- The ID bound in the header was set too low.
- The OpVariable with ID 6 was declared with the Function storage class, but defined outside of a Function.
Fix those and run spirv-val on this test.
(cherry picked from commit 05adb2479d3ee31f34c8466e336c19693170bf55)
> [Backport to 18] Fix DebugLinePriority.spt SPIR-V validation errors

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
- test/var_function_init.spvasm
A Function storage class variable needs storage for each dynamic execution instance, so emit an alloca instead of a global.  The SPIR-V Reader was already doing so for OpVariables without an initializer, but when an initializer is present it would still emit a global.
Co-authored-by: Ben Watkins <ben.watkins@arm.com>
(cherry picked from commit 648654da1d135e582dd7aeaec85855d48310109e)
> [Backport to 20] Emit alloca for all OpVariables with Function storage

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
- test/var_function_init.spvasm
A Function storage class variable needs storage for each dynamic execution instance, so emit an alloca instead of a global.  The SPIR-V Reader was already doing so for OpVariables without an initializer, but when an initializer is present it would still emit a global.
Co-authored-by: Ben Watkins <ben.watkins@arm.com>
(cherry picked from commit 648654da1d135e582dd7aeaec85855d48310109e)
> [Backport to 19] Emit alloca for all OpVariables with Function storage

- lib/SPIRV/SPIRVReader.cpp
- test/OpCopyMemory.spvasm
- test/var_function_init.spvasm
A Function storage class variable needs storage for each dynamic execution instance, so emit an alloca instead of a global.  The SPIR-V Reader was already doing so for OpVariables without an initializer, but when an initializer is present it would still emit a global.
Co-authored-by: Ben Watkins <ben.watkins@arm.com>
(cherry picked from commit 648654da1d135e582dd7aeaec85855d48310109e)
> [Backport to 18] Emit alloca for all OpVariables with Function storage

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Not all `SPIRVValue` are `SPIRVInstruction`. For example, a `SPIRVType` is a `SPIRVValue` but not a `SPIRVInstruction`, so the cast is undefined behavior. Prevent invalid casts by checking if `SV` is indeed a `SPIRVInstruction` before doing the cast.
> Prevent invalid cast.

- lib/SPIRV/SPIRVReader.cpp
Because `BB` can be `nullptr`, we shouldn't use it to get the LLVM context.  Use `Src` instead.
> fix possible nullptr dereference in OpBitCast pointer handling

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
Currently, when reverse translating, we hardcode either 0 or `SPIRAS_Private` as the address space for `alloca`s. This is not ideal as it creates tight coupling with the current AS mappings. Furthermore, it is not necessary, as the DataLayout holds the AllocaAS, which is what we need. Hence, this patch changes all hardcoded callsites where we create an `AllocaInst` to use the DataLayout specified AS. It's NFC as it does not modify existing behaviour.
> [NFC] `alloca`s should use the AllocaAS

- .github/workflows/check-code-style.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [CI] Move away from deprecated set-output

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length_legacy.spt
> Check if `OpCooperativeMatrixLengthKHR` operand is a type

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length_legacy.spt
> [Backport to 20] Check if `OpCooperativeMatrixLengthKHR` operand is a type (#3011)

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length_legacy.spt
> [Backport to 19] Check if `OpCooperativeMatrixLengthKHR` operand is a type (#3011)

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
Similar as ConvertHandleToImageINTEL, ConvertHandleToSampledImageINTEL
builtin may have the same argument type but different return types.
So we need to add ret type as name suffix when translating to LLVM IR
> [Backport to 16][SPV_INTEL_bindless_images] Add ret type to convert-SampledImage builtin name (#2576)

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_bindless_images/bindless_images_generic.ll
Similar as ConvertHandleToImageINTEL, ConvertHandleToSampledImageINTEL
builtin may have the same argument type but different return types.
So we need to add ret type as name suffix when translating to LLVM IR.
> [Backport to 15][SPV_INTEL_bindless_images] Add ret type to convert-SampledImage builtin name (#2576)

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length_legacy.spt
> [Backport to 16] Check if `OpCooperativeMatrixLengthKHR` operand is a type

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/length_legacy.spt
> [Backport to 15] Check if `OpCooperativeMatrixLengthKHR` operand is a type

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/SPV_KHR_cooperative_matrix/length_legacy.spt
Translate the operand as a type only when it is an `OpTypeCooperativeMatrixKHR`. 
This is a backport of #3011
> [Backport to 14] Check if `OpCooperativeMatrixLengthKHR` operand is a type

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
Starting from SPIR-V 1.6, the `UniformDecoration` capability also enables the `Uniform` decoration (in addition to the `Shader` capability).  llvm-spirv was not aware of this, and would always add the `Shader` (and implied `Matrix`) capabilities when consuming a SPIR-V module with a `Uniform` decoration.
> [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/SPIRVUtil.cpp
Simplify code by not having to manually track insertion positions and debug locations.
> Use IRBuilder in lowerBuiltinCallsToVariables; NFC

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- test/DecorateUniformId.spvasm
Starting from SPIR-V 1.6, the `UniformDecoration` capability also enables the `Uniform` decoration (in addition to the `Shader` capability).
> [SPIR-V 1.6] Allow UniformDecoration capability for UniformId

- lib/SPIRV/SPIRVUtil.cpp
- test/builtin_returns_struct.spvasm
This PR fixes the issue with Khronos Translator incorrectly translating calls to builtins that returns a structure and generating incorrect extractvalue applied to a pointer. The PR is to fix the issue by preserving equivalence of newly inserted values with prior values of function return's type.
> [Backport to 19] Fix incorrect translation of calls to a builtin that returns a structure (#2722)

- lib/SPIRV/SPIRVUtil.cpp
- test/builtin_returns_struct.spvasm
This PR fixes the issue with Khronos Translator incorrectly translating calls to builtins that returns a structure and generating incorrect extractvalue applied to a pointer. The PR is to fix the issue by preserving equivalence of newly inserted values with prior values of function return's type.
> [Backport to 15] Fix incorrect translation of calls to a builtin that returns a structure (#2722)

- lib/SPIRV/SPIRVUtil.cpp
- test/builtin_returns_struct.spvasm
This PR fixes the issue with Khronos Translator incorrectly translating calls to builtins that returns a structure and generating incorrect extractvalue applied to a pointer. The PR is to fix the issue by preserving equivalence of newly inserted values with prior values of function return's type.
> [Backport to 14] Fix incorrect translation of calls to a builtin that returns a structure (#2722)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- test/builtin_returns_struct.spvasm
- test/llvm-intrinsics/uadd.with.overflow.ll
- test/llvm-intrinsics/usub.with.overflow.ll
This PR fixes the issue with Khronos Translator incorrectly translating calls to builtins that returns a structure and generating incorrect extractvalue applied to a pointer. The PR is to fix the issue by preserving equivalence of newly inserted values with prior values of function return's type.
> [Backport to 18] Fix incorrect translation of calls to a builtin that returns a structure (#2722)

- lib/SPIRV/SPIRVUtil.cpp
- test/DebugInfo/builtin-get-global-id.ll
- test/get_global_size.cl
The behaviour for out-of-range dimension arguments to work-item functions is well defined in OpenCL C.  For example, `get_global_size` must return 1 if its argument is larger than `get_work_dim() - 1`.
Ensure the generated `extractelement` index never exceeds the vector size and return the correct out-of-range value (which is either 0 or 1 depending on the builtin).
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2638 .
> Emit select for out-of-range builtin var indices

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/builtin-functions.ll
- test/builtin-globals.ll
- tools/llvm-spirv/llvm-spirv.cpp
Currently, we always convert SPIR-V bultins to globals for forward translation and to functions for reverse translation.
I have a use case where I want to keep them as globals for reverse translation, so I added this mode.
Implementations for both cases already existed, I just consolidated them and added the option.
Backport of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1986.
> [Backport to 14] Add option to control builtin format for reverse translation.

- lib/SPIRV/SPIRVUtil.cpp
- test/DebugInfo/builtin-get-global-id.ll
- test/get_global_size.cl
> [Backport to 19] Emit select for out-of-range builtin var indices

- lib/SPIRV/SPIRVUtil.cpp
- test/DebugInfo/builtin-get-global-id.ll
- test/builtin_duplicate.ll
- test/get_global_size.cl
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
> [Backport to 14] Emit select for out-of-range builtin var indices

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/builtin-get-global-id.ll
- test/builtin-functions.ll
- test/builtin-globals.ll
- test/builtin_duplicate.ll
- test/get_global_size.cl
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- tools/llvm-spirv/llvm-spirv.cpp
> [Backport to 16] Emit select for out-of-range builtin var indices

- lib/SPIRV/SPIRVUtil.cpp
- test/DebugInfo/builtin-get-global-id.ll
- test/builtin_duplicate.ll
- test/get_global_size.cl
> [Backport to 18] Emit select for out-of-range builtin var indices

- lib/SPIRV/SPIRVUtil.cpp
- test/DebugInfo/builtin-get-global-id.ll
- test/builtin_duplicate.ll
- test/get_global_size.cl
> [Backport to 17] Emit select for out-of-range builtin var indices

- lib/SPIRV/SPIRVToOCL.cpp
- test/image_operand_nontemporal.spvasm
Instead of checking that the image operands are equal to the LOD mask, check that the LOD bit is in the image operands.  This way an LOD value of zero may be ignored even when image operands contains bits other than the LOD bit, such as for the SPIR-V 1.6 nontemporal image operand.
fixes #3049
> properly handle LOD values when nontemporal image operand is present

- tools/llvm-spirv/llvm-spirv.cpp
llvm-spirv.cpp was relying on transitive includes for these.
Also remove an unneeded `<set>` include.
> [NFC] Add some missing includes

- .travis.yml
spirv-val from focal reports things like:
Invalid capability operand: 6016
where 6016 is DotProductInputAll capability
> [CI] Fix spirv-val missing features by updating dist on llvm_release_11

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 14] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 16] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 17] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 18] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 19] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/DecorateUniform.spvasm
> [Backport to 20] [SPIR-V 1.6] Allow UniformDecoration capability for Uniform

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_vector_compute/buffer_surface_intel.ll
It should be a target extension type.
> [Backport to 18] Fix OpTypeBufferSurfaceINTEL translation for opaque pointers

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/INTEL/SPV_INTEL_vector_compute/buffer_surface_intel.ll
It should be a target extension type.
> [Backport to 19] Fix OpTypeBufferSurfaceINTEL translation for opaque pointers

- lib/SPIRV/SPIRVUtil.cpp
- test/GroupAndSubgroupInstructions.spvasm
- test/transcoding/OpGroupAsyncCopy.ll
LocalId should not be negative. Change its type from signed to unsigned in SPV-IR aligns with OpenCL work_group_broadcast built-in and use of GroupBroadcast built-in in SYCL header.
Also change NumElements/Stride parameters of OpGroupAsyncCopy to unsigned.
> [SPIRV-to-LLVM] Set LocalId parameter of GroupBroadcast to unsigned in SPV-IR

- lib/SPIRV/libSPIRV/SPIRVEntry.h
It should fix clang-tidy error.
> [NFC] Unlink SPIRVEntry.h and LLVMSPIRVOpts.h

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fp-intrinsics.ll
Add translation for `llvm.modf.*` intrinsics.
> Add translation for llvm.modf.*

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugDeclareUnused.cl
- test/DebugInfo/mem2reged_local_var.ll
We should translate null/undef declare records to DebugDeclare with OpDebugInfoNone instruction referenced in OpVariableId operand.
TODO: currently the specification says, that only OpVariable can be referenced by this operand. This seem to be a spec bug, we should allow OpDebugInfoNone there.
> [DebugInfo] Fix translation of some cases of mem2reged local variables

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
After https://github.com/KhronosGroup/SPIRV-Tools/pull/6027 spirv-val is now rejecting `Aligned 0` Memory Operands.  This caused various tests to fail validation with a recent SPIRV-Tools version.
> Remove `Aligned 0` from tests

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/fcmp.ll
- test/transcoding/fneg.ll
This is a follow-up fix to #2506
> [SPIR-V 1.6] Support reverse translation of FPFastMathMode decoration for `fcmp` instruction

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/fcmp.ll
- test/transcoding/fneg.ll
... decoration for `fcmp` instruction (#3108)
> [Backport to 20] [SPIR-V 1.6] Support reverse translation of FPFastMathMode

- test/debug-label-skip.ll
`--preserve-input-debuginfo-format` option of `llvm-as` is not available after community change llvm/llvm-project@40f9bb9
Also updated debug lable intrinsics to new format as it seems old format will be removed eventually as well.
> Update debug-label-skip.ll test

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugDeclareUnused.cl
- test/DebugInfo/mem2reged_local_var.ll
It's a follow up to 367ede2 with the following additions:
1. don't create unnecessary temporary alloca, instead create nullptr
const - this helps tooling later on as it won't deal with poison;
2. partially revert a change in reverse translation resetting debug
location for debug declarations - we should always try to get
location information from DebugScope, and fall back to LocalVar only if
DebugScope doesn't provide such information.
> [DebugInfo] Continue fixing translation of debug info for mem2reged vars

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- Refactored addUntypedPointerKHRType and addPointerType functions into a single function (It was marked as TODO)
- Combined both functions into one with return type SPIRVType *
- Also re inserted an assert and removed unnecessary if (Marked as TODO)
> Refactoring Two functions into One

- test/transcoding/OpenCL/convert_functions.ll
As discussed in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120#pullrequestreview-2784086336
> Add reverse translation test for integer convert with explicit rounding

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
> [Backport to 15] Remove `Aligned 0` from tests (#3105)

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
> [Backport to 17] Remove `Aligned 0` from tests (#3105)

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
> [Backport to 18] Remove `Aligned 0` from tests (#3105)

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
> [Backport to 19] Remove `Aligned 0` from tests (#3105)

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
> [Backport to 20] Remove `Aligned 0` from tests (#3105)

- test/OpLoopMergeNone.spt
- test/composite_construct_struct.spt
- test/composite_construct_vector.spt
- test/copy_object.spt
- test/right_shift.spt
- test/selection_merge.spt
- test/vector_times_scalar.spt
(cherry picked from commit ec5d4d6a5a6594d39b6120d1d12d13fd2500db9b)
> [Backport to 14] Remove `Aligned 0` from tests (#3105)

- lib/SPIRV/SPIRVWriter.cpp
Update after llvm commits
50e949f3cc47 ("[IR] Teach getAsmString to return StringRef (NFC) (#139406)", 2025-05-10) and
58014a506dd3 ("[IR] Teach getConstraintString to return StringRef (NFC) (#139401)", 2025-05-10).
> Fix build after LLVM InlineAsm changes

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
commit aa529b41c808ba3c1ed57ef1991d1327986dba81
Author: Karol Herbst <kherbst@redhat.com>
Date:   Fri Apr 25 12:29:10 2025 +0200
Add reverse translation test for integer convert with explicit rounding (#3128)
As discussed in
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120#pullrequestreview-2784086336
commit 80d20c4bcc9edb3894184309fd3b9e1fee1086ce
Author: Karol Herbst <kherbst@redhat.com>
Date:   Tue Apr 22 15:19:13 2025 +0200
Rounding modes on int to int conversions are valid OpenCL C builtin functions (#3120)
The OpenCL CTS also tests for this, so those can't be ignored.
Fixes: 04144823 ("Rewrite OpenCL explicit conversion builtins handling
(#2464)")
> [Backport to 20] Rounding modes on int to int conversions are valid OpenCL C builtin functions

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/OpenCL/convert_functions.ll
commit aa529b41c808ba3c1ed57ef1991d1327986dba81
Author: Karol Herbst <kherbst@redhat.com>
Date:   Fri Apr 25 12:29:10 2025 +0200
Add reverse translation test for integer convert with explicit rounding (#3128)
As discussed in
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/3120#pullrequestreview-2784086336
commit 80d20c4bcc9edb3894184309fd3b9e1fee1086ce
Author: Karol Herbst <kherbst@redhat.com>
Date:   Tue Apr 22 15:19:13 2025 +0200
Rounding modes on int to int conversions are valid OpenCL C builtin functions (#3120)
The OpenCL CTS also tests for this, so those can't be ignored.
Fixes: 04144823 ("Rewrite OpenCL explicit conversion builtins handling
(#2464)")
> [Backport to 19] Rounding modes on int to int conversions are valid OpenCL C builtin functions

- lib/SPIRV/OCLUtil.h
- test/DebugInfo/LocalAddressSpace.ll
- test/DebugInfo/RelativeSrcPath.ll
Previously it used posix, causing strange behaviour like reported in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/3126
It's NFC change for the translator-based tool chains. Yet if SPIR-V consumer is not llvm-spirv - the fix should help.
Note, the patch is not attempting to guess separators depending on the user's IR input, so for the linux <-> windows cross compilation the result will be odd (like it was before).
> [DebugInfo] Use native for the system separator for source path string

- lib/SPIRV/OCLUtil.h
> [Backport to 20] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 19] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 18] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 17] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 16] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 15] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/OCLUtil.h
> [Backport to 14] Make OCLUtil.h compatible with C++20 standard (#3149)

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fp_fast_math_mode/fp_contract_reassoc_fast_mode.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2028 
was supposed to get cherry-picked
> [Backport to 17] Missing addExtension in SPIRVWriter.cpp

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_fp_fast_math_mode/fp_contract_reassoc_fast_mode.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2028
was supposed to get cherry-picked
> [Backport to 18] Missing addExtension in SPIRVWriter.cpp

- lib/SPIRV/SPIRVWriter.cpp
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2028
was supposed to get cherry-picked
> [Backport to 19] Missing addExtension in SPIRVWriter.cpp

- lib/SPIRV/SPIRVWriter.cpp
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2028
was supposed to get cherry-picked
> [Backport to 20] Missing addExtension in SPIRVWriter.cpp

- .github/workflows/backport-to-branch.yml
Previous logic was picking commits with committer's SHA. But instead we should cherry-pick the merge commit itself.
TODO: if a PR is merged with "Rebase and Merge" strategy current logic will pick only the last commit. We usually don't merged like this, yet for rare accousions we should gather all of the merged commits.
> [CI] Pick SHA of commit to cherry-pick from merge commit

- lib/SPIRV/SPIRVWriter.cpp
- test/duplicate-types.ll
Check if an array type exists in TypeMap before inserting it to prevent duplications.
> Prevent duplicate array type insertion into TypeMap.

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/conversion_instructions.ll
The SPIR-V reader would crash on the added test during reverse translation.  Ensure any cooperative matrix type conversion is handled the same way as a cooperative matrix type conversion with an FPRoundingMode or SaturatedConversion decoration.
> Fix crash on coopmat conversion without decoration

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/SPV_KHR_cooperative_matrix/conversion_instructions.ll
The SPIR-V reader would crash on the added test during reverse translation. Ensure any cooperative matrix type conversion is handled the same way as a cooperative matrix type conversion with an FPRoundingMode or SaturatedConversion decoration.
(cherry picked from commit 32738f9371037124b8697f78605652fe1afc4423)
> [Backport to 14] Fix crash on coopmat conversion without decoration

- lib/SPIRV/SPIRVReader.cpp
- test/extensions/KHR/SPV_KHR_cooperative_matrix/conversion_instructions.ll
The SPIR-V reader would crash on the added test during reverse translation. Ensure any cooperative matrix type conversion is handled the same way as a cooperative matrix type conversion with an FPRoundingMode or SaturatedConversion decoration.
(cherry picked from commit 32738f9371037124b8697f78605652fe1afc4423)
> [Backport to 17] Fix crash on coopmat conversion without decoration

- CMakeLists.txt
> Fix LLVM_SPIRV_BACKEND_TARGET_PRESENT detection when building inside the LLVM tree

- test/DebugInfo/X86/dbg-value-range.ll
Update a test after llvm-project commit 28bda778437f ("Introduce MCAsmInfo::UsesSetToEquateSymbol and prefer = to .set", 2025-06-11).
> Update dbg-value-range.ll test after 28bda778437f

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Remove occurrences of IsNewDbgInfoFormat after llvm-project commit 97ac6483aaea ("[DebugInfo][RemoveDIs] Delete debug-info-format flag (#143746)", 2025-06-12).
Now only the new DebugInfo format exists, so remove the code paths that handled the old format.  There might be more code we can remove, but keep this change minimal to just fix the build.
> Update after IsNewDbgInfoFormat removal

- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix_constant_null.spvasm
Current design does not imply inheritance between `SPIRVConstantNull` and `SPIRVConstant` classes, however it is possible that we do the `static_cast` of `SPIRVValue` to `SPIRVConstant` for null constant. Return zero-value in that case.
> Support casting of `OpConstantNull` to `SPIRVConstant`

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVTypeScavenger.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/OpenCL.std/printf.spvasm
- test/extensions/EXT/SPV_EXT_relaxed_printf_string_address_space/non-constant-printf.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/CodeSectionINTEL/const-function-pointer.ll
- test/extensions/INTEL/SPV_INTEL_function_pointers/const-function-pointer.ll
- test/extensions/INTEL/intel-basic-vector-pointers-opaque.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/access_store.ll
- test/transcoding/OpSwitchChar.ll
- test/transcoding/constant-vars.ll
- test/transcoding/global_block.cl
- test/type-scavenger/call.ll
- test/type-scavenger/globals.ll
- test/type-scavenger/load-indirect.ll
- test/type-scavenger/recursive-type.ll
Backport to llvm 16 rewrite of the type scavenger to fix incorrect type scavenging like #2024.
> [Backport to 16][OpaquePointers] Rewrite the type scavenger. (#1957)

- lib/SPIRV/SPIRVReader.cpp
Update for llvm-project commit 2529de5c935a ("[ADT] Deprecate ArrayRef(std::nullopt) (#146011)", 2025-06-27).
> Update after ArrayRef(std::nullopt) deprecation

- lib/SPIRV/OCLUtil.h
Clang does not like the current way of directly assigning members of one enum to another and requires explicit static_cast on the way.
Compilation failed:
https://godbolt.org/z/3PYqsETdc
Compilation successful:
https://godbolt.org/z/bjeYK376s
> Explicitly cast OCLMemOrderKind members from std::memory_order in C++20 case

- lib/SPIRV/SPIRVWriter.cpp
- test/gep-operand-source-mismatch.ll
The source element type used in a GEP may differ from the actual type of the pointer operand (e.g., ptr i8 vs. ptr [N x T]). This mismatch can lead to incorrect address computations during translation to SPIR-V of GEP used in constexpr context, which requires that pointer types match the type of the object being accessed.
This patch inserts an explicit bitcast to convert the GEP pointer operand to the expected type, derived from the GEP’s source element type, before emitting an PtrAccessChain.
This ensures the resulting SPIR-V instruction has a correctly typed base pointer and produces valid indexing behavior.
For example:
Before this change, the following GEP was translated incorrectly: getelementptr(i8, ptr addrspace(1) @a_var, i64 2)
Whereas this nearly equivalent GEP was handled …
> [Backport to 16][OpaquePointers][LLVM->SPIRV] Cast the GEP base pointer to source type upon mismatch (#3255)

- lib/SPIRV/SPIRVBuiltinHelper.h
BuiltinCallMutator::ValueTypePair defines its own constructor with arguments (llvm::Value *V, llvm::Type *T)
BuiltinCallMutator::ValueTypePair also uses std::pair constructor with arguments (llvm::Value *&V, llvm::Type *&T)
This causes an ambiguity that confuses GCC when compiling for C++20.
Issue repro on goldbolt: https://godbolt.org/z/MTnvx6E6T
There are multiple possible fixes. I think the one with the least impact is to change BuiltinCallMutator::ValueTypePair constructor signature to conform with std::pair constructor signature.
Fixed version: https://godbolt.org/z/49WzvjK63
Other possibility is to remove the constructors that are redundant. But maybe they are very important.
> Fix potential constructor ambiguity in BuiltinCallMutator::ValueTypePair

- lib/SPIRV/CMakeLists.txt
- tools/llvm-spirv/CMakeLists.txt
When building with SPIR-V backend support, naturally we need to link against the SPIR-V backend. Currently this is done as part of the tool (`llvm-spirv`)'s CMake dependencies, instead of `SPIRVLib` which is the actual CMake target that requires the SPIR-V backend (`SPIRVTranslateModule` call inside `SPIRVWriter.cpp`).
This causes a linker error if someone depends on `SPIRVLib` directly and doesn't depend on `llvm-spirv`.
Move the dependency from the tool to the lib.
> Fix build when linking against SPIRVLib with SPIR-V backend support enabled

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_apply.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/cooperative_matrix_prefetch.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix.ll
- test/extensions/INTEL/SPV_INTEL_joint_matrix/joint_matrix_checked.ll
- test/extensions/INTEL/SPV_INTEL_usm_storage_classes/intel_usm_addrspaces.ll
- test/extensions/KHR/SPV_KHR_cooperative_matrix/cooperative_matrix.ll
- test/llvm-intrinsics/lifetime.ll
- test/llvm-intrinsics/memmove.ll
This patch removes bitcast introduced in TypeScavenger that was previously served as W/A to solve a discrepancy between LLVM's and SPIR-V's lifetime inst definitions.
> Adjust Lifetime intrinsic translation after 92c55a315eab

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
SmallDenseMap requires sentinel values out of the `SPIRVStorageClassKind` range.  This became a build error after llvm-project commit `38f82534bbe9 ("Reject out-of-bounds enum sentinels in DenseMap/DenseSet. (#150308)", 2025-07-24)`.
As the `SPIRVStorageClassKind` enum comes from an external header we cannot change it to an enum class or add an underlying type.  This is actually solved in the `spirv.hpp11` header, but migrating to that header requires more widespread changes; just switch to a `std::unordered_map` for now.
> Fix UB in UntypedPtrTyMap

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/fp-intrinsics.ll
The intrinsics were added in https://github.com/llvm/llvm-project/commit/89881480 and their behavior matches with OpenCL fmin/fmax built-in. This PR fixes llvm-spirv error when compiling __builtin_elementwise_maximumnum for libclc spirv target.
> Translate llvm.minimumnum/maximumnum intrinsics to OpenCL extended inst fmin/fmax

- .clang-tidy
The LLVM coding standard [1] generally prefers static function declarations, so turn off the `misc-use-anonymous-namespaces` option that suggests using anonymous namespaces.
[1] https://llvm.org/docs/CodingStandards.html#restrict-visibility
> .clang-tidy: disable conflicting misc-use-anonymous-namespaces

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
This PR refactors the `parseAndCreateSPIRVEntry` function by extracting the word count check into a separate static function named `validateWordCount`, in `SPIRVModule.cpp`.
> Refactor WordCount Validation to Separate Static Function

- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/INTEL/SPV_INTEL_variable_length_array/basic.ll
Otherwise their declarations would survive translation to SPIR-V.
> Add llvm.stack[save/restore] intrinsics to isKnownIntrinsic

- lib/SPIRV/SPIRVWriter.cpp
- test/addrspacecast_null.ll
This allows translation of code like the following, which previously errored:
```llvm
target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-G1"
target triple = "spir64-unknown-unknown"
define spir_kernel void @bar(ptr addrspace(1) %arg) {
pass26:
%expr = icmp eq ptr addrspace(1) addrspacecast (ptr null to ptr addrspace(1)), %arg
ret void
}
```
It is important this works because the addrspacecast is needed for addrspaces where NULL doesn't correspond to a zero value. We previously ran into correctness errors on some platforms without this cast, ref ROCm/llvm-project#281
> allow casting nullptr to any addrspace

- lib/SPIRV/SPIRVReader.cpp
Update for llvm-project commit `9b493dcad259` ("[ADT] Deprecate the redirection from SmallSet to SmallPtrSet (Take 2) (#155078)", 2025-08-23).
> Use SmallPtrSet after deprecation

- test/instructions/icmp.ll
- test/llvm-intrinsics/fp-vector-intrinsics.ll
Ported two tests from the LLVM project to the SPIRV-LLVM-Translator: icmp.ll validates integer comparison instructions  for scalar and vector types, and fp-vector-intrinsics.ll verifies floating-point vector intrinsics, ensuring accurate SPIR-V translation.
> Two tests Ported from the LLVM Project to Translator
