KhronosGroup/SPIRV-LLVM-Translator

- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVWriter.cpp
> Update SPIR-V/LLVM Translator to use new MemIntrinsics API

- .travis.yml
- CMakeLists.txt
- LLVMSPIRVLib.pc.in
- lib/SPIRV/CMakeLists.txt
- test/CMakeLists.txt
- test/lit.cfg.py
- test/lit.site.cfg.py.in
- tools/llvm-spirv/CMakeLists.txt
basically contains a complete rework of the CMake files, so that we can build the project without having to put it inside a llvm tree and build it there. A pkgconfig file is also added so that other projects can simply depend on LLVMSPIRVLib.
Travis was changed accordingly to be able to build and run the tests.
llvm-lit is a bit weirdly handled on each distribution. On Fedora I have a "python3-lit" package which provides a "lit" binary the build system uses. On Ubuntu you have to install llvm-X-tools and point LLVM_EXTERNAL_LIT to the correct lit.py file.
There were also some changes required to the lit files, so that lit doesn't try to create new directories in system paths.
Builds can be seen here until the project enables travis-ci: …
> Full conversion to standalone project + travis fixup

- CMakeLists.txt
Currently, LLVM_SPIRV_VERSION is not defined when building in-tree,
resulting in the pkgconfig file having an empty version.
Fixes: 7b8cc990 ("cmake: rework to be able to build outside LLVM")
> Always define LLVM_SPIRV_VERSION

- CMakeLists.txt
- include/LLVMSPIRVLib.h
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVWriterPass.cpp
- tools/llvm-spirv/llvm-spirv.cpp
Also, the version was bumped to 0.2.1 (from 0.2.0) due to the changes.
Fix: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/15
> Rename the installed header and install it in a prefix

- utils/check_code_tidyness.sh
Fixes: 72d4a32 ("Run clang-tidy on the codebase")
> Do not error out when clang-tidy had no relevant inputs

- lib/SPIRV/SPIRVReader.cpp
- test/right_shift.spt
transFlags sets the "exact" flag in LLVM-IR for AShr and LShr
instructions. This is in fact incorrect as this means that LLVM will do some
optimisations that are potentially illegal.
Setting the exact flag says that there are no set bits in the bits being shifted
off the end during the shift - and thus shift combining is safe to do.
In a situation like this ((X >> 5) << 2) it will be transformed into (X >> 3)
which is incorrect as the 2 LSBs may contain set bits.
This change is ported from AMDVLK
> Remove transFlags in SPIRVToLLVM

- test/transcoding/check_ro_qualifier.ll
- test/transcoding/check_wo_qualifier.ll
- test/transcoding/cl-types.ll
- test/transcoding/spirv-types.ll
This is to reflect changes introduced in https://reviews.llvm.org/D47106
[FileCheck] Make CHECK-DAG non-overlapping
Now CHECK-DAG skips repeating matches by default. We have such cases when we
check kernel_arg_type and kernel_arg_base_type with CHECK-DAG and they happen
to be the same.
> Update tests after changes in the FileCheck tool

- lib/SPIRV/SPIRVWriter.cpp
- test/image_store.ll
Image type may be represented in llvm IR in two forms:
- OpenCL form, for example, '%opencl.image2d_ro_t',
- SPIRV form, for example, '%spirv.Image._void_1_0_0_0_0_0_0',
but in both cases it is the same image type and it should be mapped to
one SPIR-V type.
> Fix llvm to spirv translation for image types

- lib/SPIRV/OCL20To12.cpp
- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
* Adding asserts to prevent possible dereference of a null pointer
* Adding return statements after llvm_unreachable
> [NFC] Refactoring to fix issues found by a static analysis tool.

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
'cl_intel_subgroup' extension allows to use sub_group_barrier() built-in
with OpenCL 1.2/2.0. It requires to translate this built-in to
reqular (core) SPIR-V instruction OpControlBarrier.
Note: currently clag generates nothing representing vendor extensions
like 'cl_intel_subgroup'. So, SPIR-V translator doesn't check that the
extensions was enabled. It assumes that if a built-in or a type which
belong to one of supported extension used in the IR, this extensions is
enabled.
> Generate OpControlBarrier for Subgroup scope for OpenCL 1.2/2.0

- tools/llvm-spirv/CMakeLists.txt
When llvm-spirv is built out of LLVM tree there might be two cases:
- SPIR-V library linked statically. This this case linker and loader are
able to handle LLVM symbols correctly.
- SPIR-V library linked dynamically. LLVM_LINK_COMPONENTS is ignored as
all LLVM components is supposed to be linked into libLLVM.so and we
should explicitly link with SPIR-V library.
If we build llvm-spirv tool in LLVM tree explicit link with SPIR-V
library might lead to multiple symbol definition (e.g. SPIR-V library
linked with libLLVM.so as LLVM component and with llmv-spirv tool via
explicit target_link_library command).
> Avoid double linking of LLVM/SPIR-V libraries.

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/lifetime.ll
- test/transcoding/lifetime-sized.ll
- test/transcoding/llvm.memmove.ll
LLVM lifetime intrinsics accept only i8* pointers + size as object
descriptors, so typical pattern for local variables is
alloca+bitcast+lifetime instructions.
SPIR-V translator tries store original type into lifetime instruction
looking though bitcast. It also removes bitcast from the SPIR-V file and
tries to recover it during SPIR-V conversion.
This patch simplifies the translation by keeping bitcast instruction and
fixes assertion of lifetime intrinsics for 8-bit objects.
> Fix lifetime intrinsics translation.

- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVWriter.cpp
- test/RelativeSrcPath.ll
A full path to file is represented with a potentially relative path to file and a path to directory in LLVM and just a path to file in SPIRV. This commit fixes translation of relative paths to files by replacing them with absolute ones.
> Fix translation of relative source file paths

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- test/InvalidAtomicBulitins.ll
Some atomic instructions allow only integer result type
> Disabling generation of invalid atomic instructions

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- test/transcoding/OpControlBarrier_cl12.ll
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
According to the description in the OpenCL specification, barrier,
work_group_barrier and sub_group_barrier builtins imply acquire-release
memory-order semantics.
Resolves #70
> Set SequentiallyConsistent bit in translation of barrier builtins

- test/DebugInfo/Generic/incorrect-variable-debugloc1.ll
- test/lit.cfg.py
This commit adds dependencies for currently unsupported debug information tests and updates one of the outdated ones in accordance with https://reviews.llvm.org/D51640 .
> Enable unsupported debug information tests

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/KernelArgTypeInOpString.ll
- test/layout.ll
- test/transcoding/cl-types.ll
- test/transcoding/spirv-types.ll
In LLVM IR information about typedef'ed type name stored only in
kernel_arg_type metadata, but it is missed while translating in SPIRV.
There is no possibility to store typedef's in SPIRV.
As a workaround we store information about type names from
kernel_arg_type metadata in an OpString instruction and restore it
while translating from SPIRV to LLVM.
> Make it possible to keep typedef'ed type names in SPIRV

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/TransOCLMD.cpp
- test/ContractionOff.ll
Previously we relied on !opencl.enable.FP_CONTRACT metadata to set
ContractionOff execution mode for a kernel. But now clang doesn't generate
this metadata. Due to lack of reliable mechanism for representation of the
pragma in LLVM IR, this patch implements sort of very primitive heuristic
to detect usage of #pragma OPENCL FP_CONTRACT OFF.
> Change translation of FP_CONTRACT to SPIRV

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/kernel_arg_name.ll
If the user has requested `kernel_arg_name` metadata, always generate
it even if some or all of the kernel arguments are unnamed.
The `-spirv-gen-kernel-arg-name-md` option seems to be lacking tests
so far, so add a new test.
> Add kernel_arg_name regardless of unnamed arguments

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/check_ro_qualifier.ll
- test/transcoding/check_wo_qualifier.ll
According to OpenCL 2.0 Table 5.21:
The type name returned will be the argument type name as it was
declared with any whitespace removed. [...] The argument type
name returned does not include any type qualifiers.
> Do not include image access qualifier in kernel_arg metadata

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/image_with_suffix.ll
Image type names may end up getting a .<n> suffix, e.g. when multiple
LLVM IR modules defining the same type name are loaded into an
LLVMContext.  The translator already has some basic handling for that,
but the included test case triggers an assert.
Improve the type name recognition handling and factor it out into a
helper function.
> Fix image type name recognition

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- test/ContractionOff.ll
6197c7d5901a0bd5638b1b464cdbff7e9ccdb210 introduced some very primitive heuristic to detect when fp-contraction is disabled to set ContractionOff execution mode.
There were test cases where contraction was enabled, but SPIR-V Translator set it to off.
The root cause is in poor algorithm of 'disabled fp-contract' detection.
This patch doesn't bring the good and reliable algorithm and only provides a workaround.
> Fix disabling of fp-contract

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/image_builtins.ll
Calls to read_imageh and write_imageh were incorrectly transcoded to
read_imagef and write_imagef.  Emit the 'h' suffix for 16-bit float
types.
> Emit half type suffix for read/write_image builtins

- lib/SPIRV/SPIRVUtil.cpp
LLVM type names may end up getting a .<n> suffix, e.g. when multiple
LLVM modules defining the same type name are loaded into a single
LLVMContext.  transTypeDesc was already ignoring such suffixes for
image and pipe types, but other OpenCL types could be affected by the
same issue, resulting in incorrect mangling of builtin function
arguments.
Strip the suffix for any type whose name starts with "opencl.".
> Ignore .n suffix for all OpenCL types

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/OpControlBarrier_cl12.ll
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
Without this attribute, LLVM passes such as SimplifyCFG may duplicate
barrier calls, which would cause incorrect behaviour of the compiled
program.
> Set noduplicate attribute for barriers

- lib/SPIRV/SPIRVReader.cpp
The error path in transValueWithoutDecoration was inside the default
case of a switch statement.  Move it to the correct place, i.e., after
the switch statement.
Reported-by: Pedro Olsen Ferreira
> Fix error path in transValueWithoutDecoration

- test/DebugInfo/Generic/2010-04-19-FramePtr.ll
> Update tests after change in LLVM

- lib/SPIRV/SPIRVReader.cpp
Update for 9ec60d7d8fa ("[opaque pointer types] Add a FunctionCallee
wrapper type, and use it.", 2019-02-01).
> Update LLVM to r352869

- lib/SPIRV/SPIRVReader.cpp
removeFromParent was used instead of eraseFromParent,
resulting in a memory leak.
> Fix for memory leak.

- lib/SPIRV/SPIRVReader.cpp
- test/KernelArgTypeInOpString2.ll
Fixed SPIRVReader/transKernelArgTypeMedataFromString to track  brackets and to not split argument when comma is inside brackets.
> Fixed SPIRVReader/transKernelArgTypeMedataFromString

- include/LLVMSPIRVLib.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/OCL20To12.cpp
- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriterPass.cpp
- lib/SPIRV/SPIRVWriterPass.h
- lib/SPIRV/TransOCLMD.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVUtil.h
- tools/llvm-spirv/llvm-spirv.cpp
The default remains the same, i.e. using the LLVM API, but removes the
option of using the std API, as it was untested and failed to compile.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/9
> Remove the _SPIRV_LLVM_API switch

- lib/SPIRV/SPIRVWriter.cpp
Order of evaluation of functions arguments is unspecified in C++. Therefore
having translation of the initializer and the type as arguments of
SPIRVModule::addVariable results in slightly different SPIR-V depending on
whether we use GCC or Clang to build the translator.
> Translate initializer of global variables before its type.

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugFunction.ll
In some cases the translator couldn't find the function described by the
DISubprogram by the name. Now we iterate over all functions in the module
untill we find the desired function using DISubprogram::describes() method.
> Fix translation of DebugFunction instruction

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
This patch introduces translation of the following FPGA memory attributes:
* register
* memory
* numbanks
* bankwidth
Link to the SPIR-V Specification:
http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/
blob/master/extensions/INTEL/SPV_INTEL_fpga_memory_attributes.html
> Translate Intel FPGA memory attributes

- lib/SPIRV/CMakeLists.txt
- tools/llvm-spirv/CMakeLists.txt
Translator builds with a pre-built LLVM recently broke due to headers
in the LLVM source tree no longer being found.
Update our CMake files for LLVM commit r353924 / 95decc39b55 ("[llvm]
[cmake] Provide split include paths in LLVMConfig", 2019-02-13).
> Update include paths for pre-built-LLVM builds

- test/CMakeLists.txt
Both llvm-config and llvm-readelf are required to run
the tests.
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Add missing dependencies to check-llvm-spirv target

- lib/SPIRV/SPIRVLowerConstExpr.cpp
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Fix typo in help text for -spirv-lower-const-expr

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/OpSwitchChar.ll
The attached test case asserted in SPIRVSwitch::validate().
Fix by Neil Hickey.  Test case by Sven van Haastregt.
> Fix OpSwitch miscalculation of Pair sizes

- test/lit.cfg.py
Only substitute DebugInfo-test-specific tools such as llvm-readelf
when running the DebugInfo tests.  Otherwise these tools may not be
available, causing llvm-lit to warn about being unable to find the
tools.
See e.g. https://travis-ci.org/KhronosGroup/SPIRV-LLVM-Translator/jobs/505139401#L1538
> lit: Fix DebugInfo test tools warnings

- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
This particularly manifested itself when running llvm-spirv with
-r -spirv-debug
> Fix nullptr dereference for -spirv-debug

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/Generic/inlined-locations.ll
When translating from SPIR-V to IR, DILocations that will be referenced by other DILocations via 
inlinedAt should be created as distinct.
> Create distinct DILocations for DebugInlinedAt instructions.

- lib/SPIRV/SPIRVReader.cpp
The previous instruction is not necessarily a SPIRVLoopMerge, but the
translator would always cast it to such and try to set loop metadata,
resulting in invalid memory accesses.
The issue was discovered using valgrind on test/selection_merge.spt .
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/6 (#6)
> Fix invalid SPIRVLoopMerge cast

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- test/DebugInfo/LocalAddressSpace.ll
Current mechanism for searching of global variables via name lookup is not
reliable. With this patch we look through all global variables untill we find
one which has attached !dbg metadata, which refers via
DIGlobalVariableExpression to DIGlobalVariable which is being translated.
> Fix debug info for __local qualified variables

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
builtins are generally not uniformly constant, so using the UniformConstant
storage class is missleading and might confuse the consumer of the spir-v
Sadly there is no perfect fit, but Input is what comes the closest
> Add the input storage class and use it for builtins instead of Uniform

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVUtil.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/NoSignedUnsignedWrap.ll
- test/transcoding/subgroup_avc_intel_generic.ll
- test/transcoding/subgroup_avc_intel_types.ll
- test/transcoding/subgroup_avc_intel_vme_image.ll
- test/transcoding/subgroup_avc_intel_wrappers.ll
This PR introduces basic infrastructure for emitting `OpExtension`s opcodes for SPIR-V extensions similar to existing infrastructure around `OpCapability`.
It also adds generation of corresponding `OpExtension` for `SPV_INTEL_device_side_avc_motion_estimation` and `SPV_KHR_no_integer_wrap_decoration`.
We already have some infrastructure for emitting `OpExtension`s, but looks like it is related to some clang generated metadata for OpenCL extensions and SPIR. I don't know is it still actual or not, but I re-used some part of it.
> Add infrastructure to emit OpExtension when it is required

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
spirv-val reported an error as an OpEntryPoint has to list all used input and output variables. Sorry for missing this.
With this patch all input and output variables get added to each OpEntryPointer declaration, but figuring out which entry point is used isn't exactly trivially solveable.
Add the SPIRV output storage class as well, so we don't forget to update the code if it gets added later.
Fixes: 2745e2a6ae71dba4f8948ec5cc7ee07e8f9a4a97
Fixes: #176 
We probably want to do a quick analysis to figure out which GlobalVariable is used from which entry point, but for that I didn't really came up with a acceptable way of doing that. Maybe we could do something with the LazyCallGraph pass here?
> Encode and decode Input and Output Variables used in entry points

- lib/SPIRV/SPIRVWriter.cpp
- test/llvm.memcpy.align.ll
Signed-off-by: Valery N Dmitriev <valery.n.dmitriev@intel.com>
> Handle llvm.memcpy with non-matching source vs destination alignment.

- lib/SPIRV/SPIRVWriter.cpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
This commit aligns the attributes' translation with the original specification
Extension specification can be found at:
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_fpga_memory_attributes.asciidoc
> Fix translation of some Intel FPGA memory attributes

- tools/llvm-spirv/llvm-spirv.cpp
I'm using the SPIRV-LLVM-Translator on Windows.  On Windows, "text" files replace a newline (character '\n') with two characters representing a carriage return and line feed ("\r\n").  Unfortunately, if the newline actually represents a SPIR-V ID, the replacement corrupts the SPIR-V file.
Fix is to use a "binary" file instead, which only writes the single byte '\n'.  With this change I am able to use the SPIRV-LLVM-Translator on Windows.
> Open SPIR-V output file as a binary file

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- test/DebugInfo/DebugFunction.cl
Update LLVM for dd6f70daf6e ("[DebugInfo] Delete TypedDINodeRef",
2019-05-07).
> Update LLVM to r360108

- .travis.yml
this was only required on trusty
should help with some CI jobs aborting due to network failures.
> travis: remove ubuntu-toolchain-r-test

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/FPGALoopAttr.ll
Following attributes/pragmas are supported:
1. ivdep
2. ivdep safelen (N)
3. ii(N)
4. max_concurrency_loop(N)
LLVM IR ->SPIRV translation (appropriatly the set order):
1. !"llvm.loop.ivdep.enable ->
4 LoopMerge {{[0-9]+}} {{[0-9]+}} 4
2. !"llvm.loop.ivdep.safelen", i32 N ->
5 LoopMerge {{[0-9]+}} {{[0-9]+}} 8 N
3. !"llvm.loop.ii.count", i32 N ->
6 LoopMerge {{[0-9]+}} {{[0-9]+}} 0x80000000 5889 N
4. !"llvm.loop.max_concurrency.count", i32 N ->
6 LoopMerge {{[0-9]+}} {{[0-9]+}} 0x80000000 5890 N
SPEC: https://github.com/KhronosGroup/SPIRV-Registry/pull/28
> Initial support of Intel FPGA loop attributes/pragmas

- include/LLVMSPIRVLib.h
- lib/SPIRV/SPIRVReader.cpp
The OpenCL runtime API requires that IL be loaded and compiled with
separate function calls:
1. clCreateProgramWithIL(), which must check that the IL is well-formed
and return CL_INVALID_VALUE if it is not.
2. clBuildProgram() or clCompileProgram(), which allow build options to
be specified.
To facilitate the above, this change adds two new API functions:
1. readSpirvModule(), which reads an istream to produce a SPIRVModule.
2. convertSpirvToLLVM(), which converts a SPIRVModule to LLVM IR.
The existing readSpirv() function is refactored in terms of these calls,
but is kept in the API for the convenience of tools such as llvm-spirv.
Fixes issue #20.
> Add separate functions for reading and translating SPIR-V

- .travis.yml
Looks like package dependencies are broken.
Adding libclang-9-dev manually to fix travis build.
> travis: Add libclang-9-dev package

- lib/SPIRV/SPIRVToOCL20.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl12.ll
- test/transcoding/AtomicCompareExchange_cl20.ll
Ensure that the `expected` argument of atomic_compare_exchange_* lives
in the generic address space in accordance with the OpenCL 2.0
specificationSection 6.13.11, "The atomic_compare_exchange
functions".
> Set atomic_compare_exchange argument address space to generic

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/TransOCLMD.cpp
- Centralise Triple validation
- Set the addressing model based on architecture bitness rather than
the specific architecture.
Signed-off-by: Kevin Petit <kevin.petit@arm.com>
> Cleanup Triple validation and use

- lib/SPIRV/SPIRVReader.cpp
Set the address space through `getOCLOpaqueTypeAddrSpace`, which is
build-time configurable through the `SPIRV_CLK_EVENT_T_ADDR_SPACE`
preprocessor macro.
There is no easy way to test this functionality using the llvm-lit test suite currently.
> Replace hardcoded address space for clk_event_t

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/annotate_attribute.ll
This patch implements translation of LLVM IR var/ptr.annotation intrinsic to SPIR-V UserSemantic decoration.
Example of code with annotate attribute:
`[[clang::annotate("{FOO}")]] int a;`
> Translate annotate attribute

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/OpLoopMergeDontUnrollHint1.spt
- test/OpLoopMergePartialUnroll.spt
- test/transcoding/LoopUnroll.ll
Possible use cases:
1. unroll [N]
going to be translated into:
SPIR-V: 5 LoopMerge [X] [Y] 256 [N]
LLVM-IR: !{!"llvm.loop.unroll.count", i32 [N]}
2. unroll 1
in this case loop unrolling should be disabled,
going to be translated into:
LLVM-IR:  !{!"llvm.loop.unroll.disable"}
unroll default (without hint) behaviour was changed as well, see:
LLVM-IR: !{!"llvm.loop.unroll.full"} -> !{!"llvm.loop.unroll.enable"}
> Support partial unrolling

- lib/SPIRV/libSPIRV/SPIRVBasicBlock.cpp
- test/DebugInfo/DebugControlFlow.cl
According to the SPIR-V specification, branch merge instructions
must immediately precede branch instructions. The patch ensures
that ExtInst predecessors of branch instructions:
- are inserted before the merge instructions;
- and thus do not break SPIRVToLLVM translation of the latter.
> Fix debug information interfering with loop controls translation

- include/LLVMSPIRVLib.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/preprocess-metadata.ll
Main purpose of this PR is to allow SPIRV-LLVM-Translator to handle some OpenCL-specific metadata (like `reqd_work_group_size`, `intel_reqd_sub_group_size`) even if LLVM IR wasn't generated from OpenCL C (`opencl.ocl.version` metadata is missed).
Summary of changes:
* renamed `TransOCLMD` pass into `PreprocessMetadata`
* update the pass to handle some metadata unconditionally 
The first user of this PR can be found in intel/llvm#164: I've re-used existing OpenCL attribute `intel_reqd_sub_group_size` in SYCL.
I'm not particularly sure about the last commit in this PR: _Remove generating of spirv.EntryPoint metadata_ - I've removed generation of `spriv.EntryPoint` metadata since there are no uses of it. Probably it is a wrong decision. **Please speak up if you think that it is better to …
> Update LLVM IR metadata preprocessing

- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVType.cpp
Fix occurrences of the following warning reported by gcc 8.3:
warning: type qualifiers ignored on cast result type
[-Wignored-qualifiers]
Reported-by: Pedro Olsen Ferreira
> Fix -Wignored-qualifiers warnings; NFC

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/X86/live-debug-variables.ll
- test/composite_construct_struct.spt
- test/opundef.spt
- test/transcoding/enqueue_kernel.cl
- test/transcoding/kernel_query.ll
StructTypes without a name will be numbered like %0, %1, ..., which
can be confusing for humans reading the IR who might interpret these
as Values.
If the SPIRVType has no name, fill in a dummy name "structtype", which
LLVM will unique into "structtype.0", "structtype.1", ..., if
necessary.
This fixes the current travis failure
```error: use of undefined type named 'type 0x8f0150'
define spir_func void @foo(%0* byval(%"type 0x8f0150") %f) #0 !dbg !8 {
^
error: -: The file was not recognized as a valid object file
FileCheck error: '-' is empty.
FileCheck command line:  /usr/lib/llvm-9/bin/FileCheck /home/travis/build/KhronosGroup/SPIRV-LLVM-Translator/test/DebugInfo/UnknownBaseType.ll
```
Update a test for LLVM commit 891c55ccc57 ("[DebugInfo] Incorrect
debug info record generated for loop …
> Updates for LLVM changes to fix travis build

- lib/SPIRV/Mangler/Mangler.cpp
- test/transcoding/OpImageSampleExplicitLod_arg.ll
- test/transcoding/enqueue_marker.cl
enqueue_marker was incorrectly mangled because the `ocl_clkevent`
type was not considered for substitution.
This patch enables substitution for all primitive types (such as
queues and events) except simple builtin types (such as char or int).
This brings the mangling of enqueue_marker into alignment with clang.
This also aligns mangling for read_image-with-gradient variants with
clang, as image types are now also considered for substitution.
> Cherry-pick ed99fc0f92 from master

- README.md
LLVM_EXTERNAL_LIT must be set if LLVM is installed from apt.llvm.org.
Otherwise, `make test' complains that it cannot find llvm-lit.
Clang executable must also be present in order to run the tests.
> [NFC] Fix README build and test instructions

- lib/SPIRV/SPIRVReader.cpp
- test/builtin_vars.ll
Before this patch, SPIR-V Translator assumed that a builtin global
variable can only be used by a load instruction (since all globals are
pointers). This patch adds support for addrspacecast instruction that
is followed by a load instruction.
> Support addrspacecast on SPIR-V built-in variables

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/OpControlBarrier_cl12.ll
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
Cherry-pick the following commits from master:
- d3f201822: Set noduplicate attribute for barriers
- 97df8a26a: Fix mangling for work_group_barrier and sub_group_barrier functions
> Cherry-pick two commits from master

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
https://github.com/KhronosGroup/SPIRV-Registry/pull/34
> Rename Maxconcurrency decoration to MaxPrivateCopies to align with spec

- test/DebugInfo/Generic/linear-dbg-value.ll
- test/DebugInfo/X86/dbg-declare-arg.ll
- test/DebugInfo/X86/reference-argument.ll
Update for the following commits:
- d0b09e3dd18 ("[DebugInfo] Terminate all location-lists at end of
block", 2019-06-10)
- c030038e736 ("[FastISel] Skip creating unnecessary vregs for
arguments", 2019-06-10)
- 5b56cc85b0f ("Rename ExpandISelPseudo->FinalizeISel, delay register
reservation", 2019-06-19)
> Update LLVM to r363800

- lib/SPIRV/SPIRVWriter.cpp
- test/undef_initializer.cpp
Now if internal global constant has undef initializer SPIRV translator
will drop this initializer. It produces errors in translation back to
LLVM IR because internal global variables must have initializers.
Undef initializer for LLVM structure be can translated to OpConstantComposite
with OpUndef constituents.
> Fix translation of undef initializers of LLVM structures

- test/transcoding/OpDot.ll
- test/transcoding/atomic_flag.cl
- test/transcoding/atomic_load_store.ll
- test/transcoding/bit_ops.cl
- test/transcoding/clk_event_t.cl
- test/transcoding/relationals.ll
Add or extend tests to improve testing coverage of:
- the atomic_flag type,
- bitwise operators,
- clk_event_t builtins,
- OpAtomicLoad,
- OpDot
> Improve test coverage

- lib/SPIRV/OCLUtil.cpp
- test/transcoding/cl_intel_sub_groups.ll
Mangle uint parameters according to 
[cl_intel_subgroups](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups.html) spec.
> Fix mangling for cl_intel_subgroups functions when reading SPIRV

- lib/SPIRV/Mangler/ManglingUtils.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
Fix -Wimplicit-fallthrough warning
* `unannotated fall-through between switch labels [-Wimplicit-fallthrough]`
Fix -Wcovered-switch-default warning
* `default label in switch which covers all enumeration values [-Wcovered-switch-default]`
> Fix build warnings

- lib/SPIRV/SPIRVReader.cpp
- test/IntelFPGAMemoryAttributes.ll
After consumption back to LLVM IR, if a variable that had Intel FPGA
decoration attached was a type of struct - the needed
@llvm.var.annotation wasn't generated.
> Fix Intel FPGA decorations for structure variables

- .travis.yml
The community is now advising that all workflows and CI systems
migrate to the GitHub monorepo, see [1] and [2].
[1] http://lists.llvm.org/pipermail/llvm-dev/2019-July/133840.html
[2] http://llvm.org/GitHubMigrationStatus.html
> travis: Switch to LLVM GitHub monorepo

- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVToOCL12.cpp
- test/barrier_explicit_arguments.spt
- test/mem_fence_explicit_arguments.spt
If a flag passed to ControlBarrier or MemoryBarrier is being
initialized in runtime - don't lose it's initialization.
> Initialize mem fence passing to barrier in runtime if necessary

- .travis.yml
Currently every commit on a release branch can overwrite published release
on github. New approach in this patch presumes that releases will be done
manually via web interface on github. This will trigger another build in
travis, which in turn will deploy build aritfacts on github.
> Changing deploy mechanism

- test/OpGroupIAdd.spt
- test/transcoding/DivRem.cl
- test/transcoding/RelationalOperators.cl
- test/transcoding/RelationalOperatorsFOrd.ll
- test/transcoding/RelationalOperatorsFUnord.ll
- test/transcoding/group_ops.cl
This also includes an XFAILed SPIR-V test for `OpGroupIAdd`, which has incorrect name mangling as it maps to `_Z21work_group_reduce_addi`, which is liable to use "no signed wrap" addition, rather than
`_Z21work_group_reduce_addj`, which should be tolerant of overflow.
> Add new transcoding tests

- lib/SPIRV/SPIRVWriter.cpp
- test/negative/unsupported-triple.ll
Check that the target triple is supported before LLVM to SPIR-V
translation, rather than during translation.  This allows us to
gracefully report InvalidTargetTriple instead of failing the target
triple assertion in PreprocessMetadata.cpp.
> Move target triple check before translation

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/debug-label-skip.ll
Translation from LLVM IR to SPIR-V is crashed if llvm.dbg.label intrinsic
is present in code.
Skip llvm.dbg.label translation because there is no support for label debug
info in SPIR-V.
> Skip llvm.dbg.label intrinsic translation

- .travis.yml
Updated travis config should support 2 use cases:
1. Ongoing development - after commit to the master branch build artifacts
should be published as a pre-release. For this purpose we maintain the
"dev-build" tag which is always pointing to the tip of master branch.
2. Creating a release - when we are ready to make a release from a release
branch we push a tag via command line or github web interface(preferred).
This triggers a travis build and deploy of binaries.
> Update deploy mechanism

- lib/SPIRV/SPIRVReader.cpp
- test/sycl_array_zero_init.ll
Don't use optimization of OpCopyMemorySized operation to memset intrinsic
if element size of zero-initialized array differs from 1 byte.
Otherwise, OpCopyMemorySized conversion to memset instruction will fail.
> Fix OpCopyMemorySized conversion to memset

- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVToOCL12.cpp
- test/barrier_explicit_arguments.spt
- test/mem_fence_explicit_arguments.spt
It fixes a wrong switch generation with translation of
ControlBarrier and MemoryBarrier instructions back to
LLVM IR.
> Add default mask for getOrCreateSwitchFunc

- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- test/spirv-ocl-builtins-version.spt
- test/transcoding/OpControlBarrier_cl12.ll
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
The `noduplicate` attribute is unnecessarily restrictive.  Align with
clang by setting the `convergent` attribute instead of `noduplicate`.
Followup from https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/109
> Set convergent attribute for barriers

- test/transcoding/enqueue_kernel.cl
- test/transcoding/kernel_arg_name.ll
- test/transcoding/kernel_query.ll
LLVM commit r367755 ("IR: print value numbers for unnamed function
arguments", 2019-08-03) changes the way unnamed arguments are printed.
Update FileCheck patterns in tests accordingly, but such that they
match both before and after the aforementioned LLVM commit, to bridge
the current gap between LLVM master and the prebuilt LLVM binaries.
> Update tests for LLVM unnamed argument printing

- lib/SPIRV/SPIRVToOCL.cpp
- test/PipeBlocking.ll
With LLVM IR consumption second argument of pipe built-in should be
void pointer. This patch fixes a bug, when Intel blocking pipes
built-ins were having second argument with the same type as data
stored in pipe. This bug could lead to a situation, when two pipe
blocking instruction were translated to LLVM IR to two functions with
different arguments types, but sharing the same name which is illegal.
> Fix Intel blocking pipe built-ins type signature

- README.md
- lib/SPIRV/SPIRVReader.cpp
- test/CMakeLists.txt
- test/OpFNegate.spvasm
- test/OpFRem.spvasm
- test/OpLogicalAnd.spvasm
- test/OpLogicalEqual.spvasm
- test/OpLogicalNot.spvasm
- test/OpLogicalNotEqual.spvasm
- test/OpLogicalOr.spvasm
- test/OpNop.spvasm
- test/OpNot.spvasm
- test/OpSNegate.spvasm
- test/lit.cfg.py
- test/lit.site.cfg.py.in
This change adds SPIR-V assembly tests for OpFNegate, OpSNegate, OpFRem, OpNot, OpLogicalAnd, OpLogicalOr, OpLogicalEqual, OpLogicalNotEqual, OpLogicalNot and OpNop, and fixes translation of the OpLogicalNot instruction to LLVM IR.
As the OpNop instruction cannot currently be decoded, the test for this is an XFAIL test.
This adds a dependency on SPIR-V Tools, which provides the `spirv-as` program needed to assemble the tests. These tests are added in the SPIR-V assembly format with the intent that other tests will be converted away from the internal SPIR-V text format in future, as per issue #211.
> Add SPIR-V assembly tests and fix translation of OpLogicalNot

- lib/SPIRV/SPIRVToOCL12.cpp
- test/float_atomic_spv_to_ocl12.spt
Some SPIR-V atomic functions are converted to OpenCL 1.2 builtins with
integral return value or arguments. For SPIR-V atomic functions with
float arguments it leads to generation of builtins with unsupported
signature.
Correct conversion of atomic functions arguments types and return type
from SPIR-V to IR with OpenCL 1.2 builtins.
> Fix atomic functions conversion to OpenCL 1.2

- lib/SPIRV/SPIRVWriter.cpp
Update for LLVM commit r369130 ("[ADT] Remove llvm::make_unique
utility.", 2019-08-16).
> Use std::make_unique after LLVM change r369130

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVUtil.h
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
This patch introduces fix for the problem related to translation of SPIR-V decoration with two (or more) Literal Strings to LLVM IR. The processing of getting Literal Strings from the related decoration was limited to the first Literal String (first '\0' symbol).
In particular, the merge attribute has two Literal String according to the specification.
> Fix invalid .spv->.bc translation of Intel FPGA merge attribute

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/enqueue_kernel.cl
__enqueue_kernel_basic and __enqueue_kernel_varargs bultins were not produced by SPIRVReader, instead of them __enqueue_kernel_basic_events and __enqueue_kernel_events_varargs with null event arguments were produced. This approach wasn't clang-consistent.
> Fix enqueue_kernel builtins translation - SPIRV to LLVM

- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/cl_intel_sub_groups.ll
OpenCL file compiled by Khronos OpenCL Clang compiler+SPIRV-LLVM using cl_intel_subgroups+cl_intel_subgroups_short omits needed OpExtension SPV_INTEL_subgroups
Signed-off-by: Ilya Mashkov ilya.mashkov@intel.com
> Add OpExtension SPV_INTEL_subgroups

- lib/SPIRV/libSPIRV/SPIRVBasicBlock.cpp
- test/DebugInfo/DebugUnstructuredControlFlow.cl
In case when debug information presents in the module, the
metadata was missing with translation back of LoopControlINTEL
instruction due to incorrect instruction ID.
> Retain llvm.loop metadata for LoopControlINTEL instruction

- lib/SPIRV/SPIRVWriter.cpp
- test/IntelFPGAMemoryAttributesForStruct.ll
Strip all bitcast and addrspace casts from the pointer argument:
llvm annotation intrinsic only takes i8*, so the original pointer
probably had to loose its addrspace and its original type.
> Fix IntelFPGA memory attrs on struct that has c'tor

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/annotation_dbg_info_drop.ll
Currently there is no analogue of *.annotation intrinsic in SPIR-V.
During IR translation this call is skipped or stored as a decoration.
Position of this intrinsic in a basic block of IR after reverse
translation may change or even lost. However, debug scope of the call
may be translated into SPIR-V in inappropriate place and result in
corruption of debug metadata for other instructions in that basic
block. Even if debug info of the call doesn't corrupt debug info of
other instructions in that basic block it isn't restored for the call
during reverse translation.
Skip debug scope info of *.annotation intrinsic call as it is useless
for now.
> [SYCL][FPGA] Skip *.annotation call debug info

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/IntelFPGAMemoryAttributesForStaticVar.ll
Attributes applied to static variables are generated with
@llvm.global.annotations, not with intrinsics as for "usual" variables.
This patch introduces converting of @llvm.global.annotations to correct SPIR-V
decorations and back.
> Translate Intel FPGA attributes for static variables

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugControlFlow.cl
- test/DebugInfo/DebugUnstructuredControlFlow.cl
This fixes 'OpLine's being inserted between branch merge
instructions and branch instructions. Although this has no
functional effect, SPIR-V specification clearly states that
Line instructions must precede branch merge instructions
> Fix Line debug info contradicting control flow semantics

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVUtil.cpp
- test/OpConvertPtrToU_narrowing.spvasm
- test/OpConvertPtrToU_widening.spvasm
- test/OpConvertUToPtr_narrowing.spvasm
- test/OpConvertUToPtr_widening.spvasm
- test/transcoding/ConvertPtr.cl
- test/transcoding/GenericCastToPtr.cl
`OpGenericCastToPtrExplicit` should be translated to `__to_global()`, `__to_local()` or `__to_private()` as appropriate, without name mangling, as this is what Clang generates.
Fix this to remove name mangling for these builtins, and add transcoding tests for both `OpGenericCastToPtrExplicit` and `OpGenericCastToPtr`.
Also add SPIR-V assembly tests for widening/narrowing `OpConvertUToPtr` and `OpConvertPtrToU` conversions, and add a transcoding test for same-width `OpConvertUToPtr` conversions.
> Fix translation of OpGenericCastToPtrExplicit and add pointer cast tests

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/ComparePointers.cl
It's converting pointers to unsigned before compare
Fix #35
> Compare pointers according to spec

- CMakeLists.txt
- README.md
Make it possible to disable the llvm-spirv test suite while still
allowing LLVM_INCLUDE_TESTS to be set to true.
> cmake: Add LLVM_SPIRV_INCLUDE_TESTS option

- CMakeLists.txt
- README.md
Update of the version in CMakeLists.txt was requested by @pierremoreau at https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/334#issuecomment-534067728
> Last minute version updates for v9.0.0-1 release

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/DebugInfo/DebugControlFlow.cl
- test/InfiniteLoopMetadataPlacement.ll
- test/OpLoopMergeDontUnrollHint1.spt
- test/OpLoopMergeNone.spt
- test/OpLoopMergePartialUnroll.spt
- test/OpLoopMergeUnroll.spt
- test/transcoding/FPGALoopAttr.ll
In accordance with the SPIR-V spec loop metadata should be attached to the header block of the loop (via OpLoopMerge or OpLoopControlINTEL) whilst in LLVM IR it should be attached to latch block of the loop (via llvm.loop metadata).
Fix attachment place of loop metadata in reverse translation.
> [SYCL][FPGA] Fix loop metadata layout in reverse translation

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
Having the SPIRVToOCL12 and SPIRVToOCL20 passes share the base class
Pass ID could cause the LLVM PassRegistry to believe it would register
the same pass twice.
Move the ID member down the class hierarchy such that each pass has
its own ID.
> Move Pass ID out of SPIRVToOCL base class

- lib/SPIRV/SPIRVToOCL.h
The ModulePass constructor takes a reference so we should forward the
reference given to the SPIRVToOCL constructor.
Reported-by: Stuart Brady
> Fix SPIRVToOCL pass ID argument to be a reference

- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
commit ab11b9188d75a9cc24faa1e76592e4a1903a6e20
Author: Guillaume Chatelet <gchatelet@google.com>
Date:   Mon Sep 30 13:34:44 2019 +0000
[Alignment][NFC] Remove AllocaInst::setAlignment(unsigned)
Summary:
This is patch is part of a series to introduce an Alignment type.
See this thread for context: http://lists.llvm.org/pipermail/llvm-dev/2019-July/133851.html
See this patch for the introduction of the type: https://reviews.llvm.org/D64790
Reviewers: courbet
Subscribers: jholewinski, arsenm, jvesely, nhaehnle, eraman, hiraditya, cfe-commits, llvm-commits
Tags: #clang, #llvm
Differential Revision: https://reviews.llvm.org/D68141
llvm-svn: 373207
> Fix build after LLVM API update

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- tools/llvm-spirv/llvm-spirv.cpp
Cherry-pick ee1fda2 from master to llvm_release_80
> Extend TranslatorOpts to handle SPIRVGenKernelArgNameMD [llvm_release_80]

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- tools/llvm-spirv/llvm-spirv.cpp
Cherry-pick ee1fda2 form master to llvm_release_90
> Extend TranslatorOpts to handle SPIRVGenKernelArgNameMD [llvm_release_90]

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/IntelFPGAMemoryAttributesForStaticVar.ll
Attributes applied to static variables are generated with
@llvm.global.annotations, not with intrinsics as for "usual" variables.
This patch introduces converting of @llvm.global.annotations to correct SPIR-V
decorations and back.
> [Backport] Translate Intel FPGA attributes for static variables

- include/LLVMSPIRVLib.h
LLVM change that caused build failure:
> Prune Pass.h include from DataLayout.h. NFCI
>
> Summary:
> Reduce include dependencies by no longer including Pass.h from
> DataLayout.h. That include seemed irrelevant to DataLayout, as
> well as being irrelevant to several users of DataLayout.
>
> Reviewers: rnk
>
> Reviewed By: rnk
>
> Subscribers: mehdi_amini, hiraditya, cfe-commits, llvm-commits
>
> Tags: #clang, #llvm
>
> Differential Revision: https://reviews.llvm.org/D69261
>
> llvm-svn: 375436
Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>
> Fix build after r375436

- lib/SPIRV/OCLUtil.cpp
- test/mangling_upsample.spt
it makes unsigned second argument for s_upsample
Signed-off-by: Ilya Mashkov ilya.mashkov@intel.com
> Fix mangling for s_upsample

- test/check_empty_file.ll
- tools/llvm-spirv/llvm-spirv.cpp
It's checking file for emptiness before translating
> Fix translator crash when provided empty file

- lib/SPIRV/SPIRVWriter.cpp
- test/IntelFPGAMemoryAttributesForStaticVar.ll
This patch fixes the problem that if LLVM IR contains llvm.global.annotation,
translator drops all the rest code except this variable.
> Fix translation of llvm.global.annotation

- lib/SPIRV/libSPIRV/SPIRVStream.h
Signed-off-by: Vyacheslav N Klochkov <vyacheslav.n.klochkov@intel.com>
> Add #include <cctype> required for std::isspace() used in SPIRVStream.h

- README.md
The subproject mirrors are no longer being maintained, so update the
README to mention the official LLVM GitHub monorepo.
> README.md: Update for LLVM GitHub monorepo switch

- lib/SPIRV/SPIRVReader.cpp
- test/InfiniteLoopMetadataPlacement.ll
A loop's attribute information may be lost during reverse translation
from SPIR-V in case if a function, which contains the loop, also have
a call to another function that is defined after the function with
the loop.
Fix this loss of loop's metadata.
> Fix loss of loop metadata during reverse translation

- lib/SPIRV/libSPIRV/SPIRV.debug.h
According to SPIR-V Registry DebugTypeTemplateTemplateParameter should have 5 operands, not 4. In function LLVMToSPIRVDbgTran::transDbgTemplateTemplateParameter it also takes 5 operands.
Signed-off-by: Ilya Mashkov ilya.mashkov@intel.com
> Fix range of TemplateTemplateParameter

- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- test/DebugInfo/X86/dw_op_minus_direct.ll
- test/DebugInfo/X86/live-debug-variables.ll
The following commits broke the build:
https://github.com/llvm/llvm-project/commit/05da2fe52162c80dfa18aedf70cf73cb11201811
https://github.com/llvm/llvm-project/commit/631be5c0d41161057d02fe08a7aeb4fbde1a91d6
https://github.com/llvm/llvm-project/commit/0908093977b2b80d00baa12f0b2f1424dde096fb
> Fix the build after changes in LLVM

- lib/SPIRV/libSPIRV/OpenCL.std.h
- lib/SPIRV/libSPIRV/SPIRVExtInst.h
These never made it into the 1.0 specification as the specification
provides dedicated instructions instead.
This is a first step towards synchronizing the translator's SPIR-V
header files to the official Khronos SPIR-V header files.
> Drop deprecated OpenCL library functions

- lib/SPIRV/SPIRVUtil.cpp
Fix unused variable warning after bc9fa54 ("Enable loop simplify pass
for all llvm.loop attributes", 2019-11-05).
> Fix unused variable warning

- test/DebugInfo/BuiltinCallLocation.cl
- test/InvalidAtomicBuiltins.cl
- test/SampledImage.cl
- test/transcoding/DivRem.cl
- test/transcoding/GenericCastToPtr.cl
- test/transcoding/RelationalOperators.cl
- test/transcoding/SatConvert.cl
- test/transcoding/TransFNeg.cl
- test/transcoding/bit_ops.cl
- test/transcoding/block_w_struct_return.cl
- test/vec_type_hint.cl
Clang's `-fdeclare-opencl-builtins` option now supports enough
builtins that these tests can use the faster TableGen based builtin
function declaration mechanism.  We still need the
`-finclude-default-header` option for OpenCL specific types and
constants, but when combined with `-fdeclare-opencl-builtins`, Clang
will not parse the full header with OpenCL builtin declarations.
This reduces the running time of the llvm-spirv test suite.
> Switch some .cl tests to use -fdeclare-opencl-builtins

- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVReader.cpp
LLVM commit 531c1161b97 ("Resubmit "[Alignment][NFC] Deprecate
CreateMemCpy/CreateMemMove"", 2019-12-16) deprecated the variants that
do not take `MaybeAlign` arguments.
> Update for LLVM API changes to CreateMemCpy

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/RecursiveDebugInfo.ll
When translating debug info for composite type from IR to SPIR-V
its template parameters are processed after deletion of temporary
forward declaration of composite type's metadata node. However,
pointer on this node is still present in metadata nodes cache map.
If some of template parameters or their dependences has reference
on this composite type's node then it leads to accessing to freed
memory.
> [SYCL] Fix incorrect debug info translation of recursive template type

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/InfiniteLoopMetadataPlacement.ll
- test/transcoding/FPGAIVDepLoopAttr.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
The new LLVM IR representation of [[intelfpga::ivdep]] takes into account
the array variables being accessed from within the loop. A brief outline is
that each array variable's GetElementPtr instruction is marked with a
so-called "index group metadata". These index groups are referenced by
IVDep-specific "llvm.loop.parallel_access_indices", which is (finally!)
attached to "llvm.loop" metadata.
The SPIR-V specification for this version of the attribute can be found at:
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_fpga_loop_controls.asciidoc
Some outline of refactoring that took place:
1) The getLoopControl() utility was moved from SPIRVUtil into SPIRVWriter,
the helper being Writer-specific anyway.
2) Several NFCs regarding getMDOperandAs...() …
> Translate the new representation of Intel FPGA IVDep loop attribute

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/read_image.cl
There are several overloads of read_image function defined by OpenCL C
spec, but all of them use the same SPIR-V instruction, so, we need to
add one more optional postfix to differentiate instructions with the
same argument types, but different return types.
Example:
- int4 read_imagei(image2d_t, sampler_t, int2)
- uint4 read_imageio(image2d_t, sampler_t, int2)
Both functions above are represented by the same SPIR-V instruction and
we need to distinguish them in SPIR-V friendly LLVM IR.
> Fix translation of read_image* built-ins to SPIR-V

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/IntelFPGAMemoryAttributes.ll
- test/IntelFPGAMemoryAttributesForStruct.ll
This also needs a change in Clang.
The decoration MaxPrivateCopies did not change. No SPIRV spec changes
required.
Signed-off-by: Mohammad Fawaz mohammad.fawaz@intel.com
> Changing max_private_copies --> private_copies (IR only)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/FPGAIVDepLoopAttr.ll
- test/transcoding/FPGALoopAttr.ll
- test/transcoding/FPGALoopMergeInst.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
The specification itself can be found at
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_fpga_loop_controls.asciidoc
As per revision B -> revision C transition in the spec, the patch
removes the "extended loop controls" field, storing the FPGA loop
controls as bit fields in the "common" LoopControl mask.
> Align FPGA Loop Controls translation with the spec (rev C)

- CMakeLists.txt
Fixes: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/131
> Make LLVM_SPIRV_VERSION depend on the base LLVM version

- CMakeLists.txt
See the corresponding issue: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/131.
> Update LLVM_SPIRV_VERSION in CMakeLists.txt to 7.1.0.1

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
This is to fix the build after
https://github.com/llvm/llvm-project/commit/ecd2aaee0645e832566850044c4ee5fc5ff76a02
"[DebugInfo] Merge DebugInfoFinder::{processDeclare,processValue} into
processVariable"
> Fix the build after changes in the LLVM project

- include/LLVMSPIRVLib.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/half_extension.ll
- test/transcoding/spec_const.ll
- tools/llvm-spirv/llvm-spirv.cpp
Translate SPIRV-friendly LLVM IR builtins represnting specialization constants `__spirv_SpecConstant` to corresponding SPIR-V instructions.
This approach works only for scalar constants, so support for `OpSpecConstantComposite` and `OpSpecConstantOp` is not implemented in this patch.
This PR also includes a patch to improve error handling for `llvm::getSpecConstInfo` API: Change return value from void to bool. Return `false` to indicate a failure. Return `true` on success.
> Generate specialization constant instructions

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/read_image.cl
There are several overloads of read_image function defined by OpenCL C
spec, but all of them use the same SPIR-V instruction, so, we need to
add one more optional postfix to differentiate instructions with the
same argument types, but different return types.
Example:
- int4 read_imagei(image2d_t, sampler_t, int2)
- float4 read_imagef(image2d_t, sampler_t, int2)
Both functions above are represented by the same SPIR-V instruction and
we need to distinguish them in SPIR-V friendly LLVM IR.
Signed-off-by: Alexey Sachkov <alexey.sachkov@intel.com>
> Backport fix translation of read_image* built-ins to SPIR-V to 9.0

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/read_image.cl
There are several overloads of read_image function defined by OpenCL C
spec, but all of them use the same SPIR-V instruction, so, we need to
add one more optional postfix to differentiate instructions with the
same argument types, but different return types.
Example:
- int4 read_imagei(image2d_t, sampler_t, int2)
- float4 read_imagef(image2d_t, sampler_t, int2)
Both functions above are represented by the same SPIR-V instruction and
we need to distinguish them in SPIR-V friendly LLVM IR.
> Backport fix translation of read_image* built-ins to SPIR-V to 8.0 release

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- test/IntelFPGAFunctionAttributes.ll
This patch implements the rest of SPV_INTEL_kernel_attributes extension.
NoGlobalOffsetINTEL execution mode indicates that the global offset is
always (0, 0, 0). Only valid with the Kernel Execution Model.
Specification can be found there: https://github.com/KhronosGroup/SPIRV-Registry/pull/55
> Enable NoGlobalOffsetINTEL execution mode translation

- .travis.yml
- README.md
It seems like there are not all llvm packages from bionic link. I suggest to change link to xenial for a while.
> Fix travis on llvm_release_100 branch

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/Generic/version.ll
This commit mirrors llvm/llvm-project@e956952edec140d2475aa7c8cbe20fbdd3320634
"DebugInfo: Flag Dwarf Version metadata for merging during LTO
When the Dwarf Version metadata was initially added (r184276) there was
no support for Module::Max - though the comment suggested that was the
desired behavior. The original behavior was Module::Warn which would
warn and then pick whichever version came first - which is pretty
arbitrary/luck-based if the consumer has some need for one version or
the other.
Now that the functionality's been added (r303590) this change updates
the implementation to match the desired goal.
The general logic here is - if you compile /some/ of your program with a
more recent DWARF version, you must have a consumer that can handle it,
so might as well use it for …
> [DebugInfo] Set ModFlagBehavior=Max for the "Dwarf Version" metadata

- test/DebugInfo/X86/dbg-value-range.ll
Update for 9f6ff07f8a3 ("[DebugInfo] Enable the debug entry values
feature by default", 2020-02-10).
> Update DebugInfo test after LLVM change 9f6ff07f8a

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
These were introduced by commit 33d4946 ("Enable NoGlobalOffsetINTEL
execution mode translation", 2020-01-16).
> Fix -Wunused-variable warnings

- lib/SPIRV/OCLUtil.cpp
- test/transcoding/atomics_int64.spt
Commit 10dee68 ("Fix translation of 64-bit atomics to OpenCL 1.2",
2019-08-15) changes the "atomic_" prefix to "atom_" for 64-bit types,
but this caused the "atom_" builtins to no longer have the volatile
qualifier to their pointer argument.
Update the atomics_int64.spt test to check for the fully mangled
names; these should include the volatile qualifier.
> Add volatile qualifier for atom_ builtins

- CMakeLists.txt
See the corresponding issue: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/131.
> Update LLVM_SPIRV_VERSION in CMakeLists.txt to 10.0.0.1

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/llvm.memset.ll
Relax a limitation of the SPIR-V writer.  The memset intrinsic is mapped
to `OpCopyMemorySized`, causing it to be converted to memcpy when
converting back from SPIR-V to LLVM.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/357
> Handle non-zero values for llvm.memset

- lib/SPIRV/OCLUtil.h
Update for 465dca79b31 ("Avoid SmallString.h include in MD5.h, NFC",
2020-02-26).
> Add SmallString include after LLVM change 465dca79b31

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
Add a default argument after LLVM commit 7a42babeb83 ("Reland
"[DebugInfo][clang][DWARF5]: Added support for debuginfo generation
for defaulted parameters in C++ templates."", 2020-03-02).
> Fix DebugInfo creation after LLVM change 7a42babeb83

- .travis.yml
macOS builds seem to have been broken since 3027e3a ("Update version
of LLVM from 10 to 11", 2020-01-28) due to apt commands being moved
into the `before_install` step.  Restore macOS testing by only running
apt commands for Linux builds.
> travis: Restore macOS builds

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- test/transcoding/spec_const.ll
Per the SPIR-V spec the SpecId decoration has 2 enabling capabilities:
Shader, Kernel. Also in section 2.1 the spec says:
"When an instruction, enumerant, or other feature specifies multiple
enabling capabilities, only one such capability needs to be declared to
use the feature."
With this commit we choose to emit Kernel capability over Shader.
> Change capability for SpecId decoration

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/FPGAIVDepLoopAttr.ll
- test/transcoding/FPGALoopAttr.ll
- test/transcoding/FPGALoopMergeInst.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
Added the appropriate checks if the extension is allowed.
> Allow Intel Loop Controls only with SPV_INTEL_fpga_loop_controls

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
The build was broken by llvm/llvm-project@118abf2
"[SVE] Update API ConstantVector::getSplat() to use ElementCount."
> Fix build after changes in the llvm project

- tools/llvm-spirv/CMakeLists.txt
Building in-tree with LLVM 11.0 master with the LLVM_LINK_LLVM_DYLIB cmake flag fails to link with the LLVMSPIRVLib library.
Add an explicit dependency to force the correct build order and linking.
Signed-off-by: Andrea Bocci <andrea.bocci@cern.ch>
> Fix building in-tree with cmake -DLLVM_LINK_LLVM_DYLIB=ON

- test/DebugInfo/COFF/no-cus.ll
One debug info test failed because now llvm-objdump do not understand --section-headers option
> Fix of test, failed due to upstream llvm-objdump option changes

- lib/SPIRV/SPIRVWriter.cpp
CompositeType class was removed from llvm-project.
> Removing usage of CompositeType to fix build

- test/DebugInfo/X86/live-debug-variables.ll
Update for 41206b61e30 ("[DebugInfo] Re-instate LiveDebugVariables
scope trimming", 2020-02-04).
> [Backport] Update DebugInfo test after LLVM change 41206b61e30

- lib/SPIRV/SPIRVWriter.cpp
- test/AllowIntrinsics.ll
Here is implementation of command-line option which will allow
to represent unknown llvm intrinsics as external function call in SPIR-V
> Implement -spirv-allow-unknown-intrinsics option

- include/LLVMSPIRVOpts.h
The GenKernelArgNameMD field would be left uninitialized when calling
the default constructor.
> Initialize a TranslatorOpts field

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/FPGALoopAttr.ll
- test/transcoding/FPGALoopMergeInst.ll
Specification can be found here:
https://github.com/KhronosGroup/SPIRV-Registry/pull/62
As per revision C -> revision E transition in the spec, patch introduces
translation of the following loop controls:
* PipelineDisableINTEL
* LoopCoalesceINTEL
* MaxInterleavingINTEL
* SpeculatedIterationsINTEL
> Translate new set of Intel FPGA Loop Controls

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/relationals.ll
Whereas it is not possible to generate vector of bools in FE,
we have to change return type for corresponding instructions in SPIRV
translator to vector of bools. SPIRV translator already did this for
some instructions, this patch extends this behaviour to handle more
instructions.
> Fix translation of relational operations

- lib/SPIRV/SPIRVToOCL20.cpp
- test/barrier_explicit_arguments.spt
This patch features two things:
- fixed translation of OpControlBarrier into OpenCL 2.0 built-ins:
Scope of the operation is now respected and we can either get
work_group_barrier or sub_group_barrier depending on it
- improved the translation so it handles non-constant 'Memory Semantic'
operand of the instruction
> Fix translation of SPIR-V OpControlBarier to LLVM IR

- lib/SPIRV/SPIRVReader.cpp
The CreateShuffleVector API only accepts `int` or `uint32_t` ArrayRef
mask arguments.
> Avoid unnecessary type conversion

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- test/atomic_explicit_arguments.spt
- test/barrier_explicit_arguments.spt
- test/float_atomic_spv_to_ocl12.spt
- test/spirv-ocl-builtins-version.spt
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
- test/transcoding/OpControlBarrier_cl20.ll
- test/transcoding/OpControlBarrier_cl20_subgroup.ll
- test/transcoding/OpControlBarrier_cl21.ll
- test/transcoding/OpMemoryBarrier_cl20.ll
- test/transcoding/atomic_explicit_arguments.cl
- test/transcoding/atomic_flag.cl
- test/transcoding/atomic_load_store.ll
- test/transcoding/atomics.spt
- test/transcoding/atomics_int64.spt
- test/transcoding/memory_access.ll
- tools/llvm-spirv/llvm-spirv.cpp
- Refactored `--spirv-ocl-builtins-version` option so it can be set via library
interface as well and renamed it into `--spirv-target-env`
- Removed logic that relied on OpSource while generating LLVM IR for
OpenCL built-in functions
- Added one more library entry entry point: 'convertSpirvToLLVM' which
is a copy of existing one, but accept TranslatorOpts argument
> Do not rely on OpSource while translating into LLVM IR

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
Several deprecated IR Builder APIs were removed, see
https://reviews.llvm.org/D76269 [opaque pointer types] Remove deprecated
Instruction/IRBuilder APIs.
> Fix build after D76269

- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
Update for LLVM commit 4aae4e3f48b ("[llvm][NFC] CallSite removal
from inliner-related files", 2020-04-13).
> Update for InlineFunction API change

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
A few methods is going to be removed from Type class, see
https://reviews.llvm.org/D77278
Applied the following transformation to the code:
```
Ty->getVectorNumElements() -> cast<VectorType>(Ty)->getNumElements()
Ty->getVectorElementCount() -> cast<VectorType>(Ty)->getElementCount()
Ty->getVectorElementType() -> cast<llvm::VectorType>(Ty)->getElementType()
```
> [NFC] Refactor for upcoming D77278 Remove asserting getters from base Type

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
99e0a01715ab79dfd7f5d07c1b302ca0591fa0b1 (squashed):
Move Pass ID out of SPIRVToOCL base class
Having the SPIRVToOCL12 and SPIRVToOCL20 passes share the base class
Pass ID could cause the LLVM PassRegistry to believe it would register
the same pass twice.
Move the ID member down the class hierarchy such that each pass has
its own ID.
Fix SPIRVToOCL pass ID argument to be a reference
The ModulePass constructor takes a reference so we should forward the
reference given to the SPIRVToOCL constructor.
Reported-by: Stuart Brady
> Backport 4f459a8e1c6d9e5d15ad58ce42bc4cee6081ee5f and

- lib/SPIRV/SPIRVUtil.cpp
Community is going to remove 'getPointerElementType' method,
https://reviews.llvm.org/D16275 was used as example while preparing this
patch.
> [NFC] GEP: replace getPointerElementType uses with getSourceElementType.

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
See https://reviews.llvm.org/D62475: [DebugInfo] Change DIEnumerator
payload type from int64_t to APInt
> [NFC] Fix build after LLVM API change (D62475)

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVWriter.cpp
Update for LLVM commit a3982491db9 ("[Pass] Ensure we don't include
PassSupport.h or PassAnalysisSupport.h directly", 2020-04-26).
> Update LLVM PassSupport.h includes

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/translate_sampler_initializer.ll
Fix crash at translation of debug info for __translate_sampler_initializer()
call with a constant argument.
LLVMToSPIRVDbgTran::transLocationInfo() method assumes that LLVM instructions
in the basic block are mapped to SPIR-V instructions in the corresponding
basic block. That's not true for __translate_sampler_initializer() call with
constant argument. Such call is being translated to an OpConstantSampler in
global scope.
> Fix translation of debug info for constant sampler

- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
"Replace all uses of CallBase::getCalledValue() with getCalledOperand()"
> Fix build after a58b62b4a

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- test/constexpr_vector.ll
Since the translator has to lower LLVM constant expressions to be able to represent them in SPIR-V,
we now need to support not only single constexprs but vectors of constexprs as well.
> Support lowering of constant expressions vector

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL20.cpp
For details about motivation of removing this code check: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/514
> Remove deprecated spirv-atomic-prefix option

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/FPGAIVDepLoopAttr.ll
The semantics of the `"!llvm.loop.parallel_access_indices"`
loop metadata node could be defined as follows:
```
The IVDep hint of this loop applies to all arrays whose
GEP instructions are marked with:
1. !llvm.index.group metadata nodes that are operands of
the given !llvm.loop.parallel_access_indices node
2. !llvm.index.group metadata nodes that are used by the
operands of the given !llvm.loop.parallel_access_indices
node
```
Case **2** is vital for IVDep's representation on loop
nests. This patch fixes its improper translation by
mapping **all** operands of a given !llvm.index.group
(if present) onto the affected array IDs.
Additionally, the test was updated to include the legacy
ivdep metadata (Clang emits it alongside the
`parallel_access_indices`-based layout).
Signed-off-by: Artem …
> Adjust FPGA IVDep translation for embedded loops

- include/LLVMSPIRVLib.h
- lib/SPIRV/SPIRVReader.cpp
- tools/llvm-spirv/llvm-spirv.cpp
Cherry-pick https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/bab8e491396b98decf53dbe73b025f9fb8de3362 from master.
> Improve error handling for llvm::getSpecConstInfo API

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/ContractionOff.ll
- tools/llvm-spirv/llvm-spirv.cpp
In SPIR-V, floating point contraction (fused multiply add) can only be
controlled per entry point using ContractionOFF execution mode: it can
either allow any floating point operation to contract across a call
graph (with an entry point as a root), or disallow contraction for a
call graph.
SPIR-V translator currently have an algorithm to determine if
ContractionOFF should be set, but this algorithm is supposed to be
very pessimistic. A single non-contracted fmul + fadd or a single
undefined function must force ContractionOFF for the entire call
graph. This behavior is used by default, or when `-ffp-contract=on` is
set.
Two more modes are added:
- `off` disables contraction for all entry points
- `fast` unconditionally enables contraction for all entry points
Signed-off-by: Andrew …
> Add --spirv-fp-contract={on|off|fast} option

- lib/SPIRV/PreprocessMetadata.cpp
This refactor is needed for some of the future commits
> Move preprocessing OCL metadata to separate function

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
This refactor is needed for some of the future commits
The idea behind these changes was to abstract from specific types of metadata.
transMetadata() does everything is needed to be done with metadata.
transOCLMetadata(), which is called by transMetadata does everything is needed to be done with OCL metadata.
> Move translation of OCL metadata to separate function

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- test/ContractionON.ll
- test/ContractionOff.ll
This patch makes several improvements to enable correct setting for
ContractionOFF:
1) Plain `fadd` or `fsub` instruction trigger ContractionOFF to
avoid optimizations that may fold them to an FMA.
2) `contract` flag is recognized on `fadd` and `fsub`, and it allows
to suppress (1).
3) Undefined (external) functions, function pointers and inline asm
calls force ContractionOFF flag.
4) Contraction information is now propagated up the call stack until
an entry point.
> Enable strict rules to set ContractionOFF

- lib/SPIRV/SPIRVLowerOCLBlocks.cpp
SPIRV Lower OCL blocks pass does not have getPassName implementation. This commit adds one
> added missing implementation of getPassName for SPIRVLowerOCLBlocks

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- test/atomic_explicit_arguments.spt
- test/mem_fence_explicit_arguments.spt
We have a lot of duplicated code for handling memory scope, order and flags arguments of different OpenCL built-ins, like barriers, atomics and fences.
Refactored all common code into helper functions. (This should be an NFC change.)
Improved translation of `OpMemoryBarrier` by adding handling for non-const operands. (This is actually what I want to achieve, but while doing so, I decided to perform a refactoring.)
Note: I'm not going to add support for non-const memory scopes, orders and flags for each and every built-in and SPIR-V instruction in scope of this PR: this is just improvement of `OpMemoryBarrier` + refactoring.
> Refactor translation of memory scopes, orders and flags

- test/DebugInfo/DebugDeclareUnused.cl
Update after LLVM commit llvm/llvm-project@77ffce6
"[Instruction] Set metadata uses to undef on deletion"
> Update DebugInfo test after LLVM changes 77ffce6

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/undef-func-call.ll
This fix resolves issue:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/524
Function translation invokes translation of LLVM loop metadata as a last step.
SPIRVToLLVM keeps a map with metadata. If function with loop metadata is
forward-referenced, translation starts and metadata is placed in the map. If
this function contains calls of undefined functions inside, it will fail -
metadata map is not empty, but there is no loop info inside the undefined
function.
Example:
```
float bar(int x);
__kernel void foo(__global float* outPtr, int i) {
for (int j = 0; j < i; ++j) {
outPtr[j] = bar(j);
}
}
```
> Fix translation of undefined function call when debug info is present

- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/transcoding/ReqdSubgroupSize.ll
There are four one-liner commits which are necessary for future changes.
> Minor changes needed for future commits

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- test/ContractionON.ll
- test/ContractionOff.ll
Add --spirv-fp-contract={on|off|fast} option (#509) is **NOT** cherry-picked, because translation options are not implemented in llvm-8 branch.
> Cherry-pick FP contract changes to llvm-8

- lib/SPIRV/SPIRVWriter.cpp
- test/trap.ll
instruction.
Clang, due to some ABI constraints needs to generate llvm.trap
intrinsics. According to the LangRef documentation a trap instruction
is lowered to a target's trap instruction or to an abort() function
if the target doesn't have a trap instruction. SPIRV has neither a
trap nor an abort instruction and no current opcode has the semantics
of an abort/trap.
Currently the IR to SPIRV translator is crashing when it finds an
llvm.trap intrinsic. The solution will require some thoughts on the
SPIRV side to decide how to implement an abort instruction.
This patch changes the translator so it doesn't crash. This will be
revised when a decision is taken.
NOTE: clang could eventually not generate an llvm.trap instruction in
the current case (non-base destructor of an abstract class needs …
> Ignore llvm.trap intrinsic

- test/DebugInfo/X86/default-subrange-array.ll
Update after LLVM commit llvm/llvm-project@d20bf5a
"[DebugInfo] Upgrade DISubrange to support Fortran dynamic arrays"
> Update DebugInfo test after LLVM changes D80197

- utils/check_code_format.sh
- utils/check_code_tidyness.sh
Patch fixes github issue for llvm 10 branch:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/496
Example failure without this patch: https://travis-ci.org/github/KhronosGroup/SPIRV-LLVM-Translator/jobs/693502720.
> Fix base branch in code check scripts for llvm 10

- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- test/transcoding/ReqdSubgroupSize.ll
* Fix CapabilitySubgroupDispatch name in SPIRVNameMapEnum.h
* Add ExecutionModeSubgroupSize to SPIRVNameMapEnum.h
> Minor amends needed for future commits:

- lib/SPIRV/libSPIRV/SPIRVDebug.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.h
- lib/SPIRV/libSPIRV/SPIRVError.h
- test/negative/atomicrmw-unsupported-operation.ll
- test/negative/invalid-int-bitwidth.ll
- test/negative/llvm.fma.ll
- test/negative/unimplemented.spt
- test/negative/unsupported-triple.ll
- test/negative/zero-length-array.ll
- test/spirv-unknown-extensions.spt
- test/spirv-version-controls-negative-1.spt
- test/spirv-version-controls-negative-2.spt
- test/spirv-version-controls.spt
- test/transcoding/NoSignedUnsignedWrap.ll
The llvm-spirv tool might be used (and actually used in intel/llvm) by some custom clang toolchains
and handling aborts from executed tools might be tricky and requires additional work.
Regular non-zero exit codes are just better for error reporting in production.
> [SPIR-V] Exchange abort() to exit() in llvm-spirv tool by default.

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/constexpr_vector.ll
- test/transcoding/SPV_INTEL_function_pointers/vector_elem.ll
Extend constexprs lowering support to lower constant vector of pure function pointers
w/o any transformations inside.
> [Backport] Improve constant expressions lowering for function pointers.

- test/read_image.cl
- test/transcoding/SPV_INTEL_media_block_io.cl
- test/transcoding/enqueue_marker.cl
- test/transcoding/group_ops.cl
- test/transcoding/pipe_builtins.cl
The combination of `-fdeclare-opencl-builtins -finclude-default-header`
stops Clang from parsing its large opencl-c.h file.  Switch some more
.cl tests that do not need the full opencl-c.h file to this flag
combination, to speed up test execution.
> Use -fdeclare-opencl-builtins for more .cl tests

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/Generic/tu-member-opaque.spvasm
Per the spec opaque types should use DebugInfoNone for the Size
operand
> Support DebugInfoNone in DebugTypeComposite

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/FPGALoopAttr.ll
- test/transcoding/FPGALoopMergeInst.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
One more step to align spirv.hpp versions
> [NFC] Fix Intel loop control masks spelling

- test/transcoding/enqueue_kernel.cl
Update tests after llvm/llvm-project@c9a52de
"[CodeGen] Simplify the way lifetime of block captures is extended"
> Update tests after LLVM changes

- lib/SPIRV/SPIRVWriter.cpp
- Use regex to avoid regular `find`s and substring
assignments;
- Make variable names more readable.
> [NFC] Improve parsing of FPGA memory decorations

- lib/SPIRV/SPIRVLowerBool.cpp
- test/TruncToBool.ll
Merged to master in #568
This version is slightly different: test doesn't contain spirv-val call. As I understood, it isn't called in this branch.
> [Backport] Fix for trunc to bool lowering (LLVM-7)

- lib/SPIRV/SPIRVWriter.cpp
- test/custom_class.ll
In case separate constructor declaration and definition the IR representation has GlobalAlias objects which didn't process properly.
> Handle LLVM function aliases

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVWriter.cpp
Update for commit eb81c85afdc ("[SVE] Deprecate default false variant
of VectorType::get", 2020-06-16).
> Use LLVM FixedVectorType::get

- lib/SPIRV/VectorComputeUtil.cpp
This commit allows to use UniformConstant and CrossWorkgroup
storage classes for VectorCompute globals
> Add common OCL address spaces for VectorCompute globals

- utils/check_code_format.sh
- utils/check_code_tidyness.sh
Patch fixes github issue:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/496
Cherry-pick of #562.
> Fix base branch in code check scripts for llvm 9

- README.md
Remove any remaining references to LLVM SVN/trunk and update any links
that were still pointing to the old LLVM split repository mirrors.
Elaborate on tags and how they match up with LLVM.
Line-wrap the affected paragraphs to 80 characters.
> README.md: Update branches section

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/GenericCastToPtr.cl
- test/transcoding/atomics.spt
- test/transcoding/memory_access.ll
`setName` function invalidates the name returned by `getName`, so
`InstName` is invalid. Since `takeName` is called later, we can avoid
this renaming altogether.
> Fix incorrect usage of StringRef

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
Bug is caused by translating of known intrinsics declarations, which should not be translated.
> Fix crash on debug info when -spirv-allow-unknow-intrinsics option enabled

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
Bug is caused by translating of known intrinsics declarations, which should not be translated.
> Fix crash on debug info when -spirv-allow-unknow-intrinsics option enabled.

- test/DebugInfo/BuiltinCallLocation.cl
- test/DebugInfo/DebugControlFlow.cl
- test/DebugInfo/DebugUnstructuredControlFlow.cl
Update for LLVM commit b0b5162fc23 ("[Driver] Pass -gno-column-info
instead of -dwarf-column-info", 2020-07-05).  Either remove the
obsolete `-dwarf-column-info` flag, or add the `-gno-column-info` flag
for tests for which column info is not relevant.
> Update DebugInfo tests for LLVM -dwarf-column-info change

- lib/SPIRV/SPIRVWriter.cpp
They were added by mistake when backported from TOT.
> Remove extra intrinsics from "isKnownIntrinsic" function

- include/LLVMSPIRVLib.h
- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriterPass.cpp
- lib/SPIRV/SPIRVWriterPass.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- tools/llvm-spirv/llvm-spirv.cpp
* Move SPIRVAllowUnknownIntrinsics option to TranslatorOpts class
* Extend LLVMSPIRVOpts.h interface allowing pass options to spirv passes
> Move SPIRVAllowUnknownIntrinsics option to TranslatorOpts class

- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
Its use was removed in dff07df ("[SPIRV] Fix assertion due to
duplicate operands in opencl version metadata. This happens when two
SPIR modules are linked together. Remove check for OCL version in
OCLTypeToSPIRV. Only check if language is C or C++.", 2015-12-16).
> Drop unused CLVer member

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_simt_call.ll
Extension is published at https://github.com/intel/llvm/pull/1612
> Add SIMTCallINTEL decoration of SPV_INTEL_vector_compute extension

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/intel_usm_addrspaces.ll
a7b763b265d introduces a bug, when it could be possible to map a
single pointer type in LLVM IR to two different pointer types in
SPIR-V (when SPV_INTEL_usm_storage_classes extension is not allowed).
This patch fixes this bug.
> Fix type mapping for pointers with Device/HostOnlyINTEL storage classes

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_simt_call.ll
Extension is published at https://github.com/intel/llvm/pull/1612
> Add SIMTCallINTEL decoration of SPV_INTEL_vector_compute extension on llvm_release_100 branch

- lib/SPIRV/VectorComputeUtil.cpp
This commit allows to use UniformConstant and CrossWorkgroup
storage classes for VectorCompute globals
> Add common OCL address spaces for VectorCompute globals on llvm_release_80 branch

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
Bug is caused by translating of known intrinsics declarations,
which should not be translated.
> Fix crash on debug info when -spirv-allow-unknow intrinsics option enabled on llvm_release_80 branch

- .travis.yml
Since [D78646](https://reviews.llvm.org/D78646), LLVM require CMake 3.13.4 to build.
> CI update: fix compilation issues

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_simt_call.ll
Extension is published at https://github.com/intel/llvm/pull/1612
> Add SIMTCallINTEL decoration of SPV_INTEL_vector_compute extension on llvm_release_80 branch

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
Bug is caused by translating of known intrinsics declarations,
which should not be translated.
> Fix crash on debug info when -spirv-allow-unknow intrinsics option enabled on llvm_release_70 branch

- lib/SPIRV/VectorComputeUtil.cpp
This commit allows to use UniformConstant and CrossWorkgroup
storage classes for VectorCompute globals
> Add common OCL address spaces for VectorCompute globals on llvm_release_70 branch

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/DebugInfo/DebugInfoWithUnknownIntrinsics.ll
Bug is caused by translating of known intrinsics declarations,
which should not be translated.
> Fix crash on debug info when -spirv-allow-unknow intrinsics option enabled on llvm_release_90 branch

- lib/SPIRV/VectorComputeUtil.cpp
This commit allows to use UniformConstant and CrossWorkgroup
storage classes for VectorCompute globals
> Add common OCL address spaces for VectorCompute globals on llvm_release_90 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/decoration_simt_call.ll
Extension is published at https://github.com/intel/llvm/pull/1612
> Add SIMTCallINTEL decoration of SPV_INTEL_vector_compute extension on llvm_release_90 branch

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/builtin_vars_opt.ll
The method did not handle correctly the case when addrspacecast instruction had
more than one usage.
> Improve SPIRVToLLVM::transOCLBuiltinFromVariable

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/IntelFPGAMemoryAccesses.ll
The initial implementation had required that the first
ptr.annotation operand be a result of a load intruction.
However, it may be the case that the LSU built-in gets applied
to a cast result/to a result of a function call, therefore
this patch drops the unfeasible requirement.
> [SYCL][FPGA] Lift the restriction on LSU intrinsic operands

- lib/SPIRV/SPIRVReader.cpp
- test/kernel-arg-ext_int-ptr.spt
> [SYCL] Fix translation of kernel args of arbitrary integer pointer type

- .travis.yml
The Xenial binaries on apt.llvm.org have been outdated for a while,
whereas the Bionic binaries seem up to date now.  Switch Travis to
test on Bionic.
Drop the pyenv fix from df75cab ("Fix Travis CI build.", 2019-07-11)
as it no longer seems to be needed for 18.04.
> [Backport] travis: Move to 18.04 (Bionic)

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/intrinsic_result_store.ll
Replacement of the read-from operand with the result of its
intrinsic call user should only happen for `llvm.ptr.annotation`
calls.
> Fix translation of LLVM intrinsics when their args are stored

- lib/SPIRV/OCL20ToSPIRV.cpp
That fixes build after:
89051ebac "GetUnderlyingObject -> getUnderlyingObject"
b0eb40ca3 "Remove unused GetUnderlyingObject paramenter"
> [NFC] Update GetUnderlyingObject usage

- lib/SPIRV/SPIRVWriter.cpp
- test/usub-sat.ll
Translate usub.sat(a, b) as (a > b) ? a - b : 0 sequence.
> Add support for usub.sat intrinsic

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/BitReversePref.ll
User may get their function a name the same as SPIR-V instruction.
In that case thier function call will be translated to SPIR-V instruction call.
The only functions that should be translated to SPIR-V instructions are SPIR-V built-ins
and they should have __spirv prefix.
Add checking for __spirv prefix in demangler to filter SPIR-V built-ins from other function calls
> Fix translation of user functions into SPIR-V instructions

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/maxnum.ll
Map to fmax SPIR-V instruction from OpenCL extended instruction set.
> Translate llvm.maxnum intrinsic function

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/GlobalFunAnnotate.ll
Implementation of saving llvm.global.annotations for functions after SPIRV translation
Add test for this
> Translating annotations for functions

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/DebugInfo/Generic/linear-dbg-value.ll
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug on llvm_release_110 branch

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/IntelFPGAMemoryAccesses.ll
- test/transcoding/intel_fpga_lsu_optimized.ll
This patch follows from 71039dd3c5dbfafab78f6b86a5bb06ba2af93c89
* Replace the destination operand with the result of its intrinsic call for store inst.
* Replace the read-from operand with the result of its intrinsic call for load inst.
> Fix translation of llvm.ptr.annotation

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/DebugInfo/Generic/template-recursive-void.ll
Propagate the change from LLVM commit 24c3dabef44 ("DebugInfo: Emit
class template parameters first, before members", 2020-08-17).
Update for LLVM commit a407ec9b6db ("Revert "Revert "[NFC][llvm] Make
the contructors of `ElementCount` private.""", 2020-08-19).
> Update after LLVM changes

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- test/constexpr_phi.ll
Put newly created insertElement instructions at the ends
of the incoming blocks instead of putting them immediately before
the phi thus breaking the module.
> Fix handling of phi nodes in LowerConstExprs.

- lib/SPIRV/PreprocessMetadata.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp

- lib/SPIRV/SPIRVWriter.cpp
Ignore other than constant integer type instead of crashing.
> Be more tolerant with buffer_location MDNode type

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug on llvm_release_100 branch

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug on llvm_release_90 branch

- lib/SPIRV/SPIRVReader.cpp
Fixed bug leaded to release build fail occured by
Float Control decs commit: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/677
> Fix release build fail

- lib/SPIRV/SPIRVReader.cpp
Backport for bugfix: #699
Fixed bug leaded to release build fail occured by
Float Control decs commit
> Fix release build fail for v7

- lib/SPIRV/SPIRVReader.cpp
Backport for bugfix: #699
Fixed bug leaded to release build fail occured by
Float Control decs commit
> Fix release build fail for v9

- lib/SPIRV/TransOCLMD.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp on llvm_release_70 branch

- lib/SPIRV/PreprocessMetadata.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp on llvm_release_90 branch

- lib/SPIRV/PreprocessMetadata.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp on llvm_release_100 branch

- lib/SPIRV/PreprocessMetadata.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp on llvm_release_110 branch

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/float-controls-decorations.ll
https://github.com/intel/llvm/pull/1611
(Master pull request https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/677)
> Float Controls Decoration backport for 110 release

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug on llvm_release_70 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/intel_multiple_fpga_loop_attrs.ll
3.23 Loop Control:
If there are multiple following operands indicated, they are ordered: Those
indicated by smaller-numbered bits appear first.
This rule was violated in previous implementation.
> Fix LoopControl parameters order

- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
Previous name was merged to llvm_release_100 and llvm_release_90 by mistake. Other branches have correct name.
> Rename "debug-info-eis" option to "spirv-debug-info-version" on llvm_release_90 branch

- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
Previous name was merged to llvm_release_100 and llvm_release_90 by mistake. Other branches have correct name.
> Rename "debug-info-eis" option to "spirv-debug-info-version" on llvm_release_100 branch

- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/capability-arbitrary-precision-integers.ll
Adjusted SPRIVConstantBase class to hold up to 8 SPIR-V words in a
constant.
Motivation for this change is that optimized LLVM IR can represent
types like `[3 x i32]` as `i96` and in combination with
SPV_INTEL_arbitrary_precision_integers extension it generates pretty
valid SPIR-V. However, during its consumption the translator reads more
than 2 SPIR-V words from an input and stores them in array for only 2
SPIR-V words, which causes memory corruption.
Discovered by debugging an issue with SYCL compiler from intel/llvm
project where internal representation of `cl::sycl::vec<int, 8>` class
were transformed into `i256` and stored in a constant.
> Support 1024-bit constants

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
This option required for compatibility with older version of translator
> Add DebugInfoEIS option to allow setting desired extended instruction set for debug info on llvm_release_110 branch

- test/DebugInfo/X86/inlined-formal-parameter.ll
Adjusted the test in accordance with llvm/llvm-project@57d8acac64b87cb4286b00485fb2da7521fc091e
> Fix inlined-formal-parameter LIT test after LLVM update

- lib/SPIRV/SPIRVLowerBool.cpp
- test/uitofp-with-bool.ll
UIToFPInst LLVM instruction is translated to OpConvertUToF SPIRV
instruction. OpConvertUToF instruction cannot receive boolean operand,
so replace boolean operand with with select instruction.
> Lower UIToFPInst with bool operand

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- test/negative/unsup_invoke_instr.ll
Exception handling instructions ( e.g. invite instruction) may fall into llvm-spirv translator (e.g from OpenMP) and this PR adds the right error message about it.
> Add error then exception handling mechanism Fall into llvm-spirv translator

- lib/SPIRV/libSPIRV/SPIRVAsm.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
In all cases what we have encountered so far each instruction has either
zero or one extension that it requires and therefore there is no need to
use `std::set` to store that information.
Replaced `std::set` with `llvm::Optional` and renamed function to
indicate that it can only return a single extension.
> [NFC] Do not use std::set in getRequiredExtensions

- lib/SPIRV/SPIRVWriter.cpp
The assertion now gives way to a simple check until all known
LLVM IR edge cases that do not accord to the condition can be
handled.
> [SYCL][FPGA] Replace the IVDep index group validity assertion

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/constrained_arifm_intr.ll
- test/constrained_cmp_intr.ll
- test/constrained_convert_intr.ll
Add llvm.experimental.constrained.* intrinsic support, namely : fadd, fsub, fmul, fdiv, frem, fma, fmulladd, fptoui, fptosi, uitofp, sitofp, fptrunc, fpext, fcmp, fcmps.
These intrinsics are not actually supported in SPIR-V, but just being emulated via existing functionality with loss of "constrained" semantic
> Add Constrained Floating-Point Intrinsics support

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/capability-arbitrary-precision-fixed-point-numbers.ll
- test/transcoding/capability-arbitrary-precision-floating-point.ll
This patch addresses https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/653#discussion_r463629986
If the appropriate extension for arbitrary precision instruction is not enabled, invalid IR will be produced. Report an error in this case.
> Do not translate arbitrary precision operations without corresponding extensions

- lib/SPIRV/SPIRVWriter.cpp
The nullptr creates a problem then falls into the stream.
> Exchange nullptr by quotes in checkError function

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
Replacing "VectorType" with a "FixedVectorType"
Fixes #506
> Removing deprecated "VectorType::getNumElements"

- lib/SPIRV/PreprocessMetadata.cpp
- test/nullptr-metadata-test.ll
> Fix emitting SPIRV metadata for non-kernel functions in PreprocessMetadata.cpp on llvm_release_80 branch

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVFunction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/Generic/debug-info-eis-option.ll
- tools/llvm-spirv/llvm-spirv.cpp
> Add OpenCL.DebugInfo.100 as alias to SPIRV.debug on llvm_release_80 branch

- lib/SPIRV/SPIRVReader.cpp
Removed extra variables, simplified code, removed dead code related to
"read_image" handling: it is not present in OpenCL.std extended instruction
set and therefore we can't encounter it in `transOCLBuiltinFromExtInst`
function.
> [NFC] Refactor transOCLBuiltinFromExtInst

- .travis.yml
This is a first step towards resolving #716: I've removed 5/8 `clang` compiler configurations
> Adjust Travis CI testing scope

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerBool.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.h
- lib/SPIRV/libSPIRV/SPIRVError.h
This is achieved by guarding most (only covered LLVM IR -> SPIR-V passes)
`verifyModule` calls by corresponding command line options, which are
disabled/enabled in accordance with _SPIRVDBG define.
Made _SPIRVDBG define disabled in release builds by default
> [NFC] Avoid verifying module in release builds

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/builtin-get-global-id.ll
debug info of work-item builtins are lost in both llvm IR -> spirv and spirv -> llvm IR translations. See #744
> Fix debug info of work-item builtin translation

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
This PR has a few updates to the SPIR-V LLVM Translator to prepare for OpenCL C 3.0 changes in Clang.
Primarily, OpenCL C 3.0 is a derivative of OpenCL C 2.0 and not OpenCL C++.  This means:
* We should run the OpenCL C++ passes for OpenCL 2.1 only, and not for versions newer than OpenCL 2.0.
* We should run similar OpenCL C 2.0 passes for OpenCL C 3.0.
At some point we could consider renaming some of the passes or the "CL21" version, but I would prefer to do that as a separate PR.
> updates for OpenCL C 3.0

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_function_pointers/global_ctor_dtor.ll
See issue #631 
Fix global ctor/dtor translation from SPIRV to LLVM IR
Translate global variable if its storage is StorageClassFunction and its name is either llvm.global_ctors or llvm.global_dtors.
Apply appending linkage to the global variable.
SPV_INTEL_function_pointers extension is required for the translation.
> Fix global ctor/dtor translation

- lib/SPIRV/SPIRVWriter.cpp
- test/empty-module.ll
When translator tool is used in toolchain it is possible that it can
receive an empty LLVM module as an input, just emit an empty SPIR-V module
with Linkage capability in this case.
> Translate empty LLVM module to empty SPIR-V module

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/Mangler/Mangler.cpp
- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/libSPIRV/SPIRVDebug.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
Remove unused includes.
Move some includes from SPIRVDebug.h to .cpp files.
Header files should only include the minimum required, to keep build times reasonable.
> Cleanup includes

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCL21ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
OpenCL C 3.0 is a derivative of OpenCL C 2.0 and not OpenCL C++.
Run the OpenCL C++ passes for OpenCL 2.1 only, and run similar
OpenCL C 2.0 passes for OpenCL C 3.0.
> [CherryPick] updates for OpenCL C 3.0

- .travis.yml
The build log did not contain the llvm-project repository revision
being built for `BUILD_EXTERNAL=0` builds.  Add it to ease debugging
of build failures.
> travis: report llvm revision for non-external builds

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/transcoding/llvm.memset.ll
There is no SPIR-V counterpart for @llvm.memset.* intrinsic. Cases with constant
value and length arguments are emulated via "storing" a constant array to the
destination.
For other cases we wrap the intrinsic in @spirv.llvm_memset_* function and
expand the intrinsic to a loop via expandMemSetAsLoop() from
llvm/Transforms/Utils/LowerMemIntrinsics.h.
During reverse translation from SPIR-V to LLVM IR we can detect
@spirv.llvm_memset_* and replace it with @llvm.memset.
> Handle @llvm.memset.* with non-constant arguments

- lib/SPIRV/SPIRVUtil.cpp
- test/llvm.fabs.ll
The OpenCL SPIR-V Environment Specification seems to allow corresponding
instruction.
> Allow to translate llvm.fabs with half argument

- test/DebugInfo/X86/dbg-declare-arg.ll
Propagate the test change from LLVM commit 55f9f87da2c ("Reapply
Revert "RegAllocFast: Rewrite and improve"", 2020-09-21).
> Update dbg-declare-arg test after LLVM change

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/capability-arbitrary-precision-integers.ll
Previously APInt constants were being stored into uint64_t value
with following encoding/decoding. Now they are being packed into
SPIRVWords array directly.
> Fix translation of APInt constants

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- test/CXX/global-ctor.cl
This PR adds support to translate global constructors from LLVM's `llvm.global_ctors` variable to SPIR-V's `Initializer` execution mode, and vice versa.
* Only emit Initializer and Finalizer from SPIR-V 1.1
* Translate Initializer to llvm.global_ctors
* Set Initializer ExecutionMode for global ctors
* Conditionalize translation of llvm.global_ctors/dtors
> Use Initializer execution mode for global constructors

- lib/SPIRV/OCLUtil.cpp
The most notable change is that usages of `std::string` were replaced
with `llvm::StringRef` to simplify code and probably speedup it a little
bit.
> [NFC] Refactor OCLBuiltinFuncMangleInfo

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/abs.ll
Add llvm.abs.i32 translation to "s_abs" instruction.
Add test for this.
> Add llvm.abs.i32 translation 

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/FPGAIVDepLoopAttrOnClosure.ll
When IVDep is applied to a regular kernel-scope array/pointer variable,
the GEP instructions that access this variable are marked with index
group metadata.
When IVDep is applied to a captured argument of a kernel, however,
the pointer operand of index group-marked instructions becomes a GEP
itself. The latter GEP accesses the closure of a kernel lambda with
an offset that signifies the number of the captured parameter in the
closure layout.
To treat the second case:
1. In forward translation, we ensure that for each memory block, all
pointer accesses marked into IVDep index groups are recognized and
translated into LoopControl parameters. Previously, only the latest
pointer access would get listed in the SPIR-V representation of
attribute parameters.
2. In backward translation, we also …
> [SYCL][FPGA] Fix IVDep translation for accesses to kernel closure fields

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/builtin_function_readnone_attr.ll
All constant built in functions should have readnone attribute in LLVM IR. 
> Add ReadNone attr for Builtin functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to this spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration

- lib/SPIRV/SPIRVReader.cpp
- test/CMakeLists.txt
- test/lit.cfg.py
- test/lit.site.cfg.py.in
- test/transcoding/linked-program.ll
* Make spirv-link usable in tests
* Add default initializer to CrossWorkgroup globals
Patches by @mantognini!
> Fix spirv-linked programs with program scope variables.

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to this spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration backport to v11

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration backport to v10

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration backport to v9

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration backport to v8

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
"VCCallable" attribute, according to spec: https://github.com/intel/llvm/pull/1612
> Implementing VectorComputeCallableFunctionINTEL decoration backport to v7

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/X86/convert-debugloc.ll
- test/DebugInfo/expr-opcode.ll
- tools/llvm-spirv/llvm-spirv.cpp
Experimental support of extra DWARF operations
As this functionality is not documented by any formal SPIR-V extension or SPIR-V
extended instruction set specification, it is disabled by default and in order
to enable generation of extra debug information, user needs to pass
`spirv-allow-extra-diexpressions` command line option to the
translator.
> [Backport] Support missing DWARF opcodes (#679)

- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- tools/spirv-tool/gen_spirv.bash
For many enums in `spirv.hpp`, an isValid function was generated in
`SPIRVIsValidEnum.h` even though that function was never used.  Remove
them to reduce build times and maintenance burden.
If a removed isValid function is needed again in the future, the enum
name needs to be added back to `gen_spirv.bash` followed by a rerun of
the script.
Regenerate SPIRVIsValidEnum.h and SPIRVNameMapEnum.h using the
updated `gen_spirv.bash` script.
Generate all .h files in one invocation
Move enum lists to top of script.
> Further improvements to generation of SPIRV*Enum.h

- README.md
Updated REAMDE.md to mention that `clang` is required to build/test the
translator.
Resolves #777
> [NFC] Update in-tree build instruction

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/builtin_vars.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/builtin_vars_opt.ll
More info about motivation for this change can be found in [this comment](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/746#issuecomment-699955286) from #746
> Add possibility to lower BuiltIn-s into SPIR-V friendly IR

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- test/lshr-constexpr.ll
It is possible that instruction has metadata operand which is actually
is a constant expression which should be lowered, for example constant
expression metadata can appear as operand of debug instruction.
> Lower constant expressions inside metadata operands

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/llvm-intrinsics/fshl.ll
"Funnel shift left" doesn't have an analogue in the OpenCL
ExtInst set. We unroll `llvm.fshl.i<n>(i<n>, i<n>, i<n>)`
into a small algorithm that performs the actual funnel shift.
A detailed description of FSHL can be found at
https://llvm.org/docs/LangRef.html#llvm-fshl-intrinsic
> Translate the llvm.fshl intrinsic function

- .clang-tidy
- .github/workflows/check-code-style.yml
Enabled warnings as errors to clarify that most of enabled checks are
required.
New feature: warnings and errors found by clang-tidy are now being
reported as annotations at "Files changed" page.
Resolves #801
> Improve clang-tidy CI check

- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
There are two main reasons this PR was created:
1. We have a problem with Travis CI and it has been basically disabled for almost a two weeks for now
2. From my point of view, GitHub Actions provide more features to make our CI jobs even better
(2) is being discussed in #716 and this PR can be considered as a temporary, i.e. if we don't like how GitHub Actions work we can always fallback to Travis CI once it is fixed.
Anyway, this PR features the following:
- two separate workflows for in-tree and out-of-tree builds
- support for master and release branches as well as for nightly builds
- in-tree build is enabled on Linux, Windows (this tries to address #726, at least partially) and macOS
- these workflows are not launched for documentation-only changes
I added links to GitHub Actions …
> [CI] Enable GitHub Actions for builds and tests

- lib/SPIRV/SPIRVReader.cpp
At this point LoopControlParameters can be empty only if a single
metadata llvm.loop.ivdep.enable is attached to a branch instruction. 
> [NFC] Remove unnecessary check for ivdep

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/2010-10-01-crash.ll
- test/DebugInfo/UnknownBaseType.ll
- test/DebugInfo/X86/dbg-byval-parameter.ll
- test/DebugInfo/X86/dbg-declare-arg.ll
- test/DebugInfo/X86/double-declare.ll
- test/EnqueueEmptyKernel.ll
- test/llvm-intrinsics/memcpy.align.ll
- test/llvm-intrinsics/memset.ll
- test/transcoding/BuildNDRange.ll
- test/transcoding/BuildNDRange_2.ll
With the latest community changes, the StructRet/ByVal parameter
attributes are now required to have a type. Fix the build by:
1. updating the LIT IR to match this policy;
2. adding correct attribute types in backwards translation.
> Align with LLORG on sret/byval parameter attribute types

- README.md
- Ensure correct naming of `LLVM_SPIRV_INCLUDE_TESTS` in the
documentation;
- Clarify the usage scenario of the `LLVM_EXTERNAL_LIT` variable.
> [Doc] Update the test build instructions

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/fast-composit-entry.ll
Added translation of VCFCEntry kernel attribute to execution mode
VectorComputeFastCompositeKernelINTEL according to this spec: https://github.com/intel/llvm/blob/693199d47868141cdcc69f8ebd80f149b3e28729/sycl/doc/extensions/SPIRV/SPV_INTEL_vector_compute.asciidoc
> [Feature] Added translation of VCFCEntry attribute

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopMergeInst.ll
Otherwise we can't make any assumptions about LoopControl parameters
order.
> Make LoopControlLoopCoalesceINTELMask parameter be mandatory

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/atomic-load-store.ll
- test/transcoding/atomics.spt
LLVM IR `store atomic` and `load atomic` instructions are now lowered
to the corresponding SPIR-V atomics.
> Support atomic ordering for LLVM load/store instructions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopMergeInst.ll
The new loop control bit NoFusionINTEL is enabled by the FPGALoopControlsINTEL
capability. If this bit is set, it indicates that the loop should not be fused
with any adjacent loop.
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/pull/85/
> Add intel::nofusion loop attribute translation

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/IntelFPGAFunctionAttributes.ll
Indicates the target clock frequency (Fmax) for the kernel, in MHz.
Only valid with the Kernel Execution Model.
Spec:
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_kernel_attributes.asciidoc
> Add SchedulerTargetFmaxMhzINTEL execution mode

- include/LLVMSPIRVExtensions.inc
When we do some changes to `include/LLVMSPIRVExtension.inc`, clang-tidy
complains about undefined `EXT` macro, because it looks at the file
alone, while it was designed to be included from another file where
`EXT` is defined.
In order to fix this constant complain, let's add a dummy definition of
`EXT` macro instead of using `#error` directive.
An example of noisy output from clang-tidy: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/381033219
> Reduce amount of noise from clang-tidy

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
There are more reasons to skip particular workflows, like:
- if we change check-code-style workflow, no need to launch builds
- if we change some CMakeLists.txt, no need to launch check-code-style
> Improve paths-ignore in our CI workflows

- lib/SPIRV/SPIRVWriter.cpp
- test/negative/invalid-constant-generic-cast.ll
- test/negative/invalid-device-local-cast.ll
- test/negative/invalid-private-global-cast.ll
Purpose of this patch is to make the translator a little bit more
user-friendly. For example following SYCL code:
```
SYCL_EXTERNAL sycl::global_ptr<int> kernel_fun(int *ptr) {
return sycl::global_ptr<int>((int*)&ptr);
}
```
is UB since it has an implicit cast from private address space to
global. It's hard to detect such UB in FE, hence this diagnostic is
moved to the translator (which already had it, but in form of an
assert).
> Replace illegal address space casts asserts with errors

- .gitignore
When a file opened in vim multiple times, vim starts producing swap
files with different extensions, for example .swo. Add them to gitignore
so git doesn't highlight them.
> Improve ignoring of vim swap files by git

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/fast-composit-entry.ll
Added translation of VCFCEntry kernel attribute to execution mode
VectorComputeFastCompositeKernelINTEL
Backport for https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/827
> [Backport] Added translation of VCFCEntry attribute(#827) branch 90

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/fast-composit-entry.ll
Added translation of VCFCEntry kernel attribute to execution mode
VectorComputeFastCompositeKernelINTEL
Backport for https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/827
> [Backport] Added translation of VCFCEntry attribute(#827) branch 100

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/fast-composit-entry.ll
Added translation of VCFCEntry kernel attribute to execution mode
VectorComputeFastCompositeKernelINTEL
Backport for https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/827
> [Backport] Added translation of VCFCEntry attribute(#827) branch 110

- lib/SPIRV/SPIRVWriter.cpp
- test/count-zero-bits.ll
LLVM transformation passes may introduce calls to these intrinsics and
supporting them in the translator also allows using GCC/Clang builtins
`__builtin_clz` and `__builtin_ctz`.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/303
> [Backport]Translate ctlz/cttz intrinsics to OpExtInst

- include/LLVMSPIRVLib.h
While checking in-memory spirv binary I've tried using `isSpirvBinary` api and hit a linking failure:
undefined reference to `SPIRV::isSpirvBinary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Looks like a signature inconsistency, as the cpp has const ref:
`lib/SPIRV/libSPIRV/SPIRVModule.cpp:bool isSpirvBinary(const std::string &Img)`
So, fixing the issue.
> Fix isSpirvBinary signature

- lib/SPIRV/SPIRVLowerBool.cpp
- test/sitofp-with-bool.ll
SIToFPInst LLVM instruction is translated to OpConvertSToF SPIRV instruction.
OpConvertSToF instruction can not receive boolean operand, so replace it with
the select instruction.
> Lower SIToFPInst with bool operand

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/X86/convert-debugloc.ll
- test/DebugInfo/expr-opcode.ll
- tools/llvm-spirv/llvm-spirv.cpp
Experimental support of extra DWARF operations
As this functionality is not documented by any formal SPIR-V extension or SPIR-V
extended instruction set specification, it is disabled by default and in order
to enable generation of extra debug information, user needs to pass
`spirv-allow-extra-diexpressions` command line option to the
translator.
> [Backport] Support missing DWARF opcodes on llvm_release_90 branch

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/relationals.ll
- test/transcoding/OpAllAny.ll
- test/transcoding/check_ro_qualifier.ll
Remove double mangling for OpAll/OpAny and relational instructions. Add
return type to name of function which corresponds to
OpImageQuerySizeLod/OpImageQuerySize instructions.
> Fix names of some instructions in SPIR-V friendly IR

- .github/workflows/check-code-style.yml
I noticed in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/879 that the code style check also runs on .cl test files, which doesn't seem desirable.
> [CI] Only check code style in include/ and lib/

- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/OpenCL/sub_group_mask.cl
BuiltIn Decorations have their own Enabling Capabilities, so report
those capabilities when emitting a BuiltIn Decoration.
> Set capabilities for BuiltIn Decorations

- lib/SPIRV/SPIRVToOCL.cpp
- test/transcoding/sub_group_ballot.ll
Various SPIR-V subgroup operations return a boolean value, whereas the
equivalent OpenCL builtins return a zero or non-zero integer value.
Until now, the SPIR-V to OpenCL conversion would yield a truncate to
convert from integer to boolean, which is incorrect because any
non-zero integer value should be treated as a "true" value.  Use a
compare for the conversion instead.
Also rename the helper function to reflect better what it does and add
some comments.
> Do not truncate subgroup return value

- .github/workflows/check-in-tree-build.yml
- README.md
The LLVM project is renaming the "master" branch to "main" [1].
Update the CI configuration and README for this change.
[1] https://foundation.llvm.org/docs/branch-rename/
> Switch to LLVM main branch

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/X86/debug-info-access.ll
- test/DebugInfo/X86/dwarf-public-names.ll
This commit fixes two issues:
1. FlagIsProtected and FlagIsPrivate had wrong values.
2. Set access flags for class/struct/union members which don't have sccess
flags set in input LLVM IR, because Clang "optimized" them out in case the
flags match with default access specifier of the containing type.
This change also required adjustment of LIT tests to reflect the fact that
now in DWARF we emit DW_AT_accessibility attribute even for members with
deafult access specifier.
> Fix access specifiers in debug info

- .github/workflows/check-out-of-tree-build.yml
- lib/SPIRV/SPIRVWriter.cpp
Ensure build warnings are not left unnoticed in CI builds.  Only do
this for out of tree builds, such that any warnings from compiling
LLVM sources are not breaking the build unnecessarily.
Fix some unused variable warnings in release builds.
> Treat warnings as errors in out of tree CI builds

- lib/SPIRV/SPIRVLowerBool.cpp
- test/uitofp-with-bool.ll
The method did not handle correctly the case where operand of UIToFPInst instruction is vector. This patch fixes it.
> Fix visitUIToFPInst method in SPIRVLowerBool

- test/DebugInfo/X86/dbg-value-location.ll
After recent changes in LLVM, debug info for this test changed for
Windows triple and caused test fail on Windows. Debug info can be
represented in several ways, it may depend on the triple. This test was
originally made for x86_64-apple-darwin10.0.0 triple, so this patch sets
this triple permanently.
> Fix LLVM-SPIRV::dbg-value-location.ll test

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/AtomicCompareExchange.ll
Previous implementation optimized produced code assuming a particular
pattern in input LLVM IR. But that assumption is not always correct.
Now we always insert extra instructions to preserve semantics of cmpxchg.
Those extra instruction can be optimized later.
> Fix translation of cmpxchg instruction

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
- test/fast-composit-entry.ll
SPV_INTEL_fast_composite extension specification separated some
decorations and execution modes from SPV_INTEL_vector_compute
Spec can be found here: intel/llvm#2882
Original PR to master: #860
> [Backport][branch 80] Update translator for new Fast Composite extension

- test/DebugInfo/X86/static_member_array.ll
This patch fixes static_member_array.ll test which fails on Windows. The
reason why it failed is the missing a-f letters in hex number from regex
in test.
> Fix test/DebugInfo/X86/static_member_array.ll

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVLLVMUtil.h
- test/llvm.is.constant.ll
This might be not the best level of support for the intrinsic, as further optimizations could help to get more precise results (i.e. constant propagation, inlining, etc.), but at the same time it should be good enough to preserve functionality of modules containing `@llvm.is.constant` intrinsic.
The issue were reported in intel/llvm#2122 and can be reproduced by compiling SYCL app with C++ headers from GCC9 (they contain calls to `__builtin_constant_p` which produces `@llvm.is.constant` intrinsic)
> Support llvm.is.constant

- include/LLVMSPIRVOpts.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/transcoding/AllowIntrinsics.ll
- test/transcoding/SPV_INTEL_vector_compute/decoration_byte_offset.ll
- test/transcoding/SPV_INTEL_vector_compute/decoration_simt_call.ll
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
- test/transcoding/SPV_INTEL_vector_compute/decoration_volatile.ll
- test/transcoding/SPV_INTEL_vector_compute/extension_vector_compute_stability.ll
- tools/llvm-spirv/llvm-spirv.cpp
Previously, enabling the option would let all intrinsics through
the translator. From now on, the option can be configured so
that only specific intrinsic calls with the given prefix are
allowed, while those not matching the prefix will result in an
error as if no option was given.
The allowed intrinsic prefixes are fed into the option as a
comma-separated list, akin to `--spirv-ext`. The list can also
be left unspecified, which, as before, will accept all intrinsic
calls into SPIR-V.
One of the relevant use cases involves llvm.genx.* intrinsics,
which stem from SYCL ESIMD code, but can also mix with common LLVM
intrinsics that stem from regular SYCL code. It would be desirable
to allow ESIMD-specific intrinsics, but still error out on other
unknown ones, To better highlight this case, …
> Accept intrinsic namings into -spirv-allow-unknown-intrinsics

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/TransOCLMD.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/callable-attribute-decoration.ll
- test/fast-composit-entry.ll
SPV_INTEL_fast_composite extension specification separated some
decorations and execution modes from SPV_INTEL_vector_compute
Spec can be found here: https://github.com/intel/llvm/pull/2882
Original PR to master: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/860
> [Backport][branch 70] Update translator for new Fast Composite extension

- .travis.yml
- README.md
We have GitHub Actions configured and there is no need to use two CI
systems at the same time.
The .travis.yml config file is not removed completed yet as we haven't
swithed to use GitHub Actions on release branches - this file will be
kept as some kind of reference for now.
> [NFC] Disable Travis CI on master branch

- lib/SPIRV/libSPIRV/SPIRVType.cpp
Fix two instances of:
```
warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
```
> Fix -Wignored-qualifiers warnings

- test/DebugInfo/X86/dwarf-pubnames-split.ll
Update for LLVM commit d39bc36b1be7 ("[debug-info] refactor
emitDwarfUnitLength", 2021-02-25).
> Update DebugInfo test after LLVM change

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/transcoding/capability-arbitrary-precision-floating-point.ll
Add processing of a new parameter To/FromSign that specifies if integer value
to cast to/from is signed or not for ArbitraryFloatCastTo/FromInt functions.
See spec update (intel/llvm#1934): https://github.com/intel/llvm/blob/ea96f3ccee007e04074af6e275dbfce4fce13717/sycl/doc/extensions/SPIRV/SPV_INTEL_arbitrary_precision_floating_point.asciidoc
> [SYCL][FPGA] Update ArbitraryFloatCastTo/FromInt processing

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/OpSource.spt
According to specification, OpSource has no semantic impact and can safely be removed from a module. Therefore, such a strict check is not required.
> Remove language check assert

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
The uniqued node could have a different address.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>
> [DbgTran] Fix wrong usage of replaceTemporary

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- test/DebugInfo/DebugInfoChecksum.ll
This is a workaround to keep CodeView checksum information throughout the
translation. The idea is to store checksum kind and value to Ops[TextIdx]
and then parse this string while creating DIFile.
> [SPIRV] Encode CodeView checksum information in SPIR-V

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/Generic/typedef-arr-size.ll
SPIRV translator does not process have the facilities to
preserve the size specified in the DICompositeType node for DW_TAG_array_type.
Instead, it relies on the size of the underlying base type to calculate the
intended size. In cases when the underlying base type is typedef - this size
can`t be restored. This commit introduces a way to recursively traverse the
definition of the base type to restore the original size
> Try to derive the size of vectors when translating DICompositeType

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/Generic/typedef-arr-size.ll
SPIRV translator does not have the facilities to preserve the size specified
in the DICompositeType node for DW_TAG_array_type.  Instead, it relies on the
size of the underlying base type to calculate the intended size. In
cases when the underlying base type is typedef - this size can`t be
restored. This commit introduces a way to recursively traverse the
definition of the base type to restore the original size
> [Backport] Try to derive the size of vectors when translating DICompositeType

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- test/OpenCL.std/vload_half.spvasm
- test/OpenCL.std/vload_halfn.spvasm
- test/OpenCL.std/vloada_halfn.spvasm
- test/OpenCL.std/vloadn.spvasm
This change respects the following statement in SPIRVRepresentationInLLVM.rst:
```
"OpenCL Extended Builtin Vector Load Function Names
The unmangled names of OpenCL extended vector load functions follow the convention:
__spirv_ocl_{VectorLoadOpCodeName}__R{ReturnType}
where
{VectorLoadOpCodeName} = vloadn|vload_half|vload_halfn|vloada_halfn"
```
>  Fix emission of SPIR-V friendly IR for vload/vload_half/vload_halfn/vloada_halfn OpenCL EIS instructions

- lib/SPIRV/SPIRVWriter.cpp
It's already handled in SPIRVEnum.h.
> [NFC] Remove unnecessary addCapability calls for decorations

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/OpGroupAsyncCopy.ll
These instructions were translated directly to OCL even if SPIR-V
friendly LLVM IR was requested.
> Fix SPIR-V friendly IR for OpGroupAsyncCopy and OpGroupWaitEvents

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/OpenCL/mem_fence.cl
This PR fixes the memory scope and memory order for legacy atomics and memory fences.
Fixes #934.
> fix legacy atomic and memory fence memory order and scope

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/DebugInfo/X86/convert-debugloc.ll
- test/DebugInfo/expr-opcode.ll
- tools/llvm-spirv/llvm-spirv.cpp
Experimental support of extra DWARF operations
As this functionality is not documented by any formal SPIR-V extension or SPIR-V
extended instruction set specification, it is disabled by default and in order
to enable generation of extra debug information, user needs to pass
`spirv-allow-extra-diexpressions` command line option to the
translator.
> [Backport] Support missing DWARF opcodes on llvm_release_80 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/SampledImage.cl
These instructions were translated directly to OCL even if SPIR-V
friendly LLVM IR was requested.
> Fix SPIRV friendly IR for OpImageSampleExplicitLod&OpSampledImage

- CMakeLists.txt
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVUtil.h
MERGE WITHOUT SQUASHING
1. Fix Fix uninitialized variables warnings, which come into place after importing HandleLLVMOptions
2. Import HandleLLVMOptions to main CMakeLists.txt to propagate configuration flags. In particular, this enables Multi-threaded option in MSVC (instead of Multi-threaded DLL)
> Add HandleLLVMOptions to main CMakeLists.txt

- lib/SPIRV/SPIRVWriter.cpp
Fix the build after LLVM commit `0a92aff721f4 ("Replace uses of
std::iterator with explicit using", 2021-04-12)`.
> Update for LLVM iterator change

- lib/SPIRV/SPIRVWriter.cpp
According to https://llvm.org/docs/LangRef.html aliasing metadata
must have following layout:
List { MD Node Scope1, (other scopes) ... }
Scope1 { MD Node Scope1, MD Node Domain1, (optional MD String) }
... (other scopes)
Domain1 { MD Node Domain1, (optional MD String) }
... (other domains)
and this pattern is actually being checked in LLVM's
ScopedNoAliasAA.cpp.
But in a harsh reality LLVM opt have bugs, which can result in this
pattern violation. So lets be more tolerant to the input IR module.
> Tolerate more inputs during alias.scope/noalias MD translation

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/IntelFPGAMemoryAttributes.ll
var.annotation shall be emitted, but instead the translator was
generating ptr.annotation. It was happening due to incorrect assumption,
that for attributed static memory variable decoration shall be applied
to alloca instruction, whilst in the reality the alloca instruction
might be hidden by several cast instructions.
> Fix incorrect translation of FPGA decoration on arrays

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/TransTypeCompositeCaseClass_.ll
This is a workaround to fix an error caused by DIBuilder which always creates
a node with the DW_TAG_struct_type tag for both class and structure.
> Fix transTypeComposite bug

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/FortranArray.ll
Handle the case when Count of Fortran metadata variables is an array
> Fix llvm-spirv crash when count of Fortran metadata variables is an array

- lib/SPIRV/SPIRVUtil.cpp
Warning message:
private field 'RetTy' is not used [-Werror,-Wunused-private-field]
Signed-off-by: Pavel V Chupin <pavel.v.chupin@intel.com>
> Fix warning when build by clang

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- test/DebugInfo/DebugInfoLexicalBlockDependency.ll
This resolves the parent scope dependency issue of lexical blocks.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>
> [DbgTran] Translate subprogram debug info before scopes

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/group-decorate.spt
The NoWrite SPIR-V function parameter provides an assurance that memory pointed to by a NoWrite pointer
will not be modified through that pointer.
The const qualifier (represented in LLVM IR for kernel functions using kernel_arg_type_qual metadata) does
not provide any such guarantee. There is nothing that prevents a function that takes a pointer to a const
pointee from stripping the const pointer away and modifying the pointee.
As such, it is not appropriate to translate from one to the other, and so the code for doing so should be
removed, so that this translation is not performed either when translating from LLVM IR to SPIR-V, or
when translating from SPIR-V to LLVM IR.
> Remove mapping of NoWrite function parameter attribute on qual metadata

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/builtin_vars_arithmetics.ll
These functions will definitely return result, so lets annotate
them with the attribute during reverse translation.
Also, in https://reviews.llvm.org/D96993 behavior of DCE pass was
changed. Now it doesn't remove non-willreturn calls. So for example
in a case when user called get_global_id(dimidx) several times -
redundant calls without 'willreturn' attribute won't be eliminated.
> Add 'willreturn' attribute to OpenCL work-item functions

- .github/workflows/check-code-style.yml
- .github/workflows/check-in-tree-build.yml
- .github/workflows/check-out-of-tree-build.yml
Changed `xml` -> `yml` to avoid launching some workflows on unrelated
changes, like we don't need to launch out-of-tree build if the only
changed file in the PR is in-tree build configuration.
> [GitHub Actions] Fix paths-ignore

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/transcoding/ForwardPtr.ll
- test/transcoding/RecursiveType.ll
- test/transcoding/SPV_INTEL_function_pointers/fp-in-recusive-type.ll
In some cases the current implementation doesn't create forward pointers
when they are required. New approach is to create forward pointers
during sorting the type instructions.
TODO:
> Redesign handling of forward pointers

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
Adding a destructor and a special class field to account for getAsInstruction instruction.
Per LLVM documentation, getAsInstruction doesn't attach the result to any Module/Function/Basic Block and therefore it is not deleted as part of their destructors; basically, any pointers to this memory are lost at the end of corresponding if scopes.
reproduce memory leak on transcoding/PipeStorage.ll test 
valgrind report without patch:
>==5395== Command: llvm-spirv PipeStorage.bc -spirv-text
==5395==
==5395==
==5395== HEAP SUMMARY:
==5395==     in use at exit: 89,374 bytes in 268 blocks
==5395==   total heap usage: 7,784 allocs, 7,516 frees, 644,989 bytes allocated
==5395==
==5395== 96 bytes in 1 blocks are definitely lost in loss record 226 …
> Fix memory leak after getAsInstruction

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/transcoding/clk_event_t.cl
This instruction was translated directly to OCL even if SPIR-V
friendly LLVM IR was requested.
> Fix SPIR-V friendly IR for event opcodes

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVIsValidEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/optnone.ll
This extension adds new Function Control mask value to request to not
optimize the corresponding function. It supposed to work as analog of
`optnone` function attribute in LLVM IR.
The spec can be found under https://github.com/intel/llvm/pull/3198
> [Backport] Implement SPV_INTEL_optnone extension on llvm_release_80 branch

- lib/SPIRV/SPIRVReader.cpp
Attempting to read past EOF may set both the `eofbit` and the
`failbit`, neither of which should be fatal in this case.  This could
cause test/OpSpecConstant.spvasm to fail spuriously.
> Only fail getSpecConstInfo if badbit is set

- lib/SPIRV/OCLUtil.h
`std::memory_order` used in this file is defined in `<atomic>`, which was
not included directly.  This fixes the build for some setups that do not include
`<atomic>` transitively somehow.
> Add missing atomic include

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
This is a patch to fix failure, caused by bringing as argument of ParseChecksum
StringRef with non-zero length, but with empty data.
> Fix for ParseChecksum function

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/PipeStorage.ll
- test/transcoding/PipeStorageIOINTEL.ll
- test/transcoding/SPV_INTEL_function_pointers/gv-func-ptr.ll
When some global variable contains constant function pointer to a
function and this global variable is referenced from the pointed
function, translation crashed because intializer for global variable was
translated before mapping of OpVariable to LLVM value. It happened
because during translation of initializer in such case the original
variable was met for the second time, but it wasn't mapped to a proper
llvm value.
> Map OpVariable to LLVM value before initializer translation

- lib/SPIRV/SPIRVLowerMemmove.cpp
- test/negative/memmove.with.phinode.src.ll
This is a patch to describe a failure in visitMemMoveInst function caused by
using it with PHINode as source.
> Add error generation when using memmove pass with PHINode as source

- lib/SPIRV/SPIRVWriter.cpp
- test/pointer_type_mapping.ll
There is a map used during forward translation. It links LLVM type
and SPIR-V type, that is being generated, LLVM type here is used as
a key. Due to a bug in type mapping (information is below), it's
possible that for a single pointer type in LLVM, the translator
will create 2 physically-indentical SPIR-V pointer types and with
previous implementation of mapType function the map would be changed
during the second type insertion. This patch prevents it, forcing
to reuse the type that was created first, though we would still have
an unused duplication of this type in SPIR-V module.
Please consider following LLVM IR sample:
%struct._ZTS4Args.Args = type { %struct._ZTS6Object.Object addrspace(4)* }
%struct._ZTS6Object.Object = type { i32 (%struct._ZTS6Object.Object addrspace(4)*, i32)* }
Here …
> [SPIR-V] Stop re-writing SPIR-V type map

- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/transcoding/AtomicFAddEXT.ll
- test/transcoding/AtomicFMaxEXT.ll
- test/transcoding/AtomicFMinEXT.ll
In backwards translation, we look to treat FP-typed atomic functions
from multi-vendor extensions similarly to "regular" atomics.
> Lower atomic FP __spirv builtins into OpenCL 1.2 builtins

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- lib/SPIRV/libSPIRV/spirv_internal.hpp
This is being done as one of the migration steps to downloading
spirv.hpp from SPIR-V Registry during the build time.
> Move SPV_INTEL_fast_composite tokens into internal:: namespace

- test/DebugInfo/DebugDeclareUnused.cl
After LLVM commit 333987b04589 ("[OpenCL] Add DWARF address spaces
mapping for SPIR", 2021-06-04), the address space is now part of the
debug info.  Update the pattern to accommodate it.
> Update DebugInfo test for LLVM address space change

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
`OpFMod` and `OpSMod` were implemented using a separate class, but
seemingly without an underlying motivation.  Instead of a separate
class, reuse the `SPIRVBinaryInst` class to unify `OpFMod` and `OpSMod`
handling with other binary instructions.
This change enables supporting FMod and SMod operators with
`OpSpecConstantOp`, which will be done in a future commit.
> [NFC] Use SPIRVBinaryInst for OpFMod and OpSMod

- lib/SPIRV/SPIRVWriter.cpp
- test/pointer_type_mapping.ll
It's a follow up change for https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1047
> Change return value of mapType function

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoChecksumCompileUnit.ll
It's a patch to fix ignoring of checksum info when translating compile unit.
The issue is _transCompileUnit()_ creating _CompileUnit_, using _getDIFile()_
insted of _getFile()_ thereby bypassing _ParseChecksum_
> Fix translating of compile unit

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/pointer_type_mapping.ll
- test/transcoding/ForwardPtr.ll
Current implementation creates forward pointer only if direct pointee
was already discovered during type traversal. But it is possible to have a
cyclic dependency when pointer points to already discovered type via multiple
intermediate types.
Modified algorithm tracks cyclic dependency case via return value of the
recursive algorithm.
> [SPIR-V] Fix duplicate pointers

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- test/SpecConstants/specconstantop-init.spvasm
This is a continuation of #1037 to improve OpSpecConstantOp handling.
This revealed that OpINotEqual was missing from
isSpecConstantOpAllowedOp.
Use an IRBuilder to get automatic folding where possible.
Co-authored-by: @StuartDBrady 
Rely on the IRBuilder to fold into constant expressions if possible.
> Improve OpSpecConstantOp handling for unary and integer comparison operators

- .github/workflows/check-code-style.yml
Using a different LLVM version to obtain the compile commands may
cause inclusion of compiler flags that aren't recognized by
the older version of clang-tidy.
> [CI] Align clang-tidy/format versions to LLVM version

- lib/SPIRV/SPIRVLowerMemmove.cpp
- test/llvm-intrinsics/dynamic-memmove.ll
Use LLVM `expandMemMoveAsLoop` function in case memmove intrinsic use has
non-constant length.
> Implement support for dynamic memmove

- lib/SPIRV/SPIRVWriter.cpp
- test/spec_const_decoration.ll
If a phi instruction uses result of __spirv_SpecConst() call which has
not been translated yet, we created a OpForward instruction. Then we
translated the call to OpSpecConstant and attached the SpecId decoration
to it. After that, when we map LLVM value to SPIR-V values we detected
that there is a OpForward instruction and replaced Id of OpSpecConstant
with Id of the OpForward instruction, leaving the decoration targeted to
non-existing instruction.
To avoid this incorrect behaviour we should attach decorations after
replacing OpForward instruction, i.e. in transDecoration method.
> Fix attachment of decoration to spec constants

- lib/SPIRV/SPIRVReader.cpp
- test/SpecConstants/specconstantop-init.spvasm
This is a continuation of #1050 to improve OpSpecConstantOp handling.
- Handle OpSpecConstantOp with SMod
- Add tests for SConvert, UConvert, BitCast OpSpecConstantOp, which do not need any further implementation work.
> Improve OpSpecConstantOp handling and testing for SMod, SConvert, UConvert, BitCast

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/SpecConstants/specconstantop-init.spvasm
- test/transcoding/spec_const.ll
- test/uitofp-with-bool.ll
`OpSpecConstantOp` may be used outside of a basic block (for example
in a variable initializer).  Modify the `SPIRVSelect` constructor to
accept a `nullptr` basic block.
Use an IRBuilder when translating `OpSelect`, so that the resulting
select expression will be created as a constant expression (and
possibly constant-folded) where possible.
Update some tests as the SPIR-V to LLVM translation now folds selects
more aggressively due to the use of IRBuilder.
> Handle OpSpecConstantOp for Select

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- test/SpecConstants/specconstantop-init.spvasm
- test/opundef.spt
This is (hopefully) the last PR in a series to improve `OpSpecConstantOp`
handling with integer operators.
Modify the constructors to allow passing a `nullptr` basic block (as is
the case for variable initializers).
Modify the constructors to take `SPIRVId`s instead of `SPIRVValue`s,
which better reflects what is stored in the class, and saves us an
unnecessary ID-to-Value-to-ID round trip in
`createInstFromSpecConstantOp`.
Use an IRBuilder when translating, so that the resulting
expression will be created as a constant expression (and
possibly constant-folded) where possible.
Modify `test/opundef.spt` to return the constructed value, so that it
does not get optimized out.
> Handle OpSpecConstantOp with VectorShuffle, CompositeExtract, and CompositeInsert

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- test/complex-constexpr.ll
When some constant expression is used as operand of regular instruction
and operand of other constant expression, the current algorithm of
lowering could produce incorrect order of instructions because it is not
possible to add instruction operand to a constant expression. Consider
following pseudo code example:
```
call foo(constexpr2(constexpr1), constexpr1)
// After first loop iteration through operands of the call instruction:
A = constexpr2(constexpr1)
call foo(A, constexpr1)
// Ok, instruction A is now a user of constexpr1, so, when second
// operand is processed, all uses of constexpr1 are updated, but the
// instruction that represents constexpr1 is inserted before call
// instruction because it is now being processed, so it will look like
// this:
A = constexpr2(B)
B = constexpr1 …
```
> Fix handling of complex constant expressions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- tools/llvm-spirv/llvm-spirv.cpp
Update for LLVM commit 3302af9d4c39 ("Support: Remove
F_{None,Text,Append} compatibility synonyms, NFC", 2021-06-15).
> Update for sys::fs::OpenFlags LLVM API change

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/LoopUnroll.ll
There were 3 assumptions made during translation of llvm.loop metadata
into LoopMerge instruction:
1. A latch block for 'for' and 'while' loop ends with a unconditional
branch instruction;
2. A latch block for 'do-while' loop ends with a conditional branch
instruction;
3. For a 'conditional' latch basic block it assumes, that the first
successor is the loop header and the second one is the exit block.
All three of them can be violated in a case of an optimized IR is passed
to the translator. In this case LoopMerge:
a. can be placed in a wrong basic block;
b. have continue target and merge block parameters sharing the same id.
This patch makes the translator to assume less and do more checks via
LLVM LoopInfo infrustructure.
> Replace assumptions during llvm.loop translation with checks

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopAttr.ll
There are 3 metadata, which map on `LoopControlLoopCountINTELMask` . Mask has 3 parameters. Default values are `-1`.
> Implemented SPIR-V support for loopcount attributes

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/X86/sycl-vec-3.ll
The SYCL/OpenCL specifications require that 3-element vectors
are sized equally to the 4-element ones (see 4.10.2.1 and 4.10.2.6,
[khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf](https://www.khronos.org/registry/SYCL/specs/sycl-1.2.1.pdf)). Meanwhile, the
logic for translating SPIR-V debug info into LLVM IR obeys a
trivial `vec_size = num_elems * elem_size` formula, which fails
for the 3-element edge case.
Example LLVM IR pre-translation:
```
!0 = !DICompositeType(tag: DW_TAG_array_type, baseType: !3, size: 128, flags: DIFlagVector, elements: !1)
!1 = !{!2}
!2 = !DISubrange(count: 3)
!3 = !DIBasicType(name: "int", size: 32, align: 32, encoding: DW_ATE_signed)
```
Faulty LLVM IR after bi-directional translation (note the size in `!0`):
```
!0 = !DICompositeType(tag: DW_TAG_array_type, …
```
> Fix SYCL/OpenCL vector size in DebugInfo reverse translation

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/SPV_INTEL_memory_access_aliasing/intel-alias-load-store.ll
- test/transcoding/SPV_INTEL_memory_access_aliasing/intel-alias-masked-load-store.ll
It should be a valid case if alias.scope and noalias mask/decoration
be applied to the same instruction.
The appropriate spec change:
https://github.com/intel/llvm/pull/3426/commits/96cc162703768714cd7e7212c07b19e56f515b2a
> Remove alias.scope/noalias exclusive restriction

- lib/SPIRV/libSPIRV/SPIRVModule.cpp
There was memory leak in function `TopologicalSort::visit`. This patch fixes it.
@AlexeySotkin, @svenvh could you please review this fix?
> Fix TopologicalSort memory leak

- lib/SPIRV/SPIRVReader.cpp
This refactoring phase comes down to moving the translation algorithm
out of the already-cluttered `SPIRVToLLVM::setLLVMLoopMetadata()` body.
For now, a static member-only class is employed: it provides encapsulation
for helper functions while avoiding the unnecessary complexity that "true"
class entities would bring. A simple `LoopsEmitted` set is used to guard
against duplication of metadata for a particular loop by the callers.
> [RFC] Improve code for IVDep backwards translation

- lib/SPIRV/OCLUtil.h
Since there's a dedicated `// Enums` section in the `OCLUtil.h` header,
move the enum definition there.
> [NFC] Move FPGA memory access enum definition

- lib/SPIRV/SPIRVReader.cpp
- test/builtin-vars-gep.ll
Some LLVM optimizations started generation of ascast -> gep -> load
sequence, this patch adds support for it.
> Add support of new IR pattern to transOCLBuiltinFromVariable

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/SPV_INTEL_memory_access_aliasing/intel-alias-lifetime.ll
The correct translation of this case will be done later, once the spec
is updated.
> Fix a crash when alias metadata is attached to a call to lifetime inrinsic

- .github/workflows/check-code-style.yml
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/transcoding/ForwardPtr.ll
- test/transcoding/RecursiveType.ll
- test/transcoding/SPV_INTEL_function_pointers/fp-in-recusive-type.ll
The type of a function parameter may be id of a forward declared pointer type.
When we decode such module, we can't construct SPIRVTypeFunction, because
actual SPIRVTypePointer has not been decoded yet. Instead we can keep ids of
paramter types which can be resolved later.
> [Backport] Replace type pointers by ids in SPIRVTypeFunction on llvm_release_100 branch

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
The type of a function parameter may be id of a forward declared pointer type.
When we decode such module, we can't construct SPIRVTypeFunction, because
actual SPIRVTypePointer has not been decoded yet. Instead we can keep ids of
paramter types which can be resolved later.
> [Backport] Replace type pointers by ids in SPIRVTypeFunction on llvm_release_90 branch

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/builtin-get-global-id.ll
debug info of work-item builtins are lost in both llvm IR -> spirv and
spirv -> llvm IR translations. See #744
This is backport of c734c5c8bbd3012a09c610e4be68e90cc603c580.
> [Backport 100] Fix debug info of work-item builtin translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/BitReversePref.ll
User may get their function a name the same as SPIR-V instruction.
In that case thier function call will be translated to SPIR-V instruction call.
The only functions that should be translated to SPIR-V instructions are SPIR-V built-ins
and they should have __spirv prefix.
Add checking for __spirv prefix in demangler to filter SPIR-V built-ins from other function calls.
This is backport of dd7e3d4ae31a6205b6045070ec46d37803d7c083 to llvm_release_80 branch.
> [Backport 80] Fix translation of user functions into SPIR-V instructions

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- lib/SPIRV/libSPIRV/spirv_internal.hpp
Bring spirv.hpp in sync with `ddf3230 ("Merge pull request #222 from
kpet/github-actions", 2021-06-30)` from
github.com/KhronosGroup/SPIRV-Headers .
This brings the `SPV_KHR_bit_instructions` and `SPV_INTEL_debug_module`
extension enum values.  Drop the internal enum value of the latter.
> [NFC] Sync spirv.hpp and regenerate SPIRVNameMapEnum.h

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
Enable using of CreateInBounds with element type due to deprecate
GetElementPtrInst::CreateInBounds without element type.
> Fix using of deprecated CreateInBounds

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
Make the following classes inherit from SPIRVInstTemplateBase:
- SPIRVSelect
- SPIRVVectorShuffle
- SPIRVCompositeExtract
- SPIRVCompositeInsert
This allows removing a switch on opcode in SPIRVInstruction.cpp.
With SPIRVSelect inheriting from SPIRVInstTemplateBase, an
OpSelect case in SPIRVWriter.cpp can now be handled through
the switch default.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1072
> [NFC] Remove switch on opcode by inheriting from SPIRVInstTemplateBase

- lib/SPIRV/SPIRVReader.cpp
Due to Windows-specific sporadic translation failures, revert until
root cause is identified.
This reverts commit 348d3cf97c121cab056331470cf761bad056c03c.
> Revert "[RFC] Improve code for IVDep backwards translation (#1084)"

- lib/SPIRV/SPIRVReader.cpp
Update for LLVM commit b00cff56cfb1 ("Reapply [IR] Don't accept
nullptr as GEP element type", 2021-07-09).
> Update for LLVM GEP API change

- lib/SPIRV/SPIRVReader.cpp
After LLVM commit 5d1464cbfe90 ("[Attributes] Make type attribute
handling more generic (NFCI)", 2021-07-12), the Attribute constructor
became stricter.  This revealed that the translator was creating
`readonly` attributes with a type attached, tripping the newly added
assertion in `Attribute::get`.
> Fix readonly attribute after new LLVM assertion

- include/LLVMSPIRVOpts.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- test/kernel-arg-ext_int-ptr.spt
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/cl-types.ll
- test/transcoding/kernel_arg_name.ll
- test/transcoding/kernel_arg_type_qual.ll
- test/transcoding/spirv-types.ll
- tools/llvm-spirv/llvm-spirv.cpp
Since constant qualifier stored in the metadata is no longer mapped
on NoWrite function parameter attribute we need a another way to
save information about it. As work around this patch stores argument
qualifier information in OpString under
'preserve-ocl-kernel-arg-type-metadata-through-string' option. This
option should be also passed during reversed translation to obtain
the metadata.
This patch also moves already existing workaround for kernel_arg_type
metadata under the option.
> Add W/A to translate OpenCL kernel_arg_type_qual metadata

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_memory_access_aliasing/intel-alias-empty-md.ll
Otherwise we might face an assert in case if empty metadata was generated by LLVM opt.
> Don't add aliasing MemAccess mask if metadata translation failed

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/libSPIRV/SPIRV.debug.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/DebugInfo/SourceLanguageLLVMToSPIRV.ll
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
- test/FortranArray.ll
When translating from LLVM IR to SPIR-V, the SourceLanguage is currently 
set to the DWARF language value, which is wrong. This PR adds a mapping 
from DWARF language codes to the correct value in the SourceLanguage enum.
> Add mapping for DWARF language codes to SourceLanguage

- test/DebugInfo/X86/dbg-file-name.ll
Update after upstream commit `fada2782cf6f ("[llc] Default
MCUseDwarfDirectory to true", 2021-07-12)`.
> Update for LLVM -enable-dwarf-directory change

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/DecorationAlignment.ll
The mapping here is between LLVM's `align <2^n>` and SPIR-V's
`Alignment <2^n>` decoration.
> Translate alignment of function parameters

- test/lit.cfg.py
A KeyError gets triggered if the lit test is running in a machine which pre-installs spirv tools without setting LD_LIBRARY_PATH in env. It would be good to add a check before using.
FYI, In my case, the llvm-spirv-translator is a llvm in-tree build. And I will use "make check-llvm-spirv" or "llvm-lit *.spv" to run  thoses lit tests. I don't have a chance to test whether it will be a problem in other build methods.
> Update lit.cfg.py to avoid an error

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/GroupAndSubgroupInstructions.spvasm
- test/image.ll
- test/read_image.cl
- test/transcoding/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_generic.cl
- test/transcoding/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_types.spt
- test/transcoding/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_vme_image.cl
- test/transcoding/SampledImage.cl
- test/transcoding/check_ro_qualifier.ll
- test/transcoding/cl_intel_sub_groups.ll
- test/transcoding/get_image_num_mip_levels.ll
- test/transcoding/image_channel.ll
This change fixes SPIR-V IR generation for the following opcodes:
1) OpImageRead
2) OpImageWrite
3) OpImageQueryOrder
3) OpImageQueryFormat
4) Opcodes from SPV_INTEL_subgroups extension
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_subgroups.asciidoc
5) Opcodes from SPV_INTEL_device_side_avc_motion_estimation extension
https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_device_side_avc_motion_estimation.asciidoc
The following translation chain testing has been implemented for all these opcodes:
LLVM->SPIRV->SPV-IR->SPIRV
> Fix SPIR-V IR for opcodes operating on images

- CMakeLists.txt
7251f3cb ("Make spirv.hpp be an external dependency (#813)",
2021-07-27) introduces use of the FetchContent module, which is only
available from CMake 3.11.
We might just as well align with LLVM's cmake requirement, so bump the
requirement to CMake 3.13.4.
> Update minimum cmake version to 3.13.4

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_vars.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/builtin_vars_opt.ll
This PR fixes the translation of SPIRV builtin variables/calls. The translator
now is able to recognize builtin-call-based SPV-IR input.
e.g. call  spir_func i64 @_Z33__spirv_BuiltinGlobalInvocationIdi(i32 1)
- LLVM --> SPIRV translation:
1. We first translate OCL work item builtins to SPV-IR builtin calls in
OCLToSPIRV. For example:
@_Z13get_global_idj(i) -> @_Z33__spirv_BuiltinGlobalInvocationIdi(i)
2. SPV-IR builtin calls are transformed to variables in LLVMToSPIRV. This
step is shared by all source inputs (SPV-IR, OCL-IR). For example:
@_Z33__spirv_BuiltinGlobalInvocationIdi(i) ->
x = load GlobalInvocationId; extract x, i
- SPIRV --> LLVM translation:
1. We lower SPIRV builtin variables into calls in SPIRVToLLVM so that SPV-IR
has builtin function calls (instead of variables) by …
> [SPV-IR] Fix SPIRV builtin variable/call translation

- lib/SPIRV/SPIRVUtil.cpp
- test/customized_func_with_underscore.ll
It's possible that the underscore-delimited postfix is not empty when we
do this check in `SPIRVToOCLBase::visitCallInst`. Should return false
instead of reporting an assertion failure.
Signed-off-by: Yilong Guo <yilong.guo@intel.com>
> Fix getSPIRVBuiltin assertion failure

- test/DebugInfo/X86/convert-debugloc.ll
Update after LLVM commit `75aa3d520d53 ("Add a DIExpression
const-folder to prevent silly expressions.", 2021-08-05)`.
> Fix test for LLVM DIExpression const-folder

- docs/SPIRVRepresentationInLLVM.rst
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/BuildNDRange.ll
- test/transcoding/BuildNDRange_2.ll
It is translated to a function with unmangled name
__spirv_BuildNDRange_{1|2|3}D with struct return parameter and array
arguments, since translator only translates it properly to SPIR-V with
this signature. _ND postfix is requred because array arguments are mangled
in the same way, so if there was no postfix, translator would produce
functions with same name for different dimensions.
> Fix SPV-IR for OpBuildNDRange

- lib/SPIRV/SPIRVReader.cpp
- test/appending-linkage-type.ll
This is a workaround to fix translation of linkage type of "llvm.used" and
"llvm.compiler.used" global variables that should be "appending" instead of
"export".
> Linkage type fix for global variables translation

- docs/SPIRVRepresentationInLLVM.rst
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1133 added
full support for SPIR-V friendly IR with SPIR-V built-in variables
mapped to calls. This commit adds info to the doc about the new supported
representation.
> Update SPIR-V friendly IR doc according to recent changes

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVWriter.cpp
Fix build after LLVM commit `92ce6db9ee76 ("[NFC] Rename
AttributeList::hasFnAttribute() -> hasFnAttr()", 2021-08-13)`.
Fixes #1154 .
> Update for LLVM hasFnAttr renaming

- include/LLVMSPIRVLib.h
- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/lower-non-standard-types.ll
It is a pass to lower bitcast instructions to non-standard SPIR-V types.
It covers only known issues. At this moment there is only one pattern
that should be covered - use of vector with unsupported number of
elements. This pattern should be handled this way:
%0 = bitcast <3 x i64> addrspace(1)* @Id to <6 x i32> addrspace(1)*
%1 = addrspacecast <6 x i32> addrspace(1)* %0 to <6 x i32> addrspace(4)*
%2 = load <6 x i32>, <6 x i32> addrspace(4)* %1, align 32
%conv = extractelement <6 x i32> %2, i32 4
%conv1 = sitofp i32 %conv to float
Must be replaced by:
%0 = addrspacecast <3 x i64> addrspace(1)* @Id to  <3 x i64> addrspace(4)*
%1 = load <3 x i64>, <3 x i64> addrspace(4)* %0, align 32
%2 = extractelement <3 x i64> %1, i32 0
%conv = trunc i64 %2 to i32
%conv1 = sitofp i32 %conv to float
It is …
> Add pass to lower Bitcast to nonstandard type instructions

- lib/SPIRV/SPIRVWriter.cpp
In case spv::ExecutionModeSharedLocalMemorySizeINTEL the new SPIRVExecutionMode was not registered via SPIRVModule::add() and was leaking
> Fix leak in LLVMToSPIRV::transExecutionMode()

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/transcoding/enqueue_kernel.cl
In LLVM it is valid if addrspace cast result pointer has not only other
address space, but also other element type. However spec states that
for Storage Class changing instructions Result Type and Pointer must point
to the same type. So, this patch adds a regularization step that adds
an additional bitcast in case address space cast changes pointer element
type as well and then everything can be easily translated to valid
SPIR-V that is accepted by spirv-val.
> Fix production of OpPtrCastToGeneric instruction

- lib/SPIRV/SPIRVReader.cpp
Fix build after LLVM commit `3f4d00bc3b51 ("[NFC] More
get/removeAttribute() cleanup", 2021-08-17)`.
> Update for LLVM addRetAttr API change

- include/LLVMSPIRVLib.h
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/lower-non-standard-vec-with-ext.ll
ea7468ed318ca38c3e9454ba0d4a73ef8579fd35 introduced new pass and
together with it a check of used in bitcast vector type. This check
should respect passed extension options, since some extensions can
allow to use more types, for example SPV_INTEL_vector_compute
adds support for 1-element vectors.
> Fix support of SPV_INTEL_vector_compute extension

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- test/ignore-builtin-linkage-name.spt
The BuiltIn variable/call name in SPV-IR should stick to
"__spirv_BuiltIn*", no matter what the SPIR-V linkage name is.
This is an issue exposed by PR #1133.
> [SPV-IR] Ignore SPIR-V linkage name for BuiltIn variable

- test/lower-non-standard-types.ll
- test/lower-non-standard-vec-with-ext.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix.ll
Recent changes in the DPC++ compiler
(https://github.com/intel/llvm/pull/3929) allow to disregard the
`sycldevice` component from the target triple in command lines. From
there on, IR files for the Translator tests should be produced using
the simplified target triple. Clean up the existing tests to match
this change.
> [Test] Drop 'sycldevice' from IR modules' triple information

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/annotate_attribute.ll
https://reviews.llvm.org/D88645 introduces additional parameter
to var/ptr/global annotation instruction, which can be set by
clang::annotation attribute that has variadic constant expression
argument. Right now we can't translate it properly and an extension
is being discussed, but yet we need a W/A for this. As a W/A the
current patch makes this argument (in case if it is const int) be
translatable as a string put in UserSemantic decorations, so the
IL flow is looking like this:
Annotation in source-code:
[[clang::annotate("custom", 30, 60)]] int *Var;
LLVM IR before:
@.str = private unnamed_addr constant [7 x i8] c"custom\00"
@.args = private unnamed_addr constant { i32, i32 } { i32 30, i32 60 }
// ...
call void @llvm.var.annotation(i8* ...,
i8* getelementptr inbounds ([7 x i8], [7 x …
> Improve LLVM annotations translation to SPIR-V

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- test/GroupAndSubgroupInstructions.spvasm
- test/spirv-ocl-builtins-version.spt
There is a patch to keep convergent attr during translation of
OpControlBarrier to prevent optimization passes from making barrier calls
control-dependent.
> Add convergent attribute during reverse translation of OpControlBarrier

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/IntelFPGAMemoryAccesses.ll
- test/transcoding/IntelFPGAMemoryAttributes.ll
This is a patch to avoid duplication of global annotation strings in reverse
translation caused by the fact that translator translates each
UserSemantic decoration, even if a similar decoration with the same string
has also been translated.
> Fix duplication of global annotation strings in reverse translation

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_vector_compute/decoration_single_element_vector.ll
Handling of SingleElementVectorINTEL decoration was amended to match new state of a spec: https://github.com/intel/llvm/pull/1612.
> Amend SingleElementVectorINTEL decoration use cases according to spec update

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/capability-arbitrary-precision-fixed-point-numbers.ll
- test/transcoding/capability-arbitrary-precision-floating-point.ll
There could be cases when return type of intrinsic is greater than 64 moves return value into argument list as sret parameter.
TODO: currently sret parameter attribute is being lost during reverse translation for the mentioned case, need to fix it.
> Fix for a bunch of fixed point integer SPIR-V instructions

- lib/SPIRV/SPIRVReader.cpp
- test/transcoding/fcmp.ll
- test/transcoding/relationals_float.ll
- test/transcoding/relationals_half.ll
Instead of translating this instructions to OCL builtin calls, use core llvm
fcmp instructions for better code preservation during translation.
> Translate OpOrdered and OpUnordered to fcmp instructions

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/relationals_float.ll
- test/transcoding/relationals_half.ll
Translate `islessgreater()` to _OpFOrdNotEqual_ instead of _OpLessOrGreater_, which is deprecated as of SPIR-V 1.5 revision 2, and has identical semantics.
Translate _OpLessOrGreater_ to `fcmp one` instead of `islessgreater()`, which has identical semantics.
> Clean up translation of islessgreater() and OpLessOrGreater

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/IntelFPGAMemoryAttributes.ll
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1206 with a
change of 'AnnotatedDecoration' to 'AnnotatedCode' brought a regression,
when the annotation information started to be duplicated in both
UserSemantic decoration and FPGA-specific decorations. This patch fixes
that.
Yet if there is an annotation string that is split in blocks like Intel
FPGA annotation, it's not necessarily an FPGA annotation. Translate the
whole string as UserSemantic decoration in this case.
> Don't emit UserSemantic with full annotation str if FPGA decorations found

- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/AtomicCompareExchange_cl20.ll
- test/transcoding/atomics.spt
The semantics of _OpAtomicCompareExchangeWeak_ are the same as those of _OpAtomicCompareExchange_. Each of the ops should be translated to `atomic_compare_exchange_strong_explicit()` when using OpenCL 2.0 builtins, and not `atomic_compare_exchange_weak_explicit()`, as use of the latter may result in unreported spurious failures which are not detectable when using _OpAtomicCompareExchangeWeak_, which does not give a direct indication of its success.
> Fix mistranslation of OpAtomicCompareExchangeWeak

- lib/SPIRV/Mangler/Mangler.cpp
- test/transcoding/OpImageWrite.cl
The issue resulted in producing incorrect, clang-inconsistent function name for OpImageWrite
SPV-IR.
Before:
`_Z18__spirv_ImageWritePU3AS133__spirv_Image__void_2_0_0_0_0_0_1Dv4_iS1_`
After:
`_Z18__spirv_ImageWritePU3AS133__spirv_Image__void_2_0_0_0_0_0_1Dv4_iS2_`
Not considering user-defined type as a candidate to substitute made a sequence
id incorrect.
> Implement substitution for user-defined type in mangler

- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVError.h
- lib/SPIRV/libSPIRV/SPIRVUtil.h
- test/negative/atomicrmw-unsupported-operation.ll
- test/transcoding/SPV_INTEL_variable_length_array/negative.ll
`toString` function is called to convert an LLVM IR instruction to a string,
mostly in order to include it into an error message in case LLVM IR is invalid.
The problem is that this function is called even when IR is valid which
significantly slows translator's work.
This patch reworks `toString` usage in `checkError` method to generate a string
only in case when LLVM IR is invalid.
> [NFC] Optimize OCLUtil::toString usage in checkError function

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- test/AtomicBuiltinsFloat.ll
- test/negative/InvalidAtomicBuiltins.cl
- test/transcoding/AtomicFAddEXTForOCL.ll
- test/transcoding/AtomicFMaxEXTForOCL.ll
- test/transcoding/AtomicFMinEXTForOCL.ll
cherry-pick from master to llvm_release_130 https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1116
> Add support for cl_ext_float_atomics in SPIRVWriter (#1116)

- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- lib/SPIRV/SPIRVToOCL.cpp
Update after LLVM commit 1ea4296208e6 ("[NFC] Remove from
UnivariateLinearPolyBase::getValue().", 2021-11-04).
> Update for LLVM ElementCount API change

- .gitignore
- test/transcoding/OpenCL/mem_fence.cl
- test/transcoding/cl_khr_extended_bit_ops.cl
* Tidy up .gitignore
* Remove builtin prototypes from tests. Clang has these prototypes since 85eb12eefdf6 ("[OpenCL] Add declarations with enum/typedef args", 2021-02-24) and 724f0e2abb0c ("[OpenCL] Add cl_khr_extended_bit_ops", 2021-07-21).
> Small cleanups

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/AtomicBuiltinsFloat.ll
- test/AtomicFAddEXTForOCL.ll
- test/AtomicFAddExt.ll
- test/AtomicFMaxEXT.ll
- test/AtomicFMaxEXTForOCL.ll
- test/AtomicFMinEXT.ll
- test/AtomicFMinEXTForOCL.ll
- test/InvalidAtomicBuiltins.cl
This patch backports https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/939 and
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1116 from master to
llvm_release_100.
Note: There are gaps on some data structures, for example there are SPIRVToOCL12
and SPIRVToOCL20 class for llvm_release_120 while SPIRVToOCL12Base and
SPIRVToOCL20Base for master, but they should play same role on the branch where
they are.
Signed-off-by: haonanya <haonan.yang@intel.com>
> [Backport][100] Add support for cl_ext_float_atomics

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/libSPIRV/SPIRVOpCode.h
- test/AtomicBuiltinsFloat.ll
- test/AtomicFAddEXTForOCL.ll
- test/AtomicFAddExt.ll
- test/AtomicFMaxEXT.ll
- test/AtomicFMaxEXTForOCL.ll
- test/AtomicFMinEXT.ll
- test/AtomicFMinEXTForOCL.ll
- test/InvalidAtomicBuiltins.cl
This patch backports https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/939
and https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1116 from master
to llvm_release_90.
Note: There are gaps on some data structures, for example there are SPIRVToOCL12
and SPIRVToOCL20 class for llvm_release_120 while SPIRVToOCL12Base and
SPIRVToOCL20Base for master, but they should play same role on the branch where
they are.
Signed-off-by: haonanya <haonan.yang@intel.com>
> [Backport][90] Add support for cl_ext_float_atomics

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/capability-arbitrary-precision-fixed-point-numbers.ll
- test/transcoding/capability-arbitrary-precision-floating-point.ll
This patch changes function call after reverse translation for ap/hls instructions with result type > 64 bit
> Fix reverse translation for ap/hls instructions if result type > 64 bit

- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
There was memory leak after creating `OpInBoundsPtrAccessChain` instruction during reverse translation. This patch fixes it.
Note: `OpInBoundsPtrAccessChain` creates from `OpSpecConstantOp` with same ID, so we can't add it to `IdEntryMap`
> Fix memory leak after OpInBoundsPtrAccessChain

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spt
Without this change, the translator produces corrupted llvm for the following kernel:
```cpp
kernel void test(read_only image2d_t image, global int* out)
{
size_t gid = get_global_id(0);
const sampler_t sampler = CLK_NORMALIZED_COORDS_TRUE |
CLK_ADDRESS_REPEAT |
CLK_FILTER_NEAREST;
if(gid % 2)
{
float4 result = read_imagef( image, sampler, (int2)(0, 0));
out[0] = result.x;
}
else
{
int4 result = read_imagei( image, sampler, (int2)(1, 1));
out[0] = result.x;
}
}
```
```
$ clang-14 -cc1 -triple spir-unknown-unknown -cl-std=CL2.0 -fdeclare-opencl-builtins -finclude-default-header -emit-llvm-bc kernel.cl
$ ./llvm-spirv kernel.bc -o …
```
> Generate seperate constant sampler initializer for each use

- lib/SPIRV/SPIRVUtil.cpp
- test/spirv-triple.ll
The translator should accept LLVM modules compiled for SPIR-V triple too.
> Added support of SPIR-V triple from LLVM.

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][80] Enable transVCMetadata flow for all functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][110] Enable transVCMetadata flow for all functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][120] Enable transVCMetadata flow for all functions

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
> [Backport][130] Enable transVCMetadata flow for all functions

- CMakeLists.txt
- test/CMakeLists.txt
- test/lit.cfg.py
- test/lit.site.cfg.py.in
- test/spirv-tools-dis.ll
- tools/llvm-spirv/CMakeLists.txt
- tools/llvm-spirv/llvm-spirv.cpp
llvm-spirv's text rendering of a SPIR-V module uses an internal
non-standard format that is not compatible with any other tools.
Add support for emitting SPIR-V assembly using the more widely used
SPIR-V Tools format.  This is achieved by linking to SPIRV-Tools and
invoking its disassembler.  For now, this functionality is only
available if the SPIRV-Tools package is found at build configuration
time.
The main motivation for this change is the proposed integration of
llvm-spirv in Clang (https://reviews.llvm.org/D112404 and
https://reviews.llvm.org/D112410).  Particularly, we would like Clang invocations
such as `clang -S -target spirv` to produce the standard SPIR-V
assembly format instead of llvm-spirv's internal format.
> Add --spirv-tools-dis option to disassemble using SPIRV-Tools

- test/DebugInfo/Generic/imported-name-inlined.ll
- test/DebugInfo/X86/2011-09-26-GlobalVarContext.ll
- test/DebugInfo/X86/debug-info-access.ll
- test/DebugInfo/X86/dwarf-linkage-names.ll
- test/DebugInfo/X86/lexical-block-file-inline.ll
- test/DebugInfo/X86/linkage-name.ll
75b622a795 "Reland [DwarfDebug] Support emitting function-local
declaration for a lexical block"
and
0ac75e82f
Reland [DwarfDebug] Move emission of global vars, types and imports
to endModule()
> [NFC] Align debug tests with recent LLVM community updates

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/ldexp.cl
backport https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1300
> [Backport][130] Convert ldexp scalar arg to vector (#1300)

- lib/SPIRV/SPIRVReader.cpp
This is a fixup for aaa3cb328dfc1f56804da28ff949c7428678a00d.
> Restrict special handling of sampler OpVariable only to UniformConstant

- lib/SPIRV/SPIRVWriter.cpp
- test/spirv-load-store.ll
This patch should unlock some possibilities to manually write SPIR-V code. 
> Add SPIR-V friendly translation for OpLoad and OpStore

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spvasm
> [Backport, llvm9] Generate seperate constant sampler initializer for each use.

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spt
> [Backport, llvm10] Generate seperate constant sampler initializer for each use.

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spt
> [Backport, llvm11] Generate seperate constant sampler initializer for each use.

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spt
> [Backport, llvm12] Generate seperate constant sampler initializer for each use.

- lib/SPIRV/SPIRVReader.cpp
- test/constant-sampler-under-control-flow.spt
> [Backport, llvm13] Generate seperate constant sampler initializer for each use.

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_kernel_attributes/intel_fpga_function_attributes.ll
This patch adds translation for disable_loop_pipelining metadata with value of 0
> Modify translation for disable_loop_pipelining metadata

- lib/SPIRV/OCLUtil.cpp
- test/AtomicBuiltinsFloat.ll
This is bug fix for cl_ext_float_atomics support which will align with
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1116
> [Backport][100] Fix wrong translation for FP-typed atomic_fetch_sub

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoSubrangeUpperBound.ll
DISubrange must contain count or upperBound. Prior to this patch
translator preserved only DISubrange's count, so if there is upperBound
insted of count, the reverse translation will fail, as resulting
DISubrange will contain nothing.
> Preserve DISubrange's upperBound

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/transcoding/capability-arbitrary-precision-floating-point.ll
SPIR-V spec update: https://github.com/intel/llvm/pull/1934/commits/3155570719f642eada299ac758212766fb48c8e0.
> Add new SignOfB argument to OpArbitraryFloatPowNINTEL

- docs/SPIRVRepresentationInLLVM.rst
This commit adds documentation for two new named metadata nodes: `spirv.Decorations` and `spirv.ParameterDecorations`. These metadata nodes allow LLVM IR to directly specify SPIR-V decorations on global variable and function parameters respectively. The translator should traverse these metadata nodes and generate the corresponding SPIR-V decoration operations.
Note: The intention of this documentation change is to gather community feedback ahead of implementation.
> [docs] Add documentation for decorations metadata

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- test/ExecutionMode.ll
- test/copy_object.spt
- test/entry-point-interfaces.ll
- test/negative/unimplemented.spt
- test/right_shift.spt
- test/transcoding/PipeStorage.ll
- test/transcoding/SPV_INTEL_inline_assembly/inline_asm_clobbers.cl
- test/transcoding/SPV_INTEL_inline_assembly/inline_asm_constraints.cl
- test/transcoding/block_w_struct_return.cl
- test/transcoding/global_block.cl
This is a patch to expand the collection of entry point interfaces.
In SPIR-V 1.4 and later OpEntryPoint must list all global variables in the
interface. Also fix quoted string output in SPIRV text format.
See: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1216
> Fix the collection of entry point interfaces

- README.md
Add information into readme about the use of the translator with assembly from SPIRV-Tools.
> Document use of SPIRV-Tools with asm output

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
The signed version of createExpression was removed in
https://github.com/intel/llvm/commit/ec501f15a8b8ace2b283732740d6d65d40d82e09
> Replace signed createExpression with unsigned

- test/DebugInfo/Generic/imported-name-inlined.ll
- test/DebugInfo/X86/2011-09-26-GlobalVarContext.ll
- test/DebugInfo/X86/debug-info-access.ll
- test/DebugInfo/X86/dwarf-linkage-names.ll
- test/DebugInfo/X86/lexical-block-file-inline.ll
- test/DebugInfo/X86/linkage-name.ll
The appropriate patches were reverted in llvm.org
This reverts commit b75aff7ebf5a2ae6fcd4c594b3bc13b5a38d7494.
> Revert "[NFC] Align debug tests with recent LLVM community updates"

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_half.ll
Previously we relied on the structure type (which represented matrix
type) mangling to obtain its layout. Now, when DPCPP magling scheme is
aligned with C++, thus the structure lost their usual mangling. Yet we
want to preserve the desired information within the matrix type, coming
from DPCPP headers. To achive this the 'Matrix structure' was changed
form:
template <typename T, int R, int C, int L, int S>
struct __spirv_JointMatrixINTEL;
to
template <typename T, int R, int C, int L, int S>
struct __spirv_JointMatrixINTEL {
T (*Value)[R][C][L + 1][S + 1];
};
so it's no longer an opaque structure and now it look like this in
LLVM IR:
%struct.__spirv_JointMatrixINTEL = type { [42 x [6 x [2 x [1 x i32]]]]* }
Here we encode the number of Rows, Cols, Layout and Scope as sizes of an
array (which …
> Change matrix joint type processing

- lib/SPIRV/SPIRVToOCL.cpp
The assertions are actually not required here, since all these
functions are being called from visitCallInst, which has the
appropriate check. But for the code consistency lets do not
trust functions' inputs.
> Address some static analyzer concerns

- lib/SPIRV/SPIRVReader.cpp
Update for LLVM commit d2cc6c2d0c2f ("Use a sorted array instead
of a map to store AttrBuilder string attributes", 2022-01-10).
> Update for AttrBuilder LLVM API change

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/SPV_INTEL_device_side_avc_motion_esimation/subgroup_avc_intel_vme_image.cl
This change fixes mangling for the following opcodes:
- `OpSubgroupAvcRefEvaluateWithMultiReferenceInterlacedINTEL`
- `OpSubgroupAvcSicEvaluateWithMultiReferenceInterlacedINTEL`
Spec: https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/INTEL/SPV_INTEL_device_side_avc_motion_estimation.asciidoc
> Fix SPIR-V Friendly IR for MultiReferenceInterlaced opcodes

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- test/relationals.ll
- test/transcoding/OpAllAny.ll
- test/transcoding/relationals_double.ll
- test/transcoding/relationals_float.ll
- test/transcoding/relationals_half.ll
Move OpenCL relational builtin translation to SPIRVToOCL
Motivation is to let standalone use of SPIRVToOCL20Legacy pass support translating relational builtin in Spirv Friendly IR.
Standalones use of SPIRVToOCL20Legacy pass may receive IR in spirv friendly IR:
```
%call3.i.i.i = tail call spir_func <16 x i8> @_Z20__spirv_FOrdLessThanDv16_dS_(<16 x double> %1, <16 x double> %2)
```
Previously "Translate SPIR-V builtins to OCL 2.0 builtins (spvtoocl20)" pass will transform it into:
```
%call3.i.i.i = call spir_func <16 x i8> @_Z6islessDv16_dS_(<16 x double> %1, <16 x double> %2)
```
After this patch, the pass will transform it into:
```
%call3.i.i.i11 = call spir_func <16 x i64> @_Z6islessDv16_dS_(<16 x double> %1, <16 x double> %2) 
```
This patch also aligns relational builtin in SPIRV …
> Move OpenCL relational builtin translation to SPIRVToOCL

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
Update for LLVM commit 184591aeeb5a ("[OpaquePtrs] Deprecate
PointerType::getElementType()", 2022-01-25).
This commit changes all affected calls to getPointerElementType, which
is a temporary solution.  Followup work around the
getPointerElementType calls will be required to align with LLVM's
opaque pointer changes.
> Update for PointerType::getElementType deprecation

- lib/SPIRV/SPIRVLowerConstExpr.cpp
- lib/SPIRV/SPIRVLowerConstExpr.h
So that it could be used in downstream.
> Move SPIRVLowerConstExprPass to header file

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/spirv_global_variable_decoration.ll
- test/spirv_param_decorations.ll
- test/spirv_param_decorations_quals.ll
This patch adds translation to and from `spirv.Decorations` and `spirv.ParameterDecorations` metadata. These metadata nodes represent global variable and function parameter decorations respectively, allowing explicit decoration in LLVM IR.
Documentation: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1319
> Implements spirv.Decorations and spirv.ParameterDecorations metadata translation

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- test/DebugInfo/DebugInfoLLVMArg.ll
In the case there are more than one argument we can't represent it with
the current SPIR-V debug info spec, therefore we drop DIArgList and
DIExpression.
> Handle translattion of DIArgList with single argument

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/fence_inst.ll
This patch adds forward translation for fence instruction.
Reverse translation uses OCL builtin for OpMemoryBarrier.
Signed-off-by: Leonid Pauzin leonid.pauzin@intel.com
> Implement forward translation for llvm.fence

- test/spirv-ocl-builtins-version.spt
This has been addressed in commit 4ccb1b29 ("Add convergent attribute
during reverse translation of OpControlBarrier (#1195)", 2021-09-06) by @KornevNikita .
> Drop outdated FIXME from test; NFC

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
The original change (74759ef) introduced assertions in case `dyn_cast` returns `nullptr`.
Restore them back after being removed in 7452422.
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/74759ef334182a32fddf1defa6f3830a87ab1f2b#diff-f8b80fcd2438a87e6b6ec7219f0cd5240975c6eea3a111afa0a4e9332a01f55dR355-R356
> Restore asserts accidentally removed in 7452422

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/GlobalFunAnnotate.ll
Added support of SPIR-V -> LLVM IR translation for UserSemantic
decoration applied to functions. Having that decoration on functions
is against SPIR-V spec, but it is useful for prototyping different features:
you can easily propagate custom annotation string through SPIR-V
to see if your idea works or not without adding new code
to the translator
Signed-off-by: amochalo [anastasiya.mochalova@intel.com](mailto:anastasiya.mochalova@intel.com)
> Cherry-pick "Support UserSemantic decoration on functions (#666)" to LLVM_90

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/transcoding/GlobalFunAnnotate.ll
Added support of SPIR-V -> LLVM IR translation for UserSemantic
decoration applied to functions. Having that decoration on functions
is against SPIR-V spec, but it is useful for prototyping different features:
you can easily propagate custom annotation string through SPIR-V
to see if your idea works or not without adding new code
to the translator
> Cherry-pick of: "Support UserSemantic decoration on functions (#666)"

- lib/SPIRV/SPIRVToOCL20.cpp
The first arg of CI is not used as arg in NewCI. So its attribute should
be removed from attributes of NewCI.
For instance, before SPIRVToOCL20Legacy pass:
`
tail call spir_func void @_Z22__spirv_ControlBarrierjjj(i32 noundef 2, i32 noundef 2, i32 noundef 272)
`
after SPIRVToOCL20Legacy pass:
`
call spir_func void @_Z18work_group_barrierj12memory_scope(i32 noundef 1, i32 noundef 1)
`
NewCI's argument attributes should only contain two elements.
I'm not able to provide a lit test because currently noundef attribute is not preserved in spirv.
> Fix SPIRV -> OCL barrier call argument attributes

- lib/SPIRV/SPIRVLowerBool.cpp
- test/transcoding/dbginfo-bug-on-bool-converts.ll
SPIRVLowerBool pass silently discards line information
producing IR without !dbg nodes arrached.
This commit addresses this issue and adds test
> fixed discarding of debug info metadata by SPIRVLowerBool pass

- tools/llvm-spirv/llvm-spirv.cpp
This header is required after
commit a5bbc6ef99bbc7fcf321326df2889e063ed77004
Author: Bill Wendling <isanbard@gmail.com>
Date:   Wed Feb 23 01:20:48 2022 -0800
[NFC] Remove unnecessary "#include"s from header files
> Fix build fail after LLVM upstream change

- lib/SPIRV/SPIRVLowerBool.cpp
- test/transcoding/dbginfo-bug-on-bool-converts.ll
SPIRVLowerBool pass silently discards line information
producing IR without !dbg nodes arrached.
This commit addresses this issue and adds test
> [Backport] fixed discarding of debug info metadata by SPIRVLowerBool pass

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/spirv_param_decorations_quals.ll
* Restore `noalias` parameter attribute test check, removed in 7f168b27.
* Restore the translation of function attributes and function parameter attributes
for entry point kernels, accidentally dropped in 85815e7 "add an entry point wrapper around functions".
> Translate function attributes (incl. parameter attrs) for entry point kernels

- lib/SPIRV/SPIRVToOCL.cpp
The first argument or first two arguments are not used as arguments in
new call instruction to OCL group builtins, so the related attributes
should be removed from attributes of new call instruction.
> Fix argument attributes for SPIRV -> OCL group builtins

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- test/specconstantop-init.spvasm
Rely on the IRBuilder to fold into constant expressions if possible.
> [Backport][120] Use IRBuilder for folding

- lib/SPIRV/SPIRVWriter.cpp
This is partial cherry-pick of c3c3c68bd0438058b92abd00f0704afe1d7fb63e (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1335),
intended to enable translation of binary operators inside constant expressions.
This is done due to original commit is too complex and depends on a chain of commits that need to be backported prior to fully backporting entire commit. For a short term, I suppose it is better to partially cherry-pick to unblock some needed functionality. It can be fully backported later on.
> [Backport][120] cherry-pick for ConstExpr Binary operators

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertAsBFloat16Float_inval_scalar_signature.ll
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertAsBFloat16Float_inval_vec_elem_ty.ll
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertAsBFloat16Float_inval_vec_size.ll
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertBFloat16AsUshort_inval_scalar_signature.ll
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertBFloat16AsUshort_inval_vec_elem_ty.ll
- test/negative/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension/ConvertBFloat16AsUshort_inval_vec_size.ll
- test/transcoding/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension.ll
- test/transcoding/SPV_INTEL_bfloat16_conversion/convert_bfloat16_generic.ll
OpenCL specification: KhronosGroup/OpenCL-Docs#762
SPIR-V: https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_bfloat16_conversion.asciidoc
> [Backport] Support cl_bf16_conversions

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/annotate_attribute.ll
This patch fixes translation for annotations, when all values of annotation
are 0.
> Fix annotation translation when the value is 0

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.cpp
- lib/SPIRV/libSPIRV/SPIRVType.h
- test/transcoding/RecursiveType.ll
The use of pointer arrays inside the recursive type leads to the SPIR-V IR, where
the TypePointer is declared after TypeArray. In turn, TypeArray can't handle the
unknown element type, because the info from TypeForwardPointer is not used.
Now the translator stores forward declared IDs to use them in backward
translation. It actually means that the translator "knows" about the type but it
would be handled later.
> Support complex recursive types that use an array of pointers

- lib/SPIRV/SPIRVReader.cpp
- test/llvm-intrinsics/memset.ll
- test/transcoding/intrinsic_result_store.ll
- test/transcoding/sycl_array_zero_init.ll
The change is done in order to avoid `llvm.memcpy` -> `llvm.memset` transformation 
which can be an incorrect assumption.
Details:
SPIR-V does not have a memset instruction, there is a direct mapping only for
`llvm.memcpy` to `OpCopyMemory*`.
To handle `llvm.memset`, the input LLVM IR is lowered by `SPIRVRegularizeLLVM`
pass. The mentioned optimization tried to restore the memset instruction but it
surely does not cover all the possible cases (e.g., memcpy is not a memset inst).
Possibly, the number of follow-up fixes for different corner cases can prove
that the optimization is not absolutely correct, and it's better to rely on
regularize pass.
> Remove Bitcast -> llvm.memset optimization in reverse translation

- test/transcoding/SPV_KHR_uniform_group_instructions/group-instructions.ll
According to https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_uniform_group_instructions.asciidoc
the OpGroupLogicalAnd/Or/Xor X argument and the result type must be
scalar/vector of bool.
> Align group-instructions.ll test with the spec

- test/llvm-intrinsics/fmuladd.ll
`%break` etc are not valid substitutions for `llvm-lit`.
> Fix invalid substitutions in test

- docs/SPIRVRepresentationInLLVM.rst
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- test/transcoding/annotation_generic_decoration.ll
The SPIR-V translator currently allows LLVM IR annotation intrinsics to carry a selection of INTEL extension decorations as part of the string in its second argument. These changes expand the parsing of these to allow generic parsing of decorations in annotation strings, identifying the decorations by their SPIR-V integer identifiers rather than reserved names.
It is legal to have decorations with reserved named specified by their SPIR-V integer identifiers, but to allow backwards compatibility the reverse translation will use the reserved names for all decorations with them.
> Expand annotation-carried decoration parsing

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- test/ExtendBitBoolArg.ll
This is a patch to regularize lshr instruction with an i1 argument.
According to the SPIR-V specification OpShiftRightLogical operands
should be of integer type.
> Extend bool arg of shift operations

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
This patch changes some of getPointerElementType calls.
It's needed for opaque pointers.
> Modify getPointerElementType calls

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
There is more preparatory work needed for the SPIRVWriter, but we can already migrate the SPIRVReader.
Co-authored-by: Pedro Olsen Ferreira
> Migrate SPIRVReader to new PassManager

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/2010-10-01-crash.ll
- test/EnqueueEmptyKernel.ll
- test/llvm-intrinsics/memcpy.align.ll
- test/transcoding/BuildNDRange.ll
- test/transcoding/BuildNDRange_2.ll
The sret attribute is supposed to indicate what would be the pointee type of the
parameter (to support the transition to opaque pointers). Somehow, the original
change to this code concluded it was supposed to be a pointer type instead,
however, for the sret attribute, while the byval attribute was correctly
handled.
> Fix sret attribute to be valid LLVM IR

- .clang-tidy
The code already uses recursion in various places and this check fails
whenever a change is made in the recursion chain.
> .clang-tidy: allow recursion

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
This is the easiest tranche of changes: where the pointer element type is
usually retrieved by looking a little further afield for the element type, or
via scavenging from sret/byval parameters.
> Remove more uses of getPointerElementType (part of issue #1444).

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
This should allow for SPIR-V->LLVM conversion when compiling with opaque
pointers enabled, though this has not yet been tested.
> Replace uses of getPointerElementType in SPIRVReader.

- .github/workflows/check-out-of-tree-build.yml
LLVM commit c99424f76560 ("[IR] Deprecate
Type::getPointerElementType() (NFC)", 2022-04-20) caused out-of-tree
builds to fail (as these use `-Werror`).  Replacing all
`Type::getPointerElementType` calls is a longer term effort so turn
deprecation errors back into warnings to resume out-of-tree builds.
> [CI] Temporarily allow use of deprecated functions

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVToOCL.cpp
Most of this tranche of calls were being used to disambiguate between different
built-ins that share the same or similar names.
The exception is the change in visitCallSPIRVPipeBuiltin, which is a convoluted
way of adding a cast to i8 addrspace(4)* if not already i8 addrspace(4)*, so it
is instead rewritten to check if a cast needs to be added without querying
getPointerElementType.
> Remove more getPointerElementType queries.

- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.cpp
- test/lower-non-standard-types-opaque.ll
This is a relatively large change, as the original pass relied on being able to
track the initial bitcast <3 x i64>* to <6 x i32>* to know where to start
rewriting. Instead, this patch starts at the final invalid extractelement call
and works its way backwards as far as necessary to generate correct code.
> Make the LowerBitCast pass support opaque pointers.

- lib/SPIRV/SPIRVWriter.cpp
OCLTypeToSPIRV is an analysis required by other passes, so we don't
need to run it explicitly.
> [NFC] Avoid excess runs of OCLTypeToSPIRV

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVUtil.cpp
It seems to be another remnant of earlier versions of dealing with block types,
as it is looking for SPIR-V builtins that have function pointer arguments. With
blocks now represented as structs, it seems that nothing will trigger this code
any more. In any case, with opaque pointers, this code becomes unnecessary (as
the bitcasts that would be deleted won't exist anymore).
> Remove function pointer cast deletion in SPIRVRegularizeLLVM.

- .github/workflows/check-code-style.yml
- .github/workflows/check-out-of-tree-build.yml
LLVMExports.cmake from already installed packages references files
from the mlir-tools package.
> [CI] Fix out-of-tree build by installing mlir-tools

- test/lower-non-standard-vec-with-ext.ll
An LLVM change in the range 1f06398e96d4..80b3dcc045f8 caused this
test to fail.  XFAIL the test while investigating.
> Disable test after LLVM change

- test/lower-non-standard-vec-with-ext.ll
In https://reviews.llvm.org/D126550, report_fatal_error was changed to not use
the abort function, which means it no longer registers as a crash by the
definition of not --crash.
> Don't use not --crash to check for report_fatal_error messages.

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
The centerpiece of this patch is the addition of getParameterTypes function,
which will parse out the pointee struct types using LLVM's built-in Itanium
demangling interface (which is unfortunately not easy to use). Passing this
information along via llvm StructTypes was chosen to minimize the impact of
this change on caller code; it is likely that a future cleanup patch to use
an enum or similar mechanism to represent possible SPIR-V struct types would
be advisable.
A side effect of this change is that several helper methods that query
pointer element types can be eliminated, which does lead to some cleanup that
got tangled up in the demangler-enabling work.
Extra function calls to getPointerElementType() are temporarily added to
disentangle this patch from work moving OCLTypeToSPIRV to …
> Recover SPIR-V opaque types from demangling function names.

- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/SPIRVLowerBitCastToNonStandardType.h
- lib/SPIRV/SPIRVLowerBool.h
- lib/SPIRV/SPIRVLowerMemmove.h
- lib/SPIRV/SPIRVLowerSaddWithOverflow.h
- lib/SPIRV/SPIRVRegularizeLLVM.h
Avoid namespace pollution for any files that include these headers.  This is a followup from #1483.
> Remove 'using namespace llvm' from some headers

- lib/SPIRV/SPIRVWriter.cpp
Factor out common code, in preparation of transitioning SPIRVWriter to
the new PassManager.
> [NFC] Use only one PassManager in SPIRVWriter

- lib/SPIRV/SPIRVWriter.cpp
LLVM is removing the getAlignment method from LoadInst and StoreInst in
these commits:
* https://github.com/llvm/llvm-project/commit/8865700f905173b71932cc241b5d36600343f425
* https://github.com/llvm/llvm-project/commit/2b89a4dc51d539cefd3628775883a32c9dd6fc64
This change fixes build errors with these LLVM changes by replacing the
remaining uses of getAlignment in SPIRVWriter with getAlign.
> [NFC][Alignment] Use getAlign in SPIRVWriter

- lib/SPIRV/SPIRVWriter.cpp
Update for LLVM commit b4cf74dc9e85 ("[NFC] Remove dead code",
2022-06-14) which removed the getAlignment method.
> Update for AllocaInst::getAlignment API removal

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/lshr-constexpr.ll
This changeset is, by itself, not yet enough to get most SPIR-V files to be
emitted when the input module is in opaque pointer mode. However, this does
remove all of the calls to `getPointerElementType` that SPIRVWriter makes
(directly or indirectly), except for the ones that directly correspond to
translating a pointer type.
A later changeset will add a type scavenger that will be used to find the
pointee type of a pointer. All calls to `getPointerElementType` that remain
after this one will be instead shifted to query the type scavenger instead. To
facilitate this change, several methods are added to avoid querying pointer
element types, and they have been added in several places where their need is
known.
The most basic of basic kernels, those that do not use pointer types (other than …
> Prepare SPIRVWriter for type conversion without opaque pointers.

- lib/SPIRV/OCLTypeToSPIRV.h
Commit 4a9c78ee ("Prepare SPIRVWriter for type conversion without
opaque pointers. (#1499)", 2022-06-20) changed
`OCLTypeToSPIRVBase::AdaptedTy` to a `ValueMap`, but that made
`OCLTypeToSPIRVBase` non-movable and non-copyable.  Landing eb8e9adc
("Migrate SPIRVWriter to new PassManager", 2022-06-20) on top caused a
build breakage as it requires `OCLTypeToSPIRVPass` to be copyable.
cc: @jcranmer-intel
> Fix build by reverting a ValueMap back to std::map

- test/transcoding/SPV_KHR_integer_dot_product-sat.ll
- tools/llvm-spirv/llvm-spirv.cpp
Fix two issues related to STL usage reported in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1433
* Fix excess kernel_arg_type_qual entry in test
The metadata had 7 entries whereas the function only has 6 parameters,
causing foreachKernelArgMD to read past the end of an std::vector.
* Fix UB when validating spirv-ext option
When passing `spirv-ext=,`, SPVExt will contain empty strings.
Calling `front` on an empty string is undefined behavior, so first
ensure that the string is not empty.
> Fix 2 STL usage issues

- CMakeLists.txt
This ensures the llvm-spirv tool is added to the "all" target, so that
it is included when installing the project.
> [CMake] Enable LLVM_BUILD_TOOLS for out-of-tree builds

- .github/workflows/check-code-style.yml
Some files cannot be parsed on their own as they for example require a
macro to be defined.  To avoid spurious failures of clang-tidy,
exclude such files from the code style checks.
Remove `spirv.hpp` from the list as it is no longer in the tree.
> [CI] Exclude some files from code style checks

- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
Prepare for handling SignExtend/ZeroExtend image operands, by merging some code for handling image operands.
* [NFC] Separate image operand and LoD handling
* [NFC] Factor out mutateArgsForImageOperands
* [NFC] Restrict access to some SPIRVToOCLBase members
> [NFC] Factor out mutateArgsForImageOperands

- lib/SPIRV/libSPIRV/SPIRVDebug.cpp
- lib/SPIRV/libSPIRV/SPIRVDebug.h
- lib/SPIRV/libSPIRV/SPIRVError.h
- test/negative/invalid-int-bitwidth.ll
- test/negative/llvm-unhandled-intrinsic.ll
- test/negative/unimplemented.spt
- test/negative/unsupported-triple.ll
- test/negative/zero-length-array.ll
- test/spirv-unknown-extensions.spt
- test/spirv-version-controls-negative-1.spt
- test/spirv-version-controls-negative-2.spt
- test/spirv-version-controls.spt
- test/transcoding/NoSignedUnsignedWrap.ll
- test/transcoding/SPV_INTEL_variable_length_array/negative.ll
This backports https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/561
Signed-off-by: haonanya <haonan.yang@intel.com>
> [SPIR-V] Exchange abort() to exit() in llvm-spirv tool by default

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVErrorEnum.h
- test/spirv-triple-with-version.ll
~We cannot emit an exact version yet, so at least warn when the user
provides an LLVM module with an exact SPIR-V version specified.~
Ensure that the SPIR-V version specified as the subarch is taken into account by llvm-spirv.
> Use SPIR-V subarch version if present in triple

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertAsBFloat16Float_inval_scalar_signature.ll
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertAsBFloat16Float_inval_vec_elem_ty.ll
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertAsBFloat16Float_inval_vec_size.ll
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertBFloat16AsUshort_inval_scalar_signature.ll
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertBFloat16AsUshort_inval_vec_elem_ty.ll
- test/negative/SPV_INTEL_bfloat16_conversion/ConvertBFloat16AsUshort_inval_vec_size.ll
- test/transcoding/SPV_INTEL_bfloat16_conversion/cl_bfloat16_conversions_extension.ll
This backports https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1406
OpenCL specification: KhronosGroup/OpenCL-Docs#762
SPIR-V: https://github.com/intel/llvm/blob/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_bfloat16_conversion.asciidoc
Signed-off-by: haonanya <haonan.yang@intel.com>
> Support cl_bf16_conversions

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/read_image.cl
- test/transcoding/SampledImage.cl
- test/transcoding/image_signedness.ll
Emit (in OCLToSPIRV) and decode (in SPIRVToOCL) the SignExtend and
ZeroExtend Image Operands introduced by SPIR-V version 1.4 to preserve
signedness of image read and write operations.  This allows
distinguishing between e.g. `read_imagei` and `read_imageui` and
enables a lossless LLVM -> SPIR-V -> LLVM conversion for those OpenCL
builtins.
Before SPIR-V 1.4, there was no way to represent the signedness of the
image operations and llvm-spirv defaulted to signed.  This commit
leaves that behaviour unchanged if llvm-spirv's maximum version is set
to SPIR-V 1.3 or below.  Add the `--spirv-max-version=1.3` flag to
some tests that rely on the old behaviour.
> Use Sign/ZeroExtend image operands for read/write_image

- test/complex-constexpr-vector.ll
LLVM commit 8edb9c3c56e8 ("[ConstantExpr] Don't create float binop
expressions", 2022-07-08) caused this test to fail.  XFAIL the test to
get CI green again.
> Update test after LLVM ConstantExpr change

- tools/llvm-spirv/llvm-spirv.cpp
This option is useful for testing opaque pointers support and controled
transition of lit tests.
> Add -emit-opaque-pointers flag

- test/vector-metadata-constexpr.ll
LLVM commit 4bb7b6fae3be ("[IR] Remove support for float binop
constant expressions", 2022-07-12) caused this test to fail.
> XFAIL constantexpr test after LLVM float binop removal

- include/LLVMSPIRVLib.h
- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVUtil.cpp
This includes a rejigging of the BuiltinFuncMangleInfo to actually act as the
source of information to pass this information into.
Only some of the call sites of mangleBuiltin have been properly updated to pass
in the pointer type element information. The various mutateCallInst* callers
have yet to be updated, so those methods are temporarily relying on querying
getPointerElementType() to generate this information.
> [OpaquePtr] Pass pointer type information into mangleBuiltin.

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Fix translation of IR from source when dot function is called
with integer arguments (ints, vectors of chars or shorts)
to properly support cl_khr_integer_dot_product extension.
Previously it translated calls such as dot(uchar4, uchar4) into
OpDot %i8, which is wrong because OpDot only operates on
floating point types.
(cherry picked from commit c8cd2f6895091f84823d94a661753c0a9765a7a7)
> [Backport to 14] Fix integer dot product translation (#1174)

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVInstruction.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.h
- lib/SPIRV/libSPIRV/SPIRVValue.cpp
This avoids the need for casts at each call site.
> [NFC] Let setMinSPIRVVersion take a VersionNumber

- lib/SPIRV/SPIRVWriter.cpp
Just to make sure that uninitialized values are not used.
> [NFC] Initialize work group size variables

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Contains slight adjustments in OCL20ToSPIRV to fit older version.
> [Backport to 10] Integer dot product translation

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Contains slight adjustments in OCLToSPIRV to fit older version.
> [Backport to 13] Integer dot product translation

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Contains slight adjustments in OCLToSPIRV to fit older version.
> [Backport to 12] Integer dot product translation

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Contains slight adjustments in OCLToSPIRV to fit older version.
> [Backport to 11] Integer dot product translation

- lib/SPIRV/OCL20ToSPIRV.cpp
- lib/SPIRV/OCLUtil.h
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_char4.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_int.ll
- test/transcoding/SPV_KHR_integer_dot_product_OCLtoSPIRV_short2.ll
Contains slight adjustments in OCL20ToSPIRV to fit older version.
> [Backport to 9] Integer dot product translation

- .clang-tidy
- lib/SPIRV/libSPIRV/spirv_internal.hpp
Split the .clang-tidy check lists out over multiple lines to improve
readability.
Suppress `misc-non-private-member-variables-in-classes` as the code
currently contains many instances that fail this check.
Drop `constexpr` from `LoopControlLoopCountINTELMask` after clang
started diagnosing this with b36453530418 ("[Clang] Diagnose
ill-formed constant expression when setting ...", 2022-07-28).
Removing `constexpr` is just a workaround, the long term fix would be
to upstream the new enum value to `spirv.hpp`.
> Suppress some clang-tidy errors

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/SPV_INTEL_joint_matrix/sycl_2020_namespace.ll
In SYCL 2020 the "::cl::sycl" has been changed to "::sycl". Update SYCL
half type support to account for that.
> Support SYCL 2020 namespace (::sycl) for SYCL Half/BFloat16 types

- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
Update for LLVM commit b5f8d42efe3e ("[ADT] Deprecate
Optional::{hasValue,getValue} (NFC)", 2022-08-07).
This is a mechanical replacement of `hasValue` to `has_value` and
`getValue` to `value`.
> Update for LLVM Optional API changes

- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/SPIRVLowerMemmove.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVModule.cpp
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
- test/image-user-sampler-args.ll
Commit 4a9c78ee ("Prepare SPIRVWriter for type conversion without
opaque pointers. (#1499)", 2022-06-20) removed `getArgIndex` in favor
of passing `Idx`, but this leads to incorrect adaptation of argument
types if sampler arguments are not in the same position between
different functions.
We might be able to drop `adaptArgumentsBySamplerUse` entirely, as we
don't represent samplers as i32 anymore; but for now just fix the
regression.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1562
> Restore getArgIndex in OCLTypeToSPIRV

- lib/SPIRV/OCLTypeToSPIRV.cpp
- test/image-user-sampler-args.ll
Commit 4a9c78ee ("Prepare SPIRVWriter for type conversion without
opaque pointers. (#1499)", 2022-06-20) removed `getArgIndex` in favor
of passing `Idx`, but this leads to incorrect adaptation of argument
types if sampler arguments are not in the same position between
different functions.
We might be able to drop `adaptArgumentsBySamplerUse` entirely, as we
don't represent samplers as i32 anymore; but for now just fix the
regression.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1562
(cherry picked from commit 87f8a58252ff91a75c524362f3dd4d452872108e)
> [Backport to 15] Restore argument tracing in OCLTypeToSPIRV

- lib/SPIRV/OCLTypeToSPIRV.cpp
- test/image-user-sampler-args.ll
Commit 4a9c78ee ("Prepare SPIRVWriter for type conversion without
opaque pointers. (#1499)", 2022-06-20) removed `getArgIndex` in favor
of passing `Idx`, but this leads to incorrect adaptation of argument
types if sampler arguments are not in the same position between
different functions.
We might be able to drop `adaptArgumentsBySamplerUse` entirely, as we
don't represent samplers as i32 anymore; but for now just fix the
regression.
Fixes https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1562
(cherry picked from commit 87f8a58252ff91a75c524362f3dd4d452872108e)
> [Backport to 14] Restore argument tracing in OCLTypeToSPIRV

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
The frontend is being changed to lower the struct name to the correct LLVM name
directly, obviating the need for this check. See
https://github.com/intel/llvm/pull/6535 for this change.
This marks the removal of the final call to the deprecated method
Type::getPointerElementType, although there remains some code that is not fully
working with opaque pointers enabled.
> Drop the JointMatrixINTEL struct-renaming pass when opaque pointers are enabled.

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
This is a bugfix for my previous change ( #1174 ) regarding the integer dot product translation. 
Slightly changed the check for Dot call in OCLToSPIRV to include more floating point types, as some were omitted by mistake.
> Dot product bugfix to include more floating point types

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Slightly changed the check for Dot call in OCL20ToSPIRV to include more scalar floating point types (eg. half), as some were omitted by mistake.
> [Backport to 9] Dot product bugfix to include more floating point types

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Slightly changed the check for Dot call in OCLToSPIRV to include more scalar floating point types (e.g. half), as some were omitted by mistake.
> [Backport to 13] Dot product bugfix to include more floating point types

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Slightly changed the check for Dot call in OCLToSPIRV to include more scalar floating point types (e.g. half), as some were omitted by mistake.
> [Backport to 12] Dot product bugfix to include more floating point types

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Slightly changed the check for Dot call in OCLToSPIRV to include more scalar floating point types (e.g. half), as some were omitted by mistake.
> [Backport to 11] Dot product bugfix to include more floating point types

- lib/SPIRV/OCL20ToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Slightly changed the check for Dot call in OCL20ToSPIRV to include more scalar floating point types (e.g. half), as some were omitted by mistake.
> [Backport to 10] Dot product bugfix to include more floating point types

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/entry_point_func.ll
- test/group-decorate.ll
- test/mem2reg.cl
- test/transcoding/DecorationMaxByteOffset.ll
- test/transcoding/FPGAUnstructuredLoopAttr.ll
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/SPV_INTEL_function_pointers/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/select.ll
- test/transcoding/SampledImage.cl
- test/transcoding/decoration_media_block_io.ll
- test/transcoding/decoration_simt_call.ll
- test/transcoding/exec_mode_argument_io_kind.ll
- test/transcoding/kernel_query.ll
SPIR-V spec states:
"It is invalid for any function to be targeted by both an OpEntryPoint instruction
and an OpFunctionCall instruction."
In order to satisfy SPIR-V that entrypoints and functions
must be different, this introduces an entrypoint wrapper around
functions at the LLVM IR level, then fixes up a few things like
naming at the SPIRV translation.
> [Backport] Add an entry point wrapper around functions (llvm pass) (#1149)

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv_internal.hpp
It was actually upstreamed to SPIR-V Headers already.
> [NFC] Remove ExecutionModeNamedBarrierCountINTEL from spirv_internal

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/entry_point_func.ll
- test/mem2reg.cl
- test/transcoding/FPGAUnstructuredLoopAttr.ll
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_work_item_fence.cl
- test/transcoding/OpenCL/barrier.cl
- test/transcoding/OpenCL/mem_fence.cl
- test/transcoding/OpenCL/sub_group_barrier.cl
- test/transcoding/OpenCL/work_group_barrier.cl
- test/transcoding/SPV_INTEL_function_pointers/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/select.ll
- test/transcoding/SampledImage.cl
- test/transcoding/kernel_query.ll
SPIR-V spec states:
"It is invalid for any function to be targeted by both an OpEntryPoint instruction
and an OpFunctionCall instruction."
In order to satisfy SPIR-V that entrypoints and functions
must be different, this introduces an entrypoint wrapper around
functions at the LLVM IR level, then fixes up a few things like
naming at the SPIRV translation.
> [Backport to 12] Add an entry point wrapper around functions (llvm pass) (#1149)

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/entry_point_func.ll
- test/mem2reg.cl
- test/transcoding/FPGAUnstructuredLoopAttr.ll
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/OpenCL/atomic_work_item_fence.cl
- test/transcoding/OpenCL/barrier.cl
- test/transcoding/OpenCL/mem_fence.cl
- test/transcoding/OpenCL/sub_group_barrier.cl
- test/transcoding/OpenCL/work_group_barrier.cl
- test/transcoding/SPV_INTEL_function_pointers/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/select.ll
- test/transcoding/SampledImage.cl
- test/transcoding/kernel_arg_type_qual.ll
- test/transcoding/kernel_query.ll
SPIR-V spec states:
"It is invalid for any function to be targeted by both an OpEntryPoint instruction
and an OpFunctionCall instruction."
In order to satisfy SPIR-V that entrypoints and functions
must be different, this introduces an entrypoint wrapper around
functions at the LLVM IR level, then fixes up a few things like
naming at the SPIRV translation.
> [Backport to 13] Add an entry point wrapper around functions (llvm pass) (#1149)

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/spirv_internal.hpp
- test/transcoding/SPV_INTEL_fpga_loop_controls/FPGALoopMergeInst.ll
The attribute generates the llvm.loop.intel.max_reinvocation_delay.count metadata in LLVM IR. There is one positive integer literal operand denoting the maximum number of cycles allowed between loop invocations. 
Spec: https://github.com/KhronosGroup/SPIRV-Registry/pull/163
> Implement SPIR-V support for max_reinvocation_delay attribute

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/entry_point_func.ll
- test/mem2reg.cl
- test/transcoding/FPGAUnstructuredLoopAttr.ll
- test/transcoding/KernelArgTypeInOpString.ll
- test/transcoding/KernelArgTypeInOpString2.ll
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/OpenCL/atomic_work_item_fence.cl
- test/transcoding/OpenCL/barrier.cl
- test/transcoding/OpenCL/mem_fence.cl
- test/transcoding/OpenCL/sub_group_barrier.cl
- test/transcoding/OpenCL/work_group_barrier.cl
- test/transcoding/SPV_INTEL_function_pointers/fp-from-host.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer-as-function-arg.ll
- test/transcoding/SPV_INTEL_function_pointers/function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/non-uniform-function-pointer.ll
- test/transcoding/SPV_INTEL_function_pointers/select.ll
- test/transcoding/SampledImage.cl
- test/transcoding/kernel_arg_type_qual.ll
- test/transcoding/kernel_query.ll
SPIR-V spec states:
"It is invalid for any function to be targeted by both an OpEntryPoint instruction
and an OpFunctionCall instruction."
In order to satisfy SPIR-V that entrypoints and functions
must be different, this introduces an entrypoint wrapper around
functions at the LLVM IR level, then fixes up a few things like
naming at the SPIRV translation.
> [Backport to 11] Add an entry point wrapper around functions (llvm pass) (#1149)

- lib/SPIRV/PreprocessMetadata.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/VectorComputeUtil.h
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEnum.h
- lib/SPIRV/libSPIRV/spirv.hpp
- test/transcoding/SPV_INTEL_vector_compute/exec_mode_named_barriers_count.ll
This adds NamedBarrierCountINTEL Execution Mode,
see more in https://github.com/intel/llvm/pull/1612
> [Backport to 11] Update SPV_INTEL_vector_compute to rev 15

- lib/SPIRV/OCLToSPIRV.cpp
- test/transcoding/dot_product_OCLtoSPIRV_half.ll
Switched the visitCallDot check to use isFloatingPointTy for scalar
floating point operands. Bugfix for previous change regarding
integer dot product.
(cherry picked from commit 71e01b53a8ac7b0c15f4bb3cd73bcefdcc137954)
> [Backport to 15] Dot product bugfix to include more floating point types (#1578)

- .github/workflows/check-out-of-tree-build.yml
This reverts commit 55d1de820841e6d9d1c6ca0cd534323d69a1cbf1.
Now that the last use of the deprecated `getPointerElementType` has
been removed, treat uses of deprecated functions as errors again.
> [CI] Reinstate deprecated-declarations warning as error

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/type-scavenger/varargs.ll
This branch doesn't quite work yet, because it turns out the demangler changes I relied on were in https://github.com/intel/llvm/pull/4207 and not in LLVM itself, so I have to go upstream that first.
> Rework the demangler to support recovering more pointer element types.

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/SPV_INTEL_function_pointers/global-function-pointer.ll
This patch helps to avoid invalid SPV generation.
When global variable contains a pointer to a function, translator tries to translate it as declaration. Then it translates this function the second time when going through the function list. This leads to double translation of the same function and to the usage of the same IDs in SPIR-V file.
> Translate function pointer from global variable as pointer, not as declaration

- lib/SPIRV/CMakeLists.txt
- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVBuiltinHelper.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVToOCL.h
Opaque pointers requires us to keep more careful track of the pointee types of the builtin methods. While these are discoverable via demangling, the existing interface of mutateCallInst* does not provide easy ways to maintain these types during remapping of OpenCL builtins to SPIR-V builtins.
This patch adds a BuiltinCallMutator that keeps track not only of the pointer element types discovered by demangling, but also of the LLVM attributes the arguments originally had, even as arguments are inserted or deleted for OpenCL<->SPIR-V builtin conversions. Additionally, the interface is intended to be more forgiving of the varieties of lambdas needed to do the conversions: for example, there is no need for different entry points to indicate a type-aware mapping, or even to indicate a function …
> Add a helper for type-aware mutateCallInst replacement.

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL12.cpp
- lib/SPIRV/SPIRVToOCL20.cpp
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/memory_access.ll
The old mutateCallInst* functions and the new mutator doesn't quite get some of the value names correct, which necessitated some test changes that were looking for particular value names.
> [Mutator] Migrate atomics builtins to the mutator interface.

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLToSPIRV.h
- lib/SPIRV/OCLUtil.h
This requires changing all of the callers of this method at the same time.
> [Mutator] Migrate OCLBuiltinTransInfo::PostProc to the mutator interface.

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- test/read_image.cl
- test/transcoding/AtomicCompareExchangeExplicit_cl20.cl
- test/transcoding/OpImageWrite.cl
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/SPV_INTEL_media_block_io.cl
- test/transcoding/atomic_explicit_arguments.cl
- test/transcoding/atomic_flag.cl
This removes code that has been rendered dead by the mutator interface, finally ending the possibility of calling `Type::getPointerElementType` on any thing that isn't an opaque pointer.
In recognition of this fact, several tests are updated to no longer use `clang -cc1 -no-opaque-pointers`. There are a few tests that still fail when this mode is used (either because the tests are looking for the wrong thing, or because legitimate bugs exist), but these will be handled in follow-up changes.
> Cleanup code after all the mutator changes

- test/transcoding/spec_const.ll
- tools/llvm-spirv/llvm-spirv.cpp
While running OpenCL-CTS SPIR-V subtests, i found that launching llvm-spirv with arguments:
`-r --spec-const=101:i64:4609589727908835759`
results in error message:
`Error: Invalid value for '-spec-const' option! In "101:i64:4609589727908835759": can't convert "4609589727908835759" to 64-bit integer number`
However, 4609589727908835759 fits into 64bits (0x3ff88d6f544bb1af). The problem seems to be that getNumWords() returns 2 so i changed it to use getActiveBits(), but i'm not 100% sure this is the proper fix.
> Fix parsing of --spec-const option

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 10] Fix wrong DICompositeType size (#1452)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 12] Fix wrong DICompositeType size (#1452)

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 13] Fix wrong DICompositeType size (#1452)

- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/annotate_attribute.ll
LLVMToSPIRVBase::transIntrinsicInst translates ptr.annotation intrinsics marking struct members by looking for struct GEPs. However, a GEPs is not necessary for the first member, and so in some cases when the first member is annotated SPIRVWriter has been emitting OpDecorate for these instead which leads to a crash in some cases on reverse translation. This change enables emitting OpMemberDecorate for the first member even if there isn't a GEP and the pointer value is based on a struct alloca instead.
This change also moves the handling of FPGARegIntel annotations so that they're translated to OpFPGARegINTEL before attempting to translate struct member annotations. This ensures that they don't get incorrectly translated with OpMemberDecorate.
> Emit OpMemberDecorate for member 0 annotations

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 11] Fix wrong DICompositeType size (#1452)

- test/OpenCL.std/vload_half.spvasm
- test/transcoding/OpBitReverse_i32.ll
- test/transcoding/OpBitReverse_v2i16.ll
- test/transcoding/OpConstantSampler.ll
- test/transcoding/OpDot.ll
- test/transcoding/OpImageWrite.cl
- test/transcoding/OpenCL/atomic_cmpxchg.cl
- test/transcoding/OpenCL/atomic_legacy.cl
- test/transcoding/SPV_KHR_integer_dot_product-nonsat.ll
- test/transcoding/atomic_flag.cl
- test/transcoding/cl_intel_sub_groups.ll
- test/transcoding/cl_khr_extended_bit_ops.cl
- test/transcoding/clk_event_t.cl
- test/transcoding/explicit-conversions.cl
- test/transcoding/fmod.ll
- test/transcoding/image_builtins.ll
- test/transcoding/image_channel.ll
- test/transcoding/image_with_suffix.ll
The affected CHECK lines ended with a function name.  Any spurious trailing characters in those function names would not be detected by the test.  Append the opening parenthesis of the call expression to catch any undesired trailing characters.
This commit only affects tests that do not require any changes besides the trailing parenthesis.
> [NFC] Add opening parenthesis to call checks

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.cpp
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- test/transcoding/multiple_user_semantic.ll
With this patch the translator will start generating multiple UserSemantic decorations
and member decorations on variables and structure types.
Co-authored-by: Arvind Sudarsanam <arvind.sudarsanam@intel.com>
> Support multiple UserSemantic decorations

- lib/SPIRV/SPIRVWriter.cpp
- test/DebugInfo/Generic/debug-info-eis-option.ll
- test/DebugInfo/Generic/linear-dbg-value.ll
- test/create-placeholders-for-phi-operands.ll
- test/dominator-order.ll
- test/transcoding/SPV_INTEL_variable_length_array/complex-cfg.ll
This implements the block ordering rule in section 2.16.1 of the SPIR-V specification:
> The order of blocks in a function must satisfy the rule that blocks appear
before all blocks they dominate.
This fixes #205.
> Reorder SPIR-V blocks to emit dominators first

- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
> [Backport to 9] Fix wrong DICompositeType size (#1452)

- test/transcoding/LoopUnroll.ll
The latest changes got interfered with the patch that fixes blocks ordering. Like this the checks actually make more sense.
> [NFC] Hotfix for LoopUnroll test

- lib/SPIRV/SPIRVRegularizeLLVM.cpp
- lib/SPIRV/SPIRVRegularizeLLVM.h
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_bfloat16.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_element.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_extract_insert_element_of_sycl_half.ll
- test/transcoding/SPV_INTEL_joint_matrix/joint_matrix_half.ll
It's not longer needed after https://github.com/intel/llvm/pull/6535
> [NFC] Remove JointMatrixINTEL W/A

- lib/SPIRV/libSPIRV/SPIRVType.h
- test/DebugInfo/SourceLanguageSPIRVToLLVM.spvasm
- test/half_extension.ll
For 16-bit floating point constants we have to emit the Float16
capability. The implementation is based on checking if cl_khr_fp16
extension from a source langue (OpenCL C) was enabled.
This commit fixes a bug: we should check for *source* extension instead
of SPIR-V extension.
> Fix Float16 capability

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/transcoding/OpGenericPtrMemSemantics.ll
- test/transcoding/OpImageSampleExplicitLod.ll
- test/transcoding/OpSwitch32.ll
- test/transcoding/OpSwitch64.ll
- test/transcoding/bitcast.ll
- test/transcoding/builtin_calls.ll
- test/transcoding/builtin_function_readnone_attr.ll
- test/transcoding/builtin_vars_arithmetics.ll
- test/transcoding/isequal.ll
- test/transcoding/unreachable.ll
Community restricted readnone, readonly and writeonly attributes to be only function parameter attributes (commit 304f1d59ca4).
This patch aligns the translator with llvm.org.
It also fixes a bug, when readnone attribute is being mapped to NoWrite SPIR-V function parameter attribute.
> Translate readnone attribute as function parameter attribute

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVBuiltinHelper.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVToOCL.cpp
- lib/SPIRV/SPIRVToOCL.h
- lib/SPIRV/SPIRVToOCL20.cpp
- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
One of the reasons behind this change is to make code more easily deal with the future prospect of opaque types, so that helper methods (like adjusting image types) can handle both pointer type and opaque type representations simply by querying if the input type is a TypedPointerType or an OpaqueType [name for the latter still pending].
The set of changes are:
* OCLTypeToSPIRV now uses TypedPointerType internally
* adaptSPIRVImageType and getSPIRVStructTypeByChangeBaseTypeName are collapsed into one method (adjustImageType) that works with TypedPointerTypes.
* A few is*StructType methods have been reverted back to is*Type methods, taking a TypedPointerType parameter instead.
* BuiltinCallHelper::addSPIRVCall{Pair} allows for the creation of SPIR-V calls that can use TypedPointerType or …
> [NFCI] Use TypedPointerType in more places.

- .travis.yml
> [CI][Backport 11] Upgrade to Ubuntu 20.04

- .travis.yml
> [CI][Backport 9] Upgrade to Ubuntu 20.04

- lib/SPIRV/OCLToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.cpp
- lib/SPIRV/OCLTypeToSPIRV.h
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVBuiltinHelper.h
- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVReader.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
We have a couple of interfaces that create the custom SPIR-V types. Again, in preparation for an eventual OpaqueType-based interface for types, these functions are being replaced with a more centralized, uniform basis for constructing these types.
Some of the related helper methods that were previously used to build the names for struct types are now obsoleted by this change and have been removed.
> Add a unified getSPIRVType interface.

- .github/workflows/check-code-style.yml
- .github/workflows/check-out-of-tree-build.yml
It does look like it's now included in libclang-common-16-dev package.
> Remove OpenMP install

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/PreprocessMetadata.cpp
- test/reqd_work_group_size_md.ll
- test/work_group_size_hint_md.ll
The `reqd_work_group_size` and `work_group_size_hint` metadata nodes are currently expected to have exactly 3 operands which are in turn translated to the 3 operands of their corresponding SPIR-V execution modes. This commit relaxes this requirement by allowing the metadata to have 1-3 operands, where the missing dimensions are padded with 1's in the corresponding execution mode. Note that the information about the dimensionality of the original metadata is lost after translation, so reverse translation will always result in the metadata having all three operands.
Motivation comes from https://github.com/intel/llvm/pull/7450 where instead of doing the implicit padding during LLVM IR generation we want to simplify the metadata to only have the operands specified. Not only does it relax the …
> Allow variable number of operands in work-group metadata

- lib/SPIRV/SPIRVUtil.cpp
- test/extensions/INTEL/SPV_INTEL_vector_compute/lower-non-standard-vec-intrinsic-with-ext.ll
> Relax OpenCL extended instruction restrictions

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> Fix builtin vars translation

- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_arithmetics.ll
Instead of creating readnone attributes on each parameter of a function it's better to put just memory(none) which was recently introduced.
See https://reviews.llvm.org/D135780
Co-authored by: Zou, Feng <feng.zou@intel.com>
> Put memory(none) attribute instead of readnone

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 15] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 14] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 13] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 12] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 11] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 10] Fix builtin vars translation

- lib/SPIRV/SPIRVUtil.cpp
- test/transcoding/builtin_vars_gep.ll
> [Backport to 9] Fix builtin vars translation

- lib/SPIRV/LLVMToSPIRVDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
`std::optional` is used instead of `Optional`.
> Fix build with llvm trunk

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/atomicrmw_fadd.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fadd_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fadd_float.ll
Some frontends can generate atomicrmw fadd instead of __spirv_AtomicFAddEXT, so we should support this too
> Translate atomicrmw fadd into AtomicFAddEXT

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 14] Relax OpenCL extended instruction restrictions

- lib/SPIRV/SPIRVTypeScavenger.cpp
The issue is that `SPIRVTypeScavenger::fixType` method performs `delete &Ty` at the end. Then this freed
pointer is used later just as value (not dereferenced). Nevertheles, Coverity claims use-after-free warning. This commit reorders function's invocations to mitigate this issue.
> Reorder invocations of fixType, ReplaceTypeInOperands and mergeType

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 13] Relax OpenCL extended instruction restrictions

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/transcoding/SPV_INTEL_vector_compute/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 11] Relax OpenCL extended instruction restrictions

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_float.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_min_max/atomicrmw_fminfmax_half.ll
Follow up from https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1757
> Translate atomicrmw fmin/fmax into OpAtomicFMinEXT/OpAtomicFMaxEXT

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/transcoding/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 8] Relax OpenCL extended instruction restrictions

- lib/SPIRV/SPIRVInternal.h
- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/transcoding/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 9] Relax OpenCL extended instruction restrictions

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/llvm-intrinsics/sqrt.ll
- test/transcoding/SPV_INTEL_vector_compute/lower-non-standard-vec-intrinsic-with-ext.ll
> [Backport to 12] Relax OpenCL extended instruction restrictions

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- test/DebugInfo/Generic/multiline.ll
Update test after llvm-project commit 6b2829dd8772 ("Allow epilogue_begin to be emitted when generating DWARF", 2022-12-09).
Update after llvm-project commit f7dffc28b3f8 ("Don't include None.h (NFC)", 2022-12-10).
> Fix build and tests for LLVM changes

- include/LLVMSPIRVOpts.h
- lib/SPIRV/LLVMSPIRVOpts.cpp
- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/OCLUtil.h
- lib/SPIRV/SPIRVBuiltinHelper.cpp
- lib/SPIRV/SPIRVBuiltinHelper.h
- lib/SPIRV/SPIRVReader.cpp
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/libSPIRV/SPIRVAsm.h
- lib/SPIRV/libSPIRV/SPIRVDecorate.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVFunction.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVMemAliasingINTEL.h
- lib/SPIRV/libSPIRV/SPIRVStream.h
- lib/SPIRV/libSPIRV/SPIRVType.h
- lib/SPIRV/libSPIRV/SPIRVValue.h
The LLVM project is migrating away from `llvm::Optional` to `std::optional`.  Update the translator to use `std::optional`.
> Use std::optional instead of llvm::Optional

- lib/SPIRV/LLVMToSPIRVDbgTran.h
- lib/SPIRV/SPIRVToLLVMDbgTran.cpp
- lib/SPIRV/SPIRVToLLVMDbgTran.h
- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- lib/SPIRV/libSPIRV/SPIRVAsm.h
- lib/SPIRV/libSPIRV/SPIRVEntry.h
- lib/SPIRV/libSPIRV/SPIRVInstruction.h
- lib/SPIRV/libSPIRV/SPIRVType.h
This is a collection of small fixes to make the code more static analyzer-friendly:
* Added initialization to some previously-uninitialized fields to make sure they have sensible "null" values even when the full constructor isn't called.
* Removed the CU member from SPIRVToLLVMDbgTran since its only use was effectively as a local variable in SPIRVToLLVMDbgTran::transCompileUnit and so it didn't need to be a member variable.
* Removed the unnecessary initialize method from LLVMParallelAccessIndices in SPIRVWriter and moved initialization logic to the constructor.
> [NFC] Member initialization and code cleanup

- CMakeLists.txt
- lib/SPIRV/CMakeLists.txt
- tools/llvm-spirv/CMakeLists.txt
Update CMakeLists.txt after llvm-project commit f09cf34d0062 ("[Support] Move TargetParsers to new component", 2022-12-20).
> [CMake] Link against LLVMTargetParser

- include/LLVMSPIRVLib.h
- lib/SPIRV/SPIRVReader.cpp
- test/SpecConstants/OpSpecConstant.spvasm
- test/lit.cfg.py
- tools/llvm-spirv/llvm-spirv.cpp
Also allow binary float spec constant input by passing a hex value with 0x prefix.
This contribution is being made by Codeplay on behalf of Samsung
> Report spec constant types when they are queried with --spec-const-info

- lib/SPIRV/OCLUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_double.ll
- test/extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_float.ll
We can support atomic fsub by just negating the operand with atomic fadd.
> Translate atomicrmw fsub into FNegate and AtomicFAddEXT

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVTypeScavenger.h
- test/type-scavenger/infinite-phi.ll
PHI instructions have their type scavenged from one of their incoming values. Originally, this used solely the first one, but it is possible for this to generate an infinite cycle (consider a pointer-swapping loop). This fixes the logic to detect such infinite cycles and to consider other incoming values instead.
> [OpaquePointers] Avoid infinite cycles in scavenging the types of PHIs.

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/undef-func-call.ll
This fix resolves issue:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/524
Function translation invokes translation of LLVM loop metadata as a last step.
SPIRVToLLVM keeps a map with metadata. If function with loop metadata is
forward-referenced, translation starts and metadata is placed in the map. If
this function contains calls of undefined functions inside, it will fail -
metadata map is not empty, but there is no loop info inside the undefined
function.
Example:
```
float bar(int x);
__kernel void foo(__global float* outPtr, int i) {
for (int j = 0; j < i; ++j) {
outPtr[j] = bar(j);
}
}
```
> [Backport to 9] Fix translation of undefined function call when debug info is present

- lib/SPIRV/SPIRVReader.cpp
- test/DebugInfo/Generic/undef-func-call.ll
This fix resolves issue:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/524
Function translation invokes translation of LLVM loop metadata as a last step.
SPIRVToLLVM keeps a map with metadata. If function with loop metadata is
forward-referenced, translation starts and metadata is placed in the map. If
this function contains calls of undefined functions inside, it will fail -
metadata map is not empty, but there is no loop info inside the undefined
function.
Example:
```
float bar(int x);
__kernel void foo(__global float* outPtr, int i) {
for (int j = 0; j < i; ++j) {
outPtr[j] = bar(j);
}
}
```
> [Backport to 8] Fix translation of undefined function call when debug info is present

- lib/SPIRV/SPIRVTypeScavenger.cpp
- lib/SPIRV/SPIRVTypeScavenger.h
- test/transcoding/multiple_user_semantic.ll
The main improvement is to enable intrinsics with more complex typing rules to be described. For example, memcpy's requirement that its two pointer arguments have the same type.
There is still a larger rewrite of the type scavenger to use TypedPointerType coming down the line. However, this rewrite also needs opaque types to represent the deferred type concept, which is why it hasn't been done yet. This is an intermediate step in the rewrite which better supports some of the other intrinsics with current issues.
> [OpaquePointers] Improvements to the type scavenger.

- CMakeLists.txt
- test/CMakeLists.txt
pkgconfig is usually not available on Windows, so try to use normal CMake modules to locate the binaries for SPIRV-Tools.
The patch doesn't change the existing behavior when the pkgconfig is available, only when it is missing.
The CMake path is available only with this patch that has already been accepted upstream:
https://github.com/KhronosGroup/SPIRV-Tools/pull/5034
> Link to SPIRV-Tools via CMake package when pkgconfig is not available

- lib/SPIRV/SPIRVBuiltinHelper.cpp
AttributeList::removeParamAttributes function sets attribute at specified
index empty so that return value of AttributeList::getNumAttrSet() keeps
unchanged after that call. When call BuiltinCallMutator::removeArg function,
there is assert failure on BuiltinCallMutator::doConversion() since new CallInst
removed arg but still holds attribute of that removed arg.
> Do not use AttributeList::removeParamAttributes

- lib/SPIRV/SPIRVWriter.cpp
- lib/SPIRV/SPIRVWriter.h
- test/transcoding/registerallocmode.ll
Frontends can use the RegisterAllocMode metadata can be used to configure the register allocation mode. Here we translate into a form that Intel Graphics Compiler can use to actually apply the configuration.
This will only be used by Intel and won't affect anything else.
This is only a temporary solution, we intend to introduce an extension in the future.
> Translate Intel-specific RegisterAllocMode metadata

- lib/SPIRV/SPIRVToOCL20.cpp
- test/transcoding/barrier-runtime-scope.ll
This partially addresses https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1805
> Translate runtime-known barrier's MemScope from SPV-IR to OCL2.0 IR

- lib/SPIRV/SPIRVUtil.cpp
- lib/SPIRV/SPIRVWriter.cpp
This is a minor fix to resolve some issues reported by static analysis:
1. Use 'assert' to NOT ignore return values from getAsInteger and consumeUnsignedInteger.
2. Use 'assert' and other means to NOT ignore return value from getConstantStringInfo.
Thanks
Signed-off-by: Arvind Sudarsanam <arvind.sudarsanam@intel.com>
> Fix issue due to ignoring return value

- lib/SPIRV/SPIRVLowerSaddWithOverflow.cpp
Update for llvm-project commit df1a74ac3c64 ("[IR] Support importing modules with invalid data layouts.", 2023-01-12).
> Update for parseIR LLVM API change
